### ISSUE TITLE
Numpad symbols are not printing on screen

### ISSUE THREAD

**Issue by RandallFlagg** [gui-cs/Terminal.Gui#1040]
If I print the numbers and symbols from `[0-9]` and `[/*-+.]` on the keys in the letters area everything is working fine. If I try to do the same with the keys in the numpad area the symbols that are not numbers don't show.

**OS:** Windows 10 x64 2004 (19041.685)
**GUI.cs version:** latest from repo ([92c2171388918bb4d9a96f2eec7a0158aee029bc](https://github.com/migueldeicaza/gui.cs/tree/92c2171388918bb4d9a96f2eec7a0158aee029bc/ReactiveExample))

It might be related to bug: https://github.com/migueldeicaza/gui.cs/issues/977

![image](https://user-images.githubusercontent.com/434681/102281857-5c0ce700-3f38-11eb-8f3d-54e254dd5177.png)

My keyboard configuration:
![image](https://user-images.githubusercontent.com/434681/102282427-464bf180-3f39-11eb-993e-07436d1e41d2.png)

The two keys tested:
**Numpad:**
![image](https://user-images.githubusercontent.com/434681/102281545-cf622900-3f37-11eb-9f5c-09e0c59a1f57.png)
**Above letters:**
![image](https://user-images.githubusercontent.com/434681/102281932-7fd02d00-3f38-11eb-9a52-fa495f816414.png)

**Comment by BDisp** [comment]
If you are running on Linux on a virtual machine it really happens.

**Comment by RandallFlagg** [comment]
It is not a VM. I updated relevant information in my first comment.

**Comment by BDisp** [comment]
I'm also using Windows 10 and that doesn´t happens to me.

**Comment by RandallFlagg** [comment]
You are using the same keyboard configuration?

**Comment by BDisp** [comment]
No but I think that doesn't have to do with keyboard configuration. Try the last version in the GUI master to check if it still happens.

**Comment by RandallFlagg** [comment]
I am working with the latest from the master as I specified in my comment.
The version I specified is not the latest? If not then please send me the sha-1 of the commit you want me to checkout.

**Comment by RandallFlagg** [comment]
I am working with the latest from the master as I specified in my comment.
The version I specified is not the latest? If not then please send me the sha-1 of the commit you want me to checkout.

I just tested again in my code and I found out that it started to work in my program but still doesn't work in the samples for some reason.

**Comment by BDisp** [comment]
Sorry my bad. I didn't realize you mean about the `Reactive `example. Yes I confirm that not working on the NumPad.

**Comment by BDisp** [comment]
Can you see the reason please, because I'm not familiar with that language.

**Comment by BDisp** [comment]
I don't know if that behavior is because the project is using the NuGet package?

**Comment by tig** [comment]
I don't have a keybaord here with num keys. Can someone please try to repro (do not use the Reactive sample as it's hard coded to a specific old nuget package).

**Comment by BDisp** [comment]
I have already managed to debug and actually the symbols [/ * - +.] from the numeric keyboard are not detected, but it may be due the `Terminal `NuGet package version.

**Comment by tig** [comment]
see #977 

Possible dupe?

**Comment by tig** [comment]
This should be fixed with

- #3078
