### ISSUE TITLE
Add View.Insert(View, int) and RemoveAt(int) methods

### ISSUE THREAD

**Issue by MihaMarkic** [gui-cs/Terminal.Gui#106]
I'd like to see View.Insert(View, int) and RemoveAt(int) methods, so the item at certain position can be added or removed.
I can create a PR...

**Comment by tig** [comment]
Why?

For tab order?

**Comment by MihaMarkic** [comment]
@tig I was creating React-ish approach to UI and hence need to deal with items at certain position.

**Comment by MihaMarkic** [comment]
FYI https://github.com/MihaMarkic/SharpReact there is a sample against GUI

**Comment by tig** [comment]
> @tig I was creating React-ish approach to UI and hence need to deal with items at certain position.

Sorry if I'm being dense, but when you say "position" do you mean screen position? Position in z-order? Or, position in the tab order?

**Comment by MihaMarkic** [comment]
@tig I think I was referring to position in Views array (not UI). Does that make sense to you?

**Comment by MihaMarkic** [comment]
It matters if you want to have virtual array and target (GUI) array in sync.
