### ISSUE TITLE
Please improve Terminal.Gui samples and tutorials 

### ISSUE THREAD

**Issue by Kadia64** [gui-cs/Terminal.Gui#1352]
you can at least help us out and give us easy to read tutorials on how to do some stuff. None of your examples make any sense

**Comment by tdhillon-552** [comment]
i know this is old but is there a good tutorial out there? I'm struggling to understand how to properly setup a basic app with multiple views

**Comment by BDisp** [comment]
If you check the `UICatalog` project you'll find a bunch of example how to setup them.

**Comment by tig** [comment]
> i know this is old but is there a good tutorial out there? I'm struggling to understand how to properly setup a basic app with multiple views
> 
> 

Tell us a little more about the app you'd like to build. 

Did the sample that's in the readme not help?

**Comment by tdhillon-552** [comment]
thanks for the response. I'm trying to understand the best way to handle navigations between windows. I really like this project and want to use it more but I'm struggling with basic navigation structuring. Here's an example:

(I apologize for not using "view" and "window" the right way)

App starts -> show main window. Onclick of a button on the main window -> go to another window. onclick of the "back" button -> show the main window.

**Comment by tdhillon-552** [comment]
This is exactly what I was looking for. Thank you for taking the time to explain it to me!
