### ISSUE TITLE
Add 'Visible' property to ColumnStyle in TableView

### ISSUE THREAD

**Issue by tznind** [gui-cs/Terminal.Gui#1465]
This is a new ticket to come out of https://github.com/migueldeicaza/gui.cs/issues/1463 (I've created a new ticket since that one is closed and was more general).

It is to add the ability to hide columns in TableView:

> I think a better solution would be to add a Visible property to the ColumnStyle class. I can look into this, it should be reasonably easy.

**Comment by radek3911** [comment]
Hello,

for anyone looking for a workaround here is what worked for me:
![image](https://user-images.githubusercontent.com/15276167/203653129-35039f96-6f00-48d4-971a-19d9942d331c.png)

I used SQL to query data and then load it from datatable to tableview. Then using ColumnStyle I set MaxWidth to 0. The only difference is a double border at the end which is not a big deal - the border does not stack so if you have more hidden columns at the end there will be still one additional border (well at least for 2 hidden columns, have not tried it with more).

Also here is the code used to apply ColumnStyles:
```cs
tableView.Style.ColumnStyles.Add(tableView.Table.Columns["colname"], new TableView.ColumnStyle() { MaxWidth = 0 });
```

**Comment by BDisp** [comment]
@tznind how about not draw if width is equal to zero?

**Comment by tznind** [comment]
Thanks for sharing this trick @radek3911, very handy.

I see you are using `Add` and the `ColumnStyle` constructor.  Another option which you might find tidier or more readable is to use `GetOrCreateColumnStyle` directly (both work fine though).

```csharp
tableView.Style.GetOrCreateColumnStyle (tableView.Table.Columns ["colname"]);
colStyle.MaxWidth = 0;
```

> @tznind how about not draw if width is equal to zero?

That would be a good idea.  Once `Visible` is added  we could do something like:

```csharp
private bool _visible = true;

public bool Visible 
{
	get { return MaxWidth > 0 &&  _visible; }
	set { _visible = value; }
}
```
_Proposed new code in `ColumnStyle`_

The ability to hide columns is definetly a nice feature to have.  

It has some complexity because keyboard navigation and mouse selection etc have to all consider invisible columns.  So for example when you press right from A1 and column B is invisible the cursor needs to move to C1.  So its not just a rendering issue.

I have been meaning to find time to dive deeper into a solution for this feature but I have also just started a new job so don't have as much time at the moment to tackle it.

**Comment by tznind** [comment]
Ok I've started tinkering on this https://github.com/gui-cs/Terminal.Gui/pull/2243 I have added as many TODO items as I can think of but there will probably be more as I dig into this feature.
