### ISSUE TITLE
Rendering directly on ubuntu server without setting Application.UseSystemConsole = true is broken

### ISSUE THREAD

**Issue by Trolldemorted** [gui-cs/Terminal.Gui#1500]
I created a fresh ubuntu20.04.3 (server) server VM, installed the dotnet sdk, checked out gui.cs, ran `dotnet run --project UICatalog` and it looked like this:

![grafik](https://user-images.githubusercontent.com/10261186/139657287-d3a612f7-8358-4427-9f5c-da78c03dc5ac.png)

In my app, I notice severe drawing issues as well (dead "pixels", skewed graph axes, ...). Am I doing something fundamentally wrong?

**Comment by BDisp** [comment]
I think this is not an issue. If no `xterm` is installed so `ncurses` will be using the limited basic colors. If the `Application.UseSystemConsole = true`, then the `dotnet` colors will be used with more options.

**Comment by Trolldemorted** [comment]
Are you certain that this is just a color scheme issue? I can see certain elements in the list if I manage to navigate to them, but their peers have the same color in my powershell, so I'd expect to see them too when I navigate to them.

Setting `Application.UseSystemConsole = true` makes the CPU usage go to 100%, are there ways around that? And can I set it easily for the entire catalog to test it?

**Comment by BDisp** [comment]
> Setting `Application.UseSystemConsole = true` makes the CPU usage go to 100%, are there ways around that?

With a `Thread.Sleep (10)` inside the `while (true)` of the `WaitWinChange ()` method will improve the performance.


> And can I set it easily for the entire catalog to test it?

`dotnet run --project UICatalog -usc`

**Comment by Trolldemorted** [comment]
>With a Thread.Sleep (10) inside the while (true) of the WaitWinChange () method will improve the performance.

That sounds great, could you merge your branch with that upstream?

>dotnet run --project UICatalog -usc

With System.Console things work as expected indeed, so I guess the next thing would be to set a different bg color?

**Comment by BDisp** [comment]
> That sounds great, could you merge your branch with that upstream?

Had already submitted here #1504.


> With System.Console things work as expected indeed, so I guess the next thing would be to set a different bg color?

Are you using the current main branch? If so, maybe the ubuntu server don't have all the resources to run full color support for `ncurses` (`CursesDriver`). @tznind can you give your opinion about this, please?

**Comment by tznind** [comment]
What are you using to access the server? are you directly logging in or using ssh? what does $TERM show (i.e. `echo $TERM`)? Typically you can get odd colours or not showing colors if you are using a different terminal protocol.  For example to get putty to work you need to set the app to use `xterm-256color` (https://github.com/migueldeicaza/gui.cs/discussions/1455)

**Comment by tig** [comment]
I believe this is fixed. Closing.
