### ISSUE TITLE
UI Catalog: Character Map - Some glyphs in right column are clipped

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#1767]
<img width="488" alt="image" src="https://user-images.githubusercontent.com/585482/171740214-b26e4d4c-9c41-4ec0-98d5-e1bfc6c05beb.png">

See 0xFb6f for example.  Note this is with Casckadia Nerd Font and other Nerd fonts (https://www.nerdfonts.com/font-downloads). 

Probably related to : https://github.com/migueldeicaza/gui.cs/issues/1766

**Comment by tig** [comment]
Repros on WSL (Windows Terminal/Ubuntu) as well: 

<img width="599" alt="image" src="https://user-images.githubusercontent.com/585482/171746564-18dd1a35-2ac9-45d0-bbe8-0b150923d5de.png">

**Comment by BDisp** [comment]
If you install the `gnome-terminal` on the `WSL` and using the `Monospace Regular` font I don't have that issue. Perhaps related font issue?

![gnome-terminal](https://user-images.githubusercontent.com/13117724/171749821-20cf9609-13b5-4100-ac33-ebfcfeb04702.png)

**Comment by BDisp** [comment]
I'm not having the clipped glyphs issue. Your font is bigger why?

![clipped-glyphs](https://user-images.githubusercontent.com/13117724/171753419-503e4ba4-803e-4351-90ae-c94782246e7b.png)

**Comment by tig** [comment]
I don't know why those glyphs look bigger on my machine. Odd.

**Comment by tig** [comment]
Either fixed by #1743 or something else because I can't repo it anymore.
