### ISSUE TITLE
Default color scheme can be hard to read for some users

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#1773]
I've seen several examples where users complain about the default color scheme.

The latest is here: 

https://github.com/PowerShell/GraphicalTools/issues/129

This Issue is to track fixing this by updating the default color schemes to have more contrast, address accessibiity concerns, etc...

This issue should be tracked along with the issues involving upgrading the color system, but should probably be tackled independently (and more quickly) than those:

https://github.com/migueldeicaza/gui.cs/issues/458
https://github.com/migueldeicaza/gui.cs/issues/457
https://github.com/migueldeicaza/gui.cs/issues/48

I found this article recently on choosing colors that I quite liked:

https://matthewstrom.com/writing/how-to-pick-the-least-wrong-colors/

**Comment by BDisp** [comment]
See https://github.com/gui-cs/Terminal.Gui/pull/1937#issuecomment-1205064726
