### ISSUE TITLE
TextView: Default background color has usability issues

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#1800]
In Wizards Scenario, I have what is essentially a modal dialog box with a TextView filling the client area:

<img width="589" alt="image" src="https://user-images.githubusercontent.com/585482/173412511-b6e21f10-c4d2-46cc-ac01-7268784de9a6.png">

Note how it's actually very hard to tell that this is a non-read-only/editible TextView. 

I think `TextView` should use the same colors as `TextField`:

<img width="380" alt="image" src="https://user-images.githubusercontent.com/585482/173414323-b3b11c50-696e-4648-b569-f913fb385381.png">

**Comment by tig** [comment]
> > I think `TextView` should use the same colors as `TextField`:
> 
> I agree and I think the `ColorScheme` need to have two new `Attribute` for `SelectedNormal` and for for `SelectedFocus` which by default will be always the foreground and background colors inverted. Normally is used by the views the `Focus` color when the view is selected but this isn't enough for all views, like the TextView. What do you think?

I agree.

**Comment by BDisp** [comment]
I thought better about it and decided not to create the new attributes just because of `TextView` and to avoid more complexity for `ColorScheme`.
