### ISSUE TITLE
Checkbox: Mouse hit area is just on the check mark making harder to use

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#1805]
On most windowing systems, clicking anywhere on a checkbox (or radio button), including the text, will cause the check to change.

Currently `Checkbox` only changes if the user clicks directly on the checkmark glyph. This makes using a mouse harder than it should be. 

![8hpjBfg 1](https://user-images.githubusercontent.com/585482/173460665-bd0d359d-cce4-4adc-9e2d-dcaa652b5d90.gif)

**Comment by BDisp** [comment]
That is not happen to me.

![checkbox-click](https://user-images.githubusercontent.com/13117724/173462301-79cae916-1d0d-411f-bab4-3af17e93ac70.gif)

**Comment by tznind** [comment]
I think this might be an AutoSizing thing or something? I have noticed in TerminalGuiDesigner that adding a CheckBox and then setting the text to something results in you only being able to drag/click it in the exact checkbox cell

**Comment by BDisp** [comment]
Closing as fixed in #1807.
