### ISSUE TITLE
Window/Dialog.Border.Thickness is 0, but there's a border

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#1858]
@bdisp, I'm confused.

Why is BorderThickness == 0 when there's clearly a border??

<img width="454" alt="image" src="https://user-images.githubusercontent.com/585482/179659023-29991f93-0cc4-46cb-a1fa-d6c568410484.png">

**Comment by tig** [comment]
I now understand this.

`Border.Thickness` is independent of `BorderStyle`. It applies to the space outside of the Window's border, which is always 1 row/column wide. 

To determine how much space the Window's border actually takes the user must do

```csharp
borderWidth = (Border.DrawMarginFrame ? 2 : 0) + Border.Thickness.Left + Border.Thickness.Right;
borderHeight = (Border.DrawMarginFrame ? 2 : 0) + Border.Thickness.Top + Border.Thickness.Bottom;
```

This is all unfortunately complex, but I understand that it is a result of the fact that `Window` was originally coded with a fixed-with (1 row/column) border and it  would be a breaking change to change that.

We need to fix the documentation to make all of this abundantly clear.

**Comment by tig** [comment]
While we're at it (this may be another issue?) but why isn't the border frame drawn the size of the `Border` rectangle?

I would think the border would be drawn around the red here:

<img width="552" alt="image" src="https://user-images.githubusercontent.com/585482/179662568-2bf590d6-4c14-452c-9794-776c79a2a20d.png">

**Comment by BDisp** [comment]
Well, borders always draw around the content view. What you are asking is a new feature.

**Comment by BDisp** [comment]
Yes the BorderStyle has to do with the DrawMarginFrame

**Comment by tig** [comment]
Just so I'm clear:

There really is no point to `Padding` because `Border.BorderThickness` does the same thing. Right?

**Comment by BDisp** [comment]
For padding there is the Border.Padding. The Border also have a method called GetSumThickness to get the space of the Border.BorderThickness more the Border.Padding.

**Comment by BDisp** [comment]
> There really is no point to `Padding` because `Border.BorderThickness` does the same thing. Right?

Right, with the option of having an extra border. The `Border.BorderThickness` in a `Windows Form` app should be associated to the `BorderStyle` but in a console application we can't draw a wide border, and as you said, the `Window` view was originally coded with a fixed-width (1 row/column) border and it would be a breaking change to change that.

**Comment by tig** [comment]
What's the recommended way to get padding INSIDE of the FrameBorder?

**Comment by BDisp** [comment]
> What's the recommended way to get padding INSIDE of the FrameBorder?

None @tig sorry. Both are outside the FrameBorder.

**Comment by tig** [comment]
> > What's the recommended way to get padding INSIDE of the FrameBorder?
> 
> None @tig sorry. Both are outside the FrameBorder.

That's too bad. I thought that's what Padding did.

**Comment by BDisp** [comment]
> That's too bad. I thought that's what Padding did.

And still does. If you remember the padding was the space between the outside limit without frame and the inside frame. So, in the case of the Window was the Window.Frame and the ContentView, which is the space where the subviews are added. If I were changing this behavior would breaking all. Unless you have any idea to workaround this

**Comment by tig** [comment]
Closing as by design
