### ISSUE TITLE
Use Undo and Redo commands with WordWrap enabled

### ISSUE THREAD

**Issue by luizfernandonb** [gui-cs/Terminal.Gui#1867]
**Is your feature request related to a problem? Please describe.**
No, it's just a feature, which in this case would be to be able to use Undo and Redo commands with WordWrap activated in a TextView.

**Comment by luizfernandonb** [comment]
@BDisp, @tig i believe this PR of yours has broken some parts of the TextView, a text file loaded using `LoadFile()` doesn't even load

![image](https://user-images.githubusercontent.com/42288418/180342995-9a289ad9-4a55-45a4-a995-0ba200d26d3a.png)

Also when you add enough characters for a line break to occur, an extra space is embedded at the end of the first line:
![image](https://user-images.githubusercontent.com/42288418/180343094-1a3106a3-4562-4df9-81df-8b4dccd384be.png)

And when we try to erase some characters, an exception is thrown (The text is not even erased):
![image](https://user-images.githubusercontent.com/42288418/180343261-bdeafaac-9afa-4afd-9fd2-18708fc9f96b.png)

**Comment by BDisp** [comment]
I think is better to reopen this issue or create a new one. I confirm this bugs and I'll try to fix them.

**Comment by luizfernandonb** [comment]
@tig, can you reopen this issue please?

**Comment by BDisp** [comment]
> Also when you add enough characters for a line break to occur, an extra space is embedded at the end of the first line

The extra space at the end of a line is for allows the cursor stay visible, otherwise the user can have some difficult to discover on what position he is in the text.
