### ISSUE TITLE
Bug when using `ScrollTo()` method

### ISSUE THREAD

**Issue by luizfernandonb** [gui-cs/Terminal.Gui#1876]
**Describe the bug**
A bit similar to the #1866 I had previously opened.

In this case, when the `ScrollTo` method runs for a few lines down and you try to type something, an error is thrown.

**To Reproduce**
In the screenshots

**Expected behavior**
Perhaps in this case, it would be correct for the cursor to go to the line that was defined in the parameter of the `ScrollTo()` method

**Screenshots**
1. Before:
![image](https://user-images.githubusercontent.com/42288418/180312926-01b9d065-07cc-47e8-9e5a-a04e468ee349.png)

2. After pressing the `Ctrl` + `CursorDown` key, which I put as binding in the code next to the console:
![image](https://user-images.githubusercontent.com/42288418/180313024-b14999ec-21df-4981-a985-a2fd70785e69.png)

3. I try to type anything and boom:
![image](https://user-images.githubusercontent.com/42288418/180313221-0e138fc9-e9f2-4e4d-af03-fe17b0089a2f.png)

**Desktop (please complete the following information):**
- OS: Windows 10 21H2 - Build 19044.1826
- Browser: Edge
- Version: 103.0.1264.62

**Comment by BDisp** [comment]
You have to test with the current main branch because it's the same bug that was fixed by the #1866 already merged.

**Comment by luizfernandonb** [comment]
> You have to test with the current main branch because it's the same bug that was fixed by the #1866 already merged.

I was waiting for a library update on NuGet to be able to test, will it take a long time to come out?

**Comment by BDisp** [comment]
> I was waiting for a library update on NuGet to be able to test, will it take a long time to come out?

I recommend to you to have two projects, one using the NuGet package and another using the gui.cs repo. Only this way you can really test if the fixes is working. Waiting for a update package sometimes it take lo long time.

**Comment by luizfernandonb** [comment]
> > I was waiting for a library update on NuGet to be able to test, will it take a long time to come out?
> 
> I recommend to you to have two projects, one using the NuGet package and another using the gui.cs repo. Only this way you can really test if the fixes is working. Waiting for a update package sometimes it take lo long time.

Okay, thanks, I'll do that, if it works, I'll close this issue.

**Comment by luizfernandonb** [comment]
> > > I was waiting for a library update on NuGet to be able to test, will it take a long time to come out?
> > 
> > 
> > I recommend to you to have two projects, one using the NuGet package and another using the gui.cs repo. Only this way you can really test if the fixes is working. Waiting for a update package sometimes it take lo long time.
> 
> Okay, thanks, I'll do that, if it works, I'll close this issue.

Yes, it solved, but is there any way to move the cursor to the line I scrolled? I can't do that, the cursor is always on the same line, I've tried using the Move method but I haven't had success.

**Comment by BDisp** [comment]
Set the cursor position to the column and row you want.

**Comment by luizfernandonb** [comment]
> Set the cursor position to the column and row you want.

I already do that, but it doesn't work, I use the `Move()` method

**Comment by luizfernandonb** [comment]
I forgot to mention, even inverting the operations, which in this case would be, putting the `Move()` method first and the `ScrollTo()` right below, in theory the cursor would change its place first and then the scroll is done, but that doesn't happen, the effect is the same as calling `ScrollTo()` method first and then `Move()`.

**Comment by luizfernandonb** [comment]
Any update on this bug? In case what I said was not clear, I can record a gif, or anything else

**Comment by BDisp** [comment]
I haven't see it yet.

**Comment by BDisp** [comment]
This unit test proves that the `CursorPosition` is working by setting his value. The `ScrollTo` method only moves the text but without change the cursor position. After scrolling you have to click on the position you want and then typing. This is the normal `ScrollTo` behavior. If you want more or less a near localization of the text the `LeftColumn` and the `TopRow` gives the information about the cols  and rows were scrolled and using the `TextView` width and height there is a approximated indicator where you are in the text.
Note that the column is 100 because the cursor need an extra column in the end of the line.

```cs
		[Fact]
		[AutoInitShutdown]
		public void MoveDown_CursorPosition ()
		{
			var tv = new TextView {
				Width = 10,
				Height = 5
			};

			// add 100 lines of wide text to view
			for (int i = 0; i < 100; i++)
				tv.Text += new string ('x', 100) + (i == 99 ? "" : Environment.NewLine);

			Assert.Equal (new Point (0, 0), tv.CursorPosition);
			tv.CursorPosition = new Point (5, 50);
			Assert.Equal (new Point (5, 50), tv.CursorPosition);

			tv.CursorPosition = new Point (200, 200);
			Assert.Equal (new Point (100, 99), tv.CursorPosition);
		}

```

**Comment by BDisp** [comment]
> > Set the cursor position to the column and row you want.
> 
> I already do that, but it doesn't work, I use the `Move()` method

This method is normally used by the `Redraw` and `PositionCursor` methods when the view is being rendering and not for set some property.

**Comment by luizfernandonb** [comment]
> This unit test proves that the `CursorPosition` is working by setting his value. The `ScrollTo` method only moves the text but without change the cursor position. After scrolling you have to click on the position you want and then typing. This is the normal `ScrollTo` behavior. If you want more or less a near localization of the text the `LeftColumn` and the `TopRow` gives the information about the cols and rows were scrolled and using the `TextView` width and height there is a approximated indicator where you are in the text. Note that the column is 100 because the cursor need an extra column in the end of the line. If you want to set to the scrolled position you can set like this: `CursorPosition = new Point(LeftColumn, TopRow)`
> 
> ```cs
> 		[Fact]
> 		[AutoInitShutdown]
> 		public void MoveDown_By_Setting_CursorPosition ()
> 		{
> 			var tv = new TextView {
> 				Width = 10,
> 				Height = 5
> 			};
> 
> 			// add 100 lines of wide text to view
> 			for (int i = 0; i < 100; i++)
> 				tv.Text += new string ('x', 100) + (i == 99 ? "" : Environment.NewLine);
> 
> 			Assert.Equal (new Point (0, 0), tv.CursorPosition);
> 			tv.CursorPosition = new Point (5, 50);
> 			Assert.Equal (new Point (5, 50), tv.CursorPosition);
> 
> 			tv.CursorPosition = new Point (200, 200);
> 			Assert.Equal (new Point (100, 99), tv.CursorPosition);
> 		}
> 
> 		[Fact]
> 		[AutoInitShutdown]
> 		public void ScrollTo_CursorPosition ()
> 		{
> 			var tv = new TextView {
> 				Width = 10,
> 				Height = 5
> 			};
> 
> 			// add 100 lines of wide text to view
> 			for (int i = 0; i < 100; i++)
> 				tv.Text += new string ('x', 100) + (i == 99 ? "" : Environment.NewLine);
> 
> 			Assert.Equal (new Point (0, 0), tv.CursorPosition);
> 			tv.ScrollTo (50);
> 			Assert.Equal (new Point (0, 0), tv.CursorPosition);
> 
> 			tv.CursorPosition = new Point (tv.LeftColumn, tv.TopRow);
> 			Assert.Equal (new Point (0, 50), tv.CursorPosition);
> 		}
> ```

Now I understand, thank you.
