### ISSUE TITLE
Support specifying the number of lines scrolled by the mouse

### ISSUE THREAD

**Issue by luizfernandonb** [gui-cs/Terminal.Gui#1880]
**Is your feature request related to a problem? Please describe.**
No, it would be a feature to specify the lines that will be skipped when using the mouse scroll

Considering that if we open a huge text file, scrolling using the mouse scroll that currently only skips one line at a time is tiring

**Describe the solution you'd like**
I thought of it more or less like this:
```C#
var tv = new TextView()
{
    // ...
    VerticalLinesToScroll = 5, // Anyway, any number, the default is 1, as it is currently
    HorizontalLinesToScroll = 3 // Anyway, any number, the default is 1, as it is currently, but in this case, the number would be to use with the command Shift + Mouse Scroll, which comes by default to scroll horizontally in the TextView
};
```

Extra note: If the values ​​are not specified, the values ​​will be the same as those that come by default in a `TextView`

Extra Note 2: Hope I'm not bothering you with so many issues

**Comment by tig** [comment]
This is great stuff.  Please don't stop helping make this library better!

**Comment by BDisp** [comment]
> ```cs
> HorizontalLinesToScroll = 3
> ```

I think you are meaning about `HorizontalColumnsToScroll`

**Comment by tznind** [comment]
If it is specifically for the mouse wheel scrolling only then its probably a good idea to put the word `MouseWheel` in the property name.  If it affects other stuff like clicking the down arrow on scrollbars then the name you suggested would be fine @BDisp.

**Comment by rsmirnov90** [comment]
I think it would also be awesome if the values could be made dynamic and be easily changeable after the widget is created.

This way, developers can implement use cases for additional scenarios such as being able to hold down modifier (or other) keys to scroll at different paces. (I.e. hold down CTRL to scroll 100 lines, SHIFT to scroll 10, etc.)

**Comment by luizfernandonb** [comment]
Any updates on this?

**Comment by popara96** [comment]
Created a [pull request](https://github.com/gui-cs/Terminal.Gui/pull/2444).
