### ISSUE TITLE
Wizard shouldn't use Colors.Toplevel for HelpText.ColorScheme

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#1912]
Because `Colors.Toplevel` is only for true top-level windows as on some terminals (Windows Terminal) a background can be set,...and it will show through:

![OMOy9vk 1](https://user-images.githubusercontent.com/585482/181413955-8da8f49e-8c93-4f67-aec9-a162cdd44142.gif)

**Comment by BDisp** [comment]
@tig how do you set that background in Windows Terminal?

**Comment by BDisp** [comment]
I already found how in the settings, it's cool..
