### ISSUE TITLE
GraphView scenario not rendering well with WindowsDriver and NetDriver.

### ISSUE THREAD

**Issue by BDisp** [gui-cs/Terminal.Gui#1923]
On `Linux` is rendering well. I suspect that is something with Win32 Console library that theses drivers uses which `Windows Terminal` stopped some support. I also check that `Windows Terminal` also doesn't respect the settings to not intercept the` Ctrl-C` which we can't use anymore, unless we unbind in the keybinding settings.

**Edit:**
This only happens when I run directly from `VS2022` with the `VsDebugConsole.exe` which is opened on the `Windows Terminal`. Compatibility issue?

**Comment by BDisp** [comment]
Guys, this is only happening on my laptop. If I push to another of the two monitors it rendering well. Any idea on is going on? Thanks.

**Comment by BDisp** [comment]
Without initializing with `Windows Terminal` but with the `Windows Console Host` is rendering well. I don't know if it's necessary additional configuration on `Windows Terminal`.

**Comment by tig** [comment]
Still repo @BDisp ?

**Comment by BDisp** [comment]
> Still repo @BDisp ?

Only with the Windows Terminal. I'm closing this because is a external issue. If someone know if it's some settings on Windows Terminal, please tell me. My configuration is a laptop and two external monitors plugged into the laptop.

**Comment by BDisp** [comment]
I ended to fix this by setting the screen resolution of the laptop equal to the other two monitors, in the case someone is also facing this issue.
