### ISSUE TITLE
Preserve trailing spaces on word wrap must be refactored on TextFormatter.

### ISSUE THREAD

**Issue by BDisp** [gui-cs/Terminal.Gui#1925]
But you need to agree that there are cases where a line starting with a space is inevitable.

```cs
			maxWidth = 8;
			expectedClippedWidth = 8;
			wrappedLines = TextFormatter.WordWrap (text, maxWidth, true);
			Assert.True (expectedClippedWidth >= wrappedLines.Max (l => l.RuneCount));
			Assert.True (expectedClippedWidth >= wrappedLines.Max (l => l.ConsoleWidth));
			Assert.Equal ("A ", wrappedLines [0].ToString ());
			Assert.Equal ("sentence", wrappedLines [1].ToString ());
			Assert.Equal (" has ", wrappedLines [2].ToString ());
			Assert.Equal ("words.", wrappedLines [^1].ToString ());
			Assert.True (wrappedLines.Count == 4);

```

The `sentence` word has already a width equal to 8 and can't moved to the next line, causing an infinite loop :-) and thus the `has` word must start with the existing space.
I also will remove from the `TextView` all the references to the `preserveTrailingSpaces == !ReadOnly` and the methods added to tweak this, because it must always have to be true to allow track all the necessary methods. So, @tig I hope you understanding this, please.

**Comment by BDisp** [comment]
I updated the introduction to this issue and would like yours feedback, please. Thanks.

**Comment by tig** [comment]
I think I understand but even if I don't, here's how I think Word Wrap should work (and how I think it works in most other editors I've ever used). 

- Avoid the following appearing at the start of word-wraped line: `.`, `,`, `;`, `:`, `!`, `?` (and probably others; there's probably a well-known char set).
- Spaces at the end of a word-wrapped line can be ignored
- If a word-wrapped line contains a single word, that that is too long to fit, it should be wrapped after the first character that will not fit (e.g.

if the width is 7, `sentence` will appear as

```
sentence
e
```

if the width is 8, `sentence` will appear as

```
sentence
```

Based on the above rules, with a width of 8, the text `A sentence has words.` will appear as

```
A
sentence
has
words.
```

If width was 7, it would be:

```
A 
sentenc
e has 
words.
````
if width where 9, it would be:

```
A
sentence
has 
words.
```

if width were 10, it would be

```
A sentence
has 
words.
```

if width were 11, it would be

```
A sentence
has words.
```

I think the key is, for word-wrap to look right, spaces (or punctuation) will never (unless in really extreme cases like width == 1).

I bet there are edge cases I'm not considering, but I think this is directionally correct. 

Note it will get even more complicated when considering how to select the text (for copy/paste).

**Comment by BDisp** [comment]
> * Spaces at the end of a word-wrapped line can be ignored

Although I tweaked on the `TextView` for copy/paste, for the selecting part of wrapped lines is nightmare and if we don't want to have a breaking changes on how the wrapped lines are handled on the `TextView` I recommend not mixing preserve trailing spaces with not preserve. I think this can be improved slowly and not and not in a hurry. I based my tests on the `Notepad++` and you will see it preserves trailing spaces.

**Comment by BDisp** [comment]
Practically Word Wrap is already working the way you indicated, but preserving the spaces on the right if enabled.

**Comment by BDisp** [comment]
> Note it will get even more complicated when considering how to select the text (for copy/paste).

That why the `TextView` must always use word wrap with trailing white spaces which already looks like with not preserve option, on both read-write and read-only. The Notepad++ also preserve trailing white spaces. If you select the text you will see it. A bug on the `StripCRLF` method in the `TextFormatter` was also fixed.
