### ISSUE TITLE
Trailing whitespace makes MessageBox.Query buttons disapear

### ISSUE THREAD

**Issue by tznind** [gui-cs/Terminal.Gui#1930]
**Describe the bug**
When there is a newline at the end of the Message then MessageBox does not render buttons 

**To Reproduce**

```csharp
using Terminal.Gui;
Application.Init();
MessageBox.Query("HeyThere",$"Line1{Environment.NewLine}Line2{Environment.NewLine}Line3{Environment.NewLine}","Ok","Cancel");
Application.Shutdown();
```
![image](https://user-images.githubusercontent.com/31306100/182182965-9a57fb02-8cf1-4ff7-a712-c8d3fb17bcc7.png)

Without the extra whitespace
```csharp
using Terminal.Gui;
Application.Init();
MessageBox.Query("HeyThere",$"Line1{Environment.NewLine}Line2{Environment.NewLine}Line3","Ok","Cancel");
Application.Shutdown();
```

![image](https://user-images.githubusercontent.com/31306100/182183120-fd6602ca-0422-4dd6-87a8-ee64df1631bf.png)

This seems to be new behaviour in `1.7.0` 

**Desktop (please complete the following information):**
 - OS: Windows

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BDisp** [comment]
Can you try with this pr #1929, please. If still has this issue I'll try to fix it. In my opinion if it end with a new line, with the intention of giving a empty line, before the buttons, then it must wraps with preserve trailing spaces enabled.

**Comment by tznind** [comment]
#1929 does not seem to make a difference (still looks like the first screenshot above).

**Comment by BDisp** [comment]
@tznind  is this you want?

![imagem](https://user-images.githubusercontent.com/13117724/182203748-b9dcdb3b-4556-4fcf-908f-e0eae479472d.png)

**Comment by tznind** [comment]
No.  The bug is that the buttons disapear.  The only thing we need is to ensure the dialog box sizes itself correctly so that the buttons don't disapear.  Everything else is fine, definetly don't want double paragraph spacing.
