### ISSUE TITLE
I am using combobox control, when I delete characters It throws the same error **IndexOutOfRangeException**

### ISSUE THREAD

**Issue by tznind** [gui-cs/Terminal.Gui#1950]
> I am using combobox control, when I delete characters It throws the same error **IndexOutOfRangeException**

_Originally posted by @ttool22 in https://github.com/gui-cs/Terminal.Gui/issues/1250#issuecomment-1211739635_

**Comment by tznind** [comment]
@ttool22 I have moved the discussion to a new issue because the one you posted in is about scroll view.  So while the Exception is the same (IndexOutOfRangeException) the root cause is likely to be different.

**Comment by tznind** [comment]
I've created a new console project with a combo box and it is working fine in 1.7.2

```csharp
using Terminal.Gui;

Application.Init();

var w = new Window();

ComboBox combobox1 = new ComboBox();
combobox1.SetSource(new List<string> { "cow", "dog", "fish" });
combobox1.Width = 10;
combobox1.Height = 4;
w.Add(combobox1);

Application.Run(w);

Application.Shutdown();
```

Can you provide more information about how your use case varies from the above?

- Do you have any event handlers?
- Do you ever change the source of the combo box? (e.g. from another Thread or in a callback)

**Comment by ttool22** [comment]
Yes, I have event handler for refreshing time every second. I call eventhandler for refreshing time in OpenSelectedItem

` timer.Elapsed += RefreshMatchTime`; 
` timer.Start();`
  
`static void RefreshMatchTime(object sender, ElapsedEventArgs e)
{
        MatchTime.Text = DateTime.Now.Second.ToString();
        Application.Refresh();  
}`

**Comment by tznind** [comment]
Ok thanks for the info.  I am able to reproduce your error.  Here is my repro:

```csharp
using System.Timers;
using Terminal.Gui;

Application.Init();

var w = new Window();

ComboBox combobox1 = new ComboBox();
combobox1.SetSource(new List<string> { "cow", "dog", "fish" });
combobox1.Width = 10;
combobox1.Height = 4;
w.Add(combobox1);

var timer = new System.Timers.Timer(10);
timer.Elapsed += (s, e) => {
    combobox1.Text = DateTime.Now.Second.ToString();
    Application.Refresh();
};
timer.Start();


Application.Run(w, (e) =>
        { 
            MessageBox.ErrorQuery("Badness", e.ToString(), "Ok");
            return false;
        }
        );

Application.Shutdown();
```

The solution is to always use `Application.MainLoop.Invoke` to update UI properties.  Please can you try updating your `RefreshMatchTime` method to use invoke:

```csharp
var timer = new System.Timers.Timer(100);
timer.Elapsed += (s, e) => {
    Application.MainLoop.Invoke(()=> { combobox1.Text = DateTime.Now.Second.ToString(); });
};

Make sure to get rid of your call to `Application.Refresh();` too.
timer.Start();
```

**Comment by tznind** [comment]
@ttool22 let me know if my suggestion works.  Alternatively if you haven't understood what I have said or how to implement it please say and I will try to rephrase.

If you do get it working make sure to close the issue as resolved

**Comment by ttool22** [comment]
@tznind 

Unfortunately it **doesn't** work

**Comment by tznind** [comment]
Can you share more of your code please? including the bit you updated with `Application.MainLoop.Invoke`

**Comment by ttool22** [comment]
`   timer.Elapsed += RefreshMatchTime;`
`   timer.Start();`

```
static void RefreshMatchTime(object sender, ElapsedEventArgs e)
{
    try
    {
        string matchTime = string.Empty;        
        Constants.Seconds = Constants.Seconds + 1;
        matchTime = Constants.Minutes + " : " + (Constants.Seconds).ToString();

        Application.MainLoop?.Invoke(() =>
        {         
            Constants.MatchTime.Text = matchTime;
            Application.Refresh();
        });
    }
    catch (Exception ex)
    {

    }
}


```

**Comment by ttool22** [comment]
I call it inside
```
ComboboxControl.OpenSelectedItem += async (ListViewItemEventArgs control) =>
{
  //code above
}
```
}

**Comment by ttool22** [comment]
You didn't call it inside  ComboboxControl.OpenSelectedItem, When I click on item in Combobox I start refresh time every second then I remove characters from combo, then error is thrown "IndexOutOfRangeEdxception"

**Comment by BDisp** [comment]
Remove `Application.Refresh();` from the code because the `Application.MainLoop?.Invoke` already will update the UI Thread.

**Comment by tznind** [comment]
I have updated and changed the assignment to be a Label rather than the combo box as I assume you are using.  It is still working as intended with no Exception.

![onopen](https://user-images.githubusercontent.com/31306100/184365045-053bd5dc-d7e0-4843-b6cb-4416322878a1.gif)

The differences I can see vs your code are:
- I only create one timer (regardless of how many times user confirms selection)
- I don't call `Application.Refresh` (as @BDisp said)

```csharp
using System.Timers;
using Terminal.Gui;

Application.Init();

var w = new Window();

Label matchTime = new Label();
matchTime.Width = 20;
matchTime.Height = 1;
matchTime.Y = 6;

ComboBox combobox1 = new ComboBox();
combobox1.SetSource(new List<string> { "cow", "dog", "fish" });
combobox1.Width = 10;
combobox1.Height = 4;

w.Add(combobox1);
w.Add(matchTime);

System.Timers.Timer? timer = null;

/*I've added async keyword here because you have it in your code but it has no effect*/
combobox1.OpenSelectedItem += async (ListViewItemEventArgs control) =>
{
    // do not create multiple timers
    if(timer == null)
    {
        timer = new System.Timers.Timer(10);
        timer.Elapsed += (s, e) =>
        {
            Application.MainLoop.Invoke(() => { matchTime.Text = DateTime.Now.Second.ToString(); });
        };
    }
    timer.Start();
};

Application.Run(w, (e) =>
        { 
            MessageBox.ErrorQuery("Badness", e.ToString(), "Ok");
            return false;
        }
        );

Application.Shutdown();
```
