### ISSUE TITLE
[Question] How to get list of marked items in `ListView`?

### ISSUE THREAD

**Issue by dend** [gui-cs/Terminal.Gui#1957]
I've successfully marked items with `AllowMarking` enabled but I now need to get the list of items that were marked. What's the best way to do that for the `ListView` instance? Doesn't seem like there is a direct property here.

**Comment by BDisp** [comment]
You have to get all the `IsMarked` that are true, like this:

```cs
var result = new List<string>();
for (int i = 0; i < source.Count; i++) {
	if (list.Source.IsMarked (i)) {
		result.Add(source [i]);
	}
}

```

**Comment by dend** [comment]
Thank you @BDisp 👏
