### ISSUE TITLE
Key Bindings in UI Catalog crashes

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#1961]
<img width="405" alt="image" src="https://user-images.githubusercontent.com/585482/186544015-ca1e2144-8bc0-496d-bf7b-23101d7dbc9e.png">

**Comment by tznind** [comment]
I've fixed this in https://github.com/gui-cs/Terminal.Gui/pull/1965 

It seems there was a change in behaviour where `SelectedItemChanged` could be fired before the View had finished construction as a byproduct of `OnEnter`.  I fixed the issue by moving the event handler registration to the last thing in the constructor and manually called the 'update view' functionality for the first list item after that.
