### ISSUE TITLE
Backspace key deletes multiple characters when editing a TextView with WordWrap = true

### ISSUE THREAD

**Issue by hippiehunter** [gui-cs/Terminal.Gui#1963]
While editing a TextView that has wordwrap turned on. Pressing the backspace key anywhere other than the last line in the window will delete 2 characters. If the backspace key deletes the last line in the file, an out of range exception will be generated trying to remove a non existent line.

1. Run the UI Catalog
2. Select Dialogs -> Editor
3. Enable word wrap in the Format menu
4. Move the cursor into the middle of the first 'hello'
5. Press backspace

**Expected behavior**
only one character should be deleted

**Comment by BDisp** [comment]
The delete key also causes this behavior when word wrap is enabled. Can you fix it too? Thanks.

**Comment by BDisp** [comment]
@hippiehunter see my fix here https://github.com/BDisp/Terminal.Gui/tree/textview-word-wrap-delete-backwards-forwards-fix.
