### ISSUE TITLE
Avoid positioning Submenus off screen

### ISSUE THREAD

**Issue by tznind** [gui-cs/Terminal.Gui#1973]
**Is your feature request related to a problem? Please describe.**
When performing a right click near the right edge of the console the context menu location is adjusted to present the whole menu (if possible).  However submenus are still opened to the right (i.e. off screen). 

![image](https://user-images.githubusercontent.com/31306100/187140776-1c865781-c2f4-41fc-b914-f72eceb62b88.png)
_Terminal.Gui context menu submenu opened at right of screen, only first few letters of menu are visible_

**Describe the solution you'd like**
Either open the submenu to the left or ontop of the previous menu e.g.:

![image](https://user-images.githubusercontent.com/31306100/187141046-f7afef85-ec69-4706-93fb-962fbd8ab1f5.png)
_Notepad++ submenu cannot fit on the right due to the screen edge so is presented to the left_

**Comment by BDisp** [comment]
Only to remember there is also a flag `UseSubMenusSingleFrame` when it's enabled, onli a single frame is show for the menus and sub-menus.
