### ISSUE TITLE
 MessageBox.Query not wrapping since 1.7.1

### ISSUE THREAD

**Issue by tznind** [gui-cs/Terminal.Gui#1979]
**Describe the bug**
In 1.6.4 MessageBox.Query would wrap long messages but as of 1.7.1 it no longer does. 

Did the default value of WordWrap change or is it something else?  The issue is still there in `main` branch (no wordwrap)

![image](https://user-images.githubusercontent.com/31306100/187896732-e8435ee0-6263-418b-87db-500c19f05ffe.png)

**Comment by BDisp** [comment]
Only to stay registered for anyone that may confused about the `AutoSize` property:
* If it's true the view text size will be calculated, so the line will be used to calculate the width and the newlines will used to calculate the height.
* If it's false the view bounds will be used.

That said, it has nothing to do about fitting on his container. For that the` Pos/Dim` are used.

**Comment by tig** [comment]
#1980 broke UI Catalog's about box, so I reverted it and have re-opened this issue.

**Comment by tig** [comment]
<img width="311" alt="image" src="https://user-images.githubusercontent.com/585482/188470938-1d643e03-5684-466a-bc40-006b22b2b791.png">

**Comment by BDisp** [comment]
I almost have a fix for this.

**Comment by BDisp** [comment]
> I almost have a fix for this.

Fixed on the #1995.

**Comment by ArgusMagnus** [comment]
I am still having this issue with v1.8.0 on windows/net6.0.

**Comment by BDisp** [comment]
I copied the Help menu from the `UICatalog` and pasted into the `StandaloneExample` net6.0 project which use the 1.8.0 nuget package and it's wrapping fine. Can you explain better why it's not working for you, please.

![imagem](https://user-images.githubusercontent.com/13117724/191553014-5369a211-3b9e-4231-8d5a-256743334093.png)

**Comment by BDisp** [comment]
@ArgusMagnus if you still having issue with this please report it here #2053.

**Comment by BDisp** [comment]
> I am still having this issue with v1.8.0 on windows/net6.0.

Fixed in https://github.com/gui-cs/Terminal.Gui/pull/2054/commits/92dc7f04d4535efad236500d7c621cdc87564a38
