### ISSUE TITLE
Setting Label.Visible to false does not hide the Label

### ISSUE THREAD

**Issue by heinrich-ulbricht** [gui-cs/Terminal.Gui#1984]
**Describe the bug**
In ReactiveExample, binding `Label.Visible` to a boolean does not hide the label when the boolean turns false.

**To Reproduce**
1. Clone the repo
2. In Visual Studio, open `Terminal.sln`, set `ReactiveExample` as Startup project
3. In `ReactiveExample` -> `LoginView.cs` make the following change (replace setting `ColorScheme` with setting `Visible`):

![image](https://user-images.githubusercontent.com/3469970/188268147-24c41232-b289-4488-84b7-1bd1c2c424e4.png)

4. Run and fill the input fields, then clear the input fields

**Expected behavior**
I expect the label to disappear when both input fields contain values This does not happen, it just stays, showing the same old text.

(My goal is to hide the validation label when the input fields are filled.)

**Screenshots**

**Modified app (as in above screenshot)**
Starting the app all is well, the label is showing ("Please, enter..."):

![image](https://user-images.githubusercontent.com/3469970/188268203-00fa72cd-472a-4d55-8659-e42365d61216.png)

After entering text the label should disappear, but instead still shows the "old" text ("Please, enter..."):

![image](https://user-images.githubusercontent.com/3469970/188268218-36ffc157-b401-4fdd-b6bb-8b32d7fc24ba.png)

**UNmodified app (as freshly pulled)**
Just to check that the bindings etc. are all set up I reverted back to the unmodified version. Here is the app when starting, showing the validation text (here in red since the code for changing the `ColorScheme` is active):

![image](https://user-images.githubusercontent.com/3469970/188268242-9c45472b-c9a5-4647-b5ff-4780ea95a1d0.png)

The validation text changes properly when having filled both input fields ("The input is valid"):

![image](https://user-images.githubusercontent.com/3469970/188268258-b5954ffa-30ba-46df-b6a6-4f108db03070.png)

And it changes back when clearing the input fields:

![image](https://user-images.githubusercontent.com/3469970/188268403-6cada197-221d-48e4-a71c-2573ba41e086.png)

Am I wrong in my expectation that hiding the label should be possible as well? If yes, how else would I do it?

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 1.7.2
 - .NET 6 console app

**Additional context**
-

**Comment by tznind** [comment]
Thanks for reporting this, looks like @BDisp has gotten a fix in for it and a unit test to prevent it happening again 🏆 .

**Comment by BDisp** [comment]
I'm reopen this because it's causing some bad behaviors on situations where we don't want to clear the view at all. I appreciate suggestions for this. On example where I don't want to clear is on a `ScrollBarView` when set Visible to false I don't want the area been cleaned if the Redraw method is overridden.
