### ISSUE TITLE
[Question]: ProgressBar Dialog while background process is in progress.

### ISSUE THREAD

**Issue by jmelosegui** [gui-cs/Terminal.Gui#2001]
I was trying to display a Dialog with a progress bar while waiting for a background process to finish.
On background process complete, I call the `Application.End(runState)` method.
Then an exception is thrown inside the `Application.RunLoop (runState)` method.

The following code is a simplification of what I intend to do in a form of a unit test.

```
[Fact, AutoInitShutdown]
public void Dialog_Test ()
{
	var d = new Dialog ("Dialog with a progress bar");
	var rs = Application.Begin (d);
	var awaiter = Task.Delay (100).GetAwaiter ();

	awaiter.OnCompleted (() => {
		Application.End (rs);
	});

	var exception = Record.Exception(() => Application.RunLoop (rs));
	Assert.Null (exception);
}
```

am I missing something here?

**Comment by BDisp** [comment]
You have to wait until the `Application.RunLoop` been finished. Change to this:
```cs
[Fact, AutoInitShutdown]
public void Dialog_Test ()
{
	var d = new Dialog ("Dialog with a progress bar");
	var rs = Application.Begin (d);
	var awaiter = Task.Delay (100).GetAwaiter ();

	awaiter.OnCompleted (() => {
		Application.RequestStop ();
	});

	var exception = Record.Exception (() => {
		Application.RunLoop (rs);
		Application.End (rs);
	});
	Assert.Null (exception);
}

```

**Comment by jmelosegui** [comment]
Thanks @BDisp  for your prompt answer.
I will try your suggestion and let you know my results.

**Comment by tznind** [comment]
For reference this is how I did it in [the designer Open method](https://github.com/gui-cs/TerminalGuiDesigner/blob/e2e2606a6a029655a234b633a92e4335bab9c356/src/UI/Editor.cs#L742-L777):

```csharp
// Create the loading screen
var open = new LoadingDialog(toOpen);

[...]

// begin the long running task
Task.Run(()=>{
    
    var decompiler = new CodeToView(new SourceCodeFile(toOpen));
    _currentDesignerFile = decompiler.SourceFile;
    instance = decompiler.CreateInstance();


}).ContinueWith((t,o)=>{


    // no longer loading
    Application.MainLoop.Invoke(()=>Application.RequestStop());


    if (t.Exception != null)
    {
        Application.MainLoop.Invoke(() =>
            ExceptionViewer.ShowException($"Failed to open '{toOpen.Name}'", t.Exception));
        return;
    }


    // if loaded correctly then 
    if (instance != null)
        ReplaceViewBeingEdited(instance);


},TaskScheduler.FromCurrentSynchronizationContext());

// launch the loading screen
Application.Run(open,ErrorHandler);

```

![image](https://user-images.githubusercontent.com/31306100/189297126-1aee2552-5500-47a1-95a6-267d44379af2.png)


I was a little worried with this pattern that the `Task.Run` delegate could finish before the `Application.Run` and maybe somehow close the main UI instead of the progress one but I think that is just paranoia.

**Comment by jmelosegui** [comment]
@BDisp the second approach you suggested worked perfectly.

@tznind I found that myself the hard way 😞  (I won't get those hours back).
But thanks for the tip. Now we have it here just in case someone else finds this issue.
