### ISSUE TITLE
TextView: Terminal Paste (Ctrl-V), pastes one char at a time, and has weird visual effects.

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#2009]
**Describe the bug**
Paste, pastes one char at a time, and has weird visual effects.

**To Reproduce**
1. Run `Text Input Controls` Scenario (or Editor)
2. Click on multi-line TextView
3. Go to https://baconipsum.com/?paras=5&type=all-meat&start-with-lorem=1
4. Copy contents to clipboard
5. Return to UI Catalog
6. Paste

**Expected behavior**
Text is pasted quickly, with no weird visual effects. 

**Screenshots**
![2SmKRx9 1](https://user-images.githubusercontent.com/585482/190295931-e85b6961-044e-46fd-84d4-cbb143d599cb.gif)

This was on Windows Terminal.

Note using the Terminal.Gui Paste (Ctrl-Y or context menu) works as expected.

**Comment by tznind** [comment]
I think that console paste will send each character one after the other to the terminal input stream.  Presumably either with a delay or flushing each character?  So each keystroke is read and processed one after the other with redraw after every one.

![image](https://user-images.githubusercontent.com/31306100/190334679-b09132e8-f5fc-4122-9470-ca287c866d68.png)

The Terminal.Gui context menu Paste will read the contents of the OS clipboard directly.  Terminal.Gui Copy/Paste has multiple implementations and some have dependencies (e.g. on linux the dependency is `xclip`).

Not sure what the most elegant way of dealing with this 'autotyping' is.

- Does the TextView delay its updates to see if more keys are comming?
- Does the driver delay releasing keys and use a flag to indicate when an event is part of a large collection of inbound keys?

I'm not sure either of these are great solutions.  But thought they were worth making to get the ball rolling discussing how we might address this issue.

FWIW I have seen this behaviour in other domains where 'auto typing' happens (e.g. keyboard macros or password managers).

**Comment by BDisp** [comment]
For sure the `Windows Terminal` is sending each key from the clipboard to the running application. `Terminal.Gui` processes this keys in the same way if it's the user were typing. The only way to avoid this is delete the shortcut key `Ctrl+V` from the `Windows Terminal`. Unfortunately there are no option to disable it, so it have to be deleted. It is really a good idea the `Windows Terminal` provide an option do disable all the shortcuts when we are running the application, like the `gnome` for `Linux `has. For this reason when I'm debugging and testing something I prefer using the `Host Windows Console` for `Windows` and `gnome` for `Linux`. At least these terminal respects the setting in each `Terminal.Gui` drivers to disable the terminal defaults and thus only the `Terminal.Gui` application keystrokes are used.

**Comment by tig** [comment]
Ok, so this is what it is. "As designed". Closing.
