### ISSUE TITLE
Keyboard: Why is CTRL-Y the paste key?

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#2010]
On Mac & Windows, the standard for cut, copy, and paste is

Ctrl/Cmd-X
Ctrl/Cmd-C
Ctrl/Cmd-V

e.g. Notepad:
<img width="169" alt="image" src="https://user-images.githubusercontent.com/585482/190296210-311aac8b-1f18-4ded-935e-d86f155eea76.png">

Why is Terminal.Gui's:

<img width="167" alt="image" src="https://user-images.githubusercontent.com/585482/190296154-31359926-45d0-4e73-93b6-8c314a890a56.png">

**Comment by BDisp** [comment]
The TextView at the begin came with that key combination and I didn't change it before to not break anything. But I think it must be standardized.

**Comment by tig** [comment]
If the Terminal captures CTRL-V, for example, is it possible for us to intercept it?

**Comment by BDisp** [comment]
> 
I don't think so. Sometimes I have to delete some Terminal short keys to be able to use Terminal.Gui  keys.

**Comment by BDisp** [comment]
If the change are made the we need to modify the existing one. 

`AddKeyBinding (Key.V | Key.CtrlMask, Command.PageDown);`

This uses Alt key so I don't know if it's needed to change:

`AddKeyBinding (((int)'V' + Key.AltMask), Command.PageUp);`

**Comment by migueldeicaza** [comment]
Control-y is part of the Unix tradition of  keybindings.   As seen in Emacs and all shell apps.

**Comment by tig** [comment]
> Control-y is part of the Unix tradition of keybindings. As seen in Emacs and all shell apps.

Good reason. I'm going to close this issue.
