### ISSUE TITLE
Add DatePicker control

### ISSUE THREAD

**Issue by ttool22** [gui-cs/Terminal.Gui#2019]
Can I represent more dates in DateField then choose one? I need **DatePicker** here in terminal?

**Comment by tznind** [comment]
Hi, thanks for asking.  Do you mean:

- Enter a range of dates? (e.g. 2001-01-01 to 2009-01-01)
- Or ability to support multiple date formats
- Or to have a visual day calendar with arrows for year/month?

**Comment by ttool22** [comment]
Whatever It would be good when I can select a date from Now to some date

**Comment by tznind** [comment]
Having a fully tui DatePicker would definetly be cool and a good ticket for the backlog.  But for the 'here and now' you might have to just consider using 2 `DateField` instead?

```
Start Date: |_______________|
End Date  : |_______________|
```

**Comment by ttool22** [comment]
No, the user has to select one date from that range, but I'll use multiple combo boxes first for months, second for days
