### ISSUE TITLE
Branch `develop` is in a screwed-up state

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#2033]
Yesterday, as I was fixing #2027 I somehow merged an old `main` branch into `develop`.

This caused a bunch of PRs that I was also reviewing and merging to get screwed up. 

So, right now, the `develop` branch is pretty much hosed.

This Issue documents my progress in trying to fix all of this.

What I know so far:

* `main` is fine. I've reviewed the history and the fixes to the API documentation are the only changes since the v1.7.2 tag. 
  * Link to tag: https://github.com/gui-cs/Terminal.Gui/releases/tag/v1.7.2
  * Link to commit for tag: https://github.com/gui-cs/Terminal.Gui/commit/8e20fb788d1bd62d73814767bf0d403ec7f4bd7f
* The error occurred when I attempted to pull `main` forward into `develop` when I merged this PR: https://github.com/gui-cs/Terminal.Gui/pull/2027. The commit was: https://github.com/gui-cs/Terminal.Gui/commit/a45314e4a9e6e3e0d1869c0e17cf1aa52abac9f3.
* So, `develop` was in a good state at the commit prior to that, which was https://github.com/gui-cs/Terminal.Gui/commit/b7ecb827f06168759cbc9510af7fc97e0a7053ec

After that, the following commits to `develop` are suspect:

* Merge branch 'develop' of tig:gui-cs/Terminal.Gui into develop - befb063faed679c2db36f8fee42bc1ba72e11d49
  * This commit occurred when I merged PR #2028 (6d3d5cc38106d155f43a29c772fe73b03231e5c7)
  * It appears to bring a bunch of old/bogus stuff in
  * 

Now, the job is to go through all the subsequent PRs & commits and ensure that all the good work @BDisp did after that gets re-merged...

Here are the impacted commits:

- [ ] Merge branch 'develop' of tig:gui-cs/Terminal.Gui into develop: b7ecb827f06168759cbc9510af7fc97e0a7053ec
  * Includes the changes @BDisp put in to fix #2014 (PR https://github.com/gui-cs/Terminal.Gui/pull/2015)
- [ ] Removed docs folder because gh-pages branch is now used: 9d1e9c9dd03b7211de8b74b74113a24c8cc0faab
- [ ] Ignore ./docs folder: 0321b25b0e6f196cc2c0188dbce3d2cc0f380218
- [ ] Fixes #2026. Added ClearOnVisibleFalse to flag if the view must be clear…: 281a849c0886e519edfcc5851941dde757e102d7
  * PR #2020 
- [ ] Fixes #2025 - API Docs are now generated via Github Action - View Source… : c6001c794b268153617d7f2c285bdd36da3e8972
  * PR #2027 
- [ ] Puts API doc overrides in ./docfx/overrides folder: 18c86032d02bea0eed4ff73411136a85b48020d1
  * PR #2029 

I've created a new branch, `develop_pre_screwup`, at b7ecb827f06168759cbc9510af7fc97e0a7053ec.

I'm now going to re-create #2014, #2020, #2027, and #2029 on that branch...

Please check my math if you're paying attention....

**Comment by tig** [comment]
Ok, `develop` is now "clean" but is missing:

* Fix for Issue #2014 - #2033
* Fix for Issue #2026
* Fix for Issue #2025

**Comment by tig** [comment]
Ok, this is all fixed & cleaned up. I think.

@BDisp - please double check.

**Comment by BDisp** [comment]
> Ok, this is all fixed & cleaned up. I think.
> 
> @BDisp - please double check.

@tig I confirm that all fixed. I did a rebase all my branches and is well updated with the develop branch. Thanks for your hard work.
