### ISSUE TITLE
Can no longer nest `Application.MainLoop.Invoke` (since 1.8.2)

### ISSUE THREAD

**Issue by tznind** [gui-cs/Terminal.Gui#2073]
**Describe the bug**
This is a behavior change in 1.8.2 and not present in 1.7.2

If a view is launched via Invoke e.g.

```csharp
btnLaunch.Clicked += ()=>{
    Application.MainLoop.Invoke(()=>Application.Run(startWindow));
    };
```

Then any calls to Invoke that are triggered from the `startWindow` are blocking and never finish until the window is closed.

While the issue is easiest to demonstrate by launching a window via Invoke I think the issue manifests in other ways too.  For example I have a window where callbacks cannot be registered in 1.8.2 (blocks until window is closed) - see https://github.com/HicServices/RDMP/pull/1448 .  

![image](https://user-images.githubusercontent.com/31306100/193575017-b8f502aa-88ff-4858-bec8-d9f38a2f244c.png)

I have looked hard and can't see any problematic Invokes in my code but I think it is definitely related to the new locking behavior

UPDATE: Ok I know why my code is getting this deadlock, it is because of the use of ContextMenu.  If you update the demo code to launch the test window via a menu you get same problem:

```csharp

var menu = new ContextMenu();
menu.MenuItems = new MenuBarItem(new []{new MenuItem("Launch",null,()=>Application.Run(startWindow))});

    btnLaunch.Clicked += ()=>{
        menu.Show();
    };
```
![blocking](https://user-images.githubusercontent.com/31306100/193577893-54f5ba7a-de2b-4eb3-b301-b039a3618e95.gif)
_When running on 1.8.2 the 'Click Me' button gets stuck at 'Cancel' and its callback to increment the counter never happens. So total only increases by 1 when you press it instead of 4.  In 1.7.2 it works correctly_

**To Reproduce**
I have created a minimum repro:

```csharp
using Terminal.Gui;

class Program
{
    static int total = 0;
    static Button btn;
    public static void Main()
    {
        Application.Init();

        var startWindow = new Window{
            Modal = true
        };

        btn = new Button{
            Text = "Click Me"
        };

        btn.Clicked += RunAsyncTest;

        var totalbtn = new Button(){
            X = Pos.Right(btn),
            Text = "total"
        };

        totalbtn.Clicked += ()=>{
          MessageBox.Query("Count",$"Count is {total}","Ok");
        };


        startWindow.Add(btn);
        startWindow.Add(totalbtn);

        var splash = new View();
        var btnLaunch = new Button("Open Window");
        
        // Goes fine
        /*btnLaunch.Clicked += ()=>{
            Application.Run(startWindow);
            };*/
        // Goes badly
        btnLaunch.Clicked += ()=>{
            Application.MainLoop.Invoke(()=>Application.Run(startWindow));
            };

        splash.Add(btnLaunch);

        Application.Top.Add(btnLaunch);

        Application.Run();

        Application.Shutdown();

    }

    private static void RunAsyncTest()
    {
        btn.Text = "Cancel";
        Interlocked.Increment(ref total);
        btn.SetNeedsDisplay();
        
        var task = Task.Run(()=>
        {
            try
            {
                RunSql();
            }
            finally{
                SetReadyToRun();
            }
        }).ContinueWith((s,e)=> {
            
            Interlocked.Increment(ref total);

            },TaskScheduler.FromCurrentSynchronizationContext());
    }

    private static void RunSql()
    {        
        Thread.Sleep(100);
        Application.MainLoop.Invoke(() => { 
            Interlocked.Increment(ref total);
            btn.Text = "Pew Pew";
            btn.SetNeedsDisplay();
        });
    }

    private static void SetReadyToRun()
    {
        Application.MainLoop.Invoke(()=>{
            btn.Text = "Click Me";
            Interlocked.Increment(ref total);
            btn.SetNeedsDisplay();
        });
    }
}
```
For csproj use:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Terminal.Gui" Version="1.8.2" />
  </ItemGroup>

</Project>
```
Run program then change back to 1.7.2 package reference

**Expected behavior**
Not sure, I'm open to discussion

**Comment by BDisp** [comment]
This is due to the #1994. @tig had alerted about (BREAKING CHANGE). So the question is would if this is the write behavior, avoiding tasks popup on the main thread that uses a modal as true, or should to be reverted to the previous behavior?

**Comment by tznind** [comment]
I think in terms of user stories we want to start with the following:

**I want to be able to launch modal dialogs from `Button` or `ContextMenu` click handlers.  And for those windows to behave normally (i.e. be able to use invokes).**

Currently launching a modal Window from `Button` behaves differently from `ContextMenu` (The difference being that the resulting dialog cannot do its own invokes).  I think because `Action` gets run through invoke in `Menu`:

https://github.com/gui-cs/Terminal.Gui/blob/32e7b63b77655ff07dc3a9dce6074e77d0590fa3/Terminal.Gui/Views/Menu.cs#L571-L584

While in `Button` it is not:

https://github.com/gui-cs/Terminal.Gui/blob/7b93f443fe68aa2c713f27486e3cae3184bf3ac0/Terminal.Gui/Views/Button.cs#L229-L235

We should understand why they are behaving differently, which one is more correct and how we can adjust the current code to still have the good stable locking stuff added in #1994 but also allow for this user story.

**Comment by BDisp** [comment]
Sorry, I made confusion because I thought you wanted that the follow should work, but was only to demonstrate the behavior you have mention.
`Application.MainLoop.Invoke(()=>Application.Run(startWindow));`

The menu run action is the same as the original but since the idle handlers lock was fixed, running a action through the `Application.MainLoop.Invoke` will block another following calls through the `Application.MainLoop.Invoke` because the running action block the idle handlers. If you wish I can submit a PR to change the `Menu` action calls or if you already have a fix for this I let you fix it.

**Comment by tznind** [comment]
> Sorry, I made confusion because I thought you wanted that the follow should work, but was only to demonstrate the behavior you have mention. `Application.MainLoop.Invoke(()=>Application.Run(startWindow));`

Yeah my post was a bit muddled, sorry about that.  I created Issue when I had a repro but before I had traced it down to ContextMenu callback being the responsible. 

Good fix though! Thanks
