### ISSUE TITLE
Enable collection initializer syntax for View

### ISSUE THREAD

**Issue by kzu** [gui-cs/Terminal.Gui#2078]
Would be nice to add support for the more structural/declarative style allowed by 
collection initializers when creating views, such as:

```csharp
	var view = new View {
		new View {
			new View()
		},
		new View()
	};
```

The only reason this currently doesn't work is that `View` does not implement `IEnumerable`:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1922	Cannot initialize type 'View' with a collection initializer because it does not implement 'System.Collections.IEnumerable'	UnitTests	...Terminal.Gui\UnitTests\ViewTests.cs	122	Active
```

The view could implement that interface explicitly like so:

```csharp
IEnumerator IEnumerable.GetEnumerator () => Subviews.GetEnumerator ();
```

And that alone would enable this usage, since the class already provides an `Add(View)` method, which is 
the other thing the compiler looks for in this initialization pattern.

**Comment by tznind** [comment]
A compromise has been agreed in principle to use `params` constructor for this use case.  See : https://github.com/gui-cs/Terminal.Gui/pull/2079#issuecomment-1283077623 for full discussion

**Comment by BDisp** [comment]
But he prefers overload your own class. Maybe you can submit a new PR with your params suggestion @tznind .
