### ISSUE TITLE
Resizing when a context menu is open causes the `Enter` event to get spammed

### ISSUE THREAD

**Issue by tznind** [gui-cs/Terminal.Gui#2095]
**Describe the bug**
The `Enter` event seems to be incorrectly firing while context menus are open.  Here is an app that demos the problem (see below).  It is most apparent when resizing.  Although I have also seen Enter events fired at other times when a context menu is opened (I first noticed it in TerminalGuiDesigner), in that case I think `Enter` was firing when the submenu popped.

**Expected behavior**
While a context menu is open no Enter events should be raised unless they are directly registered on the context menu itself.

```csharp
using Terminal.Gui;

Application.Init();
Application.Top.ColorScheme = Colors.Base;

// for logging output
var events = new TextView { ReadOnly = true, X = 50, Y = 1, Width = Dim.Fill(), Height = Dim.Fill(), Text = "Events:"};

// a root view
var root = new View() { Width = Dim.Fill(), Height = Dim.Fill(), ColorScheme = Colors.Base };
root.Enter += (s) => { events.Text += $"\nEntered root";};
root.Add(events);

// with a label (that is focusable)
var lbl = new Label("Name:") { Y = 0, CanFocus = true };
lbl.Enter += (s) => events.Text += $"\nEntered Label";
root.Add(lbl);

// and a text field
var tf = new TextField() { X = Pos.Right(lbl) + 1, Width = 10 };
tf.Enter += (s)=> events.Text += $"\nEntered TextField";
root.Add(tf);

Application.Top.Add(root);
Application.Run();
```

![wierdevents](https://user-images.githubusercontent.com/31306100/196442656-5147f392-0ee3-4e5d-affb-6e657ed7daf8.gif)
_Resizing when context menu is open causes misfiring Enter events_

**Comment by tig** [comment]
Is this still repo?

**Comment by BDisp** [comment]
> Is this still repo?

Yes it repro on the v1. Also see the gray background color before I click in the `TextField`. I think it's related with the #2571.

https://github.com/gui-cs/Terminal.Gui/assets/13117724/bddc2016-2741-4aaf-afda-2f69951b6f05

Not repro on  v2.

https://github.com/gui-cs/Terminal.Gui/assets/13117724/a81684d1-a0bf-4b5e-b2ca-e13db98e0bf1
