### ISSUE TITLE
StatusBar should support right alignment on last StatusItem

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#2106]
I was playing with the TabView scenarios and hated how Notepad looked. Just so much wasted rows/columns ;-).

In the process, I decided to to move the "Len: " indicator to the status bar. But I really want it aligned right!

<img width="565" alt="image" src="https://user-images.githubusercontent.com/585482/196818301-df371e4f-8f91-47bc-a18d-44ac5b0bf51f.png">

One way to fix this would be to support `StatusBar.ItemAlignment` property on `StatusBar` that works like `Dialog.ButtonAlignment`.

This would be trick, but wouldn't really get me what I want. The default would be `Left`.

Another idea would be to support an `StatusItem.Alignment` (Left, Center, Right..Justify doesn't make sense).

**Comment by ThomasNieto** [comment]
I was also looking for this feature but I would like to have multiple items on the right. In my use case I would have the action status items on the left and read-only status items on the right.

**Comment by tznind** [comment]
I agree! this would be very nice feature

**Comment by tig** [comment]
Closing as dupe of 

- #3073
