### ISSUE TITLE
ContextMenu: If there's no MenuBar, F9 should open/close the context menu

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#2114]
Totally a minor issue, but it would be a nice enhancement to make things more consistent.

But consider this: If there IS a MenuBar, and a Context Menu is open, what should F9 do?

**Comment by BDisp** [comment]
> But consider this: If there IS a MenuBar, and a Context Menu is open, what should F9 do?

Would open the MenuBar. ContextMenu has his own key binding.

**Comment by BDisp** [comment]
> And the Context Menu would close?

Yes, it should. Otherwise have to be fixed.

**Comment by BDisp** [comment]
Related to #2121. @tig can this be closed?
