### ISSUE TITLE
TreeView: Cursor caret should not be visible

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#2120]
![V1c1hcw 1](https://user-images.githubusercontent.com/585482/197099904-3efdcf09-dbb1-42a1-81f1-bdb25c5c4c3e.gif)

We've been slowly getting rid of the flashing caret on non-input Views. TreeView still does it.

**Comment by BDisp** [comment]
@tig how you configured the inverted color on the cursor in Windows Terminal?

**Comment by tig** [comment]
> @tig how you configured the inverted color on the cursor in Windows Terminal?

I have no idea. I don't think I did anything. 

When I start the TreeView scenario the cursor is green:

<img width="298" alt="image" src="https://user-images.githubusercontent.com/585482/197253898-196d7220-5b58-4413-a718-b6edd7844c45.png">

It turns black once I select something.

FWIW, Here's my `cursorColor` in Windows Terminal settings .json (it should be yellow).

<img width="269" alt="image" src="https://user-images.githubusercontent.com/585482/197253732-8ec3bd24-4fa7-49ee-b17d-90a047838951.png">
