### ISSUE TITLE
Scrolling Scenario: Weird visual artifacts

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#2122]
- Focusing the TextView causes the background color to change to blue
- When it has focus, there's a flickering horizontal bar
- Background changes to black when scrolling horizontally (or vertically)

I don't know if these a bugs in the Scenario or elsewhere.

![aFr00WG 1](https://user-images.githubusercontent.com/585482/197101330-f04accbd-a234-4936-a49f-fc8f74e28fbb.gif)

**Comment by BDisp** [comment]
> * Focusing the TextView causes the background color to change to blue
> 
There are none `TextView` in the scenario.

> * When it has focus, there's a flickering horizontal bar
> 
The flickering horizontal bar doesn't happen to me. The change color (Focus of the Colors.TopLevel) is due the PR #2104 which clear the views that are public or nested public and isn't overridden. Well, the `ScrollView` has a private `View.contentView` that instantiate the public `View` class. One solution for this is making the `contentView` instantiate a nested private class derived from `View`. The second solution is creating a `bool` property `ClearOnRedraw` in the `View` class with the default value as `false`. The view is only cleared if it's `true`.
Maybe there are also another views affected by this change. What yours opinions?

> * Background changes to black when scrolling horizontally (or vertically)

This is a bug. The focus color is only apply to the `Clear (ViewToScreen (bounds))` and should be `Clear ()` on the `View.Redraw` method.

**Comment by BDisp** [comment]
The third solution is fix the clearing bug and leave it as is. Looks cool :-)

![clear-fix](https://user-images.githubusercontent.com/13117724/197218087-5780b4c3-707e-4df0-b313-b1fc334a68cb.gif)
