### ISSUE TITLE
ScrollView: Tabbing to views outside of currently visible area

### ISSUE THREAD

**Issue by tznind** [gui-cs/Terminal.Gui#2139]
**Is your feature request related to a problem? Please describe.**
When using the Tab key to navigate to a View outside of the current scroll area of a ScrollView there is no update of scroll window.  It would be nice if it adjusted the current scroll location so that the focused view is visible.

**Describe the solution you'd like**
If possible adjust scroll location horizontally or vertically to expose as much of the newly focused view as possible (starting with its upper left)

**Describe alternatives you've considered**
Possibly something could be done with events to make this happen outside of ScrollView.

**Additional context**
This behavior would be consistent with other UIs like browsers or text editors where the focused location is always brought into the scroll area when changed.

**Comment by tig** [comment]
Closing. `ScrollView` no longer exists.
