### ISSUE TITLE
ComboBox: List not populating/showing when tabbing into?

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#2149]
![x6721QW 1](https://user-images.githubusercontent.com/585482/199152842-12a5e9b5-a975-4c42-8a41-7ee8000d1955.gif)

Not sure if this is a bug in `ComboBox` or the `ListView & ComboBox` Scenario.

**Comment by tig** [comment]
I'm going to move this out of the v1.9 milestone; it's existed for a while and nobody but me complained. we can fix it later.

**Comment by BDisp** [comment]
I think this isn't a issue anymore. To open the combo box simple press F4 or click on the down arrow button.
