### ISSUE TITLE
NStack v1.0.5 breaks `System_Rune_ColumnWidth` unit test

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#2171]
This is the new NStack release with "Ustring ConsoleWidth must return the exactly character size or zero and not the Rune.ColumnWidth if it's negative" fix by @BDisp in https://github.com/gui-cs/NStack/pull/84

https://github.com/gui-cs/NStack/releases/tag/v1.0.5

I've de-listed v1.0.5 from NuGet for now...

@BDisp can you explain what's going on? I assumed (perhaps incorrectly) that you had tested that fix. Thanks.

**Comment by BDisp** [comment]
@tig, yes I know that will fail with the `Terminal.Gui` unit tests, but I need to update to the latest nuget package version to fix it, thanks.

**Comment by BDisp** [comment]
@tig I submitted the PR https://github.com/tig/Terminal.Gui/pull/5 with the fixes.

**Comment by tig** [comment]
FWIW, i've now re-listed Nstack v1.0.5 on nuget.
