### ISSUE TITLE
Cursor shows up only after focus has changed (e.g. `GraphView` and `TabView`)

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#2175]
On Views that don't explicitly hide the cursor like GraphView and TabView, the blinking cursor appears only after some Focus events happen.

1) I don't believe either GraphView or TabView should show a blinking cursor on Focus.
2) This cursor behavior is odd and clearly a bug.

![cjCgGUo 1](https://user-images.githubusercontent.com/585482/200042654-3edca11e-158a-4b7f-851e-1c9c2f9dbf1c.gif)

Or TabView:

![dIlpZv4 1](https://user-images.githubusercontent.com/585482/200005667-ba0a322e-9a6d-46c4-a1b7-f93125cb95cf.gif)

**Comment by tig** [comment]
Definitely a regression. Here's `main`:

![Y5a5DqU 1](https://user-images.githubusercontent.com/585482/200006580-3405feb8-09bf-400f-8f68-e130a221449d.gif)

**Comment by tig** [comment]
Reverting #2104 fixes this:

![JvFHQFY 1](https://user-images.githubusercontent.com/585482/200020086-9a78fb32-1a98-42af-a269-e86997c41796.gif)

**Comment by BDisp** [comment]
The views that has the focus but don't want to show the cursor then they must set it as invisible.

**Comment by tig** [comment]
> The views that has the focus but don't want to show the cursor then they must set it as invisible.

That's not how it used to work. So some change after v1.8.2 broke this and needs to be reverted. Do @BDisp or @tznind know what that change might have been?

**Comment by tig** [comment]
Actually, at least for TabView this is NOT a regression from v1.8.2. This is from `main`:

Note that it doesn't start until after I move focus to the About frame and back...

![Rlbqihj 1](https://user-images.githubusercontent.com/585482/200044026-5d7be055-a2ec-48c4-b758-44a76a4759bb.gif)

And, I just checked Graph on `main` as well. it did it then too (but again, only after focus changed).

So... THIS IS NOT A REGRESSION. Sorry about the false alarm.

Renaming the Issue and un-marking it for v1.9.
