### ISSUE TITLE
`Windows & FrameViews` scenario is broken.

### ISSUE THREAD

**Issue by BDisp** [gui-cs/Terminal.Gui#2188]
@tig this is happening after your last merge.

**Comment by tig** [comment]
Ugh. Thanks.

**Comment by BDisp** [comment]
I think I found the bug.  You are re-creating the `Win` without disposing first.

```
	Win.Dispose (); // Needed this.
	Win = new Window ($"{listWin.Count} - Scenario: {GetName ()}", padding) {
		X = Pos.Center (),
		Y = 1,
		Width = Dim.Fill (10),
		Height = Dim.Percent (15)
	};
```

**Comment by tig** [comment]
This Scenario sets `Scenario.Win` but does NOT override `Scenario.Init()`.

As a result, the `Window` created by the `Scenario.Init()` and set to `Scenario.Win` is added to `Application.Top`.

That `Window` is an orphan and for some reason messes things up.

The "right" fix, is to change the scenario to override `Init` so that the original `Win` is not added to `Top.

However, this used to work (perhaps incorrectly) and now doesn't.  

I'm not yet sure what to do about that.

**Comment by tig** [comment]
> I think I found the bug. You are re-creating the `Win` without disposing first.
> 
> ```
> 	Win.Dispose (); // Needed this.
> 	Win = new Window ($"{listWin.Count} - Scenario: {GetName ()}", padding) {
> 		X = Pos.Center (),
> 		Y = 1,
> 		Width = Dim.Fill (10),
> 		Height = Dim.Percent (15)
> 	};
> ```

Correct. We found the bug at the same time ;-).

**Comment by tig** [comment]
Do you have any idea where in the library things go wrong that cause the scenario to go blank/fail to draw?

It would be nice  to know, and maybe put a `throw` in there or something?

**Comment by BDisp** [comment]
Change the `Height = Dim.Percent (25)` to show the contents.

**Comment by tig** [comment]
> Change the `Height = Dim.Percent (25)` to show the contents.

of what?

**Comment by BDisp** [comment]
> of what?

Of the `Win` above.

**Comment by tig** [comment]
I like this fix to the Scenario, as it shows people that `Scenario.Init` adds `Win` to `Top`:

```cs
// Ignore the Win that UI Catalog created and create a new one
			Application.Top.Remove (Win);
			Win?.Dispose ();
			Win = new Window ($"{listWin.Count} - Scenario: {GetName ()}", padding) {
				X = Pos.Center (),
				Y = 1,
				Width = Dim.Fill (10),
				Height = Dim.Percent (15)
			};
```

Still don't understand what you mean by `Height = Dim.Percent (25)`

**Comment by BDisp** [comment]
```
// Ignore the Win that UI Catalog created and create a new one
			Application.Top.Remove (Win);
			Win?.Dispose ();
			Win = new Window ($"{listWin.Count} - Scenario: {GetName ()}", padding) {
				X = Pos.Center (),
				Y = 1,
				Width = Dim.Fill (10),
				Height = Dim.Percent (25) // Here <----------------
			};
```

**Comment by tig** [comment]
But what will that do? I tried it and I see no difference.

**Comment by BDisp** [comment]
> Do you have any idea where in the library things go wrong that cause the scenario to go blank/fail to draw?
> 
> It would be nice to know, and maybe put a `throw` in there or something?

I think I know. Given the Win is re-created, the older one created in the `scenario.Init` was already added to the `Application.Top`. Clicking on it will cause redrawing. Given the `Win` was the first view added to the `Application.Top` it will the last to run `Redraw` doing a clear on all screen because the size are `Dim.Fill`. I think it cannot throw anything because it was added to the `Application.Top`. The dispose removed it from the `Application.Top`. Only avoiding things like this :-)

**Comment by tig** [comment]
> > Do you have any idea where in the library things go wrong that cause the scenario to go blank/fail to draw?
> > It would be nice to know, and maybe put a `throw` in there or something?
> 
> I think I know. Given the Win is re-created, the older one created in the `scenario.Init` was already added to the `Application.Top`. Clicking on it will cause redrawing. Given the `Win` was the first view added to the `Application.Top` it will the last to run `Redraw` doing a clear on all screen because the size are `Dim.Fill`. I think it cannot throw anything because it was added to the `Application.Top`. The dispose removed it from the `Application.Top`. Only avoiding things like this :-)

Correct!

```cs
			// Ignore the Win that UI Catalog created and create a new one
			//Application.Top.Remove (Win);
			//Win?.Dispose ();
			Win.Height = 10;
```

<img width="732" alt="image" src="https://user-images.githubusercontent.com/585482/200148942-f939c781-d4b9-490d-b683-8413190346f2.png">

I believe it is the fix to #2094 that caused this stupid bug in the scenario that's been there forever to be visible.

**Comment by BDisp** [comment]
> I believe it is the fix to #2094 that caused this stupid bug in the scenario that's been there forever to be visible.

In this case no. I put a breakpoint there and he never was hit, because the `Window` have the `Redraw` overridden and the `ContentView` is nested private class.

**Comment by BDisp** [comment]
I suggest to maintain the background blue because some of the Window have a black border and with the black background we can't see them to drag.

**Comment by tig** [comment]
Good call. See https://github.com/gui-cs/Terminal.Gui/pull/2192

<img width="745" alt="image" src="https://user-images.githubusercontent.com/585482/200149379-50cc2ccc-d071-4511-bbba-1b57e856add6.png">
