### ISSUE TITLE
Attributes: Support Bright/Bold, Dim, Underline, Blink, Reverse, Hidden, and Strike-through 

### ISSUE THREAD

**Issue by worksofliam** [gui-cs/Terminal.Gui#219]
Once https://github.com/gui-cs/Terminal.Gui/issues/2797 is done, we'll be read to add these:

- [ ] Bright/Bold
- [ ] Dim
- [ ] Underline
- [ ] Blink
- [ ] Reverse
- [ ] Hidden,
- [ ] Strike-through

**Comment by BDisp** [comment]
Maybe related with #1275.

**Comment by tig** [comment]
Not sure why this got closed.
