### ISSUE TITLE
CsvEditor: Column Type dialog not wide enough

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#2195]
<img width="389" alt="image" src="https://user-images.githubusercontent.com/585482/200180402-7eec5bd4-b3ae-4c5e-a5e9-3d0f4f924a5c.png">

This might be a bug in `Dialog`?

**Comment by BDisp** [comment]
I wonder how you could open a `csv` file. It' seems that the `FileDialogs` is bugged.

**Comment by tig** [comment]
> I wonder how you could open a `csv` file. It' seems that the `FileDialogs` is bugged.

Dunno. The attached works on my machine.

[Friends.csv](https://github.com/gui-cs/Terminal.Gui/files/9952915/Friends.csv)

**Comment by BDisp** [comment]
If decimal separator is the comma it throw an an exception on open. I think there must a flag to allow comma as decimal separator if it's in quotes "12,05".

![imagem](https://user-images.githubusercontent.com/13117724/200359093-2f9d7055-856a-4257-945f-b323c88ccfa1.png)

**Comment by tznind** [comment]
Parsing CSV is so hard theres a library for it https://github.com/JoshClose/CsvHelper.git (with ~3000  lines of code in it 😱 )

Do we want to take a dependency on it for `UICatalog`?  I think theres not much point in writting our own parser.

**Comment by BDisp** [comment]
> Parsing CSV is so hard theres a library for it https://github.com/JoshClose/CsvHelper.git (with ~3000 lines of code in it 😱 )
> 
> Do we want to take a dependency on `CsvHelper` for `UICatalog`? I think theres not much point in writting our own parser. I would propose that we do one of the following:
> 
>     * Add CsvHelper and use that for parsing

I believe that would be a good idea:

>     * Add a disclaimer to say that this is demo code only (and improve error message).
> 
This will be an embarrassment. Even with the disclaimer, if any user use it for professional purposes will be the Terminal.Gui responsible?

>     * Scrap the Csv Editor scenario (there are other `TableView` scenarios)
> 
Well I like the Csv Editor scenario and would be good to preserve it.

> But I'm happy to listen to alternative points of view on this. Its certainly quite a powerful demonstration of our library.

I think any open source parser that just feat the needs is the better option.

**Comment by BDisp** [comment]
> <img alt="image" width="389" src="https://user-images.githubusercontent.com/585482/200180402-7eec5bd4-b3ae-4c5e-a5e9-3d0f4f924a5c.png">
> 
> This might be a bug in `Dialog`?

Well, the main reason for this issue is for the `MessageBox` is using layout absolute.
```cs
MessageBox.Query(40,15,"Column Type","Pick a data type for the column",new ustring[]{"Date","Integer","Double","Text","Cancel"});
```

But also the `MessageBox` has a bug in the width calculation and the `Dialog` has a bug on the `ButtonAlignments.Center`.

![imagem](https://user-images.githubusercontent.com/13117724/200397832-352e7b6b-d029-426d-b1ff-378318047c12.png)

**Comment by tig** [comment]
> > <img alt="image" width="389" src="https://user-images.githubusercontent.com/585482/200180402-7eec5bd4-b3ae-4c5e-a5e9-3d0f4f924a5c.png">
> > This might be a bug in `Dialog`?
> 
> Well, the main reason for this issue is for the `MessageBox` is using layout absolute.
> 
> ```cs
> MessageBox.Query(40,15,"Column Type","Pick a data type for the column",new ustring[]{"Date","Integer","Double","Text","Cancel"});
> ```
> 
> But also the `MessageBox` has a bug in the width calculation and the `Dialog` has a bug on the `ButtonAlignments.Center`.
> 
> ![imagem](https://user-images.githubusercontent.com/13117724/200397832-352e7b6b-d029-426d-b1ff-378318047c12.png)

When you get a chance please file these as issues. thanks.

**Comment by BDisp** [comment]
> Do you think I should rename this Issue to match these?

I agree, because API bugs has more priority than the scenarios bug, but is up to you.
