### ISSUE TITLE
Editor Scenario: Crashes on Exit

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#2212]
![lNOeRpZ 1](https://user-images.githubusercontent.com/585482/200896729-9d97c2f1-089f-4e1d-ad95-c7bda01df1a0.gif)

My VS2022 install has become hooked and I can't debug right now. Sigh.

**Comment by tig** [comment]
Also does it on File.Close.

**Comment by tig** [comment]
And File.New

**Comment by BDisp** [comment]
@tig this is due to the changes you did to the `TextView`. If there wasn't any change then this assert mustn't fail. On changed contents not all the changes are real changes. It may only be only some update history. Now the `IsDirty` property is broken.

```cs
	if (_textView.Text == _originalText) {
		System.Diagnostics.Debug.Assert (!_textView.IsDirty);
		return true;
	}

```

**Comment by BDisp** [comment]
@tig I'm trying to fix this and I want to ask you, since this is new, if I can added the event keyword to the `ContentsChanged` to following the rules for the `Terminal.Gui`.

`public Action<ContentsChangedEventArgs> ContentsChanged;`
