### ISSUE TITLE
layout  mirroring  Right to Left flow

### ISSUE THREAD

**Issue by moohaad** [gui-cs/Terminal.Gui#2221]
top windows and some views need to be   Right to Left  for example FrameView

[Windows Forms supported long ago](https://learn.microsoft.com/en-us/dotnet/desktop/winforms/advanced/bi-directional-support-for-windows-forms-applications?view=netframeworkdesktop-4.8)

_Originally posted by @moohaad in https://github.com/gui-cs/Terminal.Gui/issues/894#issuecomment-1312750091_

**Comment by tznind** [comment]
Hi, thanks for raising this topic!

There is right to left support for some controls (see video and the PR you posted in).  There are not currently any 'layouts' as such (flow panels, table layout panels etc).  Currently layout is handled with `Pos` and `Dim` (e.g. `50% -1` or `Fill(margin 1)`).  

So you could manually reposition your controls and change the text direction on those that support it but it sounds like you are thinking of something more automagical?

If you were interested in implementing layouts then I think RTL would be a nice addition to such a feature.

![right-to-left](https://user-images.githubusercontent.com/31306100/201530879-a215d2df-810c-4efa-9fcb-70a79cd6381a.gif)

**Comment by tznind** [comment]
Regarding DateField specifically there is this unmerged PR to increase the representation of formats https://github.com/gui-cs/Terminal.Gui/pull/1205 and also a discussion here about the fragility of using a text field for date : https://github.com/gui-cs/Terminal.Gui/issues/617 

A full DateTimePicker would be a great addition.

**Comment by BDisp** [comment]
@moohaad I think you are talking about RTL for Arabic or Hebrew languages. If so, I already though about his implementation  but I need to understand better how it really work first.

**Comment by tig** [comment]
FWIW:

- #3415

The above PR supports Right to Left alignment (and ordering) of Views. The `Aligner` class supports `AlignmentModes.EndToStart` for this.

This could also be used w/in a potential `TextFormatter` re-write.
