### ISSUE TITLE
Update to NStack 1.0.7

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#2244]
Nstack 1.0.6 has some significant fixes. [Terminal.Gui v1.9](https://github.com/gui-cs/Terminal.Gui/discussions/2178) should incorporate it.

Waiting on @BDisp to review the final PR for Nstack; once he does, I'll fix this issue with a PR that refs Nstack v1.0.6.

**Comment by BDisp** [comment]
I'm not at home right now, but I'll review today asap.

**Comment by BDisp** [comment]
Already reviewed @tig. I like the changes very much, thanks.

**Comment by tig** [comment]
Fixed by https://github.com/gui-cs/Terminal.Gui/commit/28d9bbcc4e97186fa034dfb3ffa7ebe662e1fa30
