### ISSUE TITLE
Pressing the ENTER key in a TextField should not move the focus 

### ISSUE THREAD

**Issue by rgl** [gui-cs/Terminal.Gui#2252]
**Describe the bug**

Pressing the ENTER key in a TextField should not move the focus away from the TextField.

**To Reproduce**

1. Use the example at https://github.com/gui-cs/Terminal.Gui#sample-usage-in-c
2. Press the ENTER key (in the username TextField, which should be focused by default).
3. See that the cursor/focus is not in the TextField anymore

**Expected behavior**

I expected the focus to remain in the TextField where I've pressed the ENTER key.

**Comment by rgl** [comment]
With `IsDefault = true`, pressing the ENTER key in the `TextField` would still trigger the default button action? If not, IMHO, that's not the expected behavior (e.g. at least in Windows Forms, it does not loose focus).

**Comment by BDisp** [comment]
> With `IsDefault = false`, pressing the ENTER key in the `TextField` would still trigger the default button action?

No, if it's false then will not trigger the button action and the `TextField` maintain the focus.

**Comment by rgl** [comment]
Ah, so I do not want to do that, as that looses the ability to trigger the default button action. IMHO, it should behave be like Windows Forms, where it does not loose focus. That is a much better user experience than having the focus unexpectedly bouncing to the button.

**Comment by BDisp** [comment]
When the button is default it will get the focus but it can focus again the previous focused view with some change to the button action, It's a suggestion to do that feature :-)

**Comment by BDisp** [comment]
In `Button.cs` it's only need do like this:

```cs
		///<inheritdoc/>
		public override bool ProcessColdKey (KeyEvent kb)
		{
			if (!Enabled) {
				return false;
			}

			var focused = SuperView?.MostFocused;
			var res = ExecuteColdKey (kb);
			focused?.SetFocus ();
			return res;
		}

```

**Comment by tig** [comment]
I believe this is addressed. Closing. Reopen if you disagree.

**Comment by rgl** [comment]
@tig why do you believe its addressed? was there a commit about this?
