### ISSUE TITLE
request: visual designer

### ISSUE THREAD

**Issue by ghost** [gui-cs/Terminal.Gui#2253]
**Is your feature request related to a problem? Please describe.**
There is no visual designer that can drag and drop widgets to create a user interface (see for example windows forms designer)

**Describe the solution you'd like**
A visual designer to make user interfaces by drag and dropping widgets, which automatically generates the user interface code.
Maybe written by using terminal.gui itself , cross platform

**Comment by tznind** [comment]
There is TerminalGuiDesigner:
https://github.com/gui-cs/TerminalGuiDesigner

> Built with CodeDom and Roslyn, TerminalGuiDesigner lets you create complicated Views with drag and drop just like the WinForms designer.

Please have a try with it and let me know how you get on.  Here is the link to the Hello World tutorial: https://github.com/gui-cs/TerminalGuiDesigner/blob/main/README.md#usage

![newdemo](https://user-images.githubusercontent.com/31306100/175789072-27fcacf0-e9f0-4543-818d-50058bb46a2f.gif)

**Comment by tznind** [comment]
Author has deleted account so is unlikely to close this themselves.  Question is answered with link to the designer so closing this.
