### ISSUE TITLE
Dragging a window/modal breaks its position

### ISSUE THREAD

**Issue by Kacper-Kondracki** [gui-cs/Terminal.Gui#2255]
**Describe the bug**
Window or dialog while dragging doesn't move properly. 

**To Reproduce**
1. Run new window or modal.
2. Drag it around.
3. See how it hates being dragged around.

Example usage in C# code in repo README opens a dialog that has this bugged behaviour
EDIT: When I ran UICatalog, for some reason it works there properly, what's the difference between what ui catalog does and that example?

**Expected behavior**
Window or dialog should follow mouse position while dragging.

**Screenshots**
![Animation](https://user-images.githubusercontent.com/43544435/208196963-eb2f9e5b-ce9b-4492-9067-5ee562b61ea5.gif)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Version [e.g. 22] v1.8.2

**Additional context**
I noticed that it breaks when mouse while dragging leaves the window/modal bounds.

**Comment by BDisp** [comment]
That was already fixes by the PR https://github.com/gui-cs/Terminal.Gui/pull/2220. If you try the current develop branch you will see that is fixed. Maybe you are using the nuget package without the fix.

**Comment by Kacper-Kondracki** [comment]
> That was already fixes by the PR #2220. If you try the current develop branch you will see that is fixed. Maybe you are using the nuget package without the fix.

Yes, I overlooked it. This issue is indeed fixed. Thanks.

**Comment by tznind** [comment]
Maybe we should think about doing a release? @tig last release was September and there are quite a few bug fixes in since then?

**Comment by tig** [comment]
See #2178
