### ISSUE TITLE
Drivers use incorrect ESC codes and clear the scrollback buffer on exit

### ISSUE THREAD

**Issue by kingzawar** [gui-cs/Terminal.Gui#2261]
**Disappearing Scroll bar and scrolling**
I have found out that running Terminal.Gui in PowerShell or Command Prompt disables the scrolling. After one exits the Terminal.Gui window, the scrolling feature gets disabled including the scroll bar.

**To Reproduce**

1. Set up the quick start Terminal.Gui template, don't run the project yet.
https://github.com/gui-cs/Terminal.Gui/#quick-start

2. Use ``dir C:\Windows`` to generate significant output on the terminal, one should be able to scroll across multiple pages.
![1](https://user-images.githubusercontent.com/121673829/210072790-a1a3d9fe-e8eb-4116-8b48-d49fbf542192.png)

3. Run the template using ``dotnet run``, the Terminal.Gui window should be displayed. It can be now closed by ``Ctrl+Q``.
![2](https://user-images.githubusercontent.com/121673829/210073058-ff91d80b-8ccc-4b9b-bfd6-171bc94574f5.png)

4. Upon quitting, the default terminal should be displayed. Use ``dir C:\Windows``  to generate more text, however, this time it is not possible to scroll across several pages of the text. The scroll bar has also vanished now.
![3](https://user-images.githubusercontent.com/121673829/210073271-adb8acb4-690a-4923-a49d-64eaeff62248.png)

**Expected behavior**
It should be able to preserve history and support scrolling text after the Terminal.Gui has exited.

**Comment by tig** [comment]
I can repo on `main`, `develop`, and the `v1.7.2` tag. But not earlier. 

Happens with cmd.exe or Powershell in both Windows Terminal and Windows Console Host.

**Comment by tig** [comment]
Repos on NetDriver in a different/worse way, going back as far as 1.6.4: Clears the screen on exit (different bug?)

**Comment by tig** [comment]
Bug was introduced in https://github.com/gui-cs/Terminal.Gui/pull/1784 

> Commit d16f0f607f18b57ea9810c9e58f64eec1e0b190b
> Author: BDisp <bd.bdisp@gmail.com>
> Date: Saturday, June 11, 2022 4:18 AM
> Parent: 21210d62
> 
> Fixes some console buffer size issue on resizing reported in #1768. (#1784)

It is this line that was added:

```cs
Console.Out.Write ("\x1b[3J");
```

<img width="617" alt="image" src="https://user-images.githubusercontent.com/585482/210155611-f12d1ff8-37cb-4857-b972-6acf1cc410e4.png">


`[3J` means:

> Clears part of the screen. If n is 0 (or missing), clear from cursor to end of screen. If n is 1, clear from cursor to beginning of the screen. If n is 2, clear entire screen (and moves cursor to upper left on DOS [ANSI.SYS](https://en.wikipedia.org/wiki/ANSI.SYS)). If n is 3, clear entire screen and delete all lines saved in the scrollback buffer (this feature was added for [xterm](https://en.wikipedia.org/wiki/Xterm) and is supported by other terminal applications).

The fix appears to be to remove the line that emits that escape sequence:

```cs
		public override void ResizeScreen ()
		{
			OutputBuffer = new WindowsConsole.CharInfo [Rows * Cols];
			Clip = new Rect (0, 0, Cols, Rows);
			damageRegion = new WindowsConsole.SmallRect () {
				Top = 0,
				Left = 0,
				Bottom = (short)Rows,
				Right = (short)Cols
			};
			WinConsole.ForceRefreshCursorVisibility ();
			// Causes #2261 - Console.Out.Write ("\x1b[3J");
			Console.Out.Flush ();
		}
```

I tried `[1J` and `[2J` and they clear the screen (but not the buffer). This is a also not the correct behavior.

@BDisp do you remember what adding emitting `[3J` was supposed to fix?

**Comment by BDisp** [comment]
Well it has to do when height as buffer is false to hide the vertical scroll bar. The initial configuration isn't restored on exit. I've no time to review it right now.

**Comment by BDisp** [comment]
> Repos on NetDriver in a different/worse way, going back as far as 1.6.4: Clears the screen on exit (different bug?)

Yes its clearing on End method, I think.
