### ISSUE TITLE
Changing TextField.Text does not clear text selection.  Resulting in `ArgumentOutOfRange` exception in some situations.

### ISSUE THREAD

**Issue by tznind** [gui-cs/Terminal.Gui#2277]
**Describe the bug**

This occurs when you select a range in a `TextField` then change the `Text` to a new shorter `string` value and attempt to update the `CursorPosition`:

**To Reproduce**
```csharp
[InlineData("a")] // Fails
[InlineData ("aaaaaaaaaaa")] // Passes
[Theory]
public void TestSetTextAndMoveCursorToEnd_WhenExistingSelection(string newText)
{
	var tf = new TextField ();
	tf.Text = "fish";
	tf.CursorPosition = tf.Text.Length;

	tf.ProcessKey (new KeyEvent (Key.CursorLeft, new KeyModifiers()));

	tf.ProcessKey (new KeyEvent (Key.CursorLeft | Key.ShiftMask, new KeyModifiers { Shift = true }));
	tf.ProcessKey (new KeyEvent (Key.CursorLeft | Key.ShiftMask, new KeyModifiers { Shift = true }));

	Assert.Equal (1, tf.CursorPosition);
	Assert.Equal (2, tf.SelectedLength);

	tf.Text = newText;
	tf.CursorPosition = tf.Text.Length;
}
```

Test fails with:
```
   Source: TextFieldTests.cs line 1303
   Duration: 25 ms

  Message: 
System.ArgumentOutOfRangeException : Index and length must refer to a location within the string. (Parameter 'length')

  Stack Trace: 
String.ThrowSubstringArgumentOutOfRange(Int32 startIndex, Int32 length)
String.Substring(Int32 startIndex, Int32 length)
TextField.PrepareSelection(Int32 x, Int32 direction) line 1139
TextField.set_CursorPosition(Int32 value) line 342
TextFieldTests.TestSetTextAndMoveCursorToEnd_WhenExistingSelection(String newText) line 1318
RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```
Workaround is to call `ClearAllSelection ();` before updating `CursorPosition`.

**Comment by tznind** [comment]
> > Workaround is to call `ClearAllSelection ();` before updating `CursorPosition`.
> 
> I think the best workaround is call `ClearAllSelection ();` when updating `Text` property. What do you think @tznind?

I think that makes sense.  

Might be worth adding a guard check if the new `value` is different from the current because if user is setting the same text we can just exit early and not clear/update anything?

**Comment by BDisp** [comment]
> Might be worth adding a guard check if the new `value` is different from the current because if user is setting the same text we can just exit early and not clear/update anything?

If you look the `Text` property code there is a guard check at the beginning, so it only will be executed if the new text is different than the original text and if it isn't canceled.

**Comment by tznind** [comment]
Perfect!

**Comment by BDisp** [comment]
I think is better change the issue title to something like the or whatever you think better:

TextField.Text setter doesn't clearing text selection if not empty.
