### ISSUE TITLE
Refactor Attribute.Make to work even if a driver has not been loaded

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#2296]
Today:

https://github.com/gui-cs/Terminal.Gui/blob/2e7c2c83775de2cf8153e07cc8050ba07cecdd07/Terminal.Gui/Core/ConsoleDriver.cs#L174-L185

This makes it awkward to have the configuration manager set things up.

I'd like to propose the following:

- Modify `Attribute` such that a value of `-1` for `Attribute.Value` means "Not initialized by driver"
- Modify `Attribute.Make` to set `Value` to `-1` if it is called with no driver 
- Modify `ConsoleDriver.CreateColors` which is called from `ConsoleDriver.Init` to go through `Colors` and if any `Attribute.Value == -`, call `Make` again.

The only question I have about this is the code in `CursesDriver` that sets the `hasColors` parameter to `ConsoleDriver.CreateColors` to `true` in some cases. 

https://github.com/gui-cs/Terminal.Gui/blob/2e7c2c83775de2cf8153e07cc8050ba07cecdd07/Terminal.Gui/ConsoleDrivers/CursesDriver/CursesDriver.cs#L898-L932

@BDisp or @migueldeicaza : Do you know when/why it does this? Is it really still needed?

**Comment by BDisp** [comment]
Yes, that function is needed to `ncurses` check if the current terminal can handle colors, see https://invisible-island.net/ncurses/man/curs_color.3x.html.
Besides that, the attribute value depend of the driver which can uses different values. Not sure, but I think the -1 is used for transparency. Application.Init() call the Driver.Init (TerminalResized) to ensure that all attributes are well initialized. I really don't understand why you want to call the `Attribute.Make` method without a driver.

**Comment by tig** [comment]
> Not sure, but I think the -1 is used for transparency. Application.Init() call the Driver.Init (TerminalResized) to ensure that all attributes are well initialized. 

Good point. I'll expand `Attribute` to have a `Initialized` property instead.

>  really don't understand why you want to call the `Attribute.Make` method without a driver.

Because I need to have the configuration loaded before a driver is loaded (so the configuration can specify `UseSystemConsole`). I don't want to have to read/parse the config info multiple times.

**Comment by BDisp** [comment]
> Good point. I'll expand `Attribute` to have a `Initialized` property instead.

That is a better solution.



> Because I need to have the configuration loaded before a driver is loaded (so the configuration can specify `UseSystemConsole`). I don't want to have to read/parse the config info multiple times.

Ah, that why I couldn't run `NetDriver`. I'm curious to see what is coming up :-)
