### ISSUE TITLE
Remove unused methods from `ConsoleDriver`

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#2300]
These methods appear to be unused:

```cs
		/// <summary>
		/// Set Colors from limit sets of colors.
		/// </summary>
		/// <param name="foreground">Foreground.</param>
		/// <param name="background">Background.</param>
		public abstract void SetColors (ConsoleColor foreground, ConsoleColor background);

		// Advanced uses - set colors to any pre-set pairs, you would need to init_color
		// that independently with the R, G, B values.
		/// <summary>
		/// Advanced uses - set colors to any pre-set pairs, you would need to init_color
		/// that independently with the R, G, B values.
		/// </summary>
		/// <param name="foregroundColorId">Foreground color identifier.</param>
		/// <param name="backgroundColorId">Background color identifier.</param>
		public abstract void SetColors (short foregroundColorId, short backgroundColorId);

		/// <summary>
		/// Disables the cooked event processing from the mouse driver.  At startup, it is assumed mouse events are cooked.
		/// </summary>
		public abstract void UncookMouse ();

		/// <summary>
		/// Enables the cooked event processing from the mouse driver
		/// </summary>
		public abstract void CookMouse ();
```

In all existing drivers they are either empty implementations or there are no codepaths that call them.

CursesDriver has code in `SetColors` but there's no code I can find that ever calls `ConsoleDriver.SetColors` or `Driver.SetColors`.

We should remove these methods me thinks, even though it might be ḃreaking change (seems very unlikely).

**Comment by BDisp** [comment]
I think that are methods come from the `PDCurses`. I never seen any code used by them, but might have some logic. `SetColors` I see in the comment that can be used for RGB, but have wrong parameters, maybe superseded by the `SetAttribute`. The only issue is if someone already has some driver derived from `ConsoleDriver`.
