### ISSUE TITLE
Drivers do not normalize accented letters.

### ISSUE THREAD

**Issue by BDisp** [gui-cs/Terminal.Gui#2317]
**Describe the bug**
A space is added between `é` and `r`.

**To Reproduce**
1. Go to 'UICatalog'
2. Click on 'Tab View'
3. Scroll right until the 'Les Misérables' tab.
4. See the wrong render.

**Expected behavior**
No space between `é` and `r`.

This happens with all drivers.

**Screenshots**
![imagem](https://user-images.githubusercontent.com/13117724/216790989-7a7a22c7-e508-46bd-9155-85c58d7b6b70.png)

**Comment by tznind** [comment]
Working fine in Linux... Can you try `cmd` and `powershell`? What console are you using?

![shot-2023-02-04_22-07-05](https://user-images.githubusercontent.com/31306100/216791529-10189d3f-2944-496d-9d04-09d7ce6c4e28.jpg)

**Comment by tznind** [comment]
The fix referenced seems to be calling [Normalize](https://learn.microsoft.com/en-us/dotnet/api/system.string.normalize?view=net-7.0) on string.

Is this to say we only support Unicode that is Normalized via this method?  It's fine if that's the case, but best to be clear.

>  Some Unicode characters have multiple equivalent binary representations consisting of sets of combining and/or composite Unicode characters. For example, any of the following code points can represent the letter "ắ":
> 
>- U+1EAF
> 
>- U+0103 U+0301
> 
>- U+0061 U+0306 U+0301
>[...]

**Comment by BDisp** [comment]
> Working fine in Linux... Can you try `cmd` and `powershell`? What console are you using?

Thanks. I confirm that with the gnome-terminal is working fine. I have it installed on the WSL distro.

But with all drivers doesn't work with VsDebugger, cmd, Windows Terminal and WSL. I think this should be handled by the terminal itself. I also did a workaround on the AddRune method, by normalizing before save to the contents. That avoid the space added but I think I shouldn't do nothing, because is a terminal fault. Maybe is better doesn't submit the PR, don't you think too?

**Comment by BDisp** [comment]
Here the workaround I talked about:

```cs
				if (runeWidth == 0 && ccol > 0) {
					var r = contents [crow, ccol - 1, 0];
					var s = new string (new char [] { (char)r, (char)rune });
					string sn;
					if (!s.IsNormalized ()) {
						sn = s.Normalize ();
					} else {
						sn = s;
					}
					var c = sn [0];
					var prevPosition = crow * Cols + (ccol - 1);
					OutputBuffer [prevPosition].Char.UnicodeChar = c;
					contents [crow, ccol - 1, 0] = c;
					OutputBuffer [prevPosition].Attributes = (ushort)currentAttribute;
					contents [crow, ccol - 1, 1] = currentAttribute;
					contents [crow, ccol - 1, 2] = 1;
					WindowsConsole.SmallRect.Update (ref damageRegion, (short)(ccol - 1), (short)crow);
				} else {

```
...
```cs

			}

			if (runeWidth < 0 || runeWidth > 0) {
				ccol++;
			}

```

**Comment by tznind** [comment]
>  That avoid the space added but I think I shouldn't do nothing, because is a terminal fault. Maybe is better doesn't submit the PR, don't you think too?

I agree, I think it is an issue with the terminals since it works in gnome/bash.  

I think that we don't want to hide the issue by simply changing our example string (assuming what is there is 'valid').  But maybe the `TabView` scenario is not the place for it? 

We could have a new scenario that explores the different ways of representing these unicode characters? And ensures that our measuring APIs work consistently across OS/terminals vs the output length.  I might look into this as its quite interesting.

Not sure about the workaround... does it fix it for cmd? If so does it have any side effects? or break it for gnome/bash?

**Comment by BDisp** [comment]
Currently with the `NetDriver` also isn't rendering well in the `gnone-terminal`, but at least don't leaves a space, but by not drawing the vertical line in the end and mess up all to the right. I'll investigate it and try to fixed it, I hope.

![imagem](https://user-images.githubusercontent.com/13117724/216793021-5242da37-e6df-43be-8960-d888530ef414.png)

**Comment by BDisp** [comment]
Fixed for the `NetDriver`. So the solution is the workaround in the `AddRune` method.

![imagem](https://user-images.githubusercontent.com/13117724/216793728-8dd22595-1f2e-4543-8f4c-14b43ba997e0.png)

**Comment by BDisp** [comment]
> We could have a new scenario that explores the different ways of representing these unicode characters? And ensures that our measuring APIs work consistently across OS/terminals vs the output length. I might look into this as its quite interesting.

Interesting. I will keep linked.
