### ISSUE TITLE
selections like checkmark not showing in docker container 

### ISSUE THREAD

**Issue by saldroubi** [gui-cs/Terminal.Gui#2341]
Using Out-ConsoleGridView  https://github.com/PowerShell/GraphicalTools#example-1-output-processes-to-a-grid-view 

Get-process | Out-ConsoleGridView -OutputMode Multiple -Title "Select one or more processes"

The check mark is now not showing when used it in Docker container.  It works when I use it in PowerShell on Mac OS. 
I am wondering if I am missing a font or is there a workaround for this.

I opened an issue on this in that repository but I am not sure if this can be answered here instead:

https://github.com/PowerShell/GraphicalTools/issues/183

Thank you. 

![Out-ConsoleView_issue](https://user-images.githubusercontent.com/16247245/218286028-d075d7eb-9070-444a-a347-839d51139903.jpg)

**Comment by BDisp** [comment]
I think you will need to do this https://github.com/gui-cs/Terminal.Gui/issues/1519#issuecomment-976006302.

**Comment by saldroubi** [comment]
Thank you very much this fixed it.
