### ISSUE TITLE
Dialog bounds bigger than Cols and Rows must be allowed to drag beyond left, right and bottom.

### ISSUE THREAD

**Issue by BDisp** [gui-cs/Terminal.Gui#2434]
![dialog-bigger](https://user-images.githubusercontent.com/13117724/226341627-442857d2-4091-439c-93bd-ff1ffffef2f6.gif)

**Comment by tig** [comment]
I think the proper default behavior for draggable views is as shown once you make the console smaller above.

In otherwords, the current behavior of preventing windows from dragging outside of the SuperView Frame is not right.

right?

**Comment by BDisp** [comment]
Here is the final behavior:

![dialog-bigger-fix](https://user-images.githubusercontent.com/13117724/226380438-3167d83e-f2c9-47d2-b874-d20b443b2e06.gif)
