### ISSUE TITLE
Save as:: label in SaveDialog

### ISSUE THREAD

**Issue by robece** [gui-cs/Terminal.Gui#2440]
**Describe the bug**
There is a double :: character in "Save as" label in SaveDialog control.

**To Reproduce**
Create a SaveDialog and SaveAs.

**Expected behavior**
it's working good, this is a minor quick change for a typo error.

**Screenshots**
![image](https://user-images.githubusercontent.com/8558639/226712949-ebb1dca8-2b8b-4b9f-b3c8-02944ef654a2.png)

**Desktop (please complete the following information):**
MacOS (Ventura 13.2.1)
NuGet version 1.10.0

**Smartphone (please complete the following information):**
Not mobile

**Additional context**

**Comment by robece** [comment]
Thank you @tig, will do it, I would like to start learning more about the v2, where do you suggest me to start?

**Comment by tig** [comment]
https://github.com/gui-cs/Terminal.Gui/discussions/1940
