### ISSUE TITLE
DateField doesn't work with dd-MMM-yy format

### ISSUE THREAD

**Issue by popara96** [gui-cs/Terminal.Gui#2445]
**Description**
DateField throws an exception when the system uses dd-MMM-yy format with string literals instead of numbers.

**Steps to reproduce the behavior:**
1. Go to 'Control Panel'->'Clock and Region'->'Change date, time, or number formats'->'Additional settings'->'Date' tab->set 'Short date' to 'dd-MMM-yy'
2. Try to test DateTime in UICatalog

**Expected behavior**
We expect to see DateFields. Instead we get an exception: ___System.FormatException: 'The input string 'Mar' was not in a correct format.'___

**Screenshots**
![image](https://user-images.githubusercontent.com/31167073/227720891-01189bdd-6421-41dc-9cb7-ab83966a96ea.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: N/A
 - Version: N/A

**Comment by tig** [comment]
I believe this is fixed with

- #2851 

and 

- #3180

Right?

**Comment by MaciekWin3** [comment]
> I believe this is fixed with
> 
> * [DateField: Allow Formatting #2851](https://github.com/gui-cs/Terminal.Gui/issues/2851)
> 
> and
> 
> * [DateField not reflecting user input #3180](https://github.com/gui-cs/Terminal.Gui/issues/3180)
> 
> Right?

Yeah, that's right. What is more now you can set up format using `Culture` property in DateField.

**Comment by BDisp** [comment]
> I believe this is fixed with
> 
> * [DateField: Allow Formatting #2851](https://github.com/gui-cs/Terminal.Gui/issues/2851)
> 

Yes.

> and
> 
> * [DateField not reflecting user input #3180](https://github.com/gui-cs/Terminal.Gui/issues/3180)
> 
No, the user is asking for a MMM format which will use the month abbreviature as Mar. `DateField` only support short format data based on the culture used, "dd/MM/yyyy", "dd-MM-yyyy", "dd.MM.yyyy". The reason of that is `DateField` only validate numbers and not letters.

**Comment by MaciekWin3** [comment]
What I meant app will no longer crush 😁. Correct me if I am wrong, but with recent changes DateField will just use default format which is `"dd/MM/yyyy"` in this case.

**Comment by BDisp** [comment]
> What I meant app will no longer crush 😁. Correct me if I am wrong, but with recent changes DateField will just use default format which is `"dd/MM/yyyy"` in this case.

I updated my previous comment. @tig asked both fixes above fixed this issue where the user asked for a mask "dd-MMM-yy" which as you said will default to "dd/MM/yyyy". But I think he want used the device setting format.
But yes the PR fixed the exceptions thanks to you 😃

**Comment by BDisp** [comment]
@MaciekWin3 to allow the user to freely adding custom formats and use all the `CultureInfo` formats, I think the `DatePicker` will have better chances to achieve that, by using the `TextField` typing whatever he want and when he leaves the control, handles the validation with the `TextChanging` event. In this case the user can use different separators, month names abbreviated or full, etc. If the date is valid then the text is accepted, otherwise cancel the change.
