### ISSUE TITLE
FindDeepestView should be a public static method on the View class.

### ISSUE THREAD

**Issue by BDisp** [gui-cs/Terminal.Gui#2462]
@tig, @tznind do you agree with me about this? I'll need this in the `ComboBox` when receiving `MouseEvent` through the `RootMouseEvent`. If you don't agree I need to make it `internal static` in the `Application` class. But I think this method would be a very important helper to handle with views on the fly managed by others views. I only will advance after your feedback. Thanks.

**Comment by tig** [comment]
Please hold off with a PR for this until I'm done with #2361 - I've made changes to these APIs and it'll be merge conflict heck.

I'm getting really close!

I am not sure it needs to be exposed publicly. I'd like to dive in deeper to see if there's another part of the API that could be exposed that will let combo box do what you want. I also don't think it's well-named or designed as an API.  For example, I had to stare at it for a long time to figure out what the x and y coordinates were relative to.

I do agree it should be on `View` and not `Application`.

**Comment by BDisp** [comment]
Sorry @tig, I couldn't wait more time because I needed it for the #2479.
