### ISSUE TITLE
`Application.Begin` should set `toplevel`'s size to the console size

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#2500]
```cs
		[Fact, AutoInitShutdown]
		public void Begin_Sets_Application_Top_To_Console_Size()
		{
			Assert.Equal (new Rect (0, 0, 80, 25), Application.Top.Frame);

			((FakeDriver)Application.Driver).SetBufferSize (5, 5);
			Application.Begin (Application.Top);
			// BUGBUG: v2 - This test should pass; it does not currently
			Assert.Equal (new Rect (0, 0, 5, 5), Application.Top.Frame);
		}
```

**Comment by BDisp** [comment]
@tig the reason is the `Application.Top` only is added to the tolevels collection on the `Begin` method and not in the `Init` method. So the `TerminalResized` method isn't processed because the tolevels collection is empty.

**Comment by tig** [comment]
> @tig the reason is the `Application.Top` only is added to the tolevels collection on the `Begin` method and not in the `Init` method. So the `TerminalResized` method isn't processed because the tolevels collection is empty.

What do you think the right fix is?

**Comment by BDisp** [comment]
> What do you think the right fix is?

Don't fix. Just use the `((FakeDriver)Application.Driver).SetBufferSize (5, 5);` after the `Begin` is called.

**Comment by tig** [comment]
I spent 30 minutes debugging a test because of this. I think the current behavior is incorrect. The unit test above shows how I think it should work.

Can you explain why you disagree?

Note, here's a potential fix:

```cs
public static RunState Begin (Toplevel toplevel)
{
	if (toplevel == null) {
		throw new ArgumentNullException (nameof (toplevel));
	} else if (toplevel.IsMdiContainer && MdiTop != toplevel && MdiTop != null) {
		throw new InvalidOperationException ("Only one Mdi Container is allowed.");
	}

	var rs = new RunState (toplevel);

	// View implements ISupportInitializeNotification which is derived from ISupportInitialize
	if (!toplevel.IsInitialized) {
                toplevel.Frame = new Rect (0, 0, Driver.Cols, Driver.Rows);
		toplevel.BeginInit ();
		toplevel.EndInit ();
	}
...

```

**Comment by BDisp** [comment]
@tig but you are trying to fix the Begin method but in the test you are calling the `((FakeDriver)Application.Driver).SetBufferSize (5, 5);` before the `Application.Begin`. So, I don't understand what you are doing :-)

**Comment by tig** [comment]
> @tig but you are trying to fix the Begin method but in the test you are calling the `((FakeDriver)Application.Driver).SetBufferSize (5, 5);` before the `Application.Begin`. So, I don't understand what you are doing :-)

`SetBufferSize ()` changes `Driver.Cols` and `Driver.Rows`.

Thus my fix (`toplevel.Frame = new Rect (0, 0, Driver.Cols, Driver.Rows);` makes this code work:

```cs
		[Fact, AutoInitShutdown]
		public void Begin_Sets_Application_Top_To_Console_Size()
		{
                        // FakeDriver's default size is 80x25
			Assert.Equal (new Rect (0, 0, 80, 25), Application.Top.Frame);

                        // I want a much smaller size for my tests
			((FakeDriver)Application.Driver).SetBufferSize (5, 5);

                        // Start the app
			Application.Begin (Application.Top);

			// BUGBUG: v2 - This test should pass; it does not currently
			Assert.Equal (new Rect (0, 0, 5, 5), Application.Top.Frame);
		}
```

Make sense?

**Comment by BDisp** [comment]
Sorry I didn't look in this. Yes make sense and is a great fix. Thanks.
```cs
	// View implements ISupportInitializeNotification which is derived from ISupportInitialize
	if (!toplevel.IsInitialized) {
                toplevel.Frame = new Rect (0, 0, Driver.Cols, Driver.Rows);
		toplevel.BeginInit ();
		toplevel.EndInit ();
	}
```

**Comment by tig** [comment]
This was fixed.
