### ISSUE TITLE
'LineCanvas` has two minds about what `Length == 0` means

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#2530]
Related to: #2433 which was fixed by #2436

@tznind, I've discovered another issue related to this fix, and the idea that `Line.Length == 0` is really a one point long element...

The `inArea` param to `GenerateImage(Rect inArea)` is intended to constrain what points are returned to `inArea`.

Because `EndsAt(int x, int y)` does this...

```cs
private bool EndsAt (int x, int y)
{
	if (Orientation == Orientation.Horizontal) {
		return Start.X + Length == x && Start.Y == y;
	}

	return Start.X == x && Start.Y + Length == y;
}
```

Specifically `Start.X + Length`...

Instead of `Start.X + Length - 1`...

... it doesn't constrain the line properly.

I think the crux is 

- A length of 0 means a length of 1
- A length of 1 means a length of 2

Both these new tests pass:

```cs
[InlineData (0, 0, Orientation.Horizontal, "─")]
[InlineData (1, 0, Orientation.Horizontal, "─")]
[InlineData (0, 1, Orientation.Horizontal, "─")]
[InlineData (0, 0, Orientation.Vertical, "│")]
[InlineData (1, 0, Orientation.Vertical, "│")]
[InlineData (0, 1, Orientation.Vertical, "│")]
[Theory, AutoInitShutdown]
public void Length_0_Is_1_Long (int x, int y, Orientation orientation, string expected)
{
	Application.Begin (Application.Top);
	((FakeDriver)Application.Driver).SetBufferSize (20, 20);

	var inArea = new Rect (0, 0, 1, 1);

	var canvas = new LineCanvas ();
	// Add a line at 0, 0 that's has length of 1
	canvas.AddLine (new Point (0, 0), 1, orientation, LineStyle.Single);

	foreach (var p in canvas.GenerateImage (inArea)) {
		Application.Driver.Move (p.Key.X, p.Key.Y);
		Application.Driver.AddRune (p.Value);
	}

	string looksLike = $"{Environment.NewLine}{expected}";

	TestHelpers.AssertDriverContentsAre (looksLike, output);
}

[InlineData (0, 0, Orientation.Horizontal,"─")] //"──")]
[InlineData (1, 0, Orientation.Horizontal,"─")] //"──")]
[InlineData (0, 1, Orientation.Horizontal,"─")] //"──")]
[InlineData (0, 0, Orientation.Vertical,  "│")] //"│\n│")]
[InlineData (1, 0, Orientation.Vertical,  "│")] //"│\n│")]
[InlineData (0, 1, Orientation.Vertical,  "│")] //"│\n│")]
[Theory, AutoInitShutdown]
public void Length_1_Is_1_Long (int x, int y, Orientation orientation, string expected)
{
	Application.Begin (Application.Top);
	((FakeDriver)Application.Driver).SetBufferSize (20, 20);

	var inArea = new Rect (0, 0, 1, 1);

	var canvas = new LineCanvas ();
	// Add a line at 0, 0 that's has length of 1
	canvas.AddLine (new Point (0, 0), 1, orientation, LineStyle.Single);

	foreach (var p in canvas.GenerateImage (inArea)) {
		Application.Driver.Move (p.Key.X, p.Key.Y);
		Application.Driver.AddRune (p.Value);
	}

	string looksLike = $"{Environment.NewLine}{expected}";

	TestHelpers.AssertDriverContentsAre (looksLike, output);
}
```

I'm wondering if the right thing to do is to make it so the 2nd one is `Length_1_Is_2_Long`?

**Comment by tig** [comment]
I mistyped above.

Currently if length is 1, the result is 2 long.

**Comment by tig** [comment]
I'm working on it...

**Comment by tig** [comment]
I've confused myself, but I think I'm getting uconfused.

Existing tests show something aint' right. E.g. 

```
		[InlineData (LineStyle.Single)]
		[InlineData (LineStyle.Rounded)]
		[Theory, AutoInitShutdown]
		public void View_Draws_Horizontal (LineStyle style)
		{
			var v = GetCanvas (out var canvas);
			canvas.AddLine (new Point (0, 0), 1, Orientation.Horizontal, style);

			v.Redraw (v.Bounds);

			string looksLike =
@"    
──";
			TestHelpers.AssertDriverContentsAre (looksLike, output);
		}
```

The line here is length = 1, but the test is expecting two.

**Comment by tig** [comment]
Part of the problem is your test method `GetCanvas` is using `vBounds` but the View was not actually initialized because Begin wasn't called. 

I've fixed that:
```cs
		private View GetCanvas (out LineCanvas canvas, int offsetX = 0, int offsetY = 0)
		{
			var v = new View {
				Width = 10,
				Height = 5,
				Bounds = new Rect (0, 0, 10, 5)
			};
			Application.Top.Add (v);
			Application.Begin (Application.Top);

			var canvasCopy = canvas = new LineCanvas ();
			v.DrawContentComplete += (s, e) => {
				foreach (var p in canvasCopy.GenerateImage (v.Bounds)) {
					v.AddRune (
						offsetX + p.Key.X,
						offsetY + p.Key.Y,
						p.Value);
				}
			};

			return v;
		}
```

Now the above test is failing because the resulting line is only 1 long.

However, we KNOW it's really 2 long and the reason the test is now succeeding is `v.DrawcContentComplete` is using `v.Bounds` for `inArea`, so the line is getting "clipped". 

In the future, for tests that don't NEED a view, please don't build the tests around `View`. Instead, draw directly to `Application.Driver` like I show in `Length_0_Is_1_Long` above.

We have way too many tests that don't actually test the primitive, but depend on what View is doing.

**Comment by BDisp** [comment]
Here a prove that using `Bounds` will bad rendering and `Frame` not. Before for calculate dimension this didn't happen. Should be this the right behavior? If in the `Btn_Width` method I change to `return (btn?.Frame.Width) ?? 0;` the layout work correctly on the two outputs.

```cs
		[Fact, AutoInitShutdown]
		public void Dialog_In_Window_With_TexxtField_And_Button_AnchorEnd ()
		{
			((FakeDriver)Application.Driver).SetBufferSize (20, 5);

			var win = new Window ();

			int iterations = 0;
			Application.Iteration += () => {
				if (++iterations > 2) {
					Application.RequestStop ();
				}
			};

			win.Loaded += (s, a) => {
				var dlg = new Dialog () { Width = 18, Height = 3 };
				Button btn = null;
				btn = new Button ("Ok") {
					X = Pos.AnchorEnd () - Pos.Function (Btn_Width)
				};
				int Btn_Width ()
				{
					return (btn?.Bounds.Width) ?? 0;
				}
				var tf = new TextField ("01234567890123456789") {
					Width = Dim.Fill (1) - Dim.Function (Btn_Width)
				};

				dlg.Loaded += (s, a) => {
					Application.Refresh ();
					Assert.Equal (new Rect (14, 0, 6, 1), btn.Frame);
					Assert.Equal (new Rect (0, 0, 6, 1), btn.Bounds);
					var expected = @"
┌──────────────────┐
│┌────────────────┐│
││23456789      [ ││
│└────────────────┘│
└──────────────────┘";
					_ = TestHelpers.AssertDriverContentsWithFrameAre (expected, output);

					dlg.SetNeedsLayout ();
					dlg.LayoutSubviews ();
					Application.Refresh ();
					Assert.Equal (new Rect (10, 0, 6, 1), btn.Frame);
					Assert.Equal (new Rect (0, 0, 6, 1), btn.Bounds);
					expected = @"
┌──────────────────┐
│┌────────────────┐│
││23456789  [ Ok ]││
│└────────────────┘│
└──────────────────┘";
					_ = TestHelpers.AssertDriverContentsWithFrameAre (expected, output);
				};
				dlg.Add (btn, tf);

				Application.Run (dlg);
			};
			Application.Run (win);
		}

```

**Comment by tznind** [comment]
The line measurement of LineCanvas should be consistent with `Rect`.  Maybe we need a new primitive `Line`?  

I think it makes sense if a `Line` with `Length` of X takes up the same horizontal/vertical space as a `Rect` with `Width`/`Height` X?

Would simplify unit testing too probably and give us the option of having stuff like `Rect.ToLines()`

**Comment by tig** [comment]
> Here a prove that using `Bounds` will bad rendering and `Frame` not. Before for calculate dimension this didn't happen. Should be this the right behavior? If in the `Btn_Width` method I change to `return (btn?.Frame.Width) ?? 0;` the layout work correctly on the two outputs.

I don't think this has anything to do with this Issue. what am I missing?

**Comment by BDisp** [comment]
> However, we KNOW it's really 2 long and the reason the test is now succeeding is `v.DrawcContentComplete` is using `v.Bounds` for `inArea`, so the line is getting "clipped".

Because of this @tig, but I might had misread.

**Comment by tig** [comment]
> The line measurement of LineCanvas should be consistent with `Rect`. Maybe we need a new primitive `Line`?
> 
> I think it makes sense if a `Line` with `Length` of X takes up the same horizontal/vertical space as a `Rect` with `Width`/`Height` X?
> 
> Would simplify unit testing too probably and give us the option of having stuff like `Rect.ToLines()`

I've been working on this all day. Here's what I've discovered/settled on:

- `Length == 0` means "a zero length line at this point, which is really just a way of forcing a line-ending or cross on another line.
- `Length > 0` means "a line `Length` long. Prevously the code (and tests) were confused in this way

- Unit tests that test drawing should NOT use a `View` to do the drawing (at least for primitve aspects). It adds too much complexity and provides false-positives/negatives, hiding both proper behavior and bad. 

- Both `TestHelpers.AssertDriverContentsAre` and `TestHelpers.AssertDriverContentsWithFrameAre` have bugs in them that cause weird, indeterminate behavior in tests. Been driving me NUTS!

- `GenerateImage` is flawed in that it expects caller to pass a rect. It should figure out the bounds of the lines that have been added. I've changed it thusly:

```cs
		/// <summary>
		/// Evaluates the lines that have been added to the canvas and returns a map containing
		/// the glyphs and their locations. The glyphs are the characters that should be rendered
		/// so that all lines connect up with the appropriate intersection symbols. 
		/// </summary>
		/// <param name="inArea">A rectangle to constrain the search by.</param>
		/// <returns>A map of the points within the canvas that intersect with <paramref name="inArea"/>.</returns>
		public Dictionary<Point,Rune> GetMap (Rect inArea)
		{
			var map = new Dictionary<Point,Rune>();

			// walk through each pixel of the bitmap
			for (int y = inArea.Y; y < inArea.Y + inArea.Height; y++) {
				for (int x = inArea.X; x < inArea.X + inArea.Width; x++) {

					var intersects = _lines
						.Select (l => l.Intersects (x, y))
						.Where (i => i != null)
						.ToArray ();

					var rune = GetRuneForIntersects (Application.Driver, intersects);

					if(rune != null)
					{
						map.Add(new Point(x,y),rune.Value);
					}
				}
			}

			return map;
		}

		/// <summary>
		/// Evaluates the lines that have been added to the canvas and returns a map containing
		/// the glyphs and their locations. The glyphs are the characters that should be rendered
		/// so that all lines connect up with the appropriate intersection symbols. 
		/// </summary>
		/// <returns>A map of all the points within the canvas.</returns>
		public Dictionary<Point, Rune> GetMap () => GetMap (Canvas);
```

I do not think the version that takes an `inArea` is needed. `LineCanvas` now can compute the `Rect` that the lines occupy, letting callers do this:

```cs
		[InlineData (0, 0, 0, 0)]
		[InlineData (0, 0, 1, 0)]
		[InlineData (0, 0, 0, 1)]
		[InlineData (0, 0, 1, 1)]
		[InlineData (0, 0, 2, 2)]
		[InlineData (0, 0, 10, 10)]
		[InlineData (1, 0, 0, 0)]
		[InlineData (1, 0, 1, 0)]
		[InlineData (1, 0, 0, 1)]
		[InlineData (1, 0, 1, 1)]
		[InlineData (1, 0, 2, 2)]
		[InlineData (1, 0, 10, 10)]
		[InlineData (1, 1, 1, 0)]
		[InlineData (1, 1, 0, 1)]
		[InlineData (1, 1, 1, 1)]
		[InlineData (1, 1, 2, 2)]
		[InlineData (1, 1, 10, 10)]
		[InlineData (-1, -1, 1, 0)]
		[InlineData (-1, -1, 0, 1)]
		[InlineData (-1, -1, 1, 1)]
		[InlineData (-1, -1, 2, 2)]
		[InlineData (-1, -1, 10, 10)]
		[Theory, AutoInitShutdown]
		public void Canvas_Has_Correct_Bounds (int x, int y, int length, int height)
		{
			var canvas = new LineCanvas ();
			canvas.AddLine (new Point (x, y), length, Orientation.Horizontal, LineStyle.Single);
			canvas.AddLine (new Point (x, y), length, Orientation.Vertical, LineStyle.Single);

			int expectedWidth = Math.Max (length, 1);
			int expectedHeight = Math.Max (length, 1);

			Assert.Equal (new Rect (x, y, expectedWidth, expectedHeight), canvas.Canvas);
		}
```

I'm now almost done, but struggling with negative `Length`s. They were poorly tested before and it's easy to write code that neglects them. 

But cool shit is happening...  E.g. The two leftmost FrameViews at the top of this are simply `X = Pos.Right(leftguy) -1`
<img width="343" alt="image" src="https://user-images.githubusercontent.com/585482/231309742-a163d5fb-df32-4945-9fc4-67ecf9a54b90.png">

And this is just cool (obviously in a tiled mode we'd prevent dragging that caused overlaps and in an overappled mode we'd ensure the view being dragged occludes any it gets dragged over).

![I2ttLTc 1](https://user-images.githubusercontent.com/585482/231309984-3be42d6a-6d1e-4887-aba9-1ac7acc89ae9.gif)

```
