### ISSUE TITLE
Add mouse/keyboard resizing of views

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#2537]
Right now, dragging is handled w/in TopLevel. This needs to change to be handled within Border (or in Application, but via an interface with Border). 

- [x] Define `ViewArrangement.Movable` - if set and view has a top Border, it can be dragged with mouse. Always with keyboard (although no visual indicator if no border).
- [x] Define `ViewArrangement.Sizable` - if set and a view has left/right/bottom Border it can be resized with mouse. Always with keyboard (although no visual indicator if no border).
- [ ] Determine keyboard drag/size UI
- [ ] Remove temporary hack in `Application.cs`:
<img width="631" alt="image" src="https://github.com/gui-cs/Terminal.Gui/assets/585482/9d8a3389-e326-4864-b64f-52680721758a">

Related: 
- #https://github.com/gui-cs/Terminal.Gui/issues/2502. 

My proposal:

### Mouse:

- Dragging `Border` top or bottom resizes the view vertically
- Dragging `Border` left or right resizes the view horizontally

### Keyboard:

- Hit `Ctrl+F5` to enable **Arrange Mode** [^whyctrlf5]
- A line will get a `◊` indicating it's active for resizing. Left/Right/Up/Down will size.
- Tab to move to next line
- Shift-Tab to move back 
- `Ctrl+F5` or `Esc` to exit **Arrange Mode** 

### Mouse:

- Dragging `Border` top moves the view
- Dragging `Border` bottom resizes the view vertically
- Dragging `Border` left or right resizes the view horizontally

### Keyboard:

- Hit `Ctrl+F5` to enable **Arrange Mode** [^whyctrlf5]
- A `◊` appears in top left corner of Border indicating **Arrange Mode**
- If `ViewArrangement.Movable` is set `Left/Right/Up/Down` will move the view 
- `Tab` and `Shift+Tab` will cycle through any sides that can be sized and "Move"
  - UNLESS: `ViewArrangement.Resizable` (all side-flags) is set. Then `◊` appears in bottom right corner of Border. 
- A side selected for sizing will get `◊` centered indicating it's active for resizing. 
- `Left/Right/Up/Down` will size as appropriate
- `Ctrl+F5` to exit **Arrange Mode** 

[^whyctrlf5]: On Windows `Alt-Space, M` enables move-with-keyboard. On Mac `Ctrl-F5` "Move focus to the window toolbar". No standard on Linux. `Ctrl-F5` isn't used by Windows Terminal. Happy for a better suggestion.

**Comment by tig** [comment]
This needs to fix #2536 too

**Comment by Nutzzz** [comment]
Y'know, I like the idea in general, but I'm personally not thrilled about those spinners in particular.  I feel like one of these might be better (if not perfect).

**2 frames, horizontal and vertical:**
![Recording 2023-04-18 112921](https://user-images.githubusercontent.com/5732804/232880549-f23389a5-f72c-441c-b1cf-76072f096bb1.gif)
**3 frames, horizontal and vertical:**
![Recording 2023-04-17 175433](https://user-images.githubusercontent.com/5732804/232880570-f1f6fdac-084a-4626-8085-5d1be1fbe46f.gif)

**Comment by tig** [comment]
@BDisp this is another Issue related to #2994

**Comment by tznind** [comment]
If one of the goals of this feature is to support TGD resizing use cases then I think that the solution needs to be decoupled from Borders.  

It must be possible to drag and resize any view (regardless of whether it has a Border).  For example:

![drag-resize](https://github.com/gui-cs/Terminal.Gui/assets/31306100/0236e652-bdc1-4e5a-88f1-38858bed46e3)

It also needs to be possible to drag multiple views at once e.g.

![drag-multiple](https://github.com/gui-cs/Terminal.Gui/assets/31306100/4333c1ba-411a-4994-95da-67e13308bc8b)

**Comment by tznind** [comment]
The relevant code in TGD is in:

[MouseManager](https://github.com/gui-cs/TerminalGuiDesigner/blob/v2/src/UI/MouseManager.cs)
[DragOperation](https://github.com/gui-cs/TerminalGuiDesigner/blob/v2/src/Operations/DragOperation.cs)
[DragMemento](https://github.com/gui-cs/TerminalGuiDesigner/blob/v2/src/Operations/DragMemento.cs)
[ResizeOperation](https://github.com/gui-cs/TerminalGuiDesigner/blob/v2/src/Operations/ResizeOperation.cs)

**Comment by tig** [comment]
> If one of the goals of this feature is to support TGD resizing use cases then I think that the solution needs to be decoupled from Borders.
> 
> It must be possible to drag and resize any view (regardless of whether it has a Border). For example:
> 
> ![resize-updated](https://private-user-images.githubusercontent.com/31306100/335811521-ceff52a3-8ef2-4e68-a131-faa11af9389f.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNjg2NzcsIm5iZiI6MTcxNzI2ODM3NywicGF0aCI6Ii8zMTMwNjEwMC8zMzU4MTE1MjEtY2VmZjUyYTMtOGVmMi00ZTY4LWExMzEtZmFhMTFhZjkzODlmLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDE4NTkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhM2I5NDVlY2Q3OTdmYTMxNjEwMjY1NTlkNzY3MWVlNzU4ZGUzMTUzM2NmMTA1Y2FlZmM4MzdhNmVlMzViYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5Fk7ajNSqV5RdvAfa4h5OMWfJbTw5_6mUfVUWdMZUPw) [ ![resize-updated](https://private-user-images.githubusercontent.com/31306100/335811521-ceff52a3-8ef2-4e68-a131-faa11af9389f.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNjg2NzcsIm5iZiI6MTcxNzI2ODM3NywicGF0aCI6Ii8zMTMwNjEwMC8zMzU4MTE1MjEtY2VmZjUyYTMtOGVmMi00ZTY4LWExMzEtZmFhMTFhZjkzODlmLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDE4NTkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhM2I5NDVlY2Q3OTdmYTMxNjEwMjY1NTlkNzY3MWVlNzU4ZGUzMTUzM2NmMTA1Y2FlZmM4MzdhNmVlMzViYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5Fk7ajNSqV5RdvAfa4h5OMWfJbTw5_6mUfVUWdMZUPw) ](https://private-user-images.githubusercontent.com/31306100/335811521-ceff52a3-8ef2-4e68-a131-faa11af9389f.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNjg2NzcsIm5iZiI6MTcxNzI2ODM3NywicGF0aCI6Ii8zMTMwNjEwMC8zMzU4MTE1MjEtY2VmZjUyYTMtOGVmMi00ZTY4LWExMzEtZmFhMTFhZjkzODlmLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDE4NTkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhM2I5NDVlY2Q3OTdmYTMxNjEwMjY1NTlkNzY3MWVlNzU4ZGUzMTUzM2NmMTA1Y2FlZmM4MzdhNmVlMzViYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5Fk7ajNSqV5RdvAfa4h5OMWfJbTw5_6mUfVUWdMZUPw) [ ](https://private-user-images.githubusercontent.com/31306100/335811521-ceff52a3-8ef2-4e68-a131-faa11af9389f.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNjg2NzcsIm5iZiI6MTcxNzI2ODM3NywicGF0aCI6Ii8zMTMwNjEwMC8zMzU4MTE1MjEtY2VmZjUyYTMtOGVmMi00ZTY4LWExMzEtZmFhMTFhZjkzODlmLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDE4NTkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhM2I5NDVlY2Q3OTdmYTMxNjEwMjY1NTlkNzY3MWVlNzU4ZGUzMTUzM2NmMTA1Y2FlZmM4MzdhNmVlMzViYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5Fk7ajNSqV5RdvAfa4h5OMWfJbTw5_6mUfVUWdMZUPw)
> 
> It also needs to be possible to drag multiple views at once e.g.
> 
> ![drag-multiple](https://private-user-images.githubusercontent.com/31306100/335811309-4333c1ba-411a-4994-95da-67e13308bc8b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNjg2NzcsIm5iZiI6MTcxNzI2ODM3NywicGF0aCI6Ii8zMTMwNjEwMC8zMzU4MTEzMDktNDMzM2MxYmEtNDExYS00OTk0LTk1ZGEtNjdlMTMzMDhiYzhiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDE4NTkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkMjZhM2U1MzY4YjJiMzJmNzEyYjRkMjI4NjNkZTQyYmJiNWZhMTFlYTAxYjkyMzAyYjNjMDgwMjgyODUzZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YUzM-6gflEQ05XqRpi9mUp6BkMo_fsGfP7DSNVhh1Qg) [ ![drag-multiple](https://private-user-images.githubusercontent.com/31306100/335811309-4333c1ba-411a-4994-95da-67e13308bc8b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNjg2NzcsIm5iZiI6MTcxNzI2ODM3NywicGF0aCI6Ii8zMTMwNjEwMC8zMzU4MTEzMDktNDMzM2MxYmEtNDExYS00OTk0LTk1ZGEtNjdlMTMzMDhiYzhiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDE4NTkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkMjZhM2U1MzY4YjJiMzJmNzEyYjRkMjI4NjNkZTQyYmJiNWZhMTFlYTAxYjkyMzAyYjNjMDgwMjgyODUzZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YUzM-6gflEQ05XqRpi9mUp6BkMo_fsGfP7DSNVhh1Qg) ](https://private-user-images.githubusercontent.com/31306100/335811309-4333c1ba-411a-4994-95da-67e13308bc8b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNjg2NzcsIm5iZiI6MTcxNzI2ODM3NywicGF0aCI6Ii8zMTMwNjEwMC8zMzU4MTEzMDktNDMzM2MxYmEtNDExYS00OTk0LTk1ZGEtNjdlMTMzMDhiYzhiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDE4NTkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkMjZhM2U1MzY4YjJiMzJmNzEyYjRkMjI4NjNkZTQyYmJiNWZhMTFlYTAxYjkyMzAyYjNjMDgwMjgyODUzZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YUzM-6gflEQ05XqRpi9mUp6BkMo_fsGfP7DSNVhh1Qg) [ ](https://private-user-images.githubusercontent.com/31306100/335811309-4333c1ba-411a-4994-95da-67e13308bc8b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNjg2NzcsIm5iZiI6MTcxNzI2ODM3NywicGF0aCI6Ii8zMTMwNjEwMC8zMzU4MTEzMDktNDMzM2MxYmEtNDExYS00OTk0LTk1ZGEtNjdlMTMzMDhiYzhiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDE4NTkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkMjZhM2U1MzY4YjJiMzJmNzEyYjRkMjI4NjNkZTQyYmJiNWZhMTFlYTAxYjkyMzAyYjNjMDgwMjgyODUzZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YUzM-6gflEQ05XqRpi9mUp6BkMo_fsGfP7DSNVhh1Qg)

I'll start thinking about this... 

I can't see anything really challenging, but it will require some thought...

Are you interested in collaborating with me on it?

**Comment by tznind** [comment]
> Are you interested in collaborating with me on it?

Definetly! lets see what we can do.

**Comment by tznind** [comment]
### Drag

### Drag Phases (i.e. State)

In order to support Undo and other stuff (like cancelling an ongoing drag) I think we should keep state in the same way TGD does with `DragOperation` and it's `DragMemento`:

- Only one drag operation can be running at once
- Use `ContinueDrag` style

So the process is:

```csharp
// Establishes the origin from which all vectors are measured
StartDrag (x,y)

// Updates positions of Views, each vector replaces the last (i.e. they are not additive)
ContinueDrag(new Vector(2,5))
ContinueDrag(new Vector(3,5))
ContinueDrag(new Vector(4,5))

// View is moved to x+4 y+5 and drag state is cleared
EndDrag()
```

### Drag Multiple At Once

TGD lets you select multiple views with a selection box.  I think this can be left in TGD.  But we do need the ability to drag multiple views at once.

For sanity sake probably we should require that all views in a multiple drag should be in the same parent View.

### Drag Boundary

When a drag results in some/all of a view spilling out of it's parent:

```csharp
    /// <summary>
    /// True to allow dragging a view such that part/all of it is
    /// outside of its parent View's viewport
    /// </summary>
    bool AllowDragOffscreen;
```

### Drag Initiation

There are 3 options for a View when it comes to initiating a drag

```csharp
enum Dragability
{
    /// <summary>
    /// View cannot be dragged
    /// </summary>
    NotDraggable,

    /// <summary>
    /// View can be dragged by clicking and dragging at row 0 of
    /// the view.
    /// </summary>
    DragFromTop,

    /// <summary>
    /// The view can be dragged by clicking and dragging anywhere
    /// in the view
    /// </summary>
    DragFromAnywhere
}
```


### Drag into another View

This is an opt in feature.  It could be a global value or View specific.  But if it is tied to Views then it makes multiple view drags more complicated.

```csharp
bool AllowDragToOtherViews;
```

To support dragging a view into another view we must think:

- Does it make sense to drag a view into a Button (probably not)
- Does it make sense to drag a view into a FrameView (yes)

So we need some kind of confirmation probably an `event` with a `Cancel` member is easiest

```csharp
event EventHandler<DragEventArgs> EndDrag;
```

```csharp
internal class DragEventArgs
{
    /// <summary>
    /// Describes the views being moved and where they are being moved to
    /// </summary>
    public DragOperation DragOperation { get; }

    /// <summary>
    /// Set to true to abandon the <see cref="DragOperation"/> and return
    /// all views to original positions
    /// </summary>
    public bool Cancel { get; set; }
}
```

### Composite views

Some views have sub views that complicate click and drag.  For example `TabView`.  We need something more structured than the current hacky implementation I have:

```csharp
/// <summary>
/// <para>
/// Sometimes <see cref="View.FindDeepestView"/> returns what the library considers
/// the clicked View rather than what the user would expect.  For example clicking in
/// the <see cref="Border"/> area of a <see cref="TabView"/>.
/// </para>
/// <para>This works out what the real view is.</para>
/// </summary>
/// <param name="hit"></param>
/// <returns></returns>
public static View? UnpackHitView(this View? hit)
{
    if (hit != null && hit.GetType().Name.Equals("TabRowView"))
    {
        hit = hit.SuperView;
    }

    // Translate clicks in the border as the real View being clicked
    if (hit is Border b)
    {
        hit = b.Parent;

    }

    // TabView nesting of 'fake' views goes:
    // TabView
    //   - TabViewRow
    //   - View (pane)
    //     - Border (note you need Parent not SuperView to find Border parent)

    if (hit?.SuperView is TabView tv)
    {
        hit = tv;
    }

    return hit;
}
```

**Comment by BDisp** [comment]
A few years ago I was interested in implementing mouse/keyboard drag and drop and resizing. Then I lost the will to continue.
Indeed, @tznind is right in stating that some of the features only make sense in TGD, otherwise any user could create another IDE very easily if TG already provides it. For example, it doesn't make sense that a `TextField` can be resized or moved in TG, but only in TGD. Drag from `FileDialog` to a `TextView` is valid in TG to open a file but in TGD it is moving the `FileDialog` to the limits of the `TextView`. Drag from `ListView` over the selected item to a `TextField` is valid in TG, and a `ContextMenu` can be opened to choose to copy or move the item, but in TGD it is moving the `ListView` to the limits of the `TextField`, or possibly linking the `TextField.Text` with the selected item.
In fact, the resizing and movement of a view must be decoupled from the border and only be coupled to the limits of the frame for resizing and within the limits of the frame for movement. In TG, only views that need to be resized and movable, their code must be overwritten in the border. In TGD the behavior will be normal, activating the necessary properties to be able to use them.
In TG, by default, a view cannot be resizable or movable, but only in some derived classes, such as `Window` and `Dialog`, if they are configured for that purpose. If it is resizable then a border must exist in order to select the appropriate glyph on either side of its limits. If it is simultaneously movable, in addition to the border, the thickness of the top of the border must be at least two, which will allow the view to be moved if the mouse is placed from the second thickness.
I'm glad this is being debated and will be very relevant for the advancement of this resource.

**Comment by tig** [comment]
Good stuff. 

Not a lot of thoughts so far. But one...

Add a flag to Arrangement:

- DesignMode

When set, effectively hides the Viewport from the mouse hit test code. Thus press and drag anywhere from Border-in works. Even if Border thickness is 0.

**Comment by tig** [comment]
Also, look at Highlight/HighlightMode. Can be extended to be combined with Arrangement.DesignMode to enable the whole view to be highlighted.

**Comment by BDisp** [comment]
But it would be useful if `Arrangement.DesignMode` was only visible internally, therefore only to TG and TGD.

**Comment by tig** [comment]
> But it would be useful if `Arrangement.DesignMode` was only visible internally, therefore only to TG and TGD.

Why would we not want someone else to build a design-time tool like TGD?

**Comment by BDisp** [comment]
> Why would we not want someone else to build a design-time tool like TGD?

I thought you wanted TGD exclusivity that belongs to gui-cs. If that's not the case then I take back what I said.

**Comment by dodexahedron** [comment]
It sucks so much for us that every platform and use tha forces us to have to have a "driver" to jump through different hoops to make this all happen. 😤

It's things like this that make libraries like TG so damn nice to use - abstracting away all the BS so the consumer can have a more consistent experience without worrying about it.

/gripe 😆

**Comment by tig** [comment]
In #3705 we now have this:

![nY8gsO7 1](https://github.com/user-attachments/assets/69714e65-372c-40fc-a95c-d5aff77fc02d)

**Comment by tig** [comment]
FWIW, this model supports Views without a Border.

Right now mouse doesn't work when in "Arrange Mode", but it willl....

![sWoyDXI 1](https://github.com/user-attachments/assets/3b336437-df60-4e57-800f-aad83af83c23)

**Comment by tig** [comment]
And now....

We have full mouse move/resize capability!

![7gi42jA 1](https://github.com/user-attachments/assets/01e383f6-b4e1-4a2a-a93d-0221f5653510)
