### ISSUE TITLE
Centering window label

### ISSUE THREAD

**Issue by josefreichelt** [gui-cs/Terminal.Gui#2541]
There doesnt seem to be a way to center the window title label.
Using v1
I'd expect TextAlignment to affect it, but it doesnt.

Is there a way to do this?

**Comment by BDisp** [comment]
In v1 there is no option for that. But in the v2 will have.

**Comment by tig** [comment]
See https://github.com/gui-cs/Terminal.Gui/issues/2505

Closing.

**Comment by josefreichelt** [comment]
Ah I see, thank you very much for the response
