### ISSUE TITLE
Snake broke

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#2546]
Likely because of

- Line.Length 1 now means 1 not 2 
- Frame != Bounds

Or a combo.

**Comment by BDisp** [comment]
A smaller border title is also rendering bad.

![imagem](https://user-images.githubusercontent.com/13117724/232161506-6727b2c1-a472-4fb3-995c-64b82750a1f5.png)

**Comment by BDisp** [comment]
@tig is there something already created that use `LineCanvas` to supersede the obsolete `DrawFrame`?

**Comment by tig** [comment]
Why are you commenting on this Issue instead of a new one?

**Comment by BDisp** [comment]
The first comment because I thought the border title issue was related with the Line issue.
The second because it was only was to asking if there any method that supersede the obsolete `DrawFrame` and use the `LineCanvas`. If there isn't I can open a new issue. Sorry for the disturbing :-)
