### ISSUE TITLE
FileDialog CollectionNavigator only considers filename

### ISSUE THREAD

**Issue by tznind** [gui-cs/Terminal.Gui#2554]
**Describe the bug**

<img width="331" alt="image" src="https://user-images.githubusercontent.com/585482/232046927-9fc6d77f-bca2-4c52-a9cd-53e296f9611d.png">

> The cursor is active. When I click on an item in a column (e.g. on .dl in Type) the cursor moves to that column. I'd expect that `CollectionNavigator` would kick in and I could type `d` and the first `dir` would be selected, but no.

**Comment by BDisp** [comment]
@tznind don't forget to fix the culture in the unit test. Thanks.

**Comment by tznind** [comment]
> @tznind don't forget to fix the culture in the unit test. Thanks.

That fix is in #2522 🚀

**Comment by tznind** [comment]
Fixed in https://github.com/gui-cs/Terminal.Gui/issues/2555
