### ISSUE TITLE
Scroll control doesn't work properly

### ISSUE THREAD

**Issue by ttool22** [gui-cs/Terminal.Gui#2562]
**C# code is below**

var scrollView = new ScrollView();
scrollView.X = 0;
scrollView.Y = 0;
scrollView.Width = Dim.Fill();
scrollView.Height = Dim.Fill();
scrollView.ContentSize = new Size(Console.WindowWidth, Console.WindowHeight * 2);
_____

When I scroll down, I got this error(below), I have win 11 ;(

A clear and concCollection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at Terminal.Gui.View.Redraw(Rect bounds)
   at Terminal.Gui.FrameView.Redraw(Rect bounds)
   at Terminal.Gui.View.Redraw(Rect bounds)
   at Terminal.Gui.ScrollView.Redraw(Rect region)
   at Terminal.Gui.View.Redraw(Rect bounds)
   at Terminal.Gui.Window.Redraw(Rect bounds)
   at Terminal.Gui.Application.RunMainLoopIteration(RunState& state, Boolean wait, Boolean& firstIteration)
   at Terminal.Gui.Application.RunLoop(RunState state, Boolean wait)
   at Terminal.Gui.Application.Run(Toplevel view, Func`2 errorHandler)
   at Terminal.Gui.MessageBox.QueryFull(Boolean useErrorColors, Int32 width, Int32 height, ustring title, ustring message, Int32 

*

**Comment by BDisp** [comment]
I couldn't reproduce this. I see you are using the scroll inside a frame. On what `Terminal.Gui` version you are running, v1 or v2?

**Comment by tznind** [comment]
Or if you are using the Nuget package? If so what version?  Are you able to provide a link to your source code or give any more details.  For example where do you launch the View, do you call Application.Init etc.

**Comment by ttool22** [comment]
I ha have 1.72 version with win 11, I have added scroll inside window
**win.Add(scrollView);**
 **Application.Run(win, (e) =>
{
    MessageBox.ErrorQuery("Error", e.ToString(), "Ok");
    return false;
});**

**Comment by ttool22** [comment]
When I run my app on win 11, controls are mixed  then I fix it by expanding the window with the mouse.

**Comment by BDisp** [comment]
I recommend you to download the current v1 from the repo, which is the `develop` branch and check if the issue still exist.

**Comment by ttool22** [comment]
Now I am using the latest nuget (1.10.1), I have this error
  **at Terminal.Gui.Border.DrawTitle(View view)**

**Comment by ttool22** [comment]
I have thxed the error above, var win = new Window()
{
    X = 0,
    Y = 0,
    Width = Dim.Fill(),
    Height = Dim.Fill(),
    Border = new Border()
    {
        **BorderBrush = Color.BrightBlue**
        
    }
   
};

But my control in scrollView doesn't appear, in the previous version (1.7.2) they appear

**Comment by ttool22** [comment]
![image](https://user-images.githubusercontent.com/109524193/232791683-d89a3f46-c353-49e2-b238-a5d3e2ebc9f3.png)

I work with frame in scrollView, I fill it dinamic also I can't delete frame, I tryed FrameView.SubViews[0].Subviews.Clear(); but it throws error

 FrameView FrameControl = new FrameView()
        {
            X = 0,
            Y = 30
            Width = 120,
            Height = 0,
            Border = new Border() { BorderStyle = BorderStyle.None, BorderThickness = new Thickness(1, 1, 1, 1) },
            Visible = false,
            Id = "Frame"
        };
 FrameControl .Add(new Label() { Y = brLines * 4, X = 12, Text = "1" });
 FrameControl .Add(new Label() { Y = brLines * 4, X = 24, Text = "x", });
 FrameControl .Add(new Label() { Y = brLines * 4, X = 36, Text = "2" });****

**Comment by ttool22** [comment]
When scroll controls become mixed then throw this error

**Comment by BDisp** [comment]
You can't remove the `FrameView` with `FrameView.SubViews[0].Subviews.Clear()`. If you added the `FrameView` into the `ScrollView` and want to remove it you have to use `scrollView.Remove(FrameControl );`.

**Comment by BDisp** [comment]
This scenario https://github.com/gui-cs/Terminal.Gui/blob/develop/UICatalog/Scenarios/ASCIICustomButton.cs use a `FrameView` inside a `ScrollView`. Maybe it can help you to check what you are doing wrong.

**Comment by tig** [comment]
> This scenario https://github.com/gui-cs/Terminal.Gui/blob/develop/UICatalog/Scenarios/ASCIICustomButton.cs use a `FrameView` inside a `ScrollView`. Maybe it can help you to check what you are doing wrong.

I don't think that's a great sample. It's quite convoluted.

`Character Map` also shows this, but it too does a lot of other things.

**Comment by ttool22** [comment]
Neither do I, btw labels not clickable anymore in the latest version, lot of bugs...

**Comment by ttool22** [comment]
![image](https://user-images.githubusercontent.com/109524193/232983636-ee24abc5-193a-4596-837c-f414cdb8928a.png)

Why I have this problem on win 11?

**Comment by ttool22** [comment]
Controls are mixed by default

**Comment by BDisp** [comment]
Very strange. Do you are using `Windows Terminal`?

**Comment by ttool22** [comment]
Yes it is windows console

**Comment by ttool22** [comment]
![image](https://user-images.githubusercontent.com/109524193/233048432-b06fd24c-b4b2-4147-a6bf-ed892b563770.png)

When I scroll up, it throws this error in windows terminal, I don't have any clue how I can resolve it

**Comment by ttool22** [comment]
![image](https://user-images.githubusercontent.com/109524193/233050253-7547505e-1de7-452e-a6c3-f5e855f4e7f4.png)

**Comment by ttool22** [comment]
![image](https://user-images.githubusercontent.com/109524193/233054079-c1d090b5-1a53-4aa6-a11a-7f0ca0cd3110.png)

Is the problem with windows driver or sth else?

**Comment by BDisp** [comment]
> When I scroll up, it throws this error in windows terminal, I don't have any clue how I can resolve it

It seems that you are removing some views while `Redraw` and `LayoutSubviews` is running. You can't do it on `Redraw`. It's possible to you upload to your github a simple demo that reproduce this issue? If you want to test with another driver put `Application.UseSystemConsole = true` before `Application.Init()`.

**Comment by ttool22** [comment]
Yes every one sec I have to use the same frameView with new data. The frameview contains some controls(labels and textfields). How can I do scroll and represent these dates in frameView? Can you write some lines with small example? The important thing is that frameView creates dinamically. My question is that how I can do scroll and fill data every sec in frameview?

**Comment by tznind** [comment]
When updating Terminal.Gui from a Thread, the most important thing to do is to ensure any UI related code goes via `Application.MainLoop.Invoke`.  This is how cross thread UI access is managed in Terminal.Gui.

**Comment by BDisp** [comment]
If you had said soon you were using threads, that would be more easy. If you are initializing the FrameView every one sec on a thread, then you have this to do this in the thread method:

```cs
Application.MainLoop.Invoke () => {
scrollView.RemoveAll();
FrameView FrameControl = new FrameView()
{
X = 0,
Y = 30
Width = 120,
Height = 0,
Border = new Border() { BorderStyle = BorderStyle.None, BorderThickness = new Thickness(1, 1, 1, 1) },
Visible = false,
Id = "Frame"
};
FrameControl .Add(new Label() { Y = brLines * 4, X = 12, Text = "1" });
FrameControl .Add(new Label() { Y = brLines * 4, X = 24, Text = "x", });
FrameControl .Add(new Label() { Y = brLines * 4, X = 36, Text = "2" });
scrollView.Add(FrameControl);
};

```

**Comment by ttool22** [comment]
Thank you guys, it doesn't throws error but scroll does not work smoothly after some period

**Comment by ttool22** [comment]
I call it on this way Application.MainLoop.Invoke(async()=> { await RepresentData })}); RepresentData is a Task

**Comment by BDisp** [comment]
> I call it on this way Application.MainLoop.Invoke(async()=> { await RepresentData })}); RepresentData is a Task

That's ok, but you still must use inside the `RepresentData` again the `Application.MainLoop.Invoke` to recreate the `FrameView`.

**Comment by tig** [comment]
Doesn't seem like there's a bug here. Reopen if I'm wrong.
