### ISSUE TITLE
Cancel application exit request

### ISSUE THREAD

**Issue by inflop** [gui-cs/Terminal.Gui#2564]
Hi, is there an easy way to cancel application exit request? I want to handle a global exit request from anywhere in the application. I mean something like below. 
```csharp 
...
Application.Exit += OnApplicationExit;
...
static void OnApplicationExit(object sender, CancelEventArgs e)
{
    // Prompt the user to confirm exit
    var result = MessageBox.Query("Confirm Exit", "Are you sure you want to exit?", "Yes", "No");

    if (result == 1) // If the user selects "No"
    {
        e.Cancel = true; // Cancel the exit
    }
    else // If the user selects "Yes"
    {
        // Clean up resources or perform any necessary actions before exiting
    }
}
```

**Comment by BDisp** [comment]
The `Toplevel` has a `Closing` event that you can subscribe to cancel a `RequestStop`, but if you are talking about canceling a console from closing after clicking the window close button (X), there is no chance to cancel the window from closing like on `Windows Froms`.

**Comment by inflop** [comment]
The Closing event on the Toplevel object is good enough for my needs, thanks.
