### ISSUE TITLE
Borders scenarios needed to be refactored.

### ISSUE THREAD

**Issue by BDisp** [gui-cs/Terminal.Gui#2569]

**Comment by tig** [comment]
I'm really glad you did this, but I think you should just build on `Frames Demo` and delete these:

- `Borders Comparsions`
- `Borders on FrameView`
- `Borders on Window`

Please see the work I did in `Frames Demo` in componentizing the "editors".

Also, in v2, there is no practical difference between a `View`, a `Toplevel, `Window`, and a `FrameView` when it comes to borders. So there's no need for separate scenarios for each of them.

**Comment by BDisp** [comment]
Ups, you are right. I didn't see this scenario before, sorry. I'll do the changes.
