### ISSUE TITLE
Wizards background shifts to gray when focusing, looks bad.

### ISSUE THREAD

**Issue by krypto5863** [gui-cs/Terminal.Gui#2571]
**Describe the bug**
Focusing on a wizard window tends to make the background gray which tends to mess up the look.

**To Reproduce**
Open a wizard and click the view. It's most noticeable with textboxes an stuff.

**Expected behavior**
I expected the clicked element, buttons/textboxes/etc,. to change color to show they're focused, instead the whole window went gray.

**Screenshots**
![image](https://user-images.githubusercontent.com/29824718/233796198-dd209ada-fa74-484f-9c3f-d7bbc976bc59.png)

**Comment by BDisp** [comment]
That isn't happening with me n both v1 and v2.

![imagem](https://user-images.githubusercontent.com/13117724/233797312-1112e063-026f-4498-9478-d3cd061cfad8.png)

**Comment by krypto5863** [comment]
That's strange, I'm just running UI catalog, haven't touched anything in the project either, happens with my own separate project where I get Terminal.GUI via nuget.

**Comment by BDisp** [comment]
Maybe the nuget package isn't yet updated with the current develop branch.

**Comment by krypto5863** [comment]
Nuget version reads 1.10.1, but I cloned the repo to run the UICatalog, so it shouldn't matter anyways.

**Comment by WayneHiller** [comment]
I am having the same issue.

![image](https://user-images.githubusercontent.com/1186731/235543429-4b9a7bc6-2910-458e-9d82-ef35bc885c3e.png)

**Comment by tznind** [comment]
Here is a minimum repro

![wizard](https://user-images.githubusercontent.com/31306100/235763831-48cf22b8-16a2-447d-9fbe-2320082949f5.gif)


```csharp
using Terminal.Gui;

Application.Init();

var w = new Window();

var label = new Label("I'm outside wizard:");
var tf = new TextField("yay") { X = 20, Width = 20 };
w.Add(label);
w.Add(tf);

var wizard = new Wizard
{
    X = 0,
    Y = 1,
    Width = Dim.Fill(),
    Height = Dim.Fill(),
    Modal = false,
    TabStop = true
};

var step = new Wizard.WizardStep("Yarg");
step.Add(new Label("SomeText:"));
step.Add(new TextField() { Y=1,Width = 10});
step.Add(new Label("SomeText2:") { Y = 2, });
step.Add(new TextField() { Y = 3, Width = 10 });

wizard.AddStep(step);


var step2 = new Wizard.WizardStep("Blerg");
step2.Add(new Label("SomeText3:"));
step2.Add(new TextField() { Y = 1, Width = 10 });
wizard.AddStep(step2);

w.Add(wizard);

Application.Run(w);

Application.Shutdown();

```

**Comment by tig** [comment]
I'll look into this asap!

**Comment by Piotr86PL** [comment]
It turns out that the problem does not only occur with Wizard, but also with TabView. You can see this using the code below, but the TabView Demo from UICatalog (tab "Interactive Tab") also has this bug.

```csharp
Application.Init();
Toplevel top = Application.Top;
Window mainWindow = new Window("MainWindow");

View tabTestView = new View() { Height = Dim.Fill(), Width = Dim.Fill() };
tabTestView.Add(new Label("SomeText:") { Y = 0 });
tabTestView.Add(new TextField() { Y = 1, Width = 10 });
tabTestView.Add(new Label("SomeText2:") { Y = 2 });
tabTestView.Add(new TextField() { Y = 3, Width = 10 });

TabView tabs = new TabView() 
{ 
    Width = Dim.Fill(),
    Height = Dim.Fill()
};
tabs.AddTab(new TabView.Tab("Tab1", tabTestView),false);
mainWindow.Add(tabs);
top.Add(mainWindow);
Application.Run();
Application.Shutdown();
```

![tabview_bug](https://github.com/gui-cs/Terminal.Gui/assets/39170443/1528cc16-8bc5-4fe4-bc25-0520ec6ad61f)
![tabview_bug_uicatalog](https://github.com/gui-cs/Terminal.Gui/assets/39170443/af0c018f-62dd-4827-abdd-b5cddbcd722b)

**Comment by BDisp** [comment]
Can you reproduce this on the v2 too? Can you please write s small example that reproduce this for to more quicker find the cause? Thanks.

**Comment by heinrich-ulbricht** [comment]
@BDisp Thanks for the reponse! I'm bound to v1. The UI is moderately complex, I need to strip it down. Hope to do that over the holidays.

**Comment by BDisp** [comment]
> @BDisp Thanks for the reponse! I'm bound to v1. The UI is moderately complex, I need to strip it down. Hope to do that over the holidays.

@heinrich-ulbricht can you please test with the PR #3194 to confirm if it's working well now for you. Thanks.
