### ISSUE TITLE
How should `MouseEvent` work with `Margin`, `Border`, and `Padding`?

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#2578]
Right now in v2_develop:  The `me` parameter contains `Frame`-relative coordinates. As a result, any View that wants to override this must adjust for the frames thickness. 

E.g.  From an updated ColorPicker:
 
```cs 
                public override bool MouseEvent (MouseEvent me)
		{
			if (!me.Flags.HasFlag (MouseFlags.Button1Clicked) || !CanFocus) {
				return false;
			}

			SetFocus ();
			Cursor = new Point ((me.X - GetFramesThickness ().Left) / _boxWidth, (me.Y - GetFramesThickness ().Top) / _boxHeight);

			return true;
		}
```

I don't think most View developers should need to deal with this; they should get mouse coordinates relative to the `Bounds`.

I think `Application.ProcessMouseEvent` should be calling `view.GetFramesThickness` and using that to cause `me.X` and `me.Y` to be `Bounds` relative.

If a View implementation wants to get mouse events for its `Margin`, `Border`, or `Padding` it can do so by subscribing to the appropriate mouse events.

What do you all think?

**Comment by tznind** [comment]
I think it would be nice if there was an Enum in MouseEvent that told you where the mouse was within the `View`.  For example (padding, margin, border or client area).  We could have a direction too for those (Upper, Left, Right, Bottom) or None (for client area).

The x/y coordinates should be relative to the origin (0,0) of the bit that the mouse is operating in e.g. (0,50) of the lower margin would be a click in the middle bottom of the view when margin is 1?

**Comment by BDisp** [comment]
And to complicate even more if we want a 3D effect shadow, it will be a new frame between the `Margin` and the `Border`. His frame isn't take in account for the total location and dimensions. The `Margin` has to allow transparency and the 3D effect will draw the contents around it. Only a thought.

**Comment by tig** [comment]
> And to complicate even more if we want a 3D effect shadow, it will be a new frame between the `Margin` and the `Border`. His frame isn't take in account for the total location and dimensions. The `Margin` has to allow transparency and the 3D effect will draw the contents around it. Only a thought.

I don't think a 3deffect Frame is needed. 3d shadows should be rendered by the superview's 'DrawFrames()' after OnRenderFrames is called.

**Comment by tig** [comment]
I'm now working on this....
