### ISSUE TITLE
`Responder.MouseEvent` and `View.OnMouseEvent` are backwards - Refactor

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#2579]
I thought the event pattern was:

- Verb method (e.g. `MouseEvent`) 
   - is not virtual.
   - calls "on method" - `OnMouseEvent`
       - Invokes events - e.g. `MouseClick`

Currently, 

- Verb method called form `Applicaiton.ProcessMouseEvent` is `view.OnMouseEvent`
  - Which calls `MouseEvent()`, which tons of views override

Am I just confused or was this all done incorrectly?

**Comment by BDisp** [comment]
> Am I just confused or was this all done incorrectly?

It was done incorrectly to not breaking changes in v1. So the correct wold be:

```cs
//On Responder:
public virtual bool OnMouseEvent(MouseEvent mouseEvent)
```
```cs
//On View:
public override bool OnMouseEvent(MouseEvent mouseEvent)
```
```cs
//where will invoke first
public event EventHandler<MouseEventEventArgs> MouseEvent
//and if not canceled will call the
base.OnMouseEvent(mouseEvent)
```

**Comment by BDisp** [comment]
I think so. I also think that the `MouseClick` event is confusing and unnecessary. The `MouseEvent` event is enough.

**Comment by tig** [comment]
Should be addressed in

- #2029 

Closing

**Comment by tig** [comment]
I'm re-opening this. I'd like to fix just this part of the big "mouse mess" in order to make progress on 

- #3278

without having to fix ALL of the sins of `MouseEvent`. 

I'll be working on a PR for this today.

**Comment by BDisp** [comment]
I've already noticed that after the `v2_develop` merger, my PR is no longer working, especially the mouse in the adornments.

**Comment by tig** [comment]
> I've already noticed that after the `v2_develop` merger, my PR is no longer working, especially the mouse in the adornments.

It only worked before because you worked around bugs in `v2_develop` that I fixed in #3274 and #3277.

You will either need to wait until I finish fixing #3274 (PR #3278) or re-hack your PR temporarily.

**Comment by BDisp** [comment]
> @BDisp please look at the ToDos in #2579 and let me know your thoughts relative to this. Thanks.

On #3281 I already looked at the `Todos` and I agree with al of them. Have a good work.

**Comment by dodexahedron** [comment]
Thank you. One less work item for when I get to that mythical event refactor task, probably some time around version 42.
