### ISSUE TITLE
Support ICollectionNavigator in TableView

### ISSUE THREAD

**Issue by tznind** [gui-cs/Terminal.Gui#2581]
> 
> @tznind how hard it is to make CollectionNavigator work with tableview?

Its doable because I did a 'good enough' implementation for FileDialog (see `UpdateCollectionNavigator` method).  

But to add it as a core feature of `TableView` would require some care as we don't want to compromise performance when working with large tables.

For example if you have 1 million rows then you don't want to be regularly passing them to a new navigator just because the user changed columns.  

And you don't want to duplicate all the data at all really because it can change.

I think we would want an interface `ICollectionNavigator` and then implement `GetNextMatchingItem` to search the  `ITableSource` data directly (starting at the current offset).

Its definitely doable but requires care.

I am refactoring `FileDialog` to use `ITableSource` at the moment (its making the code much cleaner).  I can look into the collection navigation next.

_Originally posted by @tznind in https://github.com/gui-cs/Terminal.Gui/issues/2576#issuecomment-1528081506_

**Comment by tig** [comment]
See #2584 for my workaround in UI Catalog
