### ISSUE TITLE
TableView: If `FullRowSelect == true` shouldn't `Home` and `End` keys go to top / bottom?

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#2585]
Current:

```cs
			AddKeyBinding (Key.Home, Command.LeftHome);
			AddKeyBinding (Key.End, Command.RightEnd);
```

But if there's only one column (or `FullRowSelect == true`) this doesn't make sense. 

Suggestion is to change these bindings to the following if `FullRowSelect == true` or if there's only one column. 

```cs
AddKeyBinding (Key.Home, Command.TopHome);
AddKeyBinding (Key.End, Command.BottomEnd);
```

**Comment by tznind** [comment]
Even with `FullRowSelect` on, there is still a single 'active' cell (where
thr cursor is).  Primarily this drives horizontal scrolling.

So Home/End would still take you to first/last column.

There are also other use cases where the API user might care which column
is 'active' (even with FullRowSelect) e.g. opening a context menu via a
keyboard shortcut (for hide column/sort column etc).

**Comment by tig** [comment]
Totally acceptable for devs to have to change keybindings. UI Catalog now does this.

**Comment by tig** [comment]
Closing as "won't fix"
