### ISSUE TITLE
Change the glyphs type from Rune to string.

### ISSUE THREAD

**Issue by BDisp** [gui-cs/Terminal.Gui#2632]
> > One thing come on mind is to change all glyphs to string. This will be more easy to manipulate with text. What do you think?
> 
> 
> 
> I only asked because some glyphs may be set with more than one code point, like the Man, Woman and Girl emoji 👨‍👩‍👧, which is presented with `"\U0001F468\u200D\U0001F469\u200D\U0001F467"` string and cannot be displayed with only one code point.
> 
Good call. Please open an issue and I'll do that!

_Originally posted by @tig in https://github.com/gui-cs/Terminal.Gui/issues/2620#issuecomment-1546813406_
            
@tig for surrogate pairs code points please use the encoded code point e.g. `Man` 👨 or `"\U0001F468"`, instead of the decoded two surrogate pairs (`"\ud83d\udc68"`).

**Comment by tig** [comment]
> ```
>           > > One thing come on mind is to change all glyphs to string. This will be more easy to manipulate with text. What do you think?
> ```
> 
> > I only asked because some glyphs may be set with more than one code point, like the Man, Woman and Girl emoji 👨‍👩‍👧, which is presented with `"\U0001F468\u200D\U0001F469\u200D\U0001F467"` string and cannot be displayed with only one code point.
> 
> Good call. Please open an issue and I'll do that!
> 
> _Originally posted by @tig in [#2620 (comment)](https://github.com/gui-cs/Terminal.Gui/pull/2620#issuecomment-1546813406)_
> 
> @tig for surrogate pairs code points please use the encoded code point e.g. `Man` 👨 or `"\U0001F468"`, instead of the decoded two surrogate pairs (`"\ud83d\udc68"`).

Is it bad to use the decoded two surrogate pair form?

**Comment by BDisp** [comment]
> Is it bad to use the decoded two surrogate pair form?

If they are valid, of course it's not bad. But if they aren't a valid surrogate pair will throw at runtime. The encoded code point it's only for the user having his value directly, but feel free to do what you want 👌

**Comment by tig** [comment]
After first `Rune` -> `string` in `GlyphDefinitions` and realizing this makes USING the glyphs awkward (`Rune x = CM.Checked.ToRunes() [0]` or similar alternatives), I think the right thing to do is leave `GlyphDefinitions` to continue to use `Rune` as the property type, but enhance `RuneJsonConverter` to support specifying each property either a char, string, or int.

This will all be valid:

```json
    "Checked":  '☑',
    "Checked":  "☑",
    "Checked":   "/u2611",
    "Checked":   "U+2611",
    "Checked":   '/u2611',
    "Checked": 9745,
    "Man": "👨",
    "Man":  "\U0001F468",
    "Man": "\ud83d\udc68",
    "Man": "\U+1F468",
```

I will introduce both unit tests and exceptions if a property in `GlyphDefinitions` cannot be normlized to a single rune (using `Rune.TryCreate`). These will fail:

```json
    "Checked":  '☑☑',
    "Checked":  "☑☑",
    "Checked":   "/u2611/u2611",
    "TooManyMen":  "\U0001F468\U0001F468",
    "HighSurrogate": "\ud83d"
```

etc...

**Comment by tig** [comment]
See #2632. 

Should I make it a PR to your #2620 PR @BDisp, or can we merge them separately?

**Comment by BDisp** [comment]
> Should I make it a PR to your #2620 PR @BDisp, or can we merge them separately?

@tig do whatever is more easy for both.

**Comment by BDisp** [comment]
The `RuneJsonConverter` must check if a rune with two surrogates has a valid surrogate pair, which has a valid high surrogate and a valid low surrogate, otherwise shouldn't accept it. A alone high surrogate or a alone low surrogate aren't accepted. If a rune is composed by various non surrogate it may be a valid string, or if it's composed by valid surrogate pairs and with non surrogate, it may be a valid string.

**Comment by tig** [comment]
> The `RuneJsonConverter` must check if a rune with two surrogates has a valid surrogate pair, which has a valid high surrogate and a valid low surrogate, otherwise shouldn't accept it. A alone high surrogate or a alone low surrogate aren't accepted. If a rune is composed by various non surrogate it may be a valid string, or if it's composed by valid surrogate pairs and with non surrogate, it may be a valid string.

Please review the unit tests I added to `UnitTests\Configuration\RuneJsonConverterTests.cs` to ensure I've covered these cases. Thanks.

Note, the Rune constructor will throw an invalid argument exception if initialized with just a low-surrogate, so it's not possible to do this:

```cs
		/// <summary>
		/// A nonprintable (low surrogate) that should fail to ctor.
		/// </summary>
		public Rune InvalidGlyph { get; set; } = (Rune)'\ud83d';
```

**Comment by BDisp** [comment]
> Please review the unit tests I added to `UnitTests\Configuration\RuneJsonConverterTests.cs` to ensure I've covered these cases. Thanks.
> 
> Note, the Rune constructor will throw an invalid argument exception if initialized with just a low-surrogate, so it's not possible to do this:
> 
> ```cs
> 		/// <summary>
> 		/// A nonprintable (low surrogate) that should fail to ctor.
> 		/// </summary>
> 		public Rune InvalidGlyph { get; set; } = (Rune)'\ud83d';
> ```
`
With surrogate pairs, a Unicode code point from range U+D800 to U+DBFF (called "high surrogate") gets combined with another Unicode code point from range U+DC00 to U+DFFF (called "low surrogate") to generate a whole new character, allowing the encoding of over one million additional characters.`

@tig what you used above was a"high surrogate", but if you use a "low surrogate", like  `(Rune)'\udc3d'` would also fail to ctor. So, a valid surrogate pair will only be checked if a "high surrogate" is followed by a "low surrogate". Alone, both are invalid.
Adding a "low surrogate" to the unit tests would be recommendable.
