### ISSUE TITLE
Unit Tests are failing on Windows on `v2_develop` branch

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#2649]
Something weird with `WindowsClipboard`. 

<img width="510" alt="image" src="https://github.com/gui-cs/Terminal.Gui/assets/585482/ddaa69ee-5ce2-4b85-b7ee-14dda9da5866">

I'm running this down now.

**Comment by BDisp** [comment]
I don't have this issue @tig. Do you are using the right last `v2_develop` branch?

**Comment by tig** [comment]
> I don't have this issue @tig. Do you are using the right last `v2_develop` branch?

It is non-deterministic. Fucking driving me nuts.

**Comment by BDisp** [comment]
> It is non-deterministic. Fucking driving me nuts.

Visual Studio or VSCode?

**Comment by tig** [comment]
I do think we introduced a bug in WindowsDriver/Clipboard with the ustring->string change.

Forcing FakeClipboard for all unit tests that don't explicitly set `UseFakeClipboard == true` fixes this.

Hell if I can tell what broke though (or if something is actually broken).

**Comment by BDisp** [comment]
In this case I should also getting unit tests failures and I don't have. Perhaps it's something change you have done but you not yet committed and pushed to the PR branch.

**Comment by BDisp** [comment]
@tig there is something strange now. In my fork the v2_develop is up to date but upside appears say that had recent pushes. If I click on "Compare & pull request" there is nothing to compare.

![imagem](https://github.com/gui-cs/Terminal.Gui/assets/13117724/873bea5c-4444-4702-831c-429f0093f1d7)

![imagem](https://github.com/gui-cs/Terminal.Gui/assets/13117724/52faae55-6ef4-496d-b3a6-e66370141aec)

**Comment by BDisp** [comment]
Forget now it's fixed and I really don't know what was happened.
