### ISSUE TITLE
`NetDriver`: Cursor flickers  when mouse is moved 

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#2666]
#2659 fixed making the cursor visible, but at the expense of making it flicker:

![4IuExdu 1](https://github.com/gui-cs/Terminal.Gui/assets/585482/45df1ae7-c692-4519-ae09-b0081c7328e6)

I think the logic in `SetCursorPosition` may be off?

```cs
public override bool SetCursorVisibility (CursorVisibility visibility)
{
	savedCursorVisibility = visibility;
	var isVisible = Console.CursorVisible = visibility == CursorVisibility.Default;
	if (isVisible) {
		Console.Out.Write ("\x1b[?25h");
	} else {
		Console.Out.Write ("\x1b[?25l");
	}
	return isVisible;
}
```

**Comment by BDisp** [comment]
On Windows escape sequences are very slow. Try on WSL and you'll see different behavior. As more you move the mouse more flicker it's.

**Comment by tig** [comment]
It appears to me our logic is flawed. We should not be setting/unsetting the cursor so frequently!

**Comment by BDisp** [comment]
> I think the logic in `SetCursorPosition` may be off?

It's already off when it's updating the screen. No it shouldn't be off, because it's a `TextField` which want a visible cursor. The problem is Windows processes escape sequences very slowly.

**Comment by BDisp** [comment]
> It appears to me our logic is flawed. We should not be setting/unsetting the cursor so frequently!

In the `UpdateScreen` it's needed, otherwise in Windows you will see the cursor jumping all the time while the buffer is writing to the screen.

**Comment by tig** [comment]
Wow, I just went all the way back to v1.6.4 to see how the cursor behaved in NetDriver then because I didn't remember the flickering.

Now I see that the cursor wasn't visible at all, going that far back! 
🤯

Did it ever work?

Maybe this is why Miguel didn't have it enabled?

**Comment by BDisp** [comment]
> Wow, I just went all the way back to v1.6.4 to see how the cursor behaved in NetDriver then because I didn't remember the flickering.
> 
> Now I see that the cursor wasn't visible at all, going that far back! 🤯
> 
> Did it ever work?
> 
Yes it worked before, even after I implemented escape sequences that before didn't existed.

> Maybe this is why Miguel didn't have it enabled?

Miguel let it enabled, only was 100% `System.Console` which wasn't completed compatible with `Linux`. For this reason I implemented the escape sequences that you already know enough. Now it work better with `Linux` than with `Windows`. After that I saw that the cursor wasn't visible on `Windows` and that why I fix it.

**Comment by BDisp** [comment]
> This stinks. I gotta believe there's a way for us to code netdriver to reduce this flickr. So I'm going to leave this issue open.

Only if `Microsoft` make a compatible `ConPTY` terminal that acts as faster like `WSL` with escape sequences. It is a shame that there is not this in Windows, that I know.

**Comment by BDisp** [comment]
Due the #2931 fixes the `NetDriver` it's more rapid than before. Also one of the cause of this issue was the `state.Toplevel.SetNeedsDisplay ();` being called when `EnsureCursorVisibility` is true. The cursor is managed by the terminal and isn't need to draw anything to show the cursor. When `state.Toplevel` is dirty then the `Driver.Refresh` method will be called, which in turn will call `UpdateScreen` and `UpdateCursor` methods. When `state.Toplevel` isn't dirty then only the `Driver.UpdateCursor` will be called.

**Comment by tig** [comment]
This Issue seems fixed in v2_develop! 

There's still some flicker when moving the mouse, but this is so much better than before.

![MyeYCdw 1](https://github.com/gui-cs/Terminal.Gui/assets/585482/7e73bf45-f5dd-41c4-b283-9e2f0b833977)

**Comment by BDisp** [comment]
> This Issue seems fixed in v2_develop!
> 
Yes it's.

> There's still some flicker when moving the mouse, but this is so much better than before.

It's natural when the mouse is always moving. As the screen isn't dirty but the `UpdateCursor` method is always running on each iteration.
