### ISSUE TITLE
Layout subviews does not apply `Width` changes to `Bounds`

### ISSUE THREAD

**Issue by tznind** [gui-cs/Terminal.Gui#2672]
**Describe the bug**
Changes to `Width` are only reflected in `Bounds` after calling `LayoutSubviews` on super which seems fine.  But subsequent changes to `Width` are not applied to `Bounds` even after calling `LayoutSubviews` again.

If there is a workaround or this is expected behaviour let me know and I can apply to the tests in TerminalGuiDesigner.  This is a common use case in the designer (e.g. drag resizing a view) so there are several tests that fail because of it.  I notice that `Frame` is updated but don't want to re-write all my tests to just check `Frame` instead without understanding if that is correct.

**To Reproduce**

```csharp
[Fact, AutoInitShutdown]
public void TestResize ()
{
	var w = new Window ();
	var v = new View { Width = 8, Height = 8 };

	w.Add (v);

	Assert.Equal (0, v.Bounds.Width);

	w.LayoutSubviews ();

	Assert.Equal (8, v.Bounds.Width);

	v.Width = 10;

	w.LayoutSubviews ();

	// Fails here 
	Assert.Equal (10, v.Bounds.Width);
}
```

**Expected behavior**
Calling `LayoutSubviews` should always update the `Bounds` to respect the `Width`/`Height`

**Comment by BDisp** [comment]
This isn't a real bug, but it's because @tig decided int the v2 the layout views on truly works after `BeginInit` and `EndInit` has executed. This unit test will not fail:

```cs
		[Fact, AutoInitShutdown]
		public void TestResize ()
		{
			var w = new Window ();
			var v = new View { Width = 8, Height = 8 };

			w.Add (v);

			Assert.False (w.IsInitialized);
			Assert.False (v.IsInitialized);
			Assert.Equal (0, w.Bounds.Width);
			Assert.Equal (0, v.Bounds.Width);

			w.BeginInit ();
			w.EndInit ();
			Assert.True (w.IsInitialized);
			Assert.True (v.IsInitialized);
			Assert.Equal (0, w.Bounds.Width);
			Assert.Equal (8, v.Bounds.Width);

			w.LayoutSubviews ();

			Assert.Equal (0, w.Bounds.Width);
			Assert.Equal (8, v.Bounds.Width);

			v.Width = 10;

			w.LayoutSubviews ();

			// Wont fail here
			Assert.Equal (0, w.Bounds.Width);
			Assert.Equal (10, v.Bounds.Width);
		}

```

**Comment by tig** [comment]
To be clear, i didn't decide anything. 

I just realized that previously any code that relied on Bounds being valid before IsInitialized was true was a bug and added code to make this more clear. 

Does this test emit the "WARNING: " debug statement?

**Comment by BDisp** [comment]
> To be clear, i didn't decide anything.
> 
@tig when I said you have decided, it's wasn't any censure. Sorry if you interpret that.

> I just realized that previously any code that relied on Bounds being valid before IsInitialized was true was a bug and added code to make this more clear.
> 
 In my opinion if a Pos/Dim are initialized with absolute values it may be considered before `IsInitialized`. With others types I agree forcing to be set after `IsInitialized` when the `SuperView` bounds are knowing.

> Does this test emit the "WARNING: " debug statement?

Yes, it's emitting all the time :-)

**Comment by tznind** [comment]
Thanks for digging into this.  I will look at adding `BeginInit`/`EndInit` into my test or into the resize operation in the designer.

**Comment by BDisp** [comment]
Here is the reason why `Frame` did change but not `Bounds`, `if (LayoutStyle == LayoutStyle.Computed && !IsInitialized)`:

```cs
		public virtual Rect Bounds {
			get {
#if DEBUG
				if (LayoutStyle == LayoutStyle.Computed && !IsInitialized) {
					Debug.WriteLine ($"WARNING: Bounds is being accessed before the View has been initialized. This is likely a bug. View: {this}");
				}
#endif // DEBUG
				var frameRelativeBounds = Padding?.Thickness.GetInside (Padding.Frame) ?? new Rect (default, Frame.Size);
				return new Rect (default, frameRelativeBounds.Size);
			}
			set {
				// BUGBUG: Margin etc.. can be null (if typeof(Frame))
				Frame = new Rect (Frame.Location,
					new Size (
						value.Size.Width + Margin.Thickness.Horizontal + Border.Thickness.Horizontal + Padding.Thickness.Horizontal,
						value.Size.Height + Margin.Thickness.Vertical + Border.Thickness.Vertical + Padding.Thickness.Vertical
						)
					);
			}
		}

```

So, if you need calculated `Bounds` you need to run `BeginInit/EndInit` on the `SuperView`.

**Comment by tig** [comment]
Addressed in 

- #2465
