### ISSUE TITLE
StatusItem Title property not rendered after version update.

### ISSUE THREAD

**Issue by chr1st0scli** [gui-cs/Terminal.Gui#2677]
**Describe the bug**
On version 1.9.0, when I change the `Title` property of a `StatusItem`, the change is immediately rendered and reflects the new value.
On version 1.12.1, this stopped working.

**To Reproduce**
1. Use a `StatusItem` to reflect the current position of the cursor in a `TextView`. Use the TextView's `UnwrappedCursorPosition` event to update the StatusItem's `Title` like so: `_cursorPosStatusItem.Title = string.Format(Resources.CURSOR_POS_FORMAT, point.Y + 1, point.X + 1);`
2. Use version 1.9.0 and notice that the cursor position is correctly reported every time the cursor is moved in the TextView.
3. Use version 1.12.1 and notice that it doesn't work any more.

**Expected behavior**
I suspect there shouldn't be a breaking change in a minor version update.

**Screenshots**
![LineDoesNotUpdate](https://github.com/gui-cs/Terminal.Gui/assets/5046010/7208c62e-2d09-4c6f-ad9d-1e3b8545587f)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by BDisp** [comment]
Please try doing `_cursorPosStatusItem.SetNeedsDisplay()`.

**Comment by chr1st0scli** [comment]
> Please try doing `_cursorPosStatusItem.SetNeedsDisplay()`.

`_statusBar.SetNeedsDisplay();`

Thank you. This works!

**Comment by BDisp** [comment]
> `_statusBar.SetNeedsDisplay();`
> 
> Thank you. This works!

Yes you are right, `_cursorPosStatusItem `is `StatusItem` and not a `View`, sorry for my mistake.
