### ISSUE TITLE
TextView stops being responsive after application is sent to the background

### ISSUE THREAD

**Issue by chr1st0scli** [gui-cs/Terminal.Gui#2678]
**Describe the bug**
When the application's window stops being active by sending it to the background using Alt + Tab (not with the mouse) and then it is brought to the foreground again, a `TextView` component stops being responsive to many keyboard inputs. Even though, you can type in new characters, you cannot move the cursor using the keyboard arrows or change a line with *enter* or delete characters with *backspace*.

**To Reproduce**
1. Use a multi-line `TextView` in an application, type in characters and move around the cursor freely using the keyboard arrow keys.
2. Change the active window by using Alt + Tab. This of course assumes having at least one other application open in your OS.
3. Re-activate the application's window by using Alt + Tab again.
4. Notice that you cannot move the cursor with the keyboard anymore. Pressing *enter* or *backspace* also has no effect, but you can type in new characters.

**Expected behavior**
The `TextView`'s functionality should not change when the application loses focus at some point in time.

**Screenshots**
![FocusChangeWithAltNTab](https://github.com/gui-cs/Terminal.Gui/assets/5046010/b68c597c-44c2-4d3d-8cb1-a3ef2d467cc9)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**
I noticed this behavior in older versions too, it's not new.

**Comment by BDisp** [comment]
Fixed with #2679.

**Comment by chr1st0scli** [comment]
Hi @tig and @BDisp 

I was anxiously waiting for the next release, i.e. 1.13.0 for this bug fix which is now closed. In my understanding, related changes were merged only in v2_develop. Isn't there going to be a v1 patch for this?

Thank you so much.

**Comment by tig** [comment]
If someone can do a PR for this into `develop` I'll grab it and release v1.13.2 asap!

**Comment by tig** [comment]
Cool. So just the other one wasn't fixed.
