### ISSUE TITLE
Hierarchical table view

### ISSUE THREAD

**Issue by LPeter1997** [gui-cs/Terminal.Gui#2683]
This is more of a suggestion request, as I don't think this control would be general enough that too many applications could benefit from it. Feel free to close it, if it's not something you want to deal with in this library directly, which is understandable.

My problem arose, when I wanted to visualize local values in our debugger. In something like VS, this is solved by a table view, where names are in the first column and values are in the second. If a value is compound (like an instance), the row becomes expandable, and subelements are shown as table rows indented. Example:
![image](https://github.com/gui-cs/Terminal.Gui/assets/7904867/d98ab561-96bc-4cf7-98c9-ae96caa611e1)

A table view is not enough here, as if I understood from #1285, I can't just embed a tree-view in the second column or something. A tree-view feels very noisy, and values are hard to align after the field names. It's also harder to read, because there's no visual hint about separating names and values anymore.

Could table view be extended somehow to support this? If so, what would it involve? I'd imagine it would have to be a pretty hefty change, considering it builds on `DataTable`.

**Comment by tznind** [comment]
> Could table view be extended somehow to support this? If so, what would it involve? I'd imagine it would have to be a pretty hefty change, considering it builds on DataTable.

In v2 the `DataTable` layer has [been abstracted away ](https://github.com/gui-cs/Terminal.Gui/pull/2576)and there is a new `ITableSource` which might be able to support this kind of thing.

I can have a think about it

**Comment by tznind** [comment]
Ok I think this approach might work.

https://github.com/gui-cs/Terminal.Gui/pull/2685

- We have one or more `TreeView` but we don't actually mount them to a view.
- We route events to the `TreeView` so it can expand / change selections
- We implement drawing using users func delegates

TODO:
Need to make the first  column use the `TreeView` actual draw so it gets branch lines etc

Its sort of working but would need a lot of polish 

![tableOfTrees](https://github.com/gui-cs/Terminal.Gui/assets/31306100/bb7c0c9c-c609-46e9-b579-56fd0c250423)
