### ISSUE TITLE
Border color doesn't change when changing color scheme

### ISSUE THREAD

**Issue by Binto86** [gui-cs/Terminal.Gui#2686]
**Describe the bug**
The border color of some Views (for example FrameView or Window) doesn't change when changing color scheme while the application is running.

**To Reproduce**
1. Create a new application using Terminal.Gui
2. Add a new Window and add a FrameView and a Button into the Window
3. Change the ColorScheme on the button click
4. Run the application and see, that when clicking the button, the color of everything except the border changes

**Expected behavior**
The border foreground and background changes according to the new ColorScheme

**Screenshots**
Before button click:
![image](https://github.com/gui-cs/Terminal.Gui/assets/76395771/466f1dd2-2c66-4bdb-bc85-d954403201f7)

After button click:
![image](https://github.com/gui-cs/Terminal.Gui/assets/76395771/b1b6912e-2272-42b5-9b80-c26979c9f4b5)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 1.12.1 of Terminal.Gui
 
**Aditional information**
The code I use to set up this example:
```cs
Application.Init();

var win = new Window("Test");
var frame = new FrameView()
{
    X = 5,
    Y = 10,
    Width = Dim.Fill() - 5,
    Height = Dim.Fill() - 10,
    Title = "Test Frame",
};
var button = new Button(50, 0, "Change theme");
button.Clicked += () => Clicked();

win.Add(button, frame);

Application.Top.Add(win);
Application.Run();
Application.Shutdown();

void Clicked()
{
    win.ColorScheme = new ColorScheme
    {
        Disabled = Attribute.Make(Color.White, Color.Black),
        Normal = Attribute.Make(Color.Cyan, Color.Black),
        HotNormal = Attribute.Make(Color.White, Color.Black),
        Focus = Attribute.Make(Color.White, Color.Black),
        HotFocus = Attribute.Make(Color.White, Color.Black),
    };
}
```

**Comment by tznind** [comment]
In this case the border is on the `Window` not the `TextView`... can you please provide your code for this example?

**Comment by Binto86** [comment]
Am sorry I totally screwed up setting up the example project, the problem is actually with `FrameView`, I will update the original post.
I am using version 1.12.1 of Terminal.Gui

**Comment by Binto86** [comment]
I also added the code i used for this example to the original post

**Comment by BDisp** [comment]
Here the workaround:

```cs
			void Clicked ()
			{
				win.ColorScheme = new ColorScheme {
					Disabled = Attribute.Make (Color.White, Color.Black),
					Normal = Attribute.Make (Color.Cyan, Color.Black),
					HotNormal = Attribute.Make (Color.White, Color.Black),
					Focus = Attribute.Make (Color.White, Color.Black),
					HotFocus = Attribute.Make (Color.White, Color.Black),
				};
				win.Border.Background = Color.Black;
				win.Border.BorderBrush = Color.White;
				frame.Border.Background = Color.Black;
				frame.Border.BorderBrush = Color.White;
			}

```

**Comment by Binto86** [comment]
@BDisp I know about this workaround, I just think that I shouldn't need to us it.

**Comment by tig** [comment]
> @BDisp I know about this workaround, I just think that I shouldn't need to us it.

This is fixed in v2; the entire way borders works is different in v2. So for now, please you use the workaround.

**Comment by Binto86** [comment]
@tig ok thanks for the info, I didn't know about that

**Comment by BDisp** [comment]
@tig  I've the fix for this and I'll submit a PR soon. So, I reopen this. Thanks.

**Comment by BDisp** [comment]
Here is the output:

![border color-fix](https://github.com/gui-cs/Terminal.Gui/assets/13117724/149f4dd3-4bf7-499a-a749-aad4c62f4d40)

**Comment by Binto86** [comment]
Nice this is the correct behaviour

**Comment by Binto86** [comment]
I will quickly clone the repo and test this locally

**Comment by BDisp** [comment]
Try with this code:

```cs
			void Clicked ()
			{
				win.ColorScheme = new ColorScheme {
					Disabled = Attribute.Make (Color.White, Color.Black),
					Normal = Attribute.Make (Color.White, Color.Black),
					HotNormal = Attribute.Make (Color.Cyan, Color.Black),
					Focus = Attribute.Make (Color.White, Color.Black),
					HotFocus = Attribute.Make (Color.Cyan, Color.Black)
				};
			}

```

**Comment by BDisp** [comment]
I think you want this:

![border color-fix](https://github.com/gui-cs/Terminal.Gui/assets/13117724/93bff640-26b1-48e9-bb5f-dcdca32b8c58)

**Comment by BDisp** [comment]
For clarification, the attribute `HotNormal` is used to draw the title that has the focus, in this case the `Window`. The `HotFoxus` is used to draw the hot-key that has the focus, in this case the `Button`.

**Comment by Binto86** [comment]
okok, i don't need it, it was just thing I noticed and wasn't sure if its correct, otherwise, the fix is good imo

**Comment by BDisp** [comment]
Try this new code and you will understand that is very important how to set correctly the `ColorScheme`. Note that `Window` always have the focus because is the super-view.

```cs
			Application.Init ();

			var win = new Window ("Test");
			var frame = new FrameView () {
				X = 5,
				Y = 10,
				Width = Dim.Fill () - 5,
				Height = Dim.Fill () - 10,
				Title = "Test Frame",
			};
			ColorScheme originalScheme = null;

			var buttonFrame = new Button ("Restore theme") { X = Pos.Center () };
			buttonFrame.Clicked += () => RestoreTheme ();
			frame.Add (buttonFrame);

			var buttonWindow = new Button ("Change theme") { X = Pos.Center () };
			buttonWindow.Clicked += () => ChangeTheme ();

			win.Add (buttonWindow, frame);

			Application.Top.Add (win);
			Application.Run ();
			Application.Shutdown ();

			void ChangeTheme ()
			{
				originalScheme = win.ColorScheme;
				win.ColorScheme = new ColorScheme {
					Disabled = Attribute.Make (Color.White, Color.Black),
					Normal = Attribute.Make (Color.White, Color.Black),
					HotNormal = Attribute.Make (Color.Cyan, Color.Black),
					Focus = Attribute.Make (Color.Black, Color.White),
					HotFocus = Attribute.Make (Color.Cyan, Color.White)
				};
			}

			void RestoreTheme ()
			{
				win.ColorScheme = originalScheme;
			}

```

![border color-fix](https://github.com/gui-cs/Terminal.Gui/assets/13117724/05cc1610-0d41-49e2-9cdb-8a03c388fe5e)
