### ISSUE TITLE
ReadOnly TextView's broken scrolling after version update

### ISSUE THREAD

**Issue by chr1st0scli** [gui-cs/Terminal.Gui#2688]
**Describe the bug**
Another breaking change I came across when upgrading from v1.9.0 to 1.12.1, is that I cannot scroll my read-only `TextView` correctly any more.

**To Reproduce**
1. Add a quite short `TextView`, so that you don't have to insert a lot of text to reproduce the error.
2. Set it's `ReadOnly` property to `true` and its `Text` property to several lines, such that they exceed its height.
3. Scroll down to the end and then try to scroll up again, using the keyboard's up and down arrows.
4. Notice that you cannot scroll back to the top. If you type a character or use the mouse wheel, it's as if it gets unstuck for a while and then you might be able to scroll to the top.
5. Also, notice that it's sluggish, the cursor might move a little right or left when changing lines and get stuck "randomly". 

**Expected behavior**
To scroll seamlessly, like I used to.

**Screenshots**
Here, I demonstrate the different behavior between the two versions. The read-only is the bottom one, in the "output" frame.

![ReadOnlyTextViewScrollingProblem](https://github.com/gui-cs/Terminal.Gui/assets/5046010/6b6191bb-964f-4652-a865-ec6fa15a9f79)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by tig** [comment]
Thank you for reporting this. Really appreciate you providing repro instructions.

**Comment by BDisp** [comment]
This is also happening in the v2.

**Comment by BDisp** [comment]
Only to clarify that this bug is also happen if `ReadOnly` is false.

**Comment by chr1st0scli** [comment]
Hi @tig and @BDisp 

I was anxiously waiting for the next release, i.e. 1.13.0 for this bug fix which is now closed. In my understanding, related changes were merged only in v2_develop. Isn't there going to be a v1 patch for this?

Especially if you consider that there was a v1 version that did not have this problem, which was introduced by a later v1 version.

Thank you so much.

**Comment by tig** [comment]
If someone can do a PR for this into `develop` I'll grab it and release v1.13.2 asap!
