### ISSUE TITLE
Autocomplete doesn't popup after typing the first character.

### ISSUE THREAD

**Issue by BDisp** [gui-cs/Terminal.Gui#2689]
![autocomplete-issue](https://github.com/gui-cs/Terminal.Gui/assets/13117724/020714e8-819c-4a14-a1f9-7f1e5f9e0df1)

**Comment by tig** [comment]
@BDisp did you fix this in

- #2680 

If so, please close.

**Comment by BDisp** [comment]
> @BDisp did you fix this in
> 
> * [Make the TextView API more extensible #2680](https://github.com/gui-cs/Terminal.Gui/issues/2680)
> 
> If so, please close.

Yes it's fixed. I will be more attentive to closing issues that have already been fixed by me and merged into v2. Thanks.

**Comment by tig** [comment]
> Yes it's fixed. I will be more attentive to closing issues that have already been fixed by me and merged into v2. Thanks.

Soon, we should make `v2_develop` the default branch so it happens automatically. ;-)
