### ISSUE TITLE
Support for TELNET connection or changing Console I/O

### ISSUE THREAD

**Issue by wzuqui** [gui-cs/Terminal.Gui#2723]
First of all, congratulations on the quality of the toolkit.

Second, is there any way to connect the console inputs/outputs and expose in a TELNET Soket?

Today I can already do this with another Specter.Console toolkit.

Grateful

[![](https://raw.githubusercontent.com/wzuqui/wzuqui/main/telnetserver.png)]

**Comment by tznind** [comment]
Are you able to show or link the code you have written / used to get this to work with spectre console?

**Comment by wzuqui** [comment]
First I create a TELNET server and expose the TCP port.
Then I connect to the port using Windows TELNET or Putty.
When connected, I perform a rather complex handshake, in which the server requests resources from the client.
With that I have the resolution of the client's screen. Things like IAC WILL ECHO, IAC WILL SUPPRESS_GA, IAC DO SB NASW as specified in https://www.rfc-editor.org/rfc/rfc1073.

So after the handshake I create a scope and link an implementation of Spectre.Console.IAnsiConsole.

All input/output are intercepted by IAnsiConsole.

This weekend I'm going to create a repository on public github and give you the link.

```csharp
public TelnetSession(Socket clientSocket, Server server)
    {
        _logger = LogManager.GetCurrentClassLogger();
        TimeConnected = DateTime.UtcNow;
        TimeRxData = DateTime.UtcNow;
        ClientSocket = clientSocket;
        Server = server;

        _ipEndPoint = (IPEndPoint)ClientSocket.RemoteEndPoint!;

        _networkStream = Environment.NewLine.Length == 1
            ? new NetworkStreamCrlf(ClientSocket)
            : new NetworkStream(ClientSocket);
        _streamReader = new StreamWriter(_networkStream);
        var consoleOutput = new AnsiConsoleOutput(_streamReader);

        AnsiConsole = new AnsiTelnetConsole(Spectre.Console.AnsiConsole.Create(new AnsiConsoleSettings
        {
            Ansi = AnsiSupport.Yes
            , ColorSystem = ColorSystemSupport.Detect
            , Out = consoleOutput
            , Interactive = InteractionSupport.Yes
            , ExclusivityMode = null
            , Enrichment = null!
            , EnvironmentVariables = null
        })) { TelnetSession = this };
    }
```

**Comment by tznind** [comment]
Hmn I think something could be possible.  There is work ongoing to restructure and simplify the driver base #2612 which might be then adaptable to this scenario.  But there isn't a current way that I know of to do what you are describing above.

**Comment by wzuqui** [comment]
Thanks for your help, I noticed that you are developing a v2.

When that happens I will try to implement Terminal.Gui in TELNET and if I succeed I will be happy to notify you.

I await news, meanwhile you can close this issue.
