### ISSUE TITLE
Override ProcessKey in AutoComplete

### ISSUE THREAD

**Issue by qzhan15** [gui-cs/Terminal.Gui#2724]
I am currently working on an editor that supports autocompletion for keywords starting with "@" symbol. However, the default editor uses the IsWordChar function to skip all special characters. To address this, my solution is to override the IdxToWord and ProcessKey functions in my class that inherits AutoComplete.

However, I encountered a challenge when I noticed that the default ProcessKey function accesses a private field called "closed." This has left me confused about how to implement my own ProcessKey function. Should it be changed to a "protected" field? I would appreciate any suggestions on how to support the required feature in this scenario

**Comment by tznind** [comment]
Hi thanks for getting in touch and providing such a comprehensive description of your issue.

The easiest way to treat `@` as a word character is to override the `IsWordChar` method by subclassing `TextViewAutocomplete`.  


```csharp
class MyCustomAutoComplete : TextViewAutocomplete
{
	public override bool IsWordChar (Rune rune)
	{
		return rune == '@' || base.IsWordChar (rune);
	}
}
```

You can then assign this to your `TextView` by using the Autocomplete setter.  The setter is `protected` but presumably you are already subclassing `TextView`? If not then you should be able to just use set it with reflection.

```csharp
class SqlTextView : TextView {
  public void Init ()
  {
	  Autocomplete = new MyCustomAutoComplete ();
	  Autocomplete.AllSuggestions = new List<string> { "@blah" };
  }
}
```

![image](https://github.com/gui-cs/Terminal.Gui/assets/31306100/ccfcb694-697a-4ba1-9d49-0e0611d3706e)

**Comment by qzhan15** [comment]
Thank you for the quick response!  Yes, I have also realized that IsWordChar is a virtual function and I have tried it out. I was just in the process of composing a reply to mention this. :)
