### ISSUE TITLE
Small TextView is broken scrolling using scrollbar

### ISSUE THREAD

**Issue by chr1st0scli** [gui-cs/Terminal.Gui#2761]
**Describe the bug**
A notably small `TextView` cannot be scrolled correctly using a scrollbar.

This bug relates to #2688 which is corrected. I am mentioning it here because it might need a regression test after this one is corrected. 

**To Reproduce**
1. Add a quite short `TextView`, so that you don't have to insert a lot of text to reproduce the error.
2. Set it's `ReadOnly` property to true and its `Text` property to several lines, such that they exceed its height. Note that @BDisp had noted that the text view being a read only has nothing to do with the problem.
3. Attach a vertical scrollbar to it as demonstrated in the UI catalog.
4. Scroll down to the end using the keyboard arrow keys (I do it programmatically in the screenshot) and then try to scroll up again, by clicking on the scrollbar's arrows or using the mouse's middle button.
5. Notice that you cannot scroll back to the top.

**Expected behavior**
To scroll correctly.

**Screenshots**
Below I am demonstrating the inability to scroll using the scrollbar and the ability to scroll using the keyboard arrow keys with no problem. The bigger `TextView` above does not suffer from the same problem.

![ScrollbarProblem](https://github.com/gui-cs/Terminal.Gui/assets/5046010/8971044c-2cd9-4594-adbe-c1000fe2bdfa)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by BDisp** [comment]
@chr1st0scli can you test the fix in the #2770, please? Thanks.

**Comment by chr1st0scli** [comment]
@BDisp yes, sure. 

I see that we didn't make it for 1.13.5, yes?

**Comment by chr1st0scli** [comment]
@BDisp everything works on this PR!

**Comment by BDisp** [comment]
> I see that we didn't make it for 1.13.5, yes?

Yes, but I'm sure that @tig will publish after this is merged. But I want to do some more unit tests to prevents this doesn't break in future.
