### ISSUE TITLE
ReSharper: The same file is listed in UnitTests.csproj multiple times with the same 'Compile' build action:

### ISSUE THREAD

**Issue by BDisp** [gui-cs/Terminal.Gui#2762]
![imagem](https://github.com/gui-cs/Terminal.Gui/assets/13117724/a83e0677-62a8-4773-95af-2a1ea99cbb78)

**Comment by RevitArkitek** [comment]
I'm having a similar looking issue but the subtext reads 'The same files is listed in MyProject.csproj multiple times with the same 'Page' build action: 'path to .xaml'  None of these xaml files appear in the .csproj file.  Using TargetFramework = net6.0-windows, VS version = 17.7.5, ReSharper 2023.2.3 Build 232.0.20231101.132807.  It appears that this newer type of project doesn't list all files in the .csproj as it had done previously using 4.8.

**Comment by BDisp** [comment]
I had to to a git move force to rename, see https://stackoverflow.com/a/1793757/4872289.

`git mv -f CheckboxTests.cs CheckBoxTests.cs `
