### ISSUE TITLE
The developer branch is broken due the  f0d3f66 commit

### ISSUE THREAD

**Issue by BDisp** [gui-cs/Terminal.Gui#2785]
This https://github.com/gui-cs/Terminal.Gui/commit/f0d3f664fb6beeb7dc221beae9608f3d4c2e98b5 commit broken it.

**Comment by BDisp** [comment]
@tig did you really want to do this for `UnitTests` or for the` Terminal.Gui` API?

**Comment by BDisp** [comment]
Doing the changes on the `csproj` works well, but I doubt you want to do that to UnitTests

```xml
    <AssemblyVersion>1.13.6.0</AssemblyVersion>
    <FileVersion>1.13.6.0</FileVersion>
    <Version>1.13.6.0</Version>
    <InformationalVersion>1.13.6-alpha+Branch.develop.Sha.993e484cf98da0969a173b26cbbe3da03cfc518f</InformationalVersion>

```

**Comment by tig** [comment]
I'll fix this asap. I didn't mean to push directly.

**Comment by tig** [comment]
Fixed.
