### ISSUE TITLE
Windows Terminal still show vertical scroll bar using WindowsDriver.

### ISSUE THREAD

**Issue by BDisp** [gui-cs/Terminal.Gui#2793]
This is very annoying even after the `EnableConsoleScrolling` was disabled as deprecated.

https://github.com/gui-cs/Terminal.Gui/assets/13117724/bb9a2143-fbc6-46e1-a6dd-44012c69ee93

**Comment by tig** [comment]
Did you know you can turn off the WT vertical scroll bar in settings?

<img width="767" alt="image" src="https://github.com/gui-cs/Terminal.Gui/assets/585482/3210aad4-5b7c-40d5-bd03-056f33e596e0">

Emitting `[3J` deletes all data in the back scroll buffer. Other console apps do not do this. Eg. vim, emacs, midnight commander, etc... 

Even with your fix, the scrollbar still re-appears when you resize the terminal:

![k2lYdvK 1](https://github.com/gui-cs/Terminal.Gui/assets/585482/ef7f6732-7300-4417-a971-7cdde4b13314)

If you really want to have the back buffer cleared we can add this as a configurable option. In v2 it will be easy to add such an option via configurationmanager. 

```json
"WindowsDriver.ClearBackBufferOnResize": true,
```

**Comment by BDisp** [comment]
> Did you know you can turn off the WT vertical scroll bar in settings?

Yes I did, but I don't want change it only to run Terminal.Gui. `Windows Terminal` must respect the app properties. But there is a misleading about 1047 and 1049 escape sequences. Is the 1049 that handles the alternate buffer and not the 1047.
See here the correct https://learn.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences#alternate-screen-buffer, but https://invisible-island.net/xterm/ctlseqs/ctlseqs.html say that is the 1047. I think that has to do with emulator type, don't know. But 1049 does what I need and the `Console.Out.Write ("\x1b[3J")` isn't needed.

> If you really want to have the back buffer cleared we can add this as a configurable option. In v2 it will be easy to add such an option via configurationmanager.

I only want to clear when we start the `Terminal.Gui` app but after using the `Alternate Screen Buffer` to save and restore.

I'll try to find a way to these `Alternate Screen Buffer` is only used on `Windows` and only used on `Windows Terminal`.

**Comment by BDisp** [comment]
But [here](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-The-Alternate-Screen-Buffer) they refer that's the `1049` code. Since `WindowsDriver` can only executes escape sequences on `Windows Terminal` I've ensured with this [fix](https://github.com/gui-cs/Terminal.Gui/pull/2794/files#diff-edbbd230687bc3b288e4e5af89ff6d2d789a618f0e757fd084c2490a2150a858), that they are only executed on WT because on others terminals they are only echoed to the terminal which are visible after exit the app.
