### ISSUE TITLE
Hot-Reload support

### ISSUE THREAD

**Issue by ThaDaVos** [gui-cs/Terminal.Gui#2804]
**Is your feature request related to a problem? Please describe.**

It seems it's partially supported but also breaks, as after each edit the GUI seems to get layered on top of each other

**Describe the solution you'd like**

Full support for Hot-Reload - or at least that it works

**Describe alternatives you've considered**

What currently works is closing the Terminal.GUI by pressing CTRL+Q before making changes as it will get restarted after that

**Additional context**

**Comment by tig** [comment]
Can you please elaborate. 

Do you mean Hot-Reload in a debug session in VS2022?

**Comment by tig** [comment]
Closing due to lack of response by @ThaDaVos. Re-open if it's still an issue.
