### ISSUE TITLE
Hosted ScrollBarView is damaged on the scenario Editor and others in v2.

### ISSUE THREAD

**Issue by BDisp** [gui-cs/Terminal.Gui#2813]
@tig do you remember why this is happening?

`Edit:`
The issue started after the commit 0df485a8904b0856f7e5865ef095008ea88f9474.

**Comment by tig** [comment]
Not sure. I focused on CharMap and didn't notice Editor's scroll bars went missing.

**Comment by BDisp** [comment]
> FWIW, I still think we should build optional scrollbars into `View` and deprectate `ScrollBarView` in v2.
> 
> See
> 
> #2489

I agree, but I need to understand what causing this because neither `ScrollBarView` and `Editor` were changed in that commit. So, I suspect that was something with drawing or driver refresh.

**Comment by tig** [comment]
@BDisp can you update this? Is this still an issue?

**Comment by BDisp** [comment]
> @BDisp can you update this? Is this still an issue?

Yes, if you open the Editor and others scenarios where the `ScrollBarView` were hosted doesn't work. But if this is related to another already opened issue, you can close this one.
