### ISSUE TITLE
v2 View drawing is forcing to always calling only the GetNormalColor ()

### ISSUE THREAD

**Issue by BDisp** [gui-cs/Terminal.Gui#2816]
I think this limiting the views that want to call the GetFocusColor () when they are focused. Also the `Clear` is always forcing to call the GetNormalColor () even if a view set another attribute before clearing.

@tig thoughts.

**Comment by tig** [comment]
We should address this in https://github.com/gui-cs/Terminal.Gui/issues/2381.

Adding it as a requirement and closing this issue.
