### ISSUE TITLE
Cannot run tests on `develop` 

### ISSUE THREAD

**Issue by tznind** [gui-cs/Terminal.Gui#2832]
**Describe the bug**
When I do `dotnet test` in `develop` branch I get an error about runsettings.

Seems there is a line in `gui.cs\UnitTests\UnitTests.csproj` that is causing this.  Removing it fixes the problem:

```diff
- <RunSettingsFilePath>C:\Users\charlie\s\gui-cs\Terminal.Gui\UnitTests\bin\Debug\net7.0\fine-code-coverage\coverage-tool-output\UnitTests-fcc-mscodecoverage-generated.runsettings</RunSettingsFilePath>
```

```
Test run for D:\Repos\gui.cs\UnitTests\bin\Debug\net7.0\UnitTests.dll (.NETCoreApp,Version=v7.0)
Microsoft (R) Test Execution Command Line Tool Version 17.4.0 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

The Settings file 'C:\Users\charlie\s\gui-cs\Terminal.Gui\UnitTests\bin\Debug\net7.0\fine-code-coverage\coverage-tool-output\UnitTests-fcc-mscodecoverage-generated.runsettings' could not be found.
```

**Comment by BDisp** [comment]
@tznind I think you are running a older branch because now the `develop` is `v1_develop` branch.

**Comment by tznind** [comment]
Ok, got it.  Maybe we should delete `develop` branch then if we are no longer using it? Most programmers will assume `main`/`develop` is the split if that branch exists?

**Comment by BDisp** [comment]
> Ok, got it. Maybe we should delete `develop` branch then if we are no longer using it? Most programmers will assume `main`/`develop` is the split if that branch exists?

The `develop` branch doesn't exist anymore. It was set HEAD to the `v1_develop`. See #2815. You have to change set HEAD to the `v1_develop`. Unfortunately the `v1_develop` branch isn't executing the CI check. Maybe you can help on that, please. The `main` branch is now `v1` and the `v2` is the release for the `v2_develop` branch.

**Comment by tig** [comment]
And I'm going to change `v1` back to `main` and `v1_develop` back to `develop` because what I was trying won't work.

I'm going to try to do this this morning.
