### ISSUE TITLE
DateField: Allow Formatting

### ISSUE THREAD

**Issue by draptik** [gui-cs/Terminal.Gui#2851]
**Is your feature request related to a problem? Please describe.**
The current DateTime Format is hardcoded.

**Describe the solution you'd like**
The DateTime format should be configurable.

```
2023-08-30  # "iso"
08/30/23    # "us"
30.08.2023  # "europian"
```

The above are equivalent.

Currently, only the american display format ("us") seems to be available when using DateField.

Request:

Having a default dotnet parameter available for config would be nice.

**Comment by tig** [comment]
@BDisp and/or @MaciekWin3: is this Issue addressed by 

- #3188 ?
