### ISSUE TITLE
v2 pre-release nuget package

### ISSUE THREAD

**Issue by tznind** [gui-cs/Terminal.Gui#2852]
@tig is it please possible to do another v2 pre-release package? I would like to keep TerminalGuiDesigner up to date with driver developments etc

I understand you are doing some awesome work to automate this but if that is a ways off could you do a one off release of v2_develop?

**Comment by tig** [comment]
Done! 

Still not convinced I'm doing this right.

But for now...

https://www.nuget.org/packages/Terminal.Gui/2.0.0-pre.71

Any push to `v2_develop` will result in a new `v2.0.0-pre.xxx` package publish.
