### ISSUE TITLE
Make FileDialog (v2) more customizible for buttons

### ISSUE THREAD

**Issue by tznind** [gui-cs/Terminal.Gui#2859]
> Lets's make FileDialog more customizible for buttons. I suggest adding to the constructor the label for Cancel button and the ability to change the order of the buttons ([ Cancel ][ Open ] -> [ Open ][ Cancel ] -> [ Open ][ Done ]):
`..., ustring prompt, ustring cancel, bool buttonsReverseOrder,...'
> [...]
> And the ability to change the order of the buttons ([ Wait no! ][ Lets go! ] -> [ Lets go! ][ Wait no! ])
> // does not exist
> // fd.Style.ButtonsReverseOrder = true;

@Likarion 

>I'm a fan of making it more customizable but not via a constructor. Constructors should be parameter-less.
@tig 

Most of what you describe can be accomplished with the Style class.  But there are improvements that could be made.  I've put what works at the top of this code sample and what we could enable in the bottom (in comments).

```csharp
fd.Style.OkButtonText = "Lets go!";
fd.Style.ModifiedColumnName = "Date";
fd.Title = "Blerg";

// does not exist
// fd.Style.OkCancelText = "Wait no!";

// currently has internal setters (so you cannot do this).  Also needs slight adjustment
// in order of initialization so user changes would take effect
//fd.Style.PathCaption = "Pick a file";
//fd.Style.SearchCaption = "Find yer stuff";
```
![image](https://github.com/gui-cs/Terminal.Gui/assets/31306100/ba7bf0c9-dc3c-43da-b947-ee34d933109b)
_FileDialog with custom title, ok message and table column name_

_Originally posted by @tznind in https://github.com/gui-cs/Terminal.Gui/issues/2259#issuecomment-1720851070_

**Comment by tznind** [comment]
@Likarion please can you confirm that the linked PR exposes all the settings you are wanting.

Also it is worth noting that the Path and Search strings are setup for localization (default values are in strings.resx) so those can also be changed there if it is a language thing (i.e. by creating a localized language resx file).

**Comment by Likarion** [comment]
Everything's good! Thanks!
