### ISSUE TITLE
Application views do not refresh when the cursor is moved.

### ISSUE THREAD

**Issue by kacperpikacz** [gui-cs/Terminal.Gui#2860]
**Describe the bug**
Application views do not refresh when the cursor is moved. Affected versions are all above 1.9.0

**Screenshots**
![bug](https://github.com/gui-cs/Terminal.Gui/assets/76921244/594d45b4-3adf-4fbb-8c63-9b54835b4777)

**To Reproduce**
```
using Terminal.Gui;

namespace Test
{
    public class Program
    {
        static readonly List<string> GlobalList = new() { "1" };
        static readonly ListView GlobalListView = new() { Width = Dim.Fill(), Height = Dim.Fill() };
        static object? _token = null;

        static void Main()
        {

            Application.Init();

            var startButton = new Button("Start");
            var stopButton = new Button("Stop") { Y = 1 };
            var container = new View() { X = Pos.Center(), Y = Pos.Center(), Width = 8, Height = 8, ColorScheme = Colors.Error };
            
            startButton.Clicked += Start;
            stopButton.Clicked += Stop;

            GlobalListView.SetSource(GlobalList);
            container.Add(GlobalListView);

            Application.Top.Add(container);
            Application.Top.Add(startButton, stopButton);
            Application.Run();

            return;
        }

        private static void Start()
        {
            _token = Application.MainLoop.AddTimeout(TimeSpan.FromMilliseconds(100), Add);
        }

        private static void Stop()
        {
            Application.MainLoop.RemoveTimeout(_token);
        }

        private static bool Add(MainLoop mainLoop)
        {
            GlobalList.Add(new Random().Next(100).ToString());
            GlobalListView.MoveDown();
            
            return true;
        }
    }
}


```

**Expected behavior**
Application views should refresh

**Desktop**
MacOS Ventura

**Comment by BDisp** [comment]
I tested it on macOS Big Sur hosted on Windows 11 with VirtualBox and it's working well. Unfortunately it isn't possible install macOS Ventura on a Windows 11 with VirtualBox and so I can't test it.

**Comment by kacperpikacz** [comment]
Anyone else with Mac?

**Comment by BDisp** [comment]
@kacperpikacz can you run your code with the PR #2848, please. I think it is unrelated because is an issue that affect the `SynchronizationContext` but worth to try.

**Comment by kacperpikacz** [comment]
@BDisp nothing changed after running code with #2848

**Comment by BDisp** [comment]
I already suspect that. The fix was for threading issue. I hope someone else with macOS Ventura can confirm that, because with Big Sur the timer is always refreshing the screen.

**Comment by TylerReid** [comment]
@BDisp I am on Ventura, and after applying your changes the UICatalog threading example works now. Before I had to move my mouse or do other inputs in order to get the async tasks to start, but now it works as expected.

**Comment by BDisp** [comment]
> @BDisp I am on Ventura, and after applying your changes the UICatalog threading example works now. Before I had to move my mouse or do other inputs in order to get the async tasks to start, but now it works as expected.

Thanks for your answer, although this should be witted on the #306.
In this issue I ask, as you are on Ventura, if you can run the example code above and confirm if you have the same behavior as @kacperpikacz meant on this issue, please.

**Comment by TylerReid** [comment]
@BDisp Ah, I misunderstood. Your change did not fix this issue: 

https://github.com/gui-cs/Terminal.Gui/assets/2939992/dbd3bfd1-9227-4bbc-9e88-6145b0fcaa6a

**Comment by BDisp** [comment]
@TylerReid thanks very much. My fix was only for the threading issue and this one is different. It doesn't use no thread at all and if we continuously move the mouse, the console isn't refreshed. I don't have a mac, but only Big Sur installed on `Oracle VM VirtualBox` and this behavior doesn't happens. Due this limitation I can't find what is causing this behavior on Ventura. I already tried to install it on VirtualBox without success. It seems that now isn't possible to install it on a non-mac machine.

**Comment by BDisp** [comment]
@kacperpikacz and @TylerReid please run the `Mouse` scenario of the `UICatalog` and see the output for the mouse move event. Perhaps it's returning some other event. Thanks.

**Comment by TylerReid** [comment]
@BDisp I see a steady stream of ReportMousePosition events getting reported when I move in the same way.

**Comment by BDisp** [comment]
> @BDisp I see a steady stream of ReportMousePosition events getting reported when I move in the same way.

And when the mouse is continuously moved do the report still refreshing or not?

**Comment by TylerReid** [comment]
Yes, the report list refreshes with no pauses

**Comment by kacperpikacz** [comment]
The problem is laying somewhere inside `ProcessInput` method from `CursesDriver`. In 1.9 there was no `GetEscSeq` method.

Commenting `Curses.timeout (10) in ProcessInput` will help but will not solve the problem completely.

Maybe #2375

`v1.14`

https://github.com/gui-cs/Terminal.Gui/assets/76921244/00ab7633-466e-403e-be64-2455631b28c6



`v1.9`

https://github.com/gui-cs/Terminal.Gui/assets/76921244/1d73ff4d-13c9-4677-98ea-daaf3203792f



```
using Terminal.Gui;

namespace Test
{
    public class Program
    {
        static readonly List<string> GlobalList = new() { "1" };
        static readonly ListView GlobalListView = new() { Width = Dim.Fill(), Height = Dim.Fill() };

        static Label CounterLabel = new();
        static Label BlinkingLabel = new();

        static int Counter = 0;

        static object? _listToken = null;
        static object? _blinkToken = null;
        static object? _countToken = null;

        static void Main()
        {
            Application.Init();

            var startButton = new Button("Start");
            var stopButton = new Button("Stop") { Y = 1 };
            var container = new View() { X = Pos.Center(), Y = Pos.Center(), Width = 8, Height = 8, ColorScheme = Colors.Error };

            CounterLabel = new Label("0") { X = container.X - 4, Y = container.Y - 6};
            BlinkingLabel = new Label("Blink") { X = CounterLabel.X, Y = CounterLabel.Y + 11 };

            startButton.Clicked += Start;
            stopButton.Clicked += Stop;

            GlobalListView.SetSource(GlobalList);
            container.Add(GlobalListView);

            Application.Top.Add(container, CounterLabel, BlinkingLabel);
            Application.Top.Add(startButton, stopButton);
            Application.Run();

            return;
        }

        private static void Start()
        {
            _listToken = Application.MainLoop.AddTimeout(TimeSpan.FromMilliseconds(100), Add);
            _blinkToken = Application.MainLoop.AddTimeout(TimeSpan.FromMilliseconds(1000), Blink);
            _countToken = Application.MainLoop.AddTimeout(TimeSpan.FromMilliseconds(1000), Count);
        }

        private static void Stop()
        {
            Application.MainLoop.RemoveTimeout(_listToken);
            Application.MainLoop.RemoveTimeout(_blinkToken);
            Application.MainLoop.RemoveTimeout(_countToken);
        }

        private static bool Add(MainLoop mainLoop)
        {
            GlobalList.Add(new Random().Next(100).ToString());
            GlobalListView.MoveDown();
            
            return true;
        }

        private static bool Blink(MainLoop mainLoop)
        {
            Application.MainLoop.Invoke(() =>
            {
                if (BlinkingLabel.Visible)
                {
                    BlinkingLabel.Visible = false;
                    System.Diagnostics.Debug.WriteLine(BlinkingLabel.Visible);
                }
                else
                {
                    BlinkingLabel.Visible = true;
                    System.Diagnostics.Debug.WriteLine(BlinkingLabel.Visible);
                }
                
            });

            return true;
        }

        private static bool Count(MainLoop mainLoop)
        {
            Application.MainLoop.Invoke(() =>
            {
                Counter++;
                CounterLabel.Text = Counter.ToString();
            });
            
            return true;
        }
    }
}
```

**Comment by BDisp** [comment]
> Commenting `Curses.timeout (10) in ProcessInput` will help but will not solve the problem completely.
>
This is necessary for waiting a while after a `Esc` key is detected to check if it was pressed alone or if it's part of a escape sequence, like `Key.Home` or mouse event, etc.

Well, I think the culprit is the `poll` method waiting infinitely if `pollTimeout=-1` until some action is detected. I did the fix in the #2848.
I also did some change to your code:
Avoid initialize a view twice because if you use `Debug.Assert` with `Responder.Instances` to validate all instances it will fail. So, only declare the fields or initialize with all properties or initialize only with `new();` and setting the properties in the `Main()`.
```cs
        static Label CounterLabel;
        static Label BlinkingLabel; 
```
You don't need to use the `return;` in a `void Main`. Instead replace it with `Application.Shutdown();`

Also for accurating that the timeout action is running on the UI thread, change the `Add` method to call the `Application.MainLoop.Invoke`:
```cs
	private static bool Add(MainLoop mainLoop)
	{
		Application.MainLoop.Invoke(() => {
			GlobalList.Add(new Random().Next(100).ToString());
			GlobalListView.MoveDown();
		});

		return true;
	}
```
I appreciate you can run to check if the issue still persist or not. If it's fix I'll also do a commit to the `v2` as well. Thanks.

**Comment by BDisp** [comment]
You also should avoid setting the view position by using the view.X or view.Y because they will only have the correct value after running and you are only playing with fixed values until achieve the correct values. The correct way to position them is using the `Pos.X(View)` and `Pos.Y(View)` which the are dynamically calculate on the `LayoutViews`:
```cs
CounterLabel = new Label ("0") { X = Pos.X (container), Y = Pos.Y (container) - 2 };
BlinkingLabel = new Label ("Blink") { X = Pos.X (container), Y = Pos.Bottom (container) + 1 };
```

**Comment by kacperpikacz** [comment]
After running with #2848, I see no more problem present. Good job @BDisp

**Comment by kacperpikacz** [comment]
Sorry, I've used wrong source. The problem is still present.

**Comment by BDisp** [comment]
But are you sure you are running with the #2848? You'll have to debug that and try to find the cause because I can't. Loo at the `IMainLoopDriver.EventsPending` of the `UnixMainLoop.cs`. The fixes I did was for `CursesDriver` which freeze on the `var n = poll (pollmap, (uint)pollmap.Length, pollTimeout);`.

**Comment by kacperpikacz** [comment]
Yes, i can confirm that after running on #2848 the problem is still present + resizing terminal will cause complete freeze of the app.

**Comment by BDisp** [comment]
Yes it's reproducing in `macOS Monterey`. The resizing terminal issue didn't happens before I had commit the latest changes?

**Comment by kacperpikacz** [comment]
No issue with resizing before.

**Comment by BDisp** [comment]
Thanks, can you test the threading scenario, please?

**Comment by BDisp** [comment]
On resizing in the `CursesDriver.cs` on the `ProcessInput` method this `var code = Curses.get_wch (out wch);` is returning `code = -1` which is equal to `Curses.ERR` and `wch = 0`. That why the `ProcessWinChange` method doesn't run. On `Linux` this doesn't happens at all. I have to do some workaround on this.

**Comment by kacperpikacz** [comment]
Threading scenario, when I don't move cursor the return will never happen. Tested on `develop` and #2848.

https://github.com/gui-cs/Terminal.Gui/assets/76921244/f260058e-bd4c-4e39-9a73-62916ea761c1

**Comment by kacperpikacz** [comment]
Latest commit, fixes issue with resizing. But still the views will not refresh when moving cursor fast.

```
public override void Refresh ()
{
	Curses.raw ();
	Curses.noecho ();
	Curses.refresh ();
+	ProcessWinChange ();
}
```

**Comment by kacperpikacz** [comment]
Running on #2848. Inside `GetEscSeq()`method there is `code = Curses.get_wch(out wch2)` which returns -1.

https://github.com/gui-cs/Terminal.Gui/assets/76921244/79119194-b019-4403-99e7-50c7644c6581

**Comment by Likarion** [comment]
Under SSH, the terminal mouse drop into the "SELECT " state and mouse click don't working. When install 1.9.0 all works ok.

**Comment by kacperpikacz** [comment]
The bug is still not fixed completly.

**Comment by BDisp** [comment]
> The bug is still not fixed completly.

@kacperpikacz you are right. There still some more issue. But the related with this issue is already fix. Instead of reopening this I'll use the #2865, which is more related with the resize issue. Thanks.

**Comment by kacperpikacz** [comment]
Can someone take a look at this please?
