### ISSUE TITLE
`WindowsDriver` does not dispose `MainLoop` Tasks - memory leak

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#2872]
I believe this is the cause of the slowdown seen in UI Catalog when you repeatedly start and exit multiple Scenarios...

Once a fix is identified, this should be fixed in both v1 and v2.

Related: #2870 

Repo:

1. Debug.Performance Profiler... with "Memory Usage" on.
2. Take a Snapshot
3. Start and exit `Generic` 5 times
4. Take a Snapshot

Note in first snapshot `WindowsDriver` has a single ref count:

![image](https://github.com/gui-cs/Terminal.Gui/assets/585482/d962f5cb-f8c6-46cc-a3d9-9106b2c11336)

Note in 2nd snapshot `WindowsDriver` has 11 refs:
![image](https://github.com/gui-cs/Terminal.Gui/assets/585482/7587840d-99a4-4874-aa3e-7cac9a462bdb)

10 of those are from `WindowsMainLoop`. 

The `Tasks` created to poll for input (`WindowsInputHandler`) and window resizing (`CheckWinChange`) are not being cancelled properly which is causing `WindowsMainLoop` to not get disposed and since it has a ref to `_consoleDriver` the `WindowsDrivder` instance never gets clean up either.

The fix is to refactor how these Tasks/threads are created and cleaned up. This will require either 

- adding an `End` method to `IMainLoopDriver` that is called from `Application.Cleanup` 
- Adding `IDisposable` to `WiindowsMainLoop` and calling `Dispose` from `WindowsDriver.End`

OR 

- Refactoring the creation and cleanup of the Tasks/threads into `WindowsDriver` such that it manages them instead of `WindowsMainLoop`.

I suspect `CursesDriver` and `NetDriver` have same issue, but I did not test that.

**Comment by BDisp** [comment]
Yes I remember done something to that before. I even added the `End` method to the `IMainLoopDriver`, but :-)
Each driver (`ConsoleDriver` and `IMainLoopDriver`) must have the `End` method. `ConsoleDriver` already have, but but missing in `IMainLoopDriver`.

**Comment by tig** [comment]
#2880 makes some progress on this, but does not fix it.
