### ISSUE TITLE
Autocomplete is leaking memory

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#2888]
Repro:

1. Launch UI Catalog with VS Performance Profiler
2. Take a snapshot
3. Start Editor
4. Take a snapshot
5. Quit Editor
6. Take a snapshot

It will look like this:
![image](https://github.com/gui-cs/Terminal.Gui/assets/585482/1fb35857-10e9-4db3-9794-5e39ee3b9311)

Click on the "+4,873":
![image](https://github.com/gui-cs/Terminal.Gui/assets/585482/3f306d08-a301-436e-8ded-6f4bd71243f3)

Something in `AutocompleteContext` is not releasing and leaving all those `RuneCell`s around.

This is reproducable with any Scenario that uses Editor/Autocomplete.

**Comment by tznind** [comment]
This is v2 only right? RuneCell is a new addition?

**Comment by tznind** [comment]
Are you able to reproduce this on SyntaxHighlighting?

**Comment by tig** [comment]
Yes, it seems to reproduce with any Scenario where Autocomplete is enabled.
