### ISSUE TITLE
TableView renders selected rows differently than ListView

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#2899]
UI Catalog uses a ListView on left and TableView on Right:
![uBJ1wiU 1](https://github.com/gui-cs/Terminal.Gui/assets/585482/264bfd55-ab75-47e1-845e-bec29bb6827e)

The offending code is here:
![image](https://github.com/gui-cs/Terminal.Gui/assets/585482/20a2229b-b3b4-4c48-81be-41df6624dc0c)

Should be using "Focus"  not "HotFocus".

**Comment by tznind** [comment]
Fixed by the merged PR
