### ISSUE TITLE
v2 flicker in UICatalog

### ISSUE THREAD

**Issue by tznind** [gui-cs/Terminal.Gui#2903]
**Describe the bug**
When exiting or opening a scenario I get a flicker in the terminal (Windows Terminal) and a new line seems to get written to black screen before scenario window appears.

![flicker](https://github.com/gui-cs/Terminal.Gui/assets/31306100/412ed0a7-e8cd-452e-89a1-74a6e704b404)

**Comment by Nutzzz** [comment]
![ezgif.com-optimize.gif](https://github.com/gui-cs/Terminal.Gui/assets/5732804/44e6f792-fc4d-4685-b319-55c19a867d54)

**Comment by tig** [comment]
This is actually a result of an improvement in the ConsoleDrivers where they now clean up resources correctly on `Application.End`.

Remember UI Catalog is an App and each scenario is an App.  You are seeing what's in the terminal before/after each app Begin/Ends.

To fix this we would need to clear the underlying screen buffer, which would cause the terminal back-buffer to be cleared.

**Comment by tznind** [comment]
OK cool, I hadn't realised that each scenario was a separate App
start/shutdown.

Thats fine then.
