### ISSUE TITLE
`WindowsDriver` and `CursesDriver`'s MainLoops use an `Action` incorrectly

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#2921]
The right fix is to change both Windows and Curses' MainLoop implementations to do this:

<img width="478" alt="image" src="https://github.com/gui-cs/Terminal.Gui/assets/585482/8230d5d9-42e2-4d55-bbe6-696145387215">

IOW, get rid of the `ProcessInput` Action alltogether and just have them call `ProcessInput` on the driver directly.

I tested it and it appears to work fine. Am I missing something (I probably am).

_Originally posted by @tig in https://github.com/gui-cs/Terminal.Gui/pull/2911#discussion_r1363668470_

**Comment by BDisp** [comment]
> I tested it and it appears to work fine. Am I missing something (I probably am).

Yes you are missing. You can also do it for the `NetDriver`.
CursesDriver` handles differently, because it use file descriptor that will check for `revents`. If exist a revent then it will call the event attached by the `Watch` instance.

**Comment by tig** [comment]
> > I tested it and it appears to work fine. Am I missing something (I probably am).
> 
> Yes you are missing. You can also do it for the `NetDriver`. `CursesDriver` handles differently, because it use file descriptor that will check for `revents`. If exist a revent then it will call the event attached by the `Watch` instance.

I applied the same change to CursesDriver and it seems fine.

- I made `ProcessInput` `internal` on
- I removed the `WinChange` Action 
- I added a private reference to `CursesDriver` to `UnixMainLoop` 
- I now call `_cursesDrivder.ProcessInput ();` instead of invoking `WinChange?.Invoke()`

See #2922

**Comment by tig** [comment]
Related, the file descriptor watching in the CursesDriver is unnecessary functionality. I don't think any apps use it, and even if they do, they can just use native unix APIs or the .NET file system watcher classes instead. 

I think we should remove it.

**Comment by BDisp** [comment]
> Related, the file descriptor watching in the CursesDriver is unnecessary functionality. I don't think any apps use it, and even if they do, they can just use native unix APIs or the .NET file system watcher classes instead.
> 
I'm curious to see what you'll do. Only to remember that `ncurses` isn't compatible with .NET. Don't confuse the `NetDriver` with `CursesDriver`. Descriptors are native unix APIs.

> I think we should remove it.

If you intend to use `Console.ReadKey` and remove `ncurses` at all, then is better to remove `CursesDriver` too.

**Comment by tig** [comment]
> > Related, the file descriptor watching in the CursesDriver is unnecessary functionality. I don't think any apps use it, and even if they do, they can just use native unix APIs or the .NET file system watcher classes instead.
> 
> I'm curious to see what you'll do. Only to remember that `ncurses` isn't compatible with .NET. Don't confuse the `NetDriver` with `CursesDriver`. Descriptors are native unix APIs.

I really mean just making AddWatch/RemoveWatch `internal`. 

> 
> > I think we should remove it.
> 
> If you intend to use `Console.ReadKey` and remove `ncurses` at all, then is better to remove `CursesDriver` too.

That is not my intent at this point.

Can you help me understand what the two `AddWatch` calls each do?

This one's obvious: It's watching for input:
<img width="626" alt="image" src="https://github.com/gui-cs/Terminal.Gui/assets/585482/70c22f6d-a500-4ec5-8119-00c276e18302">

But what is this one doing? 
<img width="538" alt="image" src="https://github.com/gui-cs/Terminal.Gui/assets/585482/69b0227b-b013-4181-9674-adadca714bef">

**Comment by BDisp** [comment]
Yes the prior is for input and the second is reading for any writing done on the `_wakeUpPipes`. The later is useful for cancelation or from a post of the threading synchronization, normally by calling the `Wakeup` method which will interrupt the `poll` function and thus ensuring a new run loop.

**Comment by tig** [comment]
Please review changes now in this PR. More to do, but this is a massive simplifier... I think.
