### ISSUE TITLE
Some Unit Tests Are failing

### ISSUE THREAD

**Issue by a-usr** [gui-cs/Terminal.Gui#2923]
**Describe the bug**
`UnitTests/Terminal.Gui.Drivertests/Contents_Copies_From_OS_Clipboard`, `UnitTests/Terminal.Gui.Drivertests/Contents_Pastes_To_OS_Clipboard` and 
`UnitTests/Terminal.Gui.ViewTests/KeyBindings_Command` fail,

**To Reproduce**
1. Run All Unittests
2. If using vs and Testing stops once first test fails, Filter Tests for not completed tests and execute
3. Repeat 2 Until all tests have ran at least once
4. See that the three mentioned Tests have failed

**Expected behavior**
All Unittests should complete successfully

**Screenshots**
![image](https://github.com/gui-cs/Terminal.Gui/assets/81042605/d77caf9e-c626-42b4-b81e-7bdee8f5d79f)
![image](https://github.com/gui-cs/Terminal.Gui/assets/81042605/e438fb80-85ea-412a-850d-29156e6bfdc2)
![image](https://github.com/gui-cs/Terminal.Gui/assets/81042605/06ac7f83-4645-4486-a734-68227b0fc654)

**Desktop (please complete the following information):**
 -Windows

**Additional context**
None

**Comment by tig** [comment]
We should just disable the clipboard tests. They have proven to be super unreliable and no one has been able to figure out why.

**Comment by a-usr** [comment]
pwsh is actually not preinstalled on most systems. I dont have it installed, so it failed for me.

pwsh.exe is the newer version of Windows powershell (powershell.exe). powershell.exe comes preinstalled, the other one has to be downloaded from the microsoft store

https://www.reddit.com/r/PowerShell/comments/t4cuir/difference_between_windows_powershell_and/

**Comment by a-usr** [comment]
Think i have found the problem.
![image](https://github.com/gui-cs/Terminal.Gui/assets/81042605/fb470b55-9c5e-463f-b0d9-8b6ba35af891)
the expected Value is seperated by `/`, meanwhile the actual value is seperated by `.`.
I dont have any more time today, but i will fix this if this hasn't been fixed by the time i come back to this (in a few day's time)

**Comment by a-usr** [comment]
Also, to inspect the value i had to explicitly call that function from another program in case anyone is wondering

**Comment by a-usr** [comment]
Im closing this Issue for now, as this seems to be an issue with xUnit not being able to force the localization on some machines, and the Clipboard tests failed because i didn't do my research

**Comment by tznind** [comment]
> Im closing this Issue for now, as this seems to be an issue with xUnit not being able to force the localization on some machines, and the Clipboard tests failed because i didn't do my research

Thanks for taking the time to report and explore this issue, it will be useful for anyone else getting similar unit test issues in future around localization.

**Comment by BDisp** [comment]
Do you have any link that prove that? It'll be useful too. I'm curious if some more users with a Germany machine localization are having the same issue.

**Comment by a-usr** [comment]
> Do you have any link that prove that? It'll be useful too. I'm curious if some more users with a Germany machine localization are having the same issue.

Not really. Im currently on a Company machine, so it also could be the company environment messing things up. I'll try it on my own machine once im home.
