### ISSUE TITLE
[Bug / v1.x] ]Background Task Modal doesn't close when app is running on Linux

### ISSUE THREAD

**Issue by JeepNL** [gui-cs/Terminal.Gui#2942]
Terminal.Gui version: **1.14.0**
.NET SDK Version: **8 RC 2**
IDE: Visual Studio 2022 Preview (latest)

When displaying a modal while running a background task, the modal window doesn't close when finished but this happens only if you compile the app for Linux (Ubuntu 22.04) and run the program. On Windows the app runs as expected.

### To Reproduce

I've created a GitHub repo '[UbuntuModal](https://github.com/JeepNL/UbuntuModal)'  based on this sample code: https://github.com/gui-cs/Terminal.Gui/discussions/1119#discussioncomment-434675. 

I've included the batch file `Compile4Linux64.bat` which will compile the app to a single file executable for Linux. If you run this compiled app on (WSL) Ubuntu, you'll see the modal won't close. 

**Note:** The modal will close after you move your mouse or press a key while the app is running.

### Other Example

I've tried to do the same with different code, see below (_partial_), but that gives almost the same result. The difference is that you don't have to press a key or move the mouse to execute the background task, it does run, but the modal won't close after that. Again, after running the task the modal only closes when you press a key or move the mouse.

```
   private void Search()
   {
       bool search = SearchDialog(out string searchText);

       if (search)
       {
           if (bottomTable.Table.Rows.Count > 0)
           {
               bottomTable.Clear();
               RemoveColumnStyles(bottomTable); // For ASC and DESC characters
           }

           infoModal.Visible = true;
           modalTask = ValidSearchTask(searchText);
           Application.MainLoop.AddIdle(CheckSearchCompletion);
       }
   }

   private bool CheckSearchCompletion()
   {
       //if (modalTask == null || !modalTask.IsCompleted)
       if (!modalTask!.IsCompleted)
           return true; // The task is not yet complete, so keep the idle handler active

       infoModal.Visible = false;
       return false;
   }

   private Task ValidSearchTask(string searchText)
   {
       bottomTable.Table = topTable.Table.Clone();

       DataRow[] filteredRows = topTable.Table.Select($"Path LIKE '%{searchText}%' OR File LIKE '%{searchText}%'");
       foreach (DataRow row in filteredRows)
           bottomTable.Table.ImportRow(row);  // This imports the data of each row

       SetColumnStyles(bottomTable);

       if (bottomTable.Table.Rows.Count > 0)
           bottomTable.SetFocus();
       return Task.CompletedTask;
   }
```

**Comment by BDisp** [comment]
I think this issue is already fixed on the `develop` branch. Can you please use it instead of the nuget package?

**Comment by JeepNL** [comment]
Okay, I'll try!

**Comment by JeepNL** [comment]
Hi @BDisp, 

Yes it works when I use the `develop` branch 😊 Just perfect and thank you! The issue has been solved, if you want you can close it.

**Comment by BDisp** [comment]
I'll leave it open to @tig remember to publish when possible. Thanks.

**Comment by JeepNL** [comment]
Oh, wait ... something strange is happening when I use `CTRL-Q` on Ubuntu. I don't think the program closes successfully.  I can't get to my prompt any more

This happens when I compile '[UbuntuModal](https://github.com/JeepNL/UbuntuModal)' for Linux and run it. I haven't tested it much yet, but here a screenshpt what happens when I press `CTRL-Q`
![Screenshot 2023-10-30 164033](https://github.com/gui-cs/Terminal.Gui/assets/39458532/a6902988-1eb6-46c0-8021-33e4a2bb7f60)

**Comment by JeepNL** [comment]
FYI: I've tried this with .NET 7 SDK and .NET 8 RC 2 SDK, same result.

**Comment by JeepNL** [comment]
FYI (2): I don't think it happens only with pressing `CTRL-Q`. When I compile the project I'm currently working on `F1` opens a modal (window) so I can enter a search text. After pressing `F1` the program exits with the same behavior as shown in the screenshot above, So possibly this happens with every key input, but I'm not sure.

**Comment by BDisp** [comment]
You forgot to add `Application.Shutdown()` after `Application.Run()`. This is very important to do on exit.

**Comment by tig** [comment]
[v1.14.1](https://www.nuget.org/packages/Terminal.Gui) is now published.

**Comment by JeepNL** [comment]
@BDisp Oops, My Bad! I'm sorry, I feel a bit stupid I forgot that :) Thank you for your replies and thank you @tig for releasing v1.14.1 - Great library, recently started using it and loving it.
