### ISSUE TITLE
Filling a scrollview with content of variable size.

### ISSUE THREAD

**Issue by bzuidgeest** [gui-cs/Terminal.Gui#2957]
I'm trying to use terminal.Gui to create a simple tool to display the result of some documentation parsing. I have most things working, but I get stuck with a scrollview that has to contain a list of arbitrary size frameviews with a (multiline) label inside of them. 
I would expect for example that the frameview would automatically fit itself arround a label, but (at least on windows terminal) it doesn't do this. If I don't supply a absolute height the height wil be 0. 
When I add frameviews sequentially to a scrollview I would expect them to be put one after the other, but everything is just placed on top of one another. I need to set an explicit y value.
The scrollview itself I need to give a fixed contentsize.... otherwise it collapses to zero instead of fitting the content. 

Is it really this difficult to do this in this framework? Or am I doing something horribly wrong.

My loop for filling the scrollview now looks like:

```c#
//declarations of relevant views.
 valuesFrameView = new FrameView()
 {
     Title = "Values",
     X = Pos.Right(commandFrameView),
     Y = Pos.Bottom(descriptionFrameView),
     Width = Dim.Fill(0),
     Height = Dim.Fill(0),

 };

 valuesScrollView = new ScrollView()
 {
     //Title = "Values",
     X = 0,
     Y = 0,
     Width = Dim.Fill(0),
     Height = Dim.Fill(0),
     ShowVerticalScrollIndicator = true,
     ContentSize = new Size(400, 300), <-- I would expect the scrolview to calculate this based on the content added.
 };
 valuesFrameView.Add(valuesScrollView);

=================


 //int i = 0;
 bool first = true;
 foreach (ISCPCommandValueDocumentation value in command.Values2.Where(y => y.SupportedDevices.Contains(selectedModel)))
 {
     Label descriptionLabel = new Label()
     {
         Text = value.Description,
         Width = Dim.Fill(1),
         AutoSize = true
     };
     FrameView valueFrame = new FrameView()
     {
         Title = value.Name[0],
         Y = first ? 0 : Pos.Bottom(valuesScrollView.Subviews[0].Subviews.Last()),
         Width = Dim.Fill(1) ,
         Height = descriptionLabel.Bounds.Height + 2,
         AutoSize = true
     };
     valueFrame.Add(descriptionLabel);
     valuesScrollView.Add(valueFrame);
   
     first = false;
 }



 valuesScrollView.ContentSize = new Size(
     valuesFrameView.Bounds.Width == 0 ? 200 : valuesFrameView.Bounds.Width,
     valuesScrollView.Subviews[0].Subviews.Sum(x => x.Bounds.Height)
 );
```

Surely this can be done better?

The above mostly works, but the frameviews added the scrollview are still to wide.

![image](https://github.com/gui-cs/Terminal.Gui/assets/1292740/ae7f63ba-1210-4aa7-9a02-7d112f0de1a8)

I'm on version 1.14.1 from nuget. using windows /vs2022 .net core 7

Any help appreciated.

**Comment by BDisp** [comment]
```cs
 valuesScrollView.ContentSize = new Size(
     valuesFrameView.Bounds.Width == 0 ? 200 : valuesFrameView.Bounds.Width,
     valuesScrollView.Subviews[0].Subviews.Sum(x => x.Bounds.Height)
 );
```

I think the problem is this. You have to increase the content size as it grow more than 200, otherwise it'll put on top of another.

**Comment by bzuidgeest** [comment]
I added that 200 to give it some initial width before the scrollview gets its initial content after the first selection. The thing is. Even if I make the content size 3000x3000 it will still put everything on top of each other unless I use "Y = first ? 0 : Pos.Bottom(valuesScrollView.Subviews[0].Subviews.Last())," to lay it out myself. It doesn't seem to automatically resize to fit its content. Maybe thats normal for gui.cs, but any other framework I have encountered, parents ususally automatically try to fit their child objects. I feel that I should not even need to set content size.

**Comment by BDisp** [comment]
You need the content size to accommodate all the views in the scroll view. Of course you have to set the Y position of each view. So the Y of a new view is equal to `Pos.Bottom(viewsCollection[viewsCollection.Count - 1]) + 1` and increment the content size accordingly. The scroll view doesn't position the views automatically. Is your job to do that.

**Comment by bzuidgeest** [comment]
"The scroll view doesn't position the views automatically. Is your job to do that."

Ok. After thinking on it, what I expected is that the scrollview acted like a listview with an scrollbar. That clearly isn't the case then. 

Thank you for answering my question.

**Comment by BDisp** [comment]
Sorry, I forgot to tell you that there is a scenario on `UICatalog` that do what you want, more or less. It's the `ASCIICustomButton` scenario.

https://github.com/gui-cs/Terminal.Gui/assets/13117724/02f1b92f-e1df-4856-aff9-bb2345a6ad5e
