### ISSUE TITLE
Some of the scroll features on v1 are broken.

### ISSUE THREAD

**Issue by BDisp** [gui-cs/Terminal.Gui#2959]
I'm disgusted that some of the scrolling features I've helped improve aren't working well in v1, such as:

- `Clipping` scenario.
- `Editor` scenario.
- `ListsAndCombos` scenario.
- `Scrolling` scenario.

**Comment by tig** [comment]
Were these working in v1 before?

**Comment by BDisp** [comment]
> Were these working in v1 before?

The `Clipping` maybe not, don't remember, but the others yes.

**Comment by tig** [comment]
I don't understand how fixing things that were working before, then broke, requires so many new public APIs.

**Comment by BDisp** [comment]
> I don't understand how fixing things that were working before, then broke, requires so many new public APIs.

@tig it's so only two `Func`. I removed the `EventArgs` class.
