### ISSUE TITLE
Auto-join of `Border` is not always working

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#2995]
Run Frames Demo:

![image](https://github.com/gui-cs/Terminal.Gui/assets/585482/224537d8-2efe-4717-8cf3-3dce07a7fcbb)

I saw this a long time ago, but all of the discussions of "finishing" Adornments (#2994) reminded me it's broken.

**Comment by BDisp** [comment]
> I saw this a long time ago, but all of the discussions of "finishing" Adornments (#2994) reminded me it's broken.

Yes, that was after the new title drawing.
