### ISSUE TITLE
LineCanvas return LLCorner (└) instead of ULCorner (┌) if X = 0, Y = 1 and Length = -1.

### ISSUE THREAD

**Issue by BDisp** [gui-cs/Terminal.Gui#2997]
@tig did I done something wrong in this unit test?

```cs
		[Fact, SetupFakeDriver]
		public void Test_Incomplete_Frame ()
		{
			var canvas = new LineCanvas ();

			canvas.AddLine (new Point (0, 0), -1, Orientation.Vertical, LineStyle.Single);
			canvas.AddLine (new Point (0, 0), 10, Orientation.Horizontal, LineStyle.Single);
			canvas.AddLine (new Point (9, 0), 5, Orientation.Vertical, LineStyle.Single);
			canvas.AddLine (new Point (9, 4), -10, Orientation.Horizontal, LineStyle.Single);
			canvas.AddLine (new Point (0, 4), -2, Orientation.Vertical, LineStyle.Single);

			string looksLike = @"
┌────────┐
         │
         │
│        │
└────────┘";
			TestHelpers.AssertEqual (output, looksLike, $"{Environment.NewLine}{canvas}");
		}

```

But it return this:

```
Expected:

┌────────┐
         │
         │
│        │
└────────┘
But Was:

└────────┐
         │
         │
│        │
└────────┘

```

**Comment by Nutzzz** [comment]
You have the first Line going -1 (up) from 0, 0, but your expected looksLike seems to want a positive 1 (down)... right?

**Comment by BDisp** [comment]
> You have the first Line going -1 (up) from 0, 0, but your expected looksLike seems to want a positive 1 (down)... right?

No, I want to go up (vertical negative) and go right (horizontal positive). It's really a bug but a lot of unit tests are relaying on the bug and I'm trying to fix all them.

**Comment by Nutzzz** [comment]
So whether it's 1 or -1 (assuming there's no bug), would the result be the same (starting with a ULCorner)?

**Comment by BDisp** [comment]
> So whether it's 1 or -1 (assuming there's no bug), would the result be the same (starting with a ULCorner)?

That not matter. We need to follow the doc intructions:

```cs
	internal enum IntersectionType {
		/// <summary>
		/// There is no intersection
		/// </summary>
		None,

		/// <summary>
		///  A line passes directly over this point traveling along
		///  the horizontal axis
		/// </summary>
		PassOverHorizontal,

		/// <summary>
		///  A line passes directly over this point traveling along
		///  the vertical axis
		/// </summary>
		PassOverVertical,

		/// <summary>
		/// A line starts at this point and is traveling up
		/// </summary>
		StartUp,

		/// <summary>
		/// A line starts at this point and is traveling right
		/// </summary>
		StartRight,

		/// <summary>
		/// A line starts at this point and is traveling down
		/// </summary>
		StartDown,

		/// <summary>
		/// A line starts at this point and is traveling left
		/// </summary>
		StartLeft,

		/// <summary>
		/// A line exists at this point who has 0 length
		/// </summary>
		Dot
	}

```

**Comment by tznind** [comment]
When you combine a StartUp and a StartRight you should get `└`

**Comment by tznind** [comment]
```csharp
[InlineData (Orientation.Vertical,-1,Orientation.Horizontal,1, "└")] // StartUp + StartRight
		[InlineData (Orientation.Vertical, 1, Orientation.Horizontal, 1, "┌")] // StartDown + StartRight
		[InlineData (Orientation.Vertical, -1, Orientation.Horizontal, -1, "┘")] // StartUp + StartLeft
		[InlineData (Orientation.Vertical, 1, Orientation.Horizontal, -1, "┐")] // StartDown + StartLeft
		[Theory, SetupFakeDriver]
		public void TwoLinesTest (Orientation orientation1, int length1, Orientation orientation2,int length2, string expected)
		{
			var lc = new LineCanvas ();
			// Add a line at 0, 0 that's has length of 0
			lc.AddLine (new Point (0, 0), length1, orientation1, LineStyle.Single);
			lc.AddLine (new Point (0, 0), length2, orientation2, LineStyle.Single);
			TestHelpers.AssertEqual (output, expected, $"{lc}");
		}
```

**Comment by tznind** [comment]
Maybe the confusion you are having is that StartUp is -1.  It means we are going up the screen.

**Comment by BDisp** [comment]
> When you combine a StartUp and a StartRight you should get `└`

Not really, depend of the direction and of the way that they were added to `LineCanvas`. In the unit test above I want to start at `0,0,-1,Vertical (StartUp)` then I want to go from `0,0,10,Horizontal (StartRight)`, so must be `┌`.

**Comment by BDisp** [comment]
> Maybe the confusion you are having is that StartUp is -1. It means we are going up the screen.

Of course and then you want to to right to continue the frame, so it must be `┌`.

**Comment by tznind** [comment]
![image](https://github.com/gui-cs/Terminal.Gui/assets/31306100/10bd2b68-d9d8-4ce7-841f-1a8fa234cdad)

Length of y = -1 means that you do not spill into the next console row but are genearlly going up the screen.

**Comment by BDisp** [comment]
> Length of y = -1 means that you do not spill into the next console row but are genearlly going up the screen.

Yes that was my intention. Going up the screen and then turn right `┌────────`.

**Comment by tznind** [comment]
Drawing starts at the 'center' of the console cell.  The horizontal line passes through the center of the cell also.

So a you are not starting at the bottom of the cell drawing up (in which case you are right it would be `┌`

You are drawing from the centre of the cell drawing up (i.e. above where the horizontal line is - `└`)

**Comment by BDisp** [comment]
The unit test is drawing an irregular (or incomplete) rectangle. Imagine I'm drawing with a pencil. It should respect the start, positive/negative length and direction.

**Comment by tznind** [comment]
Ok let me try to convince you with another angle

Lets start drawing a graphs axis.  We start at the bottom of our view and go up and right

```csharp
lc.AddLine (new Point (0, 3), -3, Orientation.Vertical, LineStyle.Single);
lc.AddLine (new Point (0, 3), 3, Orientation.Horizontal, LineStyle.Single);
```

This gives us

```
│  
│  
└──
```

Surely  you cannot argue with this?

Lets reduce the lengths to 2

```csharp
lc.AddLine (new Point (0, 3), -2, Orientation.Vertical, LineStyle.Single);
lc.AddLine (new Point (0, 3), 2, Orientation.Horizontal, LineStyle.Single);
```

```
│ 
└─
```

Now we get the same thing when the length is 1

```csharp
lc.AddLine (new Point (0, 3), -1, Orientation.Vertical, LineStyle.Single);
lc.AddLine (new Point (0, 3), 1, Orientation.Horizontal, LineStyle.Single);
```
```
└
```

**Comment by BDisp** [comment]
> Ok let me try to convince you with another angle
> 
> Lets start drawing a graphs axis. We start at the bottom of our view. We have 2 lines, one goes up (y axis) and the other goes right (x axis)
> 
> ```cs
> lc.AddLine (new Point (0, 3), -3, Orientation.Vertical, LineStyle.Single);
> lc.AddLine (new Point (0, 3), 3, Orientation.Horizontal, LineStyle.Single);
> ```
> 
> This gives us
> 
> ```
> │  
> │  
> └──
> ```
> 
> Surely you cannot argue with this?
> 

![image](https://github.com/gui-cs/Terminal.Gui/assets/13117724/ee7b6a2b-bd58-4865-9b54-5e9a6a280f19)

Sorry. We aren't talking of graphs axis. `LineCanvas` is another matter. I already fix the bug and unit tests are failing because the `OnDrawCanvas` is buggy. I ran the `GraphView` scenario without any issue, works as before. I also ran `Spider` scenario and the only issue is when I change the direction drawing wrong corners.
Vertical -3 is `StartUp` and horizontal 3 is `StartRight`, so it gave us:

```
┌──
│
│

```
> Lets reduce the lengths to 2
> 
> ```cs
> lc.AddLine (new Point (0, 3), -2, Orientation.Vertical, LineStyle.Single);
> lc.AddLine (new Point (0, 3), 2, Orientation.Horizontal, LineStyle.Single);
> ```
> 
> ```
> │ 
> └─
> ```
> 

```
┌─
│

```
> Now we get the same thing when the length is 1
> 
> ```cs
> lc.AddLine (new Point (0, 3), -1, Orientation.Vertical, LineStyle.Single);
> lc.AddLine (new Point (0, 3), 1, Orientation.Horizontal, LineStyle.Single);
> ```
> 
> ```
> └
> ```

`┌
`

**Comment by tznind** [comment]
Sorry forget that I mentioned graphs.  LineCanvas works with same coordinate system as views.

If we have a view that is 3 by 3 

And we draw from 0,3 (lower left)

Up 3 (-3)
And then right 3

Do you agree with the fact that we end up with:

```
│  
│  
└──
```

**Comment by BDisp** [comment]
> Sorry forget that I mentioned graphs. LineCanvas works with same coordinate system as views.
> 
Sorry not to agree. I think of it more like a pencil where I start drawing and going in various directions. The order in which each doodle is recorded determines the type of rune that will be displayed.

> If we have a view that is 3 by 3
> 
A view is a rectangle and I really don't understand what you mean with it is 3 by 3.

> And we draw from 0,3 (lower left)
> 
> Up 3 `AddLine (new Point (0, 3), -3, Orientation.Vertical, LineStyle.Single` And then right 3 `AddLine (new Point (0, 3), 3, Orientation.Horizontal, LineStyle.Single);`
> 
No, I want:
Up 3 `AddLine (new Point (0, 3), -3, Orientation.Vertical, LineStyle.Single` And then right 3 `AddLine (new Point (0, 0), 3, Orientation.Horizontal, LineStyle.Single);`

> Do you agree with the fact that we end up with:
> 
> ```
> │  
> │  
> └──
> ```

No in fact it must end up with:

```
┌──
│
│

```

**Comment by BDisp** [comment]
@tznind sorry I didn't realized you used in the e.g above:

`lc.AddLine (new Point (0, 3), 3, Orientation.Horizontal, LineStyle.Single);`

but I want:

`lc.AddLine (new Point (0, 0), 3, Orientation.Horizontal, LineStyle.Single);`

**Comment by tznind** [comment]
Ok then you want this (see test)

If you want 3 symbols worth of vertical height then you must start drawing at 0,2 not 0,3.

That way you have a cell at row 2, a cell at row 1 and a cell at row 0.

**For LineCanvas to work the lines must overlap**

```csharp
[Fact]
public void Works()
{
	var canvas = new LineCanvas ();
	canvas.AddLine (new Point (0, 2), -3, Orientation.Vertical, LineStyle.Single);
	canvas.AddLine (new Point (0, 0), 3, Orientation.Horizontal, LineStyle.Single);

			string looksLike = @"┌──
│  
│  ";
			TestHelpers.AssertEqual (output, looksLike, $"{canvas}");
}
```

**Comment by BDisp** [comment]
> Ok then you want this (see test)
> 
> If you want 3 symbols worth of vertical height then you must start drawing at 0,2 not 0,3.
> 
> That way you have a cell at row 2, a cell at row 1 and a cell at row 0.
> 
> **For LineCanvas to work the lines must overlap**
> 
> ```cs
> [Fact]
> public void Works()
> {
> 	var canvas = new LineCanvas ();
> 	canvas.AddLine (new Point (0, 2), -3, Orientation.Vertical, LineStyle.Single);
> 	canvas.AddLine (new Point (0, 0), 3, Orientation.Horizontal, LineStyle.Single);
> 
> 			string looksLike = @"┌──
> │  
> │  ";
> 			TestHelpers.AssertEqual (output, looksLike, $"{canvas}");
> }
> ```
> 

If you want convince me please make the initial unit test at the beginning of this issue work. I already test that if it's larger than 1 it work, but not if it's 1.

> Snake is working fine on `v2_develop`
> 

I refer the changes on the PR I'm working, not on v2_develop.

**Comment by tznind** [comment]
> > Snake is working fine on `v2_develop`
> 
> I refer the changes on the PR I'm working, not on v2_develop.

If you have changed it and snake is no longer working doesn't mean that your changes have broken it?

**Comment by BDisp** [comment]
> If you have changed it and snake is no longer working doesn't mean that your changes have broken it?

I didn't broken the logic, direction, etc. Only some corners that not yet fixed.

Now I'm facing this problem:

```
Expected:
                ┌┤Title├───────────────────────────────────────┐
                │                   Message                    │
                │                                              │
                │                                              │
                └──────────────────────────────────────────────┘
But Was:
                ┌│Title├───────────────────────────────────────┐
                │                   Message                    │
                │                                              │
                │                                              │
                └──────────────────────────────────────────────┘

```

Instead of `┌┤` it's showing `┌│`. This make think that some of the resolvers glyphs only can be obtaining after a previous resolver is obtained and joining with the appropriate resolver. What do you think?

**Comment by tznind** [comment]
> This make me think that some of the resolvers glyphs only can be obtaining after a previous resolver is obtained and joining with the appropriate resolver.

All lines that cross a point are considered at the same time.

`LineCanvas` is well tested and your original test is intended behaviour as it was designed.  If the tests are breaking when you change the code to `LineCanvas` then that is the problem.  I've not seen a unit test that doesn't work as intended in v2_develop

**Comment by BDisp** [comment]
> All lines that cross a point are considered at the same time.
> 
> `LineCanvas` is well tested and your original test is intended behaviour as it was designed. If the tests are breaking when you change the code to `LineCanvas` then that is the problem. I've not seen a unit test that doesn't work as intended in v2_develop
> 
I'm not saying that is the case but sometimes there a unit tests that are adapted to bugs.

> A line with a length magnitude of 1 joined to a horizontal line has to be capable of producing both `┌` and `└`. So when you have Vertical -1 you get `└` and when you have Vertical 1 you get `┌`. This is **intended behaviour**.

I'm curious here. Do you see that the Vertical is always on the left side of the Horizontal? When it can be the opposite, the Vertical on the right side of the Horizontal? I know you said the is **intended behavior**. But why? You said if Vertical is -1 or 1, but you didn't said anything about if Horizontal is -1 or 1. Do you realize that can change the behavior based on this particularity?

**Comment by tznind** [comment]
> but you didn't said anything about if Horizontal is -1 or 1. Do you realize that can change the behavior based on this particularity?

| Vertical|Horizontal | Rune| 
|-|-|-|
|1|1|`┌`|
|1|-1|`┐`|
|-1|1|`└`|
|-1|-1|`┘`|

**Comment by BDisp** [comment]
Thanks. I confirm that is how it work currently on v2_develop.

```cs
		[Theory]
		[InlineData (0, 0, 1, 0, 0, 1, "┌")]
		[InlineData (0, 0, 1, 0, 0, -1, "┐")]
		[InlineData (0, 0, -1, 0, 0, 1, "└")]
		[InlineData (0, 0, -1, 0, 0, -1, "┘")]
		public void Corner_Tests (int x, int y, int length, int x1, int y1, int length1, string looksLike)
		{
			var canvas = new LineCanvas ();
			canvas.AddLine (new Point (x, y), length, Orientation.Vertical, LineStyle.Single);
			canvas.AddLine (new Point (x1, y1), length1, Orientation.Horizontal, LineStyle.Single);

			TestHelpers.AssertEqual (output, looksLike, $"{canvas}");
		}

```

When you firstly talked on graph axis I though you referred to the follow, which I know think that would have more logic. What do you think?
```
y=1         y=1
x=-1   y    x=1
       │
     ┘ │└
───────┼───────x
     ┐ │┌
       │
y=-1        y=-1
x=-1        x=1

```

**Comment by BDisp** [comment]
Do you think it's worth the effort?

**Comment by tznind** [comment]
I think it should follow the existing pattern.  Graphs have a Y axis that is the opposite of view coordinate system.

**Comment by BDisp** [comment]
@tznind, please can you explain why this is the correct code in the `StraightLine` class. I though if `Length < 0` will be the opposite direction. Thanks.

![image](https://github.com/gui-cs/Terminal.Gui/assets/13117724/dd238236-373c-4c32-985b-b5244d161c34)

![image](https://github.com/gui-cs/Terminal.Gui/assets/13117724/24825faa-488d-410f-a1be-26ca3a4e06f6)

**Comment by BDisp** [comment]
Thanks so much for your magnificent explanation. Thus is possible to track the beginning and ending of a line, no matter where was started.
