### ISSUE TITLE
Brown is missing from ColorNames in v2

### ISSUE THREAD

**Issue by tznind** [gui-cs/Terminal.Gui#3027]
**Describe the bug**
Was this intentional? I can see that `Yellow` is marked '(also known as Brown)'

![image](https://github.com/gui-cs/Terminal.Gui/assets/31306100/e235e9dd-303f-43cc-8b66-1a0e53dea1f7)

**Comment by tig** [comment]
Yes. I decided to match the official ansi color names.

**Comment by tznind** [comment]
So upgrade path is to replace `Brown` with `Yellow`? I will update the breaking changes list
