### ISSUE TITLE
In API docs, `<remarks>` need to be inside `<summary>` for docfx to work

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#3028]
Noticed a bunch of remarks were not showing up. Discovered that for all elements besides classes the remarks tags need to be contained within the summary tag. 

For all future PR please take the time to fix this in any files impacted by the PR.

**Comment by kushan23** [comment]
Hi, I would like to work on it, can I?

**Comment by tig** [comment]
Please do!!! Great way to learn the code base.

**Comment by tig** [comment]
Actually please hold off. 

I'm not convinced we should do this now. This may just be a bug in the docfx theme we're using. 

VS and VS code show the remarks correctly in intellisense.

**Comment by BDisp** [comment]
> Actually please hold off.
> 
> I'm not convinced we should do this now. This may just be a bug in the docfx theme we're using.
> 
> VS and VS code show the remarks correctly in intellisense.

Probably it's a bug in the `docfx`.

**Comment by tig** [comment]
It's the template. I'm going to switch us to a new template like this one:

<img width="782" alt="image" src="https://github.com/gui-cs/Terminal.Gui/assets/585482/626d8fda-7f78-49b6-a5bc-415222b8bfe8">

Closing.
