### ISSUE TITLE
Runes not working on Windows

### ISSUE THREAD

**Issue by rccarlson** [gui-cs/Terminal.Gui#3040]
**Describe the bug**
On the `v2_develop` branch, some Runes are not rendering correctly

**To Reproduce**
Screenshot below was created by running UICatalog and opening the "Images" demo.
[This file](https://github.com/gui-cs/Terminal.Gui/assets/43221493/58153d12-a0c9-4346-ac5a-1a8475c0075b)  was used, though this is not necessary to repro the bug

**Expected behavior**
Expected to see one of these runes from `Glyphs.cs`:
![image](https://github.com/gui-cs/Terminal.Gui/assets/43221493/a59ca5ea-48a8-498e-98c1-d712d6dd9d0a)
![image](https://github.com/gui-cs/Terminal.Gui/assets/43221493/e8de674a-30e0-4329-a429-caf06eae5cad)

**Screenshots**
![image](https://github.com/gui-cs/Terminal.Gui/assets/43221493/14362a6d-d443-43a7-968c-9400f2a711e2)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Console
 - Version: Current as of 8f1b5aceb628e642942dd9827b0998c998ebeeea

**Additional context**

**Comment by tig** [comment]
What font are you using ?

**Comment by rccarlson** [comment]
Console settings:

![image](https://github.com/gui-cs/Terminal.Gui/assets/43221493/cda7baea-b527-4d51-a1fd-dcf7449986b0)

**Comment by tznind** [comment]
This has been the case for a while for me on `v2_develop`.  When I use nerd fonts or any other font than the default then these characters do resolve.

**Comment by tig** [comment]
Ah, this looks like conhost. 

Conhost and Windows Terminal are diverging more and more and it's challenging to have a single WindowsDriver that supports both. 

Plus there ARE bugs in v2 in this regard. 

We will fix this but for now can I ask why you're not using windows terminal?

**Comment by rccarlson** [comment]
This is just what the default "Run" option brought up. I also launched the UICatalog from Command Prompt and got the same thing:
![image](https://github.com/gui-cs/Terminal.Gui/assets/43221493/5bcc95f2-198e-4627-8717-7bc3cc084a86)

**Comment by BDisp** [comment]
In the Windows Terminal settings set the Terminal default as "Lets Windows decide" and when you start debugging the WT will open instead of conhost.

**Comment by rccarlson** [comment]
My settings were already on "let windows decide"
![image](https://github.com/gui-cs/Terminal.Gui/assets/43221493/d39249b9-74ba-403a-8a41-94a25d8f3bd4)

Video of what I do to recreate the problem (I literally just launch the UICatalog):

https://github.com/gui-cs/Terminal.Gui/assets/43221493/c00a7a3a-f4c8-42de-a2b6-b9d463c5ecca

**Comment by BDisp** [comment]
Windows 10 or 11?

**Comment by rccarlson** [comment]
@BDisp Windows 10

**Comment by BDisp** [comment]
Ok that explain the behavior you are having. If you are using `PowerShell 7.4.0`, if not install it, open with the `Windows Terminal` an run the `Terminal.Gui`. Thus I think you are be able to use the Nerd font.

**Comment by rccarlson** [comment]
Running with PowerShell 7.4:

https://github.com/gui-cs/Terminal.Gui/assets/43221493/5f9c7da0-c2cd-4afb-bfdc-d9ed42d91ac3

Running with cmd:

https://github.com/gui-cs/Terminal.Gui/assets/43221493/33e515e8-d61c-4d46-9ec2-b60c6383d8b6

What do you mean by "Nerd font"? Are only specific fonts supported?

**Comment by BDisp** [comment]
Install `Oh My Posh` and the Nerds font here https://ohmyposh.dev/docs/installation/fonts.

**Comment by tznind** [comment]
> What do you mean by "Nerd font"? Are only specific fonts supported?

All fonts are supported in v1.  All fonts will be supported in v2 when it launches - this issue will be resolved before  launch.  

v2 adds support for customizing which symbols are used for what.  For example a user can configure the tick symbol to be either:

```
√ - Widely supported (this is the default for checkbox in v1)
☑ - Less widely supported but looks better (this is the **current** default in v2)
```

Seperate from this discussion is 'Nerd fonts'.  It is a category of extended font set which includes new unicode symbols that are not part of the main specification e.g. the Visual Studio logo in the below.

![image](https://github.com/gui-cs/Terminal.Gui/assets/31306100/625874b3-b2b2-4b5f-be07-e9cf63a63448)

Nerd fonts is 'opt in' i.e. you have to enable it deliberately in API or via a users config file.
