### ISSUE TITLE
Remove the `KeyCode.Unknown`

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#3055]
> > > I propose to remove the `KeyCode.Unknown` which aren't used by the drivers now, since they return `KeyCode.Null` if KeyChar is `'\0'`. Thus avoids using the prior to check if a key is valid or not and only compare if it's `KeyCode.Null`.
> > 
> > 
> > I agree.
> 
> Note that `Key` already doesn't have `Unknown`.

I think it should also been removed from the `KeyCode` enum.

_Originally posted by @BDisp in https://github.com/gui-cs/Terminal.Gui/issues/2927#issuecomment-1858909499_

**Comment by BDisp** [comment]
@tig I also have another suggestion that could be done in this issue or open a new issue if you want. `Key.IsValid` is actually relying `=> KeyCode is not (KeyCode.Null or KeyCode.Unknown);` After removing the KeyCode.Unknown which I enterally agree, it will only relying on `=> KeyCode is not KeyCode.Null;` which could be only be a KeyCode.ShiftMask, KeyCode.AltMask or KeyCode.CtrlMask. These modifiers keys alone or combined without a non modifier key shouldn't be used because I think don't make no sense, but I could be wrong. So my suggestion is change to `IsValid => KeyCode != KeyCode.Null && new Key (KeyCode & ~KeyCode.AltMask & KeyCode & ~KeyCode.CtrlMask & KeyCode & ~KeyCode.ShiftMask) != KeyCode.Null;`
What do you think?

**Comment by tig** [comment]
> @tig I also have another suggestion that could be done in this issue or open a new issue if you want. `Key.IsValid` is actually relying `=> KeyCode is not (KeyCode.Null or KeyCode.Unknown);` After removing the KeyCode.Unknown which I enterally agree, it will only relying on `=> KeyCode is not KeyCode.Null;` which could be only be a KeyCode.ShiftMask, KeyCode.AltMask or KeyCode.CtrlMask. These modifiers keys alone or combined without a non modifier key shouldn't be used because I think don't make no sense, but I could be wrong. So my suggestion is change to `IsValid => KeyCode != KeyCode.Null && new Key (KeyCode & ~KeyCode.AltMask & KeyCode & ~KeyCode.CtrlMask & KeyCode & ~KeyCode.ShiftMask) != KeyCode.Null;` What do you think?

On Windows (and maybe other platforms in the future) it is possible to detect a "Shift Key" (Shift, Ctrl, or Alt) press. We should not arbitrarily prevent devs from doing so. 

So, as long as the driver doesn't include the CtrlShift mask with the "Ctrl" key event, I agree.

Here I 

- Pressed and released "Ctrl"
- Pressed and released "Ctrl"
- Pressed and released "Enter"
- Pressed "Ctrl", Pressed "U", Released both

![image](https://github.com/gui-cs/Terminal.Gui/assets/585482/637c4826-803f-4388-b942-ce55429bf63f)

Also, in the new world, this is better syntax for what you suggest:

```cs
	/// <summary>
	/// Indicates whether the <see cref="Key"/> is valid or not. Invalid keys are <see cref="Key.Empty"/>,
	/// and keys with only shift modifiers.
	/// </summary>
	public bool IsValid => this != Empty && (NoAlt.NoShift.NoCtrl != Empty);
```

Unit tests:

```cs
	// IsValid
	[Theory]
	[InlineData (KeyCode.A, true)]
	[InlineData (KeyCode.B, true)]
	[InlineData (KeyCode.F1 | KeyCode.ShiftMask, true)]
	[InlineData (KeyCode.Null, false)]
	[InlineData (KeyCode.ShiftMask, false)]
	[InlineData (KeyCode.CtrlMask, false)]
	[InlineData (KeyCode.AltMask, false)]
	[InlineData (KeyCode.ShiftMask | KeyCode.AltMask, false)]
	public void IsValid (Key key, bool expected) => Assert.Equal (expected, key.IsValid);
```

**Comment by tig** [comment]
I can have a PR ready for this in a few min. Unless you already have one ready.

**Comment by BDisp** [comment]
> I can have a PR ready for this in a few min. Unless you already have one ready.

I'm trying to fix the `VkeyPacketSimulator` and if you have your ready please submit it, thanks. May help me fix this better.

**Comment by tig** [comment]
Almost ready.
