### ISSUE TITLE
Pos.Bottom returns PosCombine (`+0`)

### ISSUE THREAD

**Issue by tznind** [gui-cs/Terminal.Gui#3064]
**Describe the bug**

Calling Pos.Bottom is not returning the correct (simplest) Pos.

It is returning 
```csharp
Pos.Combine(Pos.View(side=bottom, target=View()({X=0,Y=0,Width=0,Height=0}))+Pos.Absolute(0))
```

Instead of 
```csharp
Pos.View(side=bottom, target=View()({X=0,Y=0,Width=0,Height=0}))
```

Here is a unit test which currently fails on v2:
```csharp
[Fact]
public void DoNotReturnPosCombine()
{
var v = new View ();
var pos = Pos.Bottom (v);

Assert.Equal (
	"Pos.View(side=bottom, target=View()({X=0,Y=0,Width=0,Height=0}))",
	pos.ToString ());
}
```

**Additional context**
While adding + 0 doesn't cause any behaviour in client apps it is still confusing.  Additionally it causes issues with TerminalGuiDesigner which really wants to know if a View currently has relative, absolute etc positioning.

**Comment by BDisp** [comment]
In this case all them (`X`, `Y`, `Left`, `Top`, `Right`, `Bottom`) are wrong as well because they all return `PosCombine(Pos.View(), Pos.Absolute(0))`
