### ISSUE TITLE
Ability to set Action on StatusItem post creation

### ISSUE THREAD

**Issue by tznind** [gui-cs/Terminal.Gui#3070]
**Is your feature request related to a problem? Please describe.**

`Action` is now `get` only.  This presents a problem in TerminalGuiDesigner where event handlers have to be declared by users within the `.cs` file (while designed views are constructed in `.Designer.cs`)

![image](https://github.com/gui-cs/Terminal.Gui/assets/31306100/d4106742-5a5e-4cdc-9d49-9e5952e656d3)

**Describe the solution you'd like**
Add `set` keyword to `Action`

**Describe alternatives you've considered**
None

**Additional context**
The API docs seem to indicate that this was possible at some point.  Or it was intended to be the case.

**Comment by tig** [comment]
I want to refactor StatusBar. It's actually a quite simple control, but was written before...

- View.Text
- View.HotKey with killer ToString support
- Frames (for StatusItem spacing/alignment)
- Consistency in eventing (KeyBindings and no Action). 
- KeyBindingScope.Application

It should just be a View that is Width = Fill and Y = AnchorEnd by default. StatusItem doesn't need to exist (any View that works ok with Height = 1) can be added.

**Comment by tig** [comment]
Fixed with new `StatusBar`
