### ISSUE TITLE
TestTreeViewColor sometimes throws because Branch<T> it's using static Attribute Default.

### ISSUE THREAD

**Issue by BDisp** [gui-cs/Terminal.Gui#3075]
The default `Attribute` constructor use the `public static readonly Attribute Default = new Attribute (Color.White, Color.Black);` which is used by the `Branch<T>` class in the `Draw` method.

```cs
			// if custom color delegate invoke it
			if (tree.ColorGetter != null) {
				var modelScheme = tree.ColorGetter (Model);

				// if custom color scheme is defined for this Model
				if (modelScheme != null) {
					// use it
					modelColor = isSelected ? modelScheme.Focus : modelScheme.Normal;
				} else {
					modelColor = new Attribute ();
				}
			}
```

Changing `modelColor = new Attribute ();` to `modelColor = new Attribute (Attribute.Default.Foreground, Attribute.Default.Background);` avoids sometimes it throwing an error.

**Edit:**

But this isn't working anymore.

**Comment by tig** [comment]
So annoying.
