### ISSUE TITLE
Potentially unintended behavior of static pre-defined keys in Keys class (v2)

### ISSUE THREAD

**Issue by dodexahedron** [gui-cs/Terminal.Gui#3079]
I am wondering if this behavior of the pre-defined static key fields in the Keys class is intentional or not:

While the fields themselves are readonly, they are **NOT** immutable - only the reference itself is - and a common instance reference is returned to all callers.

Say someone passed a key cloned from one of these via, for example, `Key.X` around in an event, since it's clearly expected, as it inherits from EventArgs. If they set any writable value in that key, it has been set globally for any future cases that static is used, which is probably not what a user would expect.

Currently, this example test would fail:

```
	[Fact]
	public void TheseAreNotSafe ( )
	{
		// Make two local keys, and grab Key.A, which is a reference to a singleton.
		Key aKey1 = Key.A;
		Key aKey2 = Key.A;

		// Assert the starting state that is expected
		Assert.False ( aKey1.Handled );
		Assert.False ( aKey2.Handled );
		Assert.False ( Key.A.Handled );

		// Now set Handled true on one of our local keys
		aKey1.Handled = true;

		// Assert the newly-expected case
		// The last two assertions will fail, because we have actually modified a singleton
		Assert.True ( aKey1.Handled );
		Assert.False ( aKey2.Handled );
		Assert.False ( Key.A.Handled );
	}

```

Changing all of the pre-defined fields to be auto get-only properties would ensure no reference equality between them, and still passes the existing tests.

That can be achieved by simply making every one of the `static readonly Key X = new()`  fields to `static Key X => new()`.

Alternatively, making sure no members can be set (including through side effects) is at least a workaround.

I think returning new instances by making them auto-get-only properties is most likely to have the behavior typically expected of that kind of thing.

**Comment by tig** [comment]
Good catch. I missed this.

**Comment by BDisp** [comment]
We need to have careful with the use of `static` and only use them on method that pass an instance parameter and return a new value for that instance. Use on fields that only have a fixed value for all instances (e.g. `MenuBar.ShortcutDelimiter` is `static` because it will be used on all `MenuBar` or `ContextMenu` instances) and not if it can have different values for each instances.

**Comment by tig** [comment]
`Key.KeyCode` was already `{ get; init }` BTW.

**Comment by dodexahedron** [comment]
> `Key.KeyCode` was already `{ get; init }` BTW.

Ha yeah I noticed that too after your comment on the other issue that it should be immutable.

**Comment by dodexahedron** [comment]
You know...

This made me think...

Shouldn't this be a struct? For cases where you want to pass a reference around, you still can, using ref, in, or out, but a Key is, ultimately, a _value_. The desire to make it immutable even reflects/supports that notion.

**Comment by tznind** [comment]
Need to be able to set Handled

And class lets consumer do shenanigans like force switching the KeyCode
with reflection.

I always see `private` and `init` as saying "you really shouldn't" while
`struct` says "you can't".  I prefer the flexibility of the former.

**Comment by dodexahedron** [comment]
Sounds reasonable enough to me. 👌
