### ISSUE TITLE
Unresolved Reference: Christmas

### ISSUE THREAD

**Issue by tznind** [gui-cs/Terminal.Gui#3082]
**Describe the bug**
Not enough Christmas References

**To Reproduce**
1. Open Issues
2. Search 'Christmas'
3. See error

**Expected behavior**
Merry Christmas! @tig @BDisp @migueldeicaza @dodexahedron and everyone else who contributes and uses Terminal.Gui.

And for those not celebrating christmas, happy holidays!

**Screenshots**
![image](https://github.com/gui-cs/Terminal.Gui/assets/31306100/d860941f-d372-41d9-aec4-b27c817ef255)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional Christmas**
Yes please!

**Comment by migueldeicaza** [comment]
Merry Christmas and happy holidays  folks!

**Comment by tig** [comment]
Merry Merry Merry!

Hugs to all.

**Comment by dodexahedron** [comment]
How fun!

Merry Christmas to you all as well! :)

**Comment by BDisp** [comment]
Reopening this to wish continued happy holidays and Happy New Year to everyone.
