### ISSUE TITLE
Feature request: customization of the color changing symbol in StatusItem

### ISSUE THREAD

**Issue by AndreyAkinshin** [gui-cs/Terminal.Gui#3090]
At the moment (v1.14.1, v2_develop), `StatusItem` allows highlighting shortcuts using the `~` symbol (e.g., `~F1~ Help`). While this is a useful feature, it prevents displaying the `~` itself in the label. I want to show the current directory in the status bar with `~` as a symbol for the home directory. Unfortunately, the current text rendering logic always eliminates all the `~` symbols.

It would be nice to introduce a property that allows customizing this symbol. Thus, for my "show current directory" task, I can redefine this symbol to something else so that it's possible to display `~` in the status bar.

It should be a very simple fix to implement in both v1.14.1 and v2 (introduce one new property + update two usages). If it sounds like a reasonable feature to add, I'm ready to send PRs.

**Comment by tig** [comment]
Sweet idea. Do it!

In v2 there will be a new control called "Bar" I've just started a PR on. I'll make sure this scenario is supported there too.
