### ISSUE TITLE
Get v2 .NET runtime targeting right.

### ISSUE THREAD

**Issue by dodexahedron** [gui-cs/Terminal.Gui#3092]
I noticed that the v2_develop branch only targets net8.0

Was this intentional?

I mean I'm all for leaving the old behind in this case, but just wanted to be sure that wasn't an accident.

**Comment by dodexahedron** [comment]
The only reference I found anywhere was here: https://github.com/gui-cs/Terminal.Gui/discussions/1940#discussioncomment-7879157 which says 7+

Supported runtimes might be a nice thing to include in the docs, too.

**Comment by tig** [comment]
I did it in trying to fix a local issue I was having with WSL testing/debugging. 

We know we are using features that only work on 7+. 

We have stated we are not willing to forgo those features to support .NET Core earlier than that. v1 will continue to be supported and is quite feature rich.

We have not clearly articulated what those things are (and I forget).

If someone wanted to think more deeply about this and clearly articulate the right settings, that would be most excellent.

**Comment by dodexahedron** [comment]
👌

I've got no problem, personally, with 8+.

In fact, it enables use of version 12 of the language, which has some very real advantages.

V2 is already a massive and breaking change with v1, and net8.0 is the current LTS, so I would say game on.

Just wanted to confirm before I start letting myself use language features.

**Comment by dodexahedron** [comment]
Closing this since I think we're all set.

If anyone has any other thoughts, by all means re-open.
