### ISSUE TITLE
Now that View is IDisposable, it should expose a Disposing event

### ISSUE THREAD

**Issue by dodexahedron** [gui-cs/Terminal.Gui#3097]
In v2, View is IDisposable.

However, there's no way, at present, for anything dependent on a view to know when that view has been disposed or is being disposed, other than trying something that's illegal at runtime, situationally.

This can lead to memory leaks, runtime exceptions, and other unexpected behavior, in consumers.

Proposal:

Implement a standard Disposing event, to be invoked in the Dispose method, so that anything dependent on a given View can gracefully clean up, when that view is disposed.

One place this is already relevant is in TerminalGuiDesigner: https://github.com/gui-cs/TerminalGuiDesigner/issues/270

Having such an event _does_ expose the possibility of bad consumer code blocking during Dispose, but that's _their_ fault, not Terminal.Gui's. We could attempt to protect users from themselves by implementing some sort of deadline mechanism, but I don't think that's necessary and has more potential downsides than benefits (plus the complexity of implementing it in the first place).

**Comment by dodexahedron** [comment]
Nice.

One additional problem is that properties and functions do not throw ObjectDisposedException if called after disposal.

Instead, it's undefined behavior. You could get a range of different exceptions since the object is still alive, if something has a reference to it that is used after disposal.

That's a distinct problem from this one, though, so I'll make a separate issue for it. That one is library-wide.

**Comment by BDisp** [comment]
Thanks. Yes I only was concerned to the subscriber to been notified to do the needed actions to avoid exceptions. But it's really a good options beside it probably will get different exceptions depending of what it will doing.
