### ISSUE TITLE
Slider crashes when Legend not set on an Option

### ISSUE THREAD

**Issue by tznind** [gui-cs/Terminal.Gui#3098]
**Describe the bug**

When adding a  new slider option with no `Legend` (e.g. `new SliderOption<string>()`) you get a hard crash at render time e.g.:

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Terminal.Gui
  StackTrace:
   at Terminal.Gui.Slider`1.<>c.<CalcSpacingConfig>b__63_0(SliderOption`1 e) in /home/runner/work/Terminal.Gui/Terminal.Gui/Terminal.Gui/Views/Slider.cs:line 733

```

**Comment by tig** [comment]
Did this get fixed with the new constructor PR?

**Comment by tznind** [comment]
No, I only made the minimum changes to enable me to continue with designer
Slider support 'happy paths'

**Comment by tig** [comment]
> **Describe the bug**
> 
> When adding a new slider option with no `Legend` (e.g. `new SliderOption<string>()`) you get a hard crash at render time e.g.:
> 
> ```
> System.NullReferenceException
>   HResult=0x80004003
>   Message=Object reference not set to an instance of an object.
>   Source=Terminal.Gui
>   StackTrace:
>    at Terminal.Gui.Slider`1.<>c.<CalcSpacingConfig>b__63_0(SliderOption`1 e) in /home/runner/work/Terminal.Gui/Terminal.Gui/Terminal.Gui/Views/Slider.cs:line 733
> ```

This no make sense. Here's line 733:

```cs
	if (_options.Count == 0) {
		return;
	}
```

This has nothing to do with whether an option has/doesn't have a `Legend`. 

Any chance you can provide more context?

**Comment by tig** [comment]
I believe this is fixed in https://github.com/gui-cs/Terminal.Gui/pull/3121

The offending line was:

```cs
max_legend = _options.Max (e => e.Legend.ToString ().Length);
```

Which is now 

```cs
max_legend = int.Max (_options.Max (e => e.Legend == null ? 0 : e.Legend.ToString ().Length), 1);
```

(this fixes another bug I found where max_legend could be 0).

**Comment by tznind** [comment]
Great changes, both bugs are fixed.  I adjusted a test case locally to ensure that rendering also worked under these circumstances and got no errors.  It would be good at some point with some tests for how the slider renders e.g. 

`TestHelpers.AssertDriverContentsAre (expected, output);`
