### ISSUE TITLE
Black gaps between lines in Rider terminal

### ISSUE THREAD

**Issue by KAW0** [gui-cs/Terminal.Gui#3111]
![obraz](https://github.com/gui-cs/Terminal.Gui/assets/16373327/5cdac272-a20b-465e-926c-65e4a1ea6b7a)
Running in Rider terminal look like this. I know I can use "Use external terminal" but I use Shell script to run my app in VM and there is no such option there
Edit: I just realised sorry for posting here not in discussion since it's probably Rider issue [🤦](https://emojipedia.org/person-facepalming)

**Comment by BDisp** [comment]
See this discussion #3041.

**Comment by tznind** [comment]
I assume that is just how Rider is designed.  A quick google does not indicate any preference or option to disable these 'scan lines'.  I would suggest opening a ticket with Jetbrains to add a config option to disable it.
