### ISSUE TITLE
Suggestion: Enable and use nullability context

### ISSUE THREAD

**Issue by dodexahedron** [gui-cs/Terminal.Gui#3112]
What it says on the tin: Nullability context - the `?` decorator and `?` and `!` operators useable when that feature is enabled - is something that would be really great to at least start using, even if work isn't immediately done to plug it in everywhere in existing code, yet.

The value for static analysis is tremendous and it doesn't change runtime behavior, since it's just a shortcut for adding various attributes to things.

Additionally, it would be helpful to use annotations in places where nullability context isn't enough (such as `[NotNullWhen(true)]` on the `out` parameter of a `TryX` method).

Enabling Roslyn to analyze things that way can reveal surprising things like unreachable code or branches that will ALWAYS be taken, due to their conditions always being true or false.

I've been doing that in TGD, as I've been writing tests, and it has enabled several nice little cleanups here and there.

And turning it on is just an xml tag in the csproj and mandates nothing. The feature just isn't useable without it being on.

Built-in analyzers are also very good at suggesting where the feature should be used, once it's on.

Library projects, especially, should generally use it, at least on the public API surface.

**Comment by tznind** [comment]
It has been discussed before e.g. see NRT discussions in https://github.com/gui-cs/Terminal.Gui/discussions/1940

Its a good idea but quite a bit of work.

**Comment by dodexahedron** [comment]
Definitely one I'm willing to approach, at some point.

I don't mind mucking about with the un-fun stuff like this.

I'll keep it in mind for future work items, then. :)

**Comment by dodexahedron** [comment]
Oh, I noticed today that nullability context can be enabled on a per-file or even more granular basis, which can help ease into it bit by bit.

To enable it for a file, just put a `#nullable enable` at the top of the file.

To enable it in specific portions of a file, you can use pairs of `#nullable enable` and `#nullable disable`, if/when desired.

Then it's not opening the flood gates on a ton of new warnings and inaccurate annotations for code that hasn't yet been annotated for nullability context.

As such, might I suggest that, for any new code added, we stick `#nullable enable` in the file or around the new class (if it's a whole new type) or even just new methods, as they're written, so we don't continue to build the debt up and can start getting the static analysis benefits even sooner?

**Comment by tig** [comment]
![image](https://github.com/gui-cs/Terminal.Gui/assets/585482/973f79c6-6cad-482e-a93c-f01a72fb30f8)

**Comment by dodexahedron** [comment]
Nice!

**Comment by dodexahedron** [comment]
I'm going to close this, since at this point everyone is well aware and generally trying to use it for new work.
