### ISSUE TITLE
`TextView` assumes `Frame == Bounds`

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#3140]
e.g: 

```cs
///<inheritdoc/>
public override void OnDrawContent (Rect contentArea)
{
	_isDrawing = true;

	SetNormalColor ();

	var offB = OffSetBackground ();
	int right = Frame.Width + offB.width + RightOffset;
	int bottom = Frame.Height + offB.height + BottomOffset;
	int row = 0;
	for (int idxRow = _topRow; idxRow < _model.Count; idxRow++) {
```

**Comment by dodexahedron** [comment]
Oh man yeah this and related issues I think are going to impact some stuff I'm debugging in TGD around hit testing.

On that note, there's a HitTest extension method on View in TGD which I think could be valuable and logocal to be in TG, instead. Not as-is, though, as it has some buggy edge cases, and several changes being made over here will require that method to be changed anyway.
