### ISSUE TITLE
View (v2) Tabbing between views is broken. ListView selectedItem does not highlight

### ISSUE THREAD

**Issue by fergusonr** [gui-cs/Terminal.Gui#3155]
Tabbing between two views does not work. Second issue is the `SelectedItem = 0` in the first list is not highlighted on startup

**Code to reproduce**
```CSHarp
using System.Collections.Generic;
using System.Diagnostics;

using Terminal.Gui;

Application.Init();

var mainWindow = new Window() { Title = "Test", X = 0, Y = 0, Width = Dim.Fill(), Height = Dim.Fill() };
var view1 = new ListView() { X = 0, Y = 0, Width = Dim.Fill(), Height = 5, SelectedItem = 0 };
var view2 = new ListView() { X = 0, Y = 5, Width = Dim.Fill(), Height = 5, };
view1.SetFocus();

var list = new List<string>() { "One", "Two", "Three" };
view1.SetSource(list);
view2.SetSource(list);

mainWindow.Add(view1, view2);

Debug.WriteLine($"view1 tabindex {view1.TabIndex} stop {view1.TabStop}");
Debug.WriteLine($"view2 tabindex {view2.TabIndex} stop {view2.TabStop}");

Application.Top.Add(mainWindow);

Application.Run();
Application.Shutdown();
```

**Expected behaviour**
Screen grab below is behaviour from v1.14.1

![tabstop](https://github.com/gui-cs/Terminal.Gui/assets/17233550/3bcd3dd3-d201-4d3e-a616-f4bbdfe6ea5d)

**Comment by BDisp** [comment]
If a combo box is initialized without setting the SelectedItem then it must be -1 and not forcing it to be 0. But tabbing should move the cursor to the ListView if it is already open, otherwise should move to the next view.

**Comment by fergusonr** [comment]
Thanks. The reproduction is two independent ListViews. Setting SelectedItem on startup works in v1.14.1

**Comment by BDisp** [comment]
> Thanks. The reproduction is two independent ListViews. Setting SelectedItem on startup works in v1.14.1

You are right, thanks. That is a bug for sure in the v2. Do you already found the bug or do you want I take a look at?

**Comment by BDisp** [comment]
Ok I already now what happening. The source must be added before set the `SelectedItem`. If source is null the `SelectedItem` isn't set because there no value to set the item 0. We can't see the cursor on the second `ListView` because the `SelectedItem` is -1, but if you move the cursor it will show. See this:

```cs
		public int SelectedItem {
			get => selected;
			set {
				if (source == null || source.Count == 0) {
					return;
				}
				if (value < -1 || value >= source.Count) {
					throw new ArgumentException ("value");
				}
				selected = value;
				OnSelectedChanged ();
			}
		}
```

Change to this:

```cs
		Application.Init ();

		var list = new List<string> () { "One", "Two", "Three" };

		var mainWindow = new Window () { Title = "Test", X = 0, Y = 0, Width = Dim.Fill (), Height = Dim.Fill () };
		var view1 = new ListView (list) { X = 0, Y = 0, Width = Dim.Fill (), Height = 5, SelectedItem = 0 };
		var view2 = new ListView (list) { X = 0, Y = 5, Width = Dim.Fill (), Height = 5, };
		//view1.SetFocus ();

		//view1.SetSource (list);
		//view2.SetSource (list);

		mainWindow.Add (view1, view2);

		Debug.WriteLine ($"view1 tabindex {view1.TabIndex} stop {view1.TabStop}");
		Debug.WriteLine ($"view2 tabindex {view2.TabIndex} stop {view2.TabStop}");

		Application.Top.Add (mainWindow);

		Application.Run ();
		Application.Shutdown ();

```

**Comment by fergusonr** [comment]
Not found the bug. Let me see if I can fix it over the weekend

**Comment by BDisp** [comment]
> Not found the bug. Let me see if I can fix it over the weekend

I already found the cause and it isn't a bug. Please see my comment above.

**Comment by tig** [comment]
can this be closed?

**Comment by BDisp** [comment]
Yes it isn't a bug.
