### ISSUE TITLE
Terminal.sln has `Terminal.Gui\.vscode\settings.json = Terminal.Gui\.vscode\settings.json`

### ISSUE THREAD

**Issue by BDisp** [gui-cs/Terminal.Gui#3176]
@tig this file doesn't exist. Does it must be part of `Terminal.sln`?

**Comment by tig** [comment]
I'll nuke it. Not sure how that happened.

**Comment by BDisp** [comment]
It's normally when using the vscode.

**Comment by tig** [comment]
It's per user and blocked by .gitignore. I added it by accident.
