### ISSUE TITLE
`DatePicker` date going out of range

### ISSUE THREAD

**Issue by MaciekWin3** [gui-cs/Terminal.Gui#3196]
**Describe the bug**
Currently, users can crash the app by setting a date out of range using the previous/next button in the DatePicker.

**To Reproduce**
1. Go to UICatalog DatePicker
2. Set the date, for example, to 12/12/9999.
3. Click next month button
4. The app crashes.

**Expected behavior**
The view should prevent setting a date out of range by disabling the previous/next buttons.

**Comment by BDisp** [comment]
You fixes when you arrive to the 01/01/10000 😄

**Comment by BDisp** [comment]
The exception also occurs when the date is 01/01/0001 and you click on the previous month.

**Comment by MaciekWin3** [comment]
> The exception also occurs when the date is 01/01/0001 and you click on the previous month.

Yes, I have also addressed this 😉
