### ISSUE TITLE
Command.Accept should be implemented on the Toplevel.

### ISSUE THREAD

**Issue by BDisp** [gui-cs/Terminal.Gui#3198]
If a `Button` is default and it's added to `Toplevel` we expect that the `Clicked` event should fire by press the `Enter` key. But it's implemented on his sub-class `Window` and thus allowing only itself and his sub-classes, like `Dialog`.
Running the following test will fail.

```cs
	[Fact, AutoInitShutdown]
	public void IsDefault_True_On_Toplevel_Fire_Clicked_Event_On_Enter_Key ()
	{
		var wasClicked = false;
		var view = new View { CanFocus = true };
		var btn = new Button { Text = "Ok", IsDefault = true };
		btn.Clicked += (s, e) => wasClicked = true;
		Application.Top.Add (view, btn);
		Application.Begin (Application.Top);
		Assert.True (view.HasFocus);

		Application.OnKeyDown (new (Key.Enter));
		Assert.True (view.HasFocus);
		Assert.True (wasClicked);
	}

```

**Comment by tig** [comment]
I thought you and I agreed on a compromise on this?

If someone wants `Window` or `Dialog`-like button behavior use `Window` or `Dialog`, not `Toplevel`.

I assert your unit test is invalid as `Toplevel` does not implement support of `IsDefault`. `Window` does.

**Comment by BDisp** [comment]
> I thought you and I agreed on a compromise on this?
> 
> If someone wants `Window` or `Dialog`-like button behavior use `Window` or `Dialog`, not `Toplevel`.
> 
> I assert your unit test is invalid as `Toplevel` does not implement support of `IsDefault`. `Window` does.

But if we reflect carefully on this subject, I think it should always be the base class (Toplevel) that should implement all common features and the derived classes only implement specific features that the base class does not have.
Furthermore, nothing prevents a user from just wanting to use Application.Top to add their views.
But I could also be wrong if you already have a very advanced idea in which what I said is not justified.

**Comment by tig** [comment]
> I think it should always be the base class (Toplevel) that should implement all common features and the derived classes only implement specific features that the base class does not have. Furthermore, nothing prevents a user from just wanting to use Application.Top to add their views. But I could also be wrong if you already have a very advanced idea in which what I said is not justified.

`Application.Run<Window>()` works just fine.

And, as I said in the discussion where you agreed on the compromise, which you're now revisiting:

https://github.com/gui-cs/Terminal.Gui/pull/3151#issuecomment-1885079433

<img width="622" alt="image" src="https://github.com/gui-cs/Terminal.Gui/assets/585482/432ce115-b185-4623-be02-1df4e553e5f5">

**Comment by BDisp** [comment]
I'm already remembering that and when I agreed it was that Toplevel would be removed.
However, while it exists it makes more sense for Toplevel to take care of the common functionalities of any view.
I think you should first remove Toplevel and definitely assume Window as the top-level view.
While this is not done, we can consider that Toplevel is still responsible for knowing how to deal with a standard button.

**Comment by BDisp** [comment]
Unless you keep in mind just keeping the Toplevel class where only sub-classes are allowed to be added and not other views. Window as a derived class already allows any view to be added as long as it is not Toplevel or perhaps even Window.

**Comment by BDisp** [comment]
But if you've already changed the unit tests to only work with Window and Dialog, then I can close this issue and the pull request. So you don't have to worry about that. Then please tell me. Thanks

**Comment by tig** [comment]
I think this issue should be closed.
