### ISSUE TITLE
v2_develop release builds broken by conditional compilation

### ISSUE THREAD

**Issue by dodexahedron** [gui-cs/Terminal.Gui#3208]
There's some conditional compilation based on whether the DEBUG_IDISPOSABLE symbol is declared or not.

The UnitTests project will fail to build in release configuration, which of course doesn't define that symbol.

It's some code that references `Responder.Instances`, which doesn't exist unless that symbol is defined.

Noticed that when I was doing full test runs after merging from v2_develop as of ad234aa8702a66e406951b2a78738f2b2e9b9f92, which is the latest as of this posting.

**Comment by dodexahedron** [comment]
I wasn't sure if the intention was to keep that stuff in or if it was just meant to be temporary, during debugging, so I didn't want to touch it until someone can comment.

**Comment by tig** [comment]
I did this way back in v1 when IDisposable support was added. I didn't want those checks in Release builds.

I still want them in Debug and still don't want them in Release.

**Comment by dodexahedron** [comment]
Sounds good.

In that case, just some adjustment of the placement of the preprocessor directives is all that's needed to fix it.

**Comment by dodexahedron** [comment]
I fixed release build testing across a couple of my PRs, so this can be closed.
