### ISSUE TITLE
Mainloop stops when there is no focus or events

### ISSUE THREAD

**Issue by RonSijm** [gui-cs/Terminal.Gui#3243]
Hey there, I've tested this on Develop Branch from source, V2_Dev branch from source, and on the 2.0.0-pre.251 nuget.

So the simplest representation of my use-case:

In the main window I start a loop:

    var task = new Task(async () =>
    {
        while (true)
        {
            Label.Text = DateTime.Now.ToString()
            await Task.Delay(5000);
        }
    });

    task.Start();

This works, but only if the console has focus and I move the mouse around, then eventually `OnDrawContent` on my label is called.

If my console does not have focus, the window does not update until I set focus to the console again, and hover over it.

It looks like [Terminal.Gui.Application RunIteration()](https://github.com/gui-cs/Terminal.Gui/blob/4430fe2cc62352a97837cb3302764f2e7f324bad/Terminal.Gui/Application.cs#L809) is waiting for events (I assume in this case it's triggered by a MouseHover or GetFocus kinda event) - before it considers whether components need updating.

The main loop seems to be stuck until something unlocks [this here](https://github.com/gui-cs/Terminal.Gui/blob/4430fe2cc62352a97837cb3302764f2e7f324bad/Terminal.Gui/ConsoleDrivers/WindowsDriver.cs#L2071)

To test my suspicion I changed my code to this, which unlocks the main loop:

    var task = new Task(async () =>
    {
        while (true)
        {
            Label.Text = DateTime.Now.ToString()
            Application.Wakeup();
            await Task.Delay(5000);
        }
    });

(Specifically notable: `Application.Wakeup();` added after updating the text)

I'm not sure how best to fix this, I'd think that on an action that requires a redraw of a component, such as updating the text, an artificial event should be thrown such as "PossibleRedrawRequired event which unlocks the main loop - Or the main loop should be woken up with something like `Application.Wakeup();`

**Comment by BDisp** [comment]
To update the UI from another thread it's needed to call inside `Application.MainLoop.Invoke(() => { Label.Text = DateTime.Now.ToString(); })`. Not needed to use the `Application.Wakeup()`.

**Comment by RonSijm** [comment]
I don't think it's a threading issue, I'm just using a task to not block the main loop, and have an easy constant loop

`Application.MainLoop.Invoke(() => { Label.Text = DateTime.Now.ToString(); })`  just calls `AddIdle`  which also does:

    internal Func<bool> AddIdle (Func<bool> idleHandler)
    {
        lock (_idleHandlersLock)
        {
            _idleHandlers.Add (idleHandler);
        }

        MainLoopDriver.Wakeup ();

        return idleHandler;
    }

So the `Application.MainLoop.Invoke` is basically a helper function of "Do action and wakeup"

When changing Terminal.Gui.View.Text to this it also solves it:

    public virtual string Text
    {
        get => _text;
        set
        {
            var isUpdated = _text != value;

            _text = value;
            SetHotKey ();
            UpdateTextFormatterText ();
            OnResizeNeeded ();

            if (isUpdated)
            {
                Application.Wakeup ();
            }

    #if DEBUG
            if (_text != null && string.IsNullOrEmpty (Id))
            {
                Id = _text;
            }
    #endif
        }
    }

But I assume that this behavior is not only on the View element, but others as well

**Comment by RonSijm** [comment]
So where would you suggest I put this loop inside the main thread so that it's ticked every x seconds, to show that the same happens on the main thread?

I've tried adding it to Iteration of the Application:

        Application.Iteration += async (sender, args) =>
        {
            Label.Text = DateTime.Now.ToString();
        };

But Iteration is not triggered unless there are events detected, same as the original issue. If you just leave the console open without doing anything, the console is completely idle

**Comment by BDisp** [comment]
As I said before you only need to do this:

```cs
Application.MainLoop.Invoke (() =>
    {
        Label.Text = DateTime.Now.ToString();
    };

```

**Comment by tig** [comment]
Closing as by-design.
