### ISSUE TITLE
Improve id generation and de-couple from testing

### ISSUE THREAD

**Issue by dodexahedron** [gui-cs/Terminal.Gui#3250]
As discussed in #3242, we can improve id generation for views and make them independent of build configuration.

This could simplify some logic in View.

Current thought is to use a static counter field that is simply incremented in a thread-safe manner (such as Interlocked.Increment) with every new View created, and append that to the type name.

Might also be a good idea to prefix with an underscore or other common convention, to help avoid potential collisions with user-specified ids by using an unlikely character sequence.

**Comment by tig** [comment]
@dodexahedron when you get a chance can you please update this Issue to

- Make the title more clear what "id"s you are referring to
- Latest thinking on the technical plan for doing this?

**Comment by dodexahedron** [comment]
This one is way down toward the bottom of my list, but it is on it. Super low importance. More of a nice-to-improve.

**Comment by tig** [comment]
If you can't update it so that when I read it I know what you're talking about i'm gonna close it.

**Comment by dodexahedron** [comment]
That works for me.

Tagging myself again to find it later.

@dodexahedron
