### ISSUE TITLE
Application closes unexpectedly

### ISSUE THREAD

**Issue by AbdulovHell** [gui-cs/Terminal.Gui#3257]
Hello. I have a simple form that has several TabView each of which contains ListView. There is a problem that after starting running the application simply closes by itself after a short random period of time. There are no errors or exceptions. I just see "Bye! Press Ctrl+C" as if I closed it myself as usual. Has anyone already encountered this? How can i try to track this? I am using Terminal.Gui v1.15.1 NuGet.

```
[STAThread]
static void Main(string[] args)
{
    ...
    
    GUIThread = new Thread(() =>
    {
        try
        {
            Application.Run<MainWnd>();
        }
        catch (Exception excp)
        {           
            System.Console.WriteLine($"{excp.Message}\n{excp.StackTrace}");
        }
        finally
        {
            Application.Shutdown();
            WaitQuit.Release();
        }
    });
    GUIThread.Name = "GUI main thread";
    GUIThread.Start();
    
    ...

    WaitQuit.WaitOne();
    System.Console.WriteLine("Bye! Press Ctrl+C");
}
```

**Comment by tznind** [comment]
Some things to try:

- Avoid using `Console.WriteLine` while app is running
- Call Application.Run from the main thread of your program
- If updating UI from another Thread or Task, ensure you wrap the update
code in `MainLoop.Invoke(()=> action);`
- ensure you don't update the UI a million times a second ;)

**Comment by AbdulovHell** [comment]
This one works. 
1.
```
GUIThread = new Thread(UIWindowProc);
GUIThread.Name = "GUI main thread";
GUIThread.Start();
```
2.
```
[STAThread]
private static void UIWindowProc(object obj)
{
...
}
```
