### ISSUE TITLE
Sample Application fills terminal with nonsense after shutdown when mouse moves.

### ISSUE THREAD

**Issue by byamagata** [gui-cs/Terminal.Gui#3266]
**Describe the bug**
After quitting the sample application using Ctrl+Q, the terminal will fill with nonsense and continue to fill while the mouse is moving over the terminal.  

**To Reproduce**
1. `dotnet new tui`
2. After app startup, quit by using `Ctrl+Q`
3. Move mouse around terminal

**Expected behavior**
Application quits as expected, no mouse inputs are captured

**Screenshots**
<img width="1360" alt="image" src="https://github.com/gui-cs/Terminal.Gui/assets/26102991/152bab74-dc7b-4a5b-864f-ecf4b635b45a">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 14.3.1
 - Shell: zsh (inside iTerm2)

**Comment by tznind** [comment]
Hmn from memory the template references the latest nuget package.  So could
be os or a breaking change in latest v1 package?

I will have a look and see if I can reproduce when I get a chance.  Can you
please post the program.cs  code that is generated for you on  your machine?

**Comment by dodexahedron** [comment]
Not to derail any troubleshooting or anything, but...

For what it's worth, I have encountered the same behavior, on both Windows and Linux as the client OS, using Konsole and Windows Terminal, with SSH sessions to remote systems running zsh. It seems even more likely to happen when something takes over the whole terminal, such as less, tmux, screen, or a Terminal.Gui application, which leads me to believe there's a bug or peculiarity of zsh at the bottom of this. Those experiences go back years.

**Comment by bytedreamer** [comment]
Sending the command `reset` resolves the issue with a SSH session into a Raspberry Pi
