### ISSUE TITLE
Add `ViewDiagnosticFlags.MouseCursor`

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#3306]
When debugging mouse stuff, I often wish I could see where Terminal.Gui THINKS the mouse is. We may not need this long term, but it'd be useful now as we're debugging `Adornments` and the trickyness around coordinates.

The idea would be, if enabled, the foreground/background color of the `Cell` the mouse is over would invert.

I think this goes in `Application.MouseEvent` (and not `ConsoleDriver` or `View`).

**Comment by BDisp** [comment]
On the same way that tabbing can set focus a view which `CanFocus` is true, then clicking on a view can also set the focus. I think in the `ViewMouse.cs` should be like this:

```cs
    protected bool OnMouseClick (MouseEventEventArgs args)
    {
        if (!Enabled)
        {
            return true;
        }

        MouseClick?.Invoke (this, args);
        if (args.Handled)
        {
            return true;
        }

        if (!HasFocus && CanFocus)
        {
            SetFocus();
        }

        return args.Handled;
    }
```

**Comment by tig** [comment]
> On the same way that tabbing can set focus a view which `CanFocus` is true, then clicking on a view can also set the focus. I think in the `ViewMouse.cs` should be like this:
> 
> ```cs
>     protected bool OnMouseClick (MouseEventEventArgs args)
>     {
>         if (!Enabled)
>         {
>             return true;
>         }
> 
>         MouseClick?.Invoke (this, args);
>         if (args.Handled)
>         {
>             return true;
>         }
> 
>         if (!HasFocus && CanFocus)
>         {
>             SetFocus();
>         }
> 
>         return args.Handled;
>     }
> ```

What does this have to do with mouse cursor diagnostics?

**Comment by BDisp** [comment]
Forget.
