### ISSUE TITLE
Code Cleanup with R# - File Layout is annoying

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#3308]
Some of the current settings are annoying and should be changed:

## R# claims to support placing backing fields above their properties in FIle Layout. 

But this does not work. 

https://youtrack.jetbrains.com/issue/RSRP-484909/Support-Place-backing-field-above-property-in-file-layout

I want this, and it's super annoying that the global reformat we did screwed this up. To this end, I want to change the default Ctrl-E/C profile to NOT apply file layout.

It can be applied separrately with a "File Layout" profile.

## Sorting is annoying

I configured properties, methods, etc... to sort based on name. This is annoying when it actually makes having related things near each other. For example in ViewLayout.cs, the logical order of X, Y, Width, Height is exactly that. But because we have sorting on, they get placed as Height, Width, X, Y.

**Comment by BDisp** [comment]
I've noticed this for a long time and I thought you wanted it that way, anyway...

**Comment by dodexahedron** [comment]
You should grab the file layout extensions R# extension, which actually provides this. I use that.

The settings are not quite right yet, even using that, but I just haven't cared enough since it's such a minor thing.

**Comment by dodexahedron** [comment]
Also, there might be a way to make it ignore things like underscores for purposes of sorting.

But typical guidelines are to have private and static stuff up top (which includes constructors) and then everything else follows.

Personally, I like to also have all properties be placed before methods, but that's just my pref.
