### ISSUE TITLE
Menu is responding even outside the limits, not moving to the view that has the mouse.

### ISSUE THREAD

**Issue by BDisp** [gui-cs/Terminal.Gui#3326]
See on this video where the menu item is moved even outside it's limit and clicking below on the `ListView` or the `TableView` doesn't select any.

https://github.com/gui-cs/Terminal.Gui/assets/13117724/7a102a46-5849-44e8-9249-d84cb3420b80

**Comment by dodexahedron** [comment]
Might this behavior change or be fixed as part of @tig's work on improving/fixing the rules for drawing/positioning in relation to bounds?

**Comment by BDisp** [comment]
It's really a menu bug and I'll submit a PR and he do whatever he want.

**Comment by dodexahedron** [comment]
Cool beans. Just wanted to mention just in case it was duplicated effort. :)

**Comment by BDisp** [comment]
I'm used to it.
