### ISSUE TITLE
The scroll bars in the CharacterMap scenario are broken.

### ISSUE THREAD

**Issue by BDisp** [gui-cs/Terminal.Gui#3331]
@tig do you remember if you did any change?

https://github.com/gui-cs/Terminal.Gui/assets/13117724/4d932674-bfeb-4b09-bbae-0b6b9d9512e6

**Comment by tig** [comment]
Hmmmm

I swear they were working last week. But I don't remember clearly.

**Comment by tig** [comment]
(Should be 'contentArea`... I fixed this in my `Bounds->Viewport` expirment branch).

**Comment by BDisp** [comment]
I think you should create a new PR for that fix before you merge that PR.

**Comment by tig** [comment]
Actually that's not the only issue. 

Looks like clipping is broken too. 

Horizontal scrolling draws goofy. Previously I was relying on clip for horizontal and trying. To be smart about vertical.
