### ISSUE TITLE
Clipping scenario - Adornments don't redraw 

### ISSUE THREAD

**Issue by BDisp** [gui-cs/Terminal.Gui#3332]
I can move the window 1 or 2 (both are incorrectly as 1). Only after I move them the I can also move the window 3. It seems the window 3 is moved at start but not repainted on the console. Only after we move one of the others windows we check that the window 3 isn't in the original place.

https://github.com/gui-cs/Terminal.Gui/assets/13117724/bb08a37c-77fa-4a40-9239-e8a699fd1145

**Comment by tig** [comment]
Window 3 *is* moving, but for some reason re-draw is not working correctly. You can see this by forcing a redraw by resizing the terminal or moving a scrollbar.

Looking into it now.

**Comment by BDisp** [comment]
Yes, that was what I said above, but it wasn't been repainted or re-draw.
