### ISSUE TITLE
A full-screen `Modal` view should not be movable/sizable

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#3344]
As noted by @BDisp in https://github.com/gui-cs/Terminal.Gui/issues/3342#issuecomment-2010882239_

>`Toplevel` created by the `Application.Init` shouldn't be moveable, otherwise it will behave badly because it represent all the available space on a terminal.

It should also not be sizable (not currently supported, but will be when #2537 is addressed).

This is not just about `Toplevel`s created by `Init`. In the `Adornments` scenario, I do not use `Application.Top` but run the Scenario using `Application.Run (editor)`. The `editor` Toplevel is meant to be full screen... and it behaves badly as @BDisp  noted.

To fix this, I propose modifying the View move/drag code in Adornment (which will be moved to Border asap) to check for `Modal == true && IsFullScreen` and ignoring `Arrangement` if so.

We'll have to figure out what `IsFullScreen` means. It could be something like `if (X == 0 && Y == 0 && Width == Fill && Height == Fill)`

**Comment by BDisp** [comment]
> We'll have to figure out what `IsFullScreen` means. It could be something like `if (X == 0 && Y == 0 && Width == Fill && Height == Fill)`

Well, that depends if the Parent has or not superview. If it doesn't have then it should be `if (X == 0 && Y == 0 && Width == Driver.Cols && Height == Driver.Rows)`

**Comment by tig** [comment]
Wasn't what we thought it was. I had a bug in `OnResizeNeeded`. PR incoming.
