### ISSUE TITLE
SetRelativeLayout doesn't handled with positive/negative location offset.

### ISSUE THREAD

**Issue by BDisp** [gui-cs/Terminal.Gui#3362]
Actually the `LayoutSubview` is passing `GetBoundsOffset ()` location in the parameter but this hasn't no impact on the `SetRelativeLayout ` because this that not handles the location offset (positive or negative). Thus, for now, until the content offset is implemented, is more appropriate to pass an `Point.Empty`.

**Comment by tig** [comment]
I discovered this as part of #3269.

What I figured out is `SetRelativeLayout` has no need to know the location, it just needs the size. Now, in #3269 it looks like this:

```cs
    /// <summary>
    ///     Adjusts <see cref="Frame"/> given the SuperView's ContentSize (nominally the same as
    ///     <c>this.SuperView.ContentSize</c>)
    ///     and the position (<see cref="X"/>, <see cref="Y"/>) and dimension (<see cref="Width"/>, and
    ///     <see cref="Height"/>).
    /// </summary>
    /// <remarks>
    /// <para>
    /// If <see cref="X"/>, <see cref="Y"/>, <see cref="Width"/>, or <see cref="Height"/> are
    /// absolute, they will be updated to reflect the new size and position of the view. Otherwise, they
    /// are left unchanged.
    /// </para>
    /// </remarks>
    /// <param name="superviewContentSize">
    ///     The size of the SuperView's content (nominally the same as <c>this.SuperView.ContentSize</c>).
    /// </param>
    internal void SetRelativeLayout (Size superviewContentSize)

...

    private void LayoutSubview (View v, Size contentSize)
    {
        v.SetRelativeLayout (contentSize);
        v.LayoutSubviews ();
        v.LayoutNeeded = false;
    }
```

This simplifies and clarifies things substantially. I've added a ton of additional unit tests in #3269 that give confidence it's all working correctly.  

I don't recommend we merge your change, and instead focus on ensuring #3269 is ready. It is close!

**Comment by BDisp** [comment]
No worries. I'll close all my PR then. The #3269 was done as is because @dodexahedron saw that the location wasn't used at all and he done well. But now I'm proving that the location can be handled, and must, in the `SetRelativeLayout`. I give up then,

**Comment by BDisp** [comment]
I'm reopen this because I'm convinced that the `SetRelativeLayout` should handled the location offset, although until now it wasn't never used.

**Comment by BDisp** [comment]
Closing this because it is really not necessary for `SetRelativeLayout` to deal with negative locations and it is more than proven with @tig's excellent work in #3323. Thanks.
