### ISSUE TITLE
Must set AutoSize to false before setting Width

### ISSUE THREAD

**Issue by tznind** [gui-cs/Terminal.Gui#3366]
> Must set AutoSize to false before setting Width

I get this exception a lot now when trying to upgrade TGD.  Is it a temporary measure?

It seems like this is an attempt to prevent two conflicting sizing mechanisms (auto and Width).  If it is here to stay then why instead not just make AutoSize a `Dim` e.g.

```csharp
myView.Width = Dim.AutoSize()
// Or
myView.Width = Dim.AutoWidth(myView)
// Or
myView.Width = Dim.AutoSize(myView,width: true)
```

If it were a Dim then it wouldn't be possible to set both, Width would either be auto or other.

Maybe a View has to implement `IAutoSizeable` or something to support this approach.

**Comment by tig** [comment]
This is temporary, but only because AutoSize is going away once I finish `Dim.Auto`.

The reason this is in there now is before AutoSize was not deterministic w.r.t. when/where Height/Width got set.

I refactored the code in #3202 to simplify it ahead of finishing `Dim.Auto`. To make it all understantable I removed all code that tried to allow changes to Width/Height work (it never could be cause of race conditions).

Before setting those properties if AutoSize is on was supposed to work, but didn't really.

Now setting those properties if AutoSize is on is an error.

**Comment by tznind** [comment]
> This is temporary, but only because AutoSize is going away once I finish Dim.Auto.

So the new way to autosize is going to be `Dim.Auto`? Maybe the way for me to progress here would be to just set AutoSize to false anywhere I am setting a Dim property or creating a View.

**Comment by tig** [comment]
> > This is temporary, but only because AutoSize is going away once I finish Dim.Auto.
> 
> So the new way to autosize is going to be `Dim.Auto`? Maybe the way for me to progress here would be to just set AutoSize to false anywhere I am setting a Dim property or creating a View.

The only built-in views that enable AutoSize = true are Button and Label.

**Comment by realChrisDeBon** [comment]
> > > This is temporary, but only because AutoSize is going away once I finish Dim.Auto.
> > 
> > 
> > So the new way to autosize is going to be `Dim.Auto`? Maybe the way for me to progress here would be to just set AutoSize to false anywhere I am setting a Dim property or creating a View.
> 
> The only built-in views that enable AutoSize = true are Button and Label.

So we should set AutoSize to false prior to adjusting Height or Width of either of these elements? My entire application locks up if I tinker with an element's height or width it seems.

**Comment by tig** [comment]
> > > > This is temporary, but only because AutoSize is going away once I finish Dim.Auto.
> > > 
> > > 
> > > So the new way to autosize is going to be `Dim.Auto`? Maybe the way for me to progress here would be to just set AutoSize to false anywhere I am setting a Dim property or creating a View.
> > 
> > 
> > The only built-in views that enable AutoSize = true are Button and Label.
> 
> So we should set AutoSize to false prior to adjusting Height or Width of either of these elements? My entire application locks up if I tinker with an element's height or width it seems.

Correct.
