### ISSUE TITLE
NetDriver sometimes isn't decoding the correct color value

### ISSUE THREAD

**Issue by BDisp** [gui-cs/Terminal.Gui#3377]
**Describe the bug**
`NetDriver` doesn't use the correct color the selected menu bar on Windows and Linux. `WindowsDriver` and `CursesDriver` doesn't have this issue.

**To Reproduce**
1. Open UICatalog
2. Open ASCIICustomButtonTest scenario
3. Click on the Window Size menu bar.
4. The selected menu bar is showing with the Blue/White color

**Expected behavior**
 It should showing with the Black/White

**Screenshots**

![image](https://github.com/gui-cs/Terminal.Gui/assets/13117724/af80252c-1850-4148-9cf5-2f8c6352e0c1)

@tig do you have any idea why this is happening?

**Comment by tig** [comment]
Odd. FWIW, adding a hotkey to `Window Size` changes things:

<img width="208" alt="image" src="https://github.com/gui-cs/Terminal.Gui/assets/585482/5057c2a4-dd90-49ff-bb26-20d8a24b1dfb">

It's not unique to the ASCIIBUttonText scenario.

**Comment by BDisp** [comment]
> It's not unique to the ASCIIBUttonText scenario.

Yes I know. That also happened when I added a menu bar on a toplevel that also has an `AdornmentEditor`.
