### ISSUE TITLE
`Dialog` width sometimes increases before it close.

### ISSUE THREAD

**Issue by BDisp** [gui-cs/Terminal.Gui#3379]
Do this issue is happening to you? Click on the `Toplevel` button and after the `Dialog` is open click on the `Yes` button keeping the button pressed. You'll see that the `Dialog` width increasing before it close.

https://github.com/gui-cs/Terminal.Gui/assets/13117724/3f7f1565-cb3f-432c-8eb7-925371d1522b

_Originally posted by @BDisp in https://github.com/gui-cs/Terminal.Gui/issues/3372#issuecomment-2034543312_

**Comment by tig** [comment]
It's actually the MessageBox code that's broken here. 

The Ready handler needs to call d.LayoutSubviews.

**Comment by BDisp** [comment]
> It's actually the MessageBox code that's broken here.
> 
> The Ready handler needs to call d.LayoutSubviews.

Thanks. It's working well now. I think you was meaning the `Loaded` handler.

**Comment by tig** [comment]
Fixed in #3370.
