### ISSUE TITLE
Title Centering

### ISSUE THREAD

**Issue by raithedavion** [gui-cs/Terminal.Gui#3390]
**Is your feature request related to a problem? Please describe.**
No, i just want the ability to center titles in a Windows/Frame/Modal instead of it always being on the left.

**Describe the solution you'd like**
Title positioning similar to how we can center text (ie: Pos.Center()).  

**Describe alternatives you've considered**
I've considered writing my own class that handles this (inheriting the existing one) and just overriding this piece, but I'm not that familiar with Terminal.Gui so I'm not entirely sure where to look to begin with.  

**Additional context**
None

**Comment by tznind** [comment]
Are you using v1 or v2? The designer has some custom draw code in [Choices Dialog](https://github.com/gui-cs/TerminalGuiDesigner/blob/main/src/UI/Windows/ChoicesDialog.cs) which does centering. 

![shot-2024-04-07_20-28-23](https://github.com/gui-cs/Terminal.Gui/assets/31306100/86e735b5-2a01-40e5-b396-df1e490b5303)

**Comment by raithedavion** [comment]
Version 1.

**Comment by tig** [comment]
In v2 it will be trivial. 

"view.Border.TitleLabel.X = Pos.Center"
