### ISSUE TITLE
View.Dispose doen't call UngrabMouse if MouseGrabView is the view itself.

### ISSUE THREAD

**Issue by BDisp** [gui-cs/Terminal.Gui#3394]
This unit test will fail. The `MouseGrabView` must unset, otherwise the dispose view will be accessible if the mouse is hover it.

```cs
    [Fact]
    [AutoInitShutdown]
    public void MouseGrabView_Is_Set_To_Null_If_A_View_Was_Disposed ()
    {
        var count = 0;
        var view = new View { Width = 1, Height = 1 };
        view.MouseEvent += (s, e) => count++;
        var top = new Toplevel ();
        top.Add (view);
        Application.Begin (top);

        Assert.Null (Application.MouseGrabView);
        Application.GrabMouse (view);
        Assert.Equal (view, Application.MouseGrabView);
        top.Remove (view);
        view.Dispose ();
#if DEBUG_IDISPOSABLE
        Assert.True (view.WasDisposed);
#endif

        Application.OnMouseEvent (new () { X = 0, Y = 0, Flags = MouseFlags.Button1Pressed });
        Assert.Null (Application.MouseGrabView);
        Assert.Equal (0, count);
    }

```

**Comment by tig** [comment]
I think the bug is in the test (and whatever code it emulates in the library).

If someone calls `Application.GrabMouse` it is a bug if they don't call `Application.UnGrabMouse`.

**Comment by BDisp** [comment]
> I think the bug is in the test (and whatever code it emulates in the library).
> 
> If someone calls `Application.GrabMouse` it is a bug if they don't call `Application.UnGrabMouse`.

If `AutoInitShutdown` was used then it will be set to null in `ResetState`. This problem was happening to me when I removed and disposed a view that previously called `GrabMouse`. By moving the mouse, the `MouseGrabView` associated with this view was processed.

**Comment by tig** [comment]
> > I think the bug is in the test (and whatever code it emulates in the library).
> > If someone calls `Application.GrabMouse` it is a bug if they don't call `Application.UnGrabMouse`.
> 
> If `AutoInitShutdown` was used then it will be set to null in `ResetState`. This problem was happening to me when I removed and disposed a view that previously called `GrabMouse`. By moving the mouse, the `MouseGrabView` associated with this view was processed.

I think you need to figure out how to make `Menu` correctly call `Application.UnGrabMouse` since it was who called `Application.GrabMouse`.

**Comment by BDisp** [comment]
> I think you need to figure out how to make `Menu` correctly call `Application.UnGrabMouse` since it was who called `Application.GrabMouse`.

By chance it wasn't the Menu that initially caused me this problem but rather the scroll bar, after it was removed and disposed. During the unit tests, the Mouse also threw the error and I corrected that error. If you want me to remove the code in the Dispose method, please say so.

**Comment by tig** [comment]
I do. By putting it there you are hiding another bug further up the chain.

**Comment by BDisp** [comment]
> I do. By putting it there you are hiding another bug further up the chain.

Done,
