### ISSUE TITLE
Does Terminal.GUI supports aarch64 arhitecture?

### ISSUE THREAD

**Issue by otalado** [gui-cs/Terminal.Gui#3403]
I wonder if Terminal.GUI supports an aarch64 architecture? I am wondering as I tried to run the sample app on Raspberry Pi 5 Bookworm 64bit. It fails with strange errors, but from the errors, I cannot figure out what's the issue.
If it does not, are you planning to support the 64-bit ARM chips anytime in the future?

**Comment by tig** [comment]
If dotnet 8 is supported on that platform Terminal.Gui should work.

Questions for you:

1. What version of Terminal.gui are you trying? 
2. If v1, can you please try v2?
3. What are the "strange errors" you are seeing. It's really hard to help without more details.

Cheers!

**Comment by tznind** [comment]
Not sure about 'Raspberry Pi 5 Bookworm 64bit' specificially, but I have had Terminal.Gui running in Raspbery Pi (both with the UI OS and the console only OS).  See #1697 for various videos of  Terminal.Gui running on raspberry Pi and debugging of mouse in console only install.  Or you can follow this [direct link which shows UICatalog with mouse and keyboard control (YouTube)](https://www.youtube.com/watch?v=H17Vck6w4_c)

**Comment by dodexahedron** [comment]
As long as you compile against AnyCPU or the appropriate platform-specific TFM, you should be able to use it on any hardware and OS capable of running .net 8.

I don't _think_ we have any hardware intrinsics anywhere that would prevent such use, anyway.

**Comment by tig** [comment]
Stale. Closing.
