### ISSUE TITLE
LayoutSubviews should be restricted to the `ContentSize` and not `Viewport.Size`

### ISSUE THREAD

**Issue by BDisp** [gui-cs/Terminal.Gui#3453]
@tig I think this wasn't happening before.

![WindowsTerminal_J3BeGnIiw5](https://github.com/gui-cs/Terminal.Gui/assets/13117724/8fce6d4b-e125-420a-9911-9ceba59f643f)

**Comment by tig** [comment]
> @tig I think this wasn't happening before.
> 

Uncheck `ClearContentOnly` and `ClipContentOnly` I have them on by default to illustrate how they work.

**Comment by tig** [comment]
See the API docs for these here:

https://gui-cs.github.io/Terminal.GuiV2Docs/api/Terminal.Gui.ViewportSettings.html

**Comment by BDisp** [comment]
What I want to get across with this post is that recalculating subview positions should only change when the ContentSize changes and not when the viewport size changes. Of course I'm referring to non-absolute Pos/Dim.

**Comment by dodexahedron** [comment]
That doesn't sound right to me. 🤔 

If something is centered or otherwise relative to anything but top left, its position will change if the viewport changes, no?

**Comment by tig** [comment]
> What I want to get across with this post is that recalculating subview positions should only change when the ContentSize changes and not when the viewport size changes. Of course I'm referring to non-absolute Pos/Dim.

Right you are.

Not sure how that happened or how I missed a unit test for it. I'll fix asap.

**Comment by tig** [comment]
> That doesn't sound right to me. 🤔
> 
> If something is centered or otherwise relative to anything but top left, its position will (or should, anyway) change if the viewport changes, no?

Layout is tied to the "Content Area" which is defined by `View.ContentSize`. A subview with `X = Pos.Center()` will be at the center of `ContentSize.Width`. 

By default `Viewport.Size` is the same as `ContentSize`. In that case, you are right.

However, the whole point of `ContentSize` is to enable a virtual content area that is independent from the `Viewport`. In this scenario, we set `ContentSize` to `60x40` and thus `X = Pos.Center()` should NOT be centered in `Viewport`.

**Comment by tig** [comment]
> > What I want to get across with this post is that recalculating subview positions should only change when the ContentSize changes and not when the viewport size changes. Of course I'm referring to non-absolute Pos/Dim.
> 
> Right you are.
> 
> Not sure how that happened or how I missed a unit test for it. I'll fix asap.

I see what I did. In cleaning up some old `Dim.Auto` code I had in `LayoutSubviews` I goofed. This is correct:

![image](https://github.com/gui-cs/Terminal.Gui/assets/585482/dcdd6a69-d3d1-4151-a4d8-2ecd1f2d3142)

I'll fix this asap and add more unit tests!

![1jQnEjm 1](https://github.com/gui-cs/Terminal.Gui/assets/585482/841aaba6-6335-4982-b5a0-e7cfeec7fc04)

**Comment by dodexahedron** [comment]
> By default `Viewport.Size` is the same as `ContentSize`. In that case, you are right.

Yeah, that was the thought process involved there.

The rest makes sense and sounds good to me, as well. 👍

**Comment by BDisp** [comment]
> I'll fix this asap and add more unit tests!

How about enable `FineCodeCoverage` again? This way we could have statistics on the APIs whose unit tests remain to be created. Of course, we have to exclude unit testing of operating system-specific drivers for now.
