### ISSUE TITLE
Tools (e.g. PS scripts) should not change my prompt

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#3464]
@dodexahedron please don't do this:

![image](https://github.com/gui-cs/Terminal.Gui/assets/585482/45ec13f4-2ac5-4b71-b2ec-e69c125b18bd)

**Comment by dodexahedron** [comment]
What is that you guys are using, by the way? Looks nice.

**Comment by BDisp** [comment]
> What is that you guys are using, by the way? Looks nice.

It's Oh My Posh see https://ohmyposh.dev/.

**Comment by dodexahedron** [comment]
Done in #3465 

Alternate prompts didn't even occur to me, even though I use a custom one on my laptop already. Not sure what the actual thought process was being sticking that in there, the night I wrote that, TBH. 😅

**Comment by dodexahedron** [comment]
Oh I remember. It was based on a powershell "application" I use that does similar stuff, and I had actually meant to leave it out and put it instead behind a flag.

But meh. No need at all anyway. So just took it out all the way.

**Comment by dodexahedron** [comment]
BTW just remove the module or exit the session if you didn't already, and that'll reset. Nothing is saved to your profile or anything.

**Comment by dodexahedron** [comment]
I've already stuck oh-my-posh on 12 different systems I've had to deal with since earlier.

I like. 👍
