### ISSUE TITLE
`Dim.Auto (DimAutoStyle.Text)` confuses `TextFormatter` when `Width` is absoulte and `Height` is auto

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#3469]
- Change `CheckBox`'s constructor to set `Height = Dim.Auto (DimAutoStyle.Text)`
- Checkbox unit tests fail when they shouldn't

![image](https://github.com/gui-cs/Terminal.Gui/assets/585482/73139cbd-1888-4af3-8da0-01fa7e99b3d0)

This test sets Width to an absolute. 

```cs
        var checkBox = new CheckBox
        {
            X = 1,
            Y = Pos.Center (),
            Text = "Check this out 你",
            TextAlignment = Alignment.Centered,
            Width = 25
        };
```

For some reason, this is confusing TextFormatter.

**Comment by tig** [comment]
The bug is here. I knew this was a hack.  ;-)

![image](https://github.com/gui-cs/Terminal.Gui/assets/585482/009217c7-ead2-46ee-8683-9ef0f35397b2)

The root of the issue is `TextFormatter.AutoSize` applies to both width & height. Like `View`, it needs to treat them independently.

There may be another workaround that doesn't require rewriting TextFormatter...

**Comment by tig** [comment]
I found this, and have a workaround in the `PosAlign` scenario in https://github.com/gui-cs/Terminal.Gui/pull/3415

**Comment by BDisp** [comment]
> The root of the issue is `TextFormatter.AutoSize` applies to both width & height. Like `View`, it needs to treat them independently.

It only consider the text direction for the `AutoSize`.
