### ISSUE TITLE
FakeConsole throws System.IndexOutOfRangeException using SetupFakeDriverAttribute.

### ISSUE THREAD

**Issue by BDisp** [gui-cs/Terminal.Gui#3475]
Any attempt to write to the console buffer may throw a `System.IndexOutOfRangeException` exception, because the `SetupFakeDriver` only sets the size of the `Cols` and `Rows` without updating the size of the `FakeConsole` buffer.

![image](https://github.com/gui-cs/Terminal.Gui/assets/13117724/30e26093-12f7-49fa-a24d-dafda6959c41)

**Comment by dodexahedron** [comment]
Just copying the comment I made in the PR, for visibility:

We need to move that (the fake driver) out of the core library anyway.

But that's a relatively low-importance issue with potentially relatively high effort to refactor, so I'm kinda ambivalent as to whether that should be done before or after V2 release.
