### ISSUE TITLE
.NET 8 support for v1.xxx

### ISSUE THREAD

**Issue by cjlotz** [gui-cs/Terminal.Gui#3484]
Any possibility of publishing a package for v1.xxx that adds support for .NET 8.0?

**Comment by tig** [comment]
> Any possibility of publishing a package for v1.xxx that adds support for .NET 8.0?

What's not working?

**Comment by cjlotz** [comment]
I wasn't able to compile the latest v1.16.0 packages when targeting .NET 8.  If this should be possible, I suspect this might be PC related to some recent updates might have broken my .NET installation.

**Comment by tig** [comment]
You were correct; we were only setup to compile with net7.

The library, via nuget, should work fine in a net8 project. But you are right the solution would not compile using the net8 SDK.

- #3486 

... fixes this.
