### ISSUE TITLE
GitHub Project Stuff

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#3487]
> @dodexahedron says:

> A fair amount of important stuff is already here, but yes there are some tweaks that might make life better.

> I would also strongly suggest we have a public project, because a big part of the value of projects is the visibility this all enables. Or we can just make the existing one public and optionally make a private one for internal junk if we want/need to, and even optionally a private repository if we ever need to for whatever.

Done - https://github.com/orgs/gui-cs/projects

> An issue can be a member of more than one project, too, which can be used to keep things shown in public cleaner and more relevant to a consumer's needs/desires for tracking progress. Things like workflows (automatic as well as custom) also can apply regardless of project, and the default/built-in workflows like closing an issue when a PR is merged already do that by default without having to set it up.

We have examples of this now.

> It would also be nice, both for us and the public, to have some more specific but still general milestones defined for general work areas as well as when any large task comes along. Basically, exactly how I've got it in the [project](https://github.com/users/dodexahedron/projects/10) I showed you in the V2 discussion thread. The V2 project is the whole enchilada, and things like "True Color Support," "Cut Curses Crap," and other stuff belong as milestones the issues can also be associated with. That then not only gives a better idea of where effort is going (both for our and consumers' benefit), but can be used in project views, as well, when desired, which I put as notes on the cards in the first 3 tabs of my project and used as an actual grouping for the "[All Linked Items](https://github.com/users/dodexahedron/projects/10/views/4)" tab, which is basically a big consolidated project work listing, for all statuses.  Milestones actually belong to a repository, though (they are a sub-tab in the issues tab), so they can be used independently or in conjunction with projects, at will, which is pretty nice.

Done. E.g. 

![image](https://github.com/gui-cs/Terminal.Gui/assets/585482/c7d63d7e-9845-4782-bb44-3274ded1c5b7)

> Also, does the gui-cs organization have at least a GitHub Teams subscription? If not, I'm willing to front the bill for that for 4 seats (@tig, @BDisp, @tznind, and myself, unless any one of the crew doesn't want/need the extra goodies). Being able to set everyone up as team members with appropriate roles and branch protection would be a nice quality of life win for all of us, among plenty of other little bells and whistles that open up with a paid license level. And we can evaluate how many paid seats are actually still required after the first year, but I'm also willing to do 4 for a second year, too. Though I bet github would be willing to work out a deal, if you haven't already tried that, for at least the owner seat. I don't need any kind of public recognition or mention or anything for that, either. Just want to make life as easy as possible. :)

No. 

![image](https://github.com/gui-cs/Terminal.Gui/assets/585482/d7c6dd92-d4cf-4523-9296-a20a0a7b1bf7)

> Oh, and license levels for org members can be mixed, with it just affecting which features they can and can't use.

> As for actual stuff to do to this project, specifically, I think a good way to approach that is for me to copy the project layout and make a dummy example on my account to use as a sample/proposal/sandbox before actually doing anything significant that would be destructive to what's currently here.

> @dodexahedron edit to add:

> Oh yeah - since replies aren't possible on a draft item, and issues aren't private, I guess just edit this and add input at the bottom for now. A private repository would be handy for that sort of thing but requires Teams licensing. Private _issues_ would be great, too, but github still doesn't have that feature and just tells you to make a private issues-only repository to fake it. 🙄

> But, projects can have issues from multiple repositories, so private issues could still be placed in a public project whenever they need to exist, and wouldn't be visible to anyone who doesn't have access to the private repo, making it mostly seamless after the actual repo is created. There's the private security bug reporting thing, but that's ephemeral and not really the same anyway.

> Also... ugh... don't try to use this interface from a phone browser. It's very difficult to NOT accidentally drag cards...

Other than the `gui-cs` org account, all of this is now done, I think...

**Comment by tig** [comment]
@dodexahedron  can I close this?

**Comment by dodexahedron** [comment]
Yep, good to go I think.

Can always fire up anither if the need arises.
