### ISSUE TITLE
Address issues preventing TGD from being feature complete with V2

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#3490]
This is a tracking issue for ensure we're focused on addressing v2 issues that prevent TGD from functioning properly as a v2 app.

The focus should be on functional, not visual issues. We can tackle visual things later.

I assert this is a V2 Alpha Release Blocker. Happy to debate this.

@tznind Please feel free to either add commentary to this Issue with known issues or create new Issues and set them to the V2 Alpha Project.

**Comment by dodexahedron** [comment]
Alpha nah. Typically API isn't stable til Beta. But that's unimportant.

I want to be sure you know, though, that additional stuff is coming that should be of great benefit to consumers of TG - especially things like TGD. Mostly interfaces and some dedicated consistency review and sync.

And some of it will be pretty quick, too - not talking multi-week complex stuff.

**Comment by tig** [comment]
> Alpha nah. Typically API isn't stable til Beta. But that's unimportant.

See the new Alpha Project. I think we are aligned.

> I want to be sure you know, though, that additional stuff is coming that should be of great benefit to consumers of TG - especially things like TGD. Mostly interfaces and some dedicated consistency review and sync.
> 
> And some of it will be pretty quick, too - not talking multi-week complex stuff.

Hope so! I'm really keen on being laser focused on two things:

- Getting TGD in to shape with v2
- Making v2_develop be the primary branch (addressing all the stuff required per #2699).

**Comment by tig** [comment]
TGD related PR:

- https://github.com/gui-cs/TerminalGuiDesigner/pull/189

**Comment by tig** [comment]
We should find all places in TGD where reflection is used to get to the internals of TG and open an Issue for each to address.

- `PosExtensions`
- `DimExtensions`
- `ColorSchemes` - `TGD.FindDeclaredColorScheme`
- `ViewExtensions`

etc...

**Comment by dodexahedron** [comment]
I'm not seeing that draft issue I posted for the interface stuff. 🤔

**Comment by dodexahedron** [comment]
A thought:

Am I on all existing projects after you did all that lovely reorganization?

**Comment by tig** [comment]
> A thought:
> 
> Am I on all existing projects after you did all that lovely reorganization?

There's only one now: https://github.com/orgs/gui-cs/projects/5

**Comment by tig** [comment]
Closing as dupe of #3650
