### ISSUE TITLE
Finish `Dim.Auto (Content)`

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#3499]
This puppy is not really finished:

- https://github.com/gui-cs/Terminal.Gui/pull/3451

`DimAutoStyle.Content` sorta works. Needs moar. This issue is to track.

**Comment by tig** [comment]
I appreciate you doing this, but there is a LOT going on in those tests. Is there any way you can simplify them down to more precise cases? If not, that's ok... but it would make my life a lot easier.

**Comment by BDisp** [comment]
Basically in each test, using `DimAutoStyle.Auto`, I am testing 3 views, where the first does not use the maximum value, the second uses an absolute value and the third uses `Fill`. In the first test I am using `ContentSize` and in the second I am using `Text`, where `view2.TextDirection = TextDirection.TopBottom_LeftRight`. Practically the tests pass as expected and the only exception is in the second test, using `Text`, in the view that is using `Fill`, it does not respect the width of the superview (40), returning `Text.Length` (35). I didn't want to use `Theory` to avoid complicating things and making it simpler.
