### ISSUE TITLE
`Ctrl+Z` not suspending

### ISSUE THREAD

**Issue by Bigsby** [gui-cs/Terminal.Gui#3512]
** Describe the bug**
`Ctrl+Z` not working in version `2.0.0-pre.`

**To Reproduce**
```cs
using Terminal.Gui;

static class Program
{
    class MainWindow : Toplevel
    {
        Label label;
        public MainWindow()
        {
            label = new Label
            {
                Text = "Hello, world!"
            };
            Add(label);
        }
    }

    static void Main(string[] args)
    {

        Application.Init();
        try
        {
            Application.Run<MainWindow>().Dispose();
        }
        finally
        {
            Application.Shutdown();
        }
    }
}

```
**Expected behavior**
When `Ctrl+Z` is pressed, the `app` should be suspended and returned to last state, when brought to foreground (`fg`).

**Desktop (please complete the following information):**
 - OS: macOS 14.4.1
 - Terminal: Terminal and iTerm2
 - Version: Terminal.Gui v2.0.0-pre.949

**Additional context**
This works fine in version `1.16.0`. I tried to test against the first `pre` versions of `2.0.0` and:
*** version <=`2.0.0-pre.231` ***
  - `Ctrl+Z` works always first time, but:
  - when returning to the `app`, `Ctrl+Z` and `Ctrl+Q` (`QuitKey`) don't work;
  - keyboard input is echoing
  - after exiting with `Ctrl+C`, mouse movements output *stuff* to the terminal.
 
*** version >= `2.0.0-pre.232` ***
  - `Ctrl+Z` does nothing.  
  - `OnKeyDown` is called.
 ```cs
        public override bool OnKeyDown(Key keyEvent)
        {
            label.Text = $"Keydown {keyEvent}";
            if (keyEvent == Key.Esc)
                Application.RequestStop();
            if (keyEvent == Key.Z.WithCtrl)
            {
                label.Text += " is Z with Ctrl";
                return false;
            }
            if (keyEvent == Key.Q.WithCtrl)
            {
                label.Text += " is Q with Ctrl";
                return false;
            }
            return true;
        }
```
if the code above is added to `MainWindow`, `Ctrl+Q` (`QuitKey`) is bubbled and Application exits but `Ctrl+Z` just updates `label.Text`.

**Comment by tig** [comment]
Why do you use Suspend? (I'm just curious).

**Comment by BDisp** [comment]
@tif the Unix system has the functionality to suspend a certain application in the terminal by pressing Ctrl+Z. Allows you to execute commands, etc. To return to the application, type fg.
See here https://fsl.fmrib.ox.ac.uk/fslcourse/unix_intro/job.html

**Comment by dodexahedron** [comment]
It's a common use case. Even today with tabs and such, it's still often more convenient to just suspend and resume unless you thought ahead to tmux immediately or something.

While there's precedent for it not necessarily being just ctrl-z[^1], it's best to keep it standard, at least as default. If the user wants to override, let them.

[^1]: For example, nano on some distros ships with the sequence being ctrl-T,Z.

**Comment by Bigsby** [comment]
> Why do you use Suspend? (I'm just curious).

As others commented, it is a common workflow for the *nix CLI crowd. Very common when editing files in terminal-based editors (e.g., [Neo]Vim, Nano). Something like:
1. Open file in editor
2. Change file and save
3. Suspend (`Ctrl+Z`) editor (*background it*)
4. Test
6. Foreground editor
7. If test is good, close editor, else, back to 2.

**Comment by Bigsby** [comment]
I could swear it did. More testing to do then.

**Comment by tig** [comment]
> @Bigsby FYI on the v2, Ctrl+Q key doesn't Quit an application anymore. Now it's the Esc key.

Actually, Ctrl-Q is still the default. The UICatalog config.json overrrides it.

I DO want to change the default to Esc though for v2!
