### ISSUE TITLE
Enable Views to expose "Design Time" default data?

### ISSUE THREAD

**Issue by tznind** [gui-cs/Terminal.Gui#3522]
By default, many Views have no good visual representation unless set with "data". E.g. `ListView`, `RadioGroup`, and `Slider`.

This Issue is to come up with a design and implementation that allows a "designer" (TGD) or "tester" (AllViewsTester/Unit Tests) component to say to a View "Hey, go into a good demo mode".

My current (probably lame) thinking is we'd do this by defining an interface that a View that supports such a thing could implement:

```cs
public interface ISupportsDesignMode
{
   // Call this to tell the View to load "demo data" 
   public bool LoadDemoData ();
}
```
 
## Background

Slider<> is doing strange things when setting it's `Text` property.

```csharp


    [Test]
    public void TestTextSliderString()
    {
        var s = new Slider<string>();
        ClassicAssert.IsEmpty(s.Options);

        var s2 = new Slider<string>();
        s2.Text = "I've got a lovely bunch of coconuts";
        ClassicAssert.IsEmpty(s2.Options);
    }
```

`Text` should be completely independent from `Options`.

It seems `Text` setter is putting data into `Options`.  This is problematic for many reasons.  It happens also with the `<int>` generic.  Notice how if you reverse the properties it will have different result.  

- Set Text first and you can overwrite with Options
- Set Options first and Text overwrites completely the Options

```csharp

    [Test]
    public void TestTextSliderInt()
    {
        var o = new SliderOption<int>("hi", new System.Text.Rune('d'), 32);
        var s1 = new Slider<int>
        {
            Text = "fff",
            Options = new List<SliderOption<int>> { o }
        };

        Assert.That(s1.Options.Single(), Is.EqualTo(o));

        var s2 = new Slider<int>
        {
            // When order is reversed
            Options = new List<SliderOption<int>> {o },
            Text = "fff",
        };

        // It fails
        Assert.That(s2.Options.Single(),Is.EqualTo(o));
    }
```

**Comment by tig** [comment]
I wanted Slider to work in AllViewsTester so I made setting `Text` to a comma delimited string equivalent to setting `Options`.

Feel free to undo this, but I'd live ideas on how to make AllViewsTester support causing Views to be "useful/visible" without having custom logic per-view. 

I did the same thing to `RadioGroup`.

**Comment by tznind** [comment]
Hmn, I don't think `Text` should be the place for this.  It looks like a `string` but it behaves like a method.  

In general I think properties are not the place for non deterministic behaviours.

Consider the following example:

```csharp
    [Test]
    public void TestTextSliderString()
    {
        var s1 = new Slider<string>();
        var s2 = new Slider<string>();
        s2.Text = "I've got a lovely bunch of coconuts, here they are sitting in a row!";
     
        // This line does not do what it looks like
        s1.Text = s2.Text;

        TestContext.Out.WriteLine("Options:" + s1.Options.Count); //2
        TestContext.Out.WriteLine("Options:" + s2.Options.Count); //6!

        ClassicAssert.IsTrue(s1.Options.Count == s2.Options.Count );
    }
```

**Comment by BDisp** [comment]
I think the `Text` and `Title` properties should be independent and have no relationship between them. By default, `Text` will be drawn inside the view, with the exception of custom drawing. The `Title` should only be used when a view has a border and is not an empty string.
