### ISSUE TITLE
v2: Button alignment in MessageBox is no longer centered

### ISSUE THREAD

**Issue by fergusonr** [gui-cs/Terminal.Gui#3523]
2.0.0-pre.1491 MessageBox buttons are aligned to the right. They were previously centred. 

If this is a v2 style change, then perhaps we should have a Query() method signature with a ButtonAlignment parameter
```CSharp
MessageBox.Query(50, 7, "Quit?", "Are you sure you want to quit?", 0, "Yes", "No");
```

![MessageBox](https://github.com/gui-cs/Terminal.Gui/assets/17233550/6ce5597f-3dc8-4ae4-bc55-9d22a4b0c4d0)

**Comment by tig** [comment]
With POS.Align I was experimenting with layouts. I forgot I left this in. 

For v2 I want to do two things:

Change the defaults from v1 to make the look and feel distinct. 

Make it configurable (MB and Dialog can/should be different).

**Comment by tig** [comment]
And I mean configurable via CM. Not api.

**Comment by fergusonr** [comment]
> And I mean configurable via CM. Not api.

Great thanks.
