### ISSUE TITLE
Allow to set Contents to dirty to just refresh the screen.

### ISSUE THREAD

**Issue by BDisp** [gui-cs/Terminal.Gui#3525]
There are situations in which it is not necessary to perform the views layout and redrawing, but just set the `Contents` to dirty to update only the screen, improving the performance.

**Comment by tig** [comment]
I don't understand what scenarios you are referring to. Can you please explain a specific situation where this would come into play?

**Comment by BDisp** [comment]
> I don't understand what scenarios you are referring to. Can you please explain a specific situation where this would come into play?

This is related with the PR #3515 for to be used on the `Suspend` method. Above there is already a commit https://github.com/BDisp/Terminal.Gui/commit/9297d05c131f639c2c95f7cfdab74f0f713e19eb that references that.

**Comment by BDisp** [comment]
This was already fixes on #3515 and merged.
