### ISSUE TITLE
Checking if clipboard is available on windows

### ISSUE THREAD

**Issue by MaciekWin3** [gui-cs/Terminal.Gui#3541]
**Describe the bug**
I am developing a simple password manager in F# and I noticed that after rebooting or taking a screenshot, all of a sudden I can't access the clipboard from my app. When I checked what the issue was, I discovered that the `IsSupported` field from `Clipboard` class is false, which results in not being able to access or set data in the clipboard. In the Windows implementation, checking if the clipboard is supported is based on this piece of code:

```csharp
private const uint CF_UNICODE_TEXT = 13;

public override bool IsSupported { get; } = IsClipboardFormatAvailable (CF_UNICODE_TEXT);

...

[DllImport ("User32.dll", SetLastError = true)]
[return: MarshalAs (UnmanagedType.Bool)]
private static extern bool IsClipboardFormatAvailable (uint format);
```
So basically, we are checking if the current format of the clipboard is UnicodeText, not if the clipboard is available on the given platform.

So whenever I take a screenshot and then run my app (which uses clipboard functionality from Terminal.Gui) on a Windows device, it stops working as intended.

Also, I think it is worth mentioning that if app already runs and I take a screenshot, everything works as intended.

I tried this simple workaround which seems to work fine, but before submitting a PR, I wanted to confirm that I am not overlooking some edge cases:
```csharp
private static bool IsClipboardAvailable ()
{
    if (OpenClipboard (default))
    {
        CloseClipboard ();
        return true;
    }

    return false;
}
```

**To Reproduce**
If you want to reproduce this issue you can try it using my [app](https://github.com/MaciekWin3/TermKeyVault). Try copying a password to the clipboard after a PC reboot or after taking a screenshot.

**Comment by BDisp** [comment]
I think there is no bug here. From what I understand, you copy text to the clipboard and after the reboot the clipboard is reset and it does not contain any value. The other situation is that you copy text to the clipboard and then take a screenshot and of course the text is no longer on the clipboard but the screenshot is. If you try to do the same with Notepad you also get the same result, because the image is not compatible with text.
I haven't really tested it yet, but normally when I use the clipboard it always uses the most recent content, but if it's possible to get a list of the clipboard content so we can select what we want, that's new to me.

**Comment by MaciekWin3** [comment]
> From what I understand, you copy text to the clipboard and after the reboot the clipboard is reset and it does not contain any value. The other situation is that you copy text to the clipboard and then take a screenshot and of course the text is no longer on the clipboard but the screenshot is. If you try to do the same with Notepad you also get the same result, because the image is not compatible with text.

You are right. However, what I meant is that, for example, after a PC reboot, when I try to copy text to the clipboard using `Clipboard.TrySetClipboardData`, it fails as there is no unicode text there so `IsClipboardFormatAvailable` and `IsSupported` property both return false. I think the intended behavior when the clipboard is empty is to copy text from Terminal.Gui app to the clipboard. This is the use case that bothers me the most.

**Comment by BDisp** [comment]
> You are right. However, what I meant is that, for example, after a PC reboot, when I try to copy text to the clipboard using `Clipboard.TrySetClipboardData`, it fails as there is no unicode text there so `IsClipboardFormatAvailable` and `IsSupported` property both return false. I think the intended behavior when the clipboard is empty is to copy text from Terminal.Gui app to the clipboard. This is the use case that I am facing in my app.

So in this case just use the following:

`Clipboard.Contents = "your text";`

**Comment by tznind** [comment]
I think he is saying that once printscreen is used then copy to clipboard fails from then on - not that the clipboard text is being overwritten

**Comment by BDisp** [comment]
Now I got it, sorry. I was doing a print screen after open the Terminal.Gui. Now opening the app after the print screen I confirm now that this is bugged for sure.

**Comment by MaciekWin3** [comment]
> I think he is saying that once printscreen is used **before app starts** then copy to clipboard fails from then on - not that the clipboard text is being overwritten.

Yes, that is what I meant
