### ISSUE TITLE
When adding more than one Window + TextView together with a MenuBar, the displayed text changes to the text of the first added Window

### ISSUE THREAD

**Issue by luizfernandonb** [gui-cs/Terminal.Gui#3545]
**Describe the bug**
When more than one `Window` is added together with a `TextView` and a `MenuBar` is also added, when hovering the mouse over the console the text displayed is that of the first `Window` added
I don't know if I explained it correctly, sorry

**To Reproduce**
The code below shows the bug:
```C#
using Terminal.Gui;

Application.Init();

var menuBar = new MenuBar
{
    Menus =
    [
        new()
        {
            Title = "Foo",
            Children =
            [
                new()
                {
                    Title = "Bar",
                },
            ]
        },
    ],
};

foreach (var arg in new[] { "1", "2" })
{
    var win = new Window()
    {
        Title = arg,
    };

    var editor = new TextView()
    {
        Width = Dim.Fill(),
        Height = Dim.Fill(),
        Text = arg
    };

    win.Add(editor);

    Application.Top.Add(win);
}

Application.Top.Add(menuBar);
Application.Run();
Application.Shutdown();
```

**Expected behavior**
The same thing is expected to happen when the `MenuBar` is not added (Just comment on `Application.Top.Add(menuBar)`), the text displayed is that of the last Window added and when hovering the mouse over it, the text remains the same

**Screenshots**
When starting the program:
![image](https://github.com/gui-cs/Terminal.Gui/assets/42288418/0ded160f-9f80-42dc-9b67-2b6da21ee6aa)

After hovering the mouse over the console:
![image](https://github.com/gui-cs/Terminal.Gui/assets/42288418/eb17ee6f-b8f8-4a4e-bfce-9d2df7917722)

**Comment by BDisp** [comment]
Thank you for presenting this issue. From what I noticed there is a contradiction in how views are drawn and how views are focused.
The `FocusFirst` instruction is trying to focus on the first focusable view but the drawing is drawing the last visible view which will be overlapped. It turns out that the most focused view does not correspond to the focused superview and this is incorrect.

**Comment by luizfernandonb** [comment]
> I changed the code to allowing toggling between windows.

I was able to change between windows using `Ctrl + Tab`, the problem was only when the mouse passed over the console after the first launch, which is the bug I described

**Comment by BDisp** [comment]
> I was able to change between windows using `Ctrl + Tab`, the problem was only when the mouse passed over the console after the first launch, which is the bug I described

I know that through the keyboard you can switch between windows, but the bug was due to an improper focus in the `Application.Begin` method and the `CanFocus` property. Please test with PR #3548 and check if it is working properly. Thanks.
