### ISSUE TITLE
v2: Big performance impact on ListView/ComboBox's that contain a lot of items

### ISSUE THREAD

**Issue by fergusonr** [gui-cs/Terminal.Gui#3551]
2.0.0-pre.1588 On lists with a lot of items (4k) the code below when selecting an item from the combo, takes 8 seconds to close the dialog
 
**Expected behavior**
2.0.0-pre.1491 the dialog close is instantaneous

Maybe something to do with ObservableCollection firing events for every item on close?

```CSharp
Application.Init();

var list = new List<string>();

for (int i = 0; i < 4000; i++)
	list.Add($"item{i}");

var combo = new ComboBox() { Width = Dim.Fill(), Height = Dim.Fill() };
combo.SetSource(new ObservableCollection<string>(list));
combo.OpenSelectedItem += (object sender, ListViewItemEventArgs e) => Application.RequestStop();

var dialog = new Dialog() { Title = "Main", Width = Dim.Percent(40), Height = Dim.Percent(50) };
dialog.Add(combo);
Application.Run(dialog);

MessageBox.Query("Selected", combo.Text);

Application.Run();
Application.Shutdown();
```

**Comment by BDisp** [comment]
Thanks for reporting this. I'll fix that. I advice to put `Application.Top.Dispose()` before the `Application.Shutdown()`. Thanks.

**Comment by fergusonr** [comment]
Great, thanks!

**Comment by BDisp** [comment]
Done with #3552.
