### ISSUE TITLE
`Dim.Auto (Content)` is broken if subviews use `Pos.Center` etc...

### ISSUE THREAD

**Issue by BDisp** [gui-cs/Terminal.Gui#3567]
![WindowsTerminal_DGKWnv3Fhi](https://github.com/gui-cs/Terminal.Gui/assets/13117724/373e6472-3968-49e3-b67f-53f90783a741)

**Comment by tig** [comment]
Yes. 

I'm working on it.

**Comment by tig** [comment]
Dupe of #3499

**Comment by dodexahedron** [comment]
> Dupe of #3499

Ok, I wasn't going crazy then haha. I _knew_ I had seen this brought up before. 😅
