### ISSUE TITLE
v1 - Example.cs does not work

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#3579]
### Discussed in https://github.com/gui-cs/Terminal.Gui/discussions/3578

<div type='discussions-op-text'>

<sup>Originally posted by **hsnprojects** July  2, 2024</sup>
Example.cs app runs, but after logging in it cannot retrieve usernameText field because Application.Top is null.</div>

**Comment by BDisp** [comment]
@tig something went wrong here. In the v2_develop the code isn't the same as your pull request.

https://github.com/gui-cs/Terminal.Gui/blob/716ac3177fac1b15f12db51c52d05fcc154bcc87/Example/Example.cs#L6-L16

**Comment by tig** [comment]
I only updated develop. It should not have impacted v2.

**Comment by BDisp** [comment]
> I only updated develop. It should not have impacted v2.

Ops sorry I thought it was on v2. On v2 it doesn't output to the screen because the write is called before shutdown.

**Comment by tig** [comment]
> > I only updated develop. It should not have impacted v2.
> 
> Ops sorry I thought it was on v2. On v2 it doesn't output to the screen because the write is called before shutdown.

Yeah, we should fix that.

**Comment by BDisp** [comment]
> Yeah, we should fix that.

Done it [here](https://github.com/gui-cs/Terminal.Gui/pull/3582/commits/594921b3df9a8f9d8ac181536b3da2b60917cd1b).
