### ISSUE TITLE
`DateField` unit tests fail on `macos.latest`

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#3592]
See https://github.com/gui-cs/Terminal.Gui/actions/runs/9831020519/job/27137868075#step:7:6759

@BDisp Can you look into this since you have more familiarity with the culture stuff than I?

**Comment by BDisp** [comment]
I have to find out which culture he is failing. It looks like at least one is failing on macOS (zh-CN/zh-TW). But I'll have to debug on macOS to confirm.

**Comment by tig** [comment]
> I have to find out which culture he is failing. It looks like at least one is failing on macOS (zh-CN/zh-TW). But I'll have to debug on macOS to confirm.

It's easy to tweak `dotnet-core.yml` to run on macos now...

**Comment by tig** [comment]
Hopefully you saw that I disabled the unit test from running on macos:

![image](https://github.com/gui-cs/Terminal.Gui/assets/585482/a10d2389-6dfb-4b0a-b97d-bbed6474432e)

**Comment by dodexahedron** [comment]
> > I have to find out which culture he is failing. It looks like at least one is failing on macOS (zh-CN/zh-TW). But I'll have to debug on macOS to confirm.
> 
> It's easy to tweak `dotnet-core.yml` to run on macos now...

Tests can also be specified to run in more than one culture.

That's something I'll stick on my todo list for #3558 since that's a pretty logical place for it.
