### ISSUE TITLE
Focus gets confused with `ContextMenu`. 

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#3635]
Via @bdisp:

There is a strange behavior with the `ContextMenu`. Open the ContextMenus scenario and right click on the first `TextField`. Then click on another `TextField` and click again on the first one and the cursor isn't showing. If you double click the text will be selected but only clicking doesn't set the cursor on the first `TextField`. But the cursor is always showing on the other `TextField` you clicked.

This repros on v2_develop.

_Originally posted by @tig in https://github.com/gui-cs/Terminal.Gui/issues/3634#issuecomment-2266056084_

**Comment by BDisp** [comment]
This was partially fixed when navigating with the keyboard navigation but with mouse it still has the issue.
