### ISSUE TITLE
Overlapped broken on the v2_develop branch using the BackgroundWorkerCollection scenario.

### ISSUE THREAD

**Issue by BDisp** [gui-cs/Terminal.Gui#3636]
### Here is some of the issues after opening the scenario:
- After pressing F9 to open the `MenuBar` the keys navigations doesn't. Only work with mouse.
- After opening `MenuBar->View->WorkerApp` pressing F9 to opening the `MenuBar` the menu isn't position correctly. See image:

![image](https://github.com/user-attachments/assets/8426faf1-3472-431a-96a9-40888b616d67)

- Press enter do Run Worker, again for Start and wait until the result `Work list:` is open. Press again F9 to open the `MenuBar` and again the menu isn't position correctly. Seems that the application assumes that the `MenuBar` is on the focused view (`OverlappedChildren`) and not on the `Application.OverlappedTop`.
- Close the opened `Work list:` by clicking the `Close` button and an exception is throwed. See image:

![image](https://github.com/user-attachments/assets/682f3f98-ff90-46d2-b270-7707e39a97d1)

- Another situation is when pressing F9 to open the `MenuBar` and we click outside the menu on another toplevel, the menu stays opened and it must be closed to allows selecting the other toplevel.

https://github.com/user-attachments/assets/c5c6b9a6-abd6-4b7a-a256-6734fcb3c5a0

**Comment by BDisp** [comment]
@tig maybe you can fix this in the #3634?

**Comment by tig** [comment]
> @tig maybe ou can fix this in the #3634?

`BackgroundWorkerCollection` will need to be rewritten with #3634. I do not understand the logic of that Scenario after hours of studying it. Maybe it's because threading confuses me in general. 

What I would prefer is for you to rewrite it. I will let you know when progress on #3634 is far enough long for you to do this.

**Comment by BDisp** [comment]
> `BackgroundWorkerCollection` will need to be rewritten with #3634. I do not understand the logic of that Scenario after hours of studying it. Maybe it's because threading confuses me in general.
> 
> What I would prefer is for you to rewrite it. I will let you know when progress on #3634 is far enough long for you to do this.

If it's to rewrite as a `Toplevel` with `Window` as subviews I prefer to delete it at all, because it uses a different methodology. You need to distinguish overlapped subviews from overlapped toplevels. The threading has nothing to do with the issues. `MenuBar` has bugs. It seems sometimes that an open menu is hidden but not effectively closed which will cause navigation behaviors issues.

**Comment by tig** [comment]
> > `BackgroundWorkerCollection` will need to be rewritten with #3634. I do not understand the logic of that Scenario after hours of studying it. Maybe it's because threading confuses me in general.
> > What I would prefer is for you to rewrite it. I will let you know when progress on #3634 is far enough long for you to do this.
> 
> It it's to rewrite as a `Toplevel` with `Window` as subviews I prefer to delete it at all, because it uses a different methodology. You need to distinguish overlapped subviews from overlapped toplevels. The threading has nothing to do with the issues. `MenuBar` has bugs. It seems sometimes that an open menu is hidden but not effectively closed which will cause navigation behaviors issues.

Do you agree we need a good multi-threading example for v2.

**Comment by tig** [comment]
> > > `BackgroundWorkerCollection` will need to be rewritten with #3634. I do not understand the logic of that Scenario after hours of studying it. Maybe it's because threading confuses me in general.
> > > What I would prefer is for you to rewrite it. I will let you know when progress on #3634 is far enough long for you to do this.
> > 
> > 
> > It it's to rewrite as a `Toplevel` with `Window` as subviews I prefer to delete it at all, because it uses a different methodology. You need to distinguish overlapped subviews from overlapped toplevels. The threading has nothing to do with the issues. `MenuBar` has bugs. It seems sometimes that an open menu is hidden but not effectively closed which will cause navigation behaviors issues.
> 
> Do you agree we need a good multi-threading example for v2.

Oh, and I meant https://github.com/gui-cs/Terminal.Gui/issues/2491 when I wrote #3634 above.

**Comment by BDisp** [comment]
> Do you agree we need a good multi-threading example for v2.

The Threading scenario was created more for the threading examples. The BackgroundWorkerCollection was created to demonstrate more the MDI concept now called Overlapped. But I understand that the overlapped feature can work well with both concepts, although with different code:
- With overlapped top and overlapped childs.
- With overlapped top and subviews.

**Comment by tig** [comment]
Closing.

I've added ensuring we have a good "Multiple overlapped, MDI-like views" example in #2491.
