### ISSUE TITLE
Ctrl-Q Closes Application

### ISSUE THREAD

**Issue by JessicaK908** [gui-cs/Terminal.Gui#3654]
**Describe the bug**
Ctrl-q closes out the application.

**To Reproduce**
Run debugger. Press ctrl-q.

**Expected behavior**
Application closes.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro - 22H2 - 19045.4717
 - Debugger: Visual Studio
 - Version: 2022

**Smartphone (please complete the following information):**
n/a

**Additional context**
I'm trying to assign this hotkey to a function, and it keeps closing out, instead of running the function.

**Comment by BDisp** [comment]
What Terminal.Gui version do you are using? If it's v2 then it only close with the Esc key.

**Comment by tznind** [comment]
If you do not want Ctrl+Q to exit you can just rebind or unbind the `Application.QuitKey`

e.g.

```csharp
// Or add any other key
Application.QuitKey = Key.Null;
```

**Comment by JessicaK908** [comment]
> What Terminal.Gui version do you are using? If it's v2 then it only close with the Esc key.

1.17.1

**Comment by JessicaK908** [comment]
> If you do not want Ctrl+Q to exit you can just rebind or unbind the `Application.QuitKey`
> 
> e.g.
> 
> ```cs
> // Or add any other key
> Application.QuitKey = Key.Null;
> ```

That took care of it. Thank you.

**Comment by BDisp** [comment]
Sorry I didn't saw the `Additional context` before. So I think this is already clarified. If something persist with this issue, please reopen.

**Comment by JessicaK908** [comment]
> Sorry I didn't saw the `Additional context` before. So I think this is already clarified. If something persist with this issue, please reopen.

No worries. I appreciate it still. It got solved, and I am finding this package fin to play with. I did have one other issue that was connected with this. (I use alt-q to close out the entire application (which threw this), and I didn't notice is was ctrl-q until after I mapped another method to it. (Blaming my exit method used with alt-q.) I coded the TUI to launch the console by Application.Shutdown() and calling another method for the console that would recall the TUI via the start TUI method again when it received the command (if ReadLine() == "exit") to exit. If I used that way of closing it, it would throw a NullReferenceException. (Not a major issue as it happens when it suppose to close anyway...) It would only do it after calling the closing the console, and this issue doesn't happen when I use my hotkey which is coded to use a method that calls Application.Shutdown() and follows with Environment.Exit(0). I wouldn't worry about it too much for now. It isn't a major issue for this project, but I could see it becoming an issue for any future projects. Once again, thank you.

**Comment by BDisp** [comment]
If you are calling `Application.Shutdown()` to exit the app then you are doing it wrong because this method must only be calling after the `Application.Run` is exit, after calling the `Application.RequestStop()` and then call the the first mentioned method.

**Comment by tznind** [comment]
If you are using a regular console app then switching to and fro from Tui you will need to make sure to pair your `Init` with `Shutdown`.  Before you can relaunch Tui you need a new `Application.Init` call.

If you are just closing a popup window witin app then it would be `Application.RequestStop()`
