### ISSUE TITLE
v2: Keyboard navigation on MessageBox no longer working

### ISSUE THREAD

**Issue by fergusonr** [gui-cs/Terminal.Gui#3655]
2.0.0-v2-develop.2164
Keyboard navigation of messageBox buttons no longer works. Left/right arrows do not navigate buttons

**Reproduce**
```CSharp
MessageBox.Query(50, 7, "Quit?", "Are you sure you want to quit?", 0, "Yes", "No");
```
**Expected behavior**
![messageBox](https://github.com/user-attachments/assets/12c83031-8d98-4094-9730-2a614994f636)

**Comment by tig** [comment]
On it.  Thanks!

**Comment by fergusonr** [comment]
All good now. thankyou!
