### ISSUE TITLE
Null reference in v2 in FindDeepestView

### ISSUE THREAD

**Issue by tznind** [gui-cs/Terminal.Gui#3667]
**Describe the bug**
`FindDeepestView` can crash when a view has null Margin e.g. MenuBar (in below code `start` is a `MenuBar`
![image](https://github.com/user-attachments/assets/59959a98-d548-4da3-b61e-918154a14f51)

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Terminal.Gui
  StackTrace:
   at Terminal.Gui.View.FindDeepestView(View start, Point& location) in Terminal.Gui\View.cs:line 2160
```

**Comment by tig** [comment]
The only way this can happen is if `BeginInit/EndInit` was not called on `start`.

**Comment by tig** [comment]
> The only way this can happen is if `BeginInit/EndInit` was not called on `start`.

I take that back. That's old/fake news.

It should not be possible for those to be null if the View constructor was called:

```cs
    public View ()
    {
        SetupAdornments ();
        SetupKeyboard ();

        //SetupMouse ();
        SetupText ();
    }

    private void SetupAdornments ()
    {
        //// TODO: Move this to Adornment as a static factory method
        if (this is not Adornment)
        {
            Margin = new (this);
            Border = new (this);
            Padding = new (this);
        }
    }
```

... Unless the View was disposed...

```cs
    private void DisposeAdornments ()
    {
        Margin?.Dispose ();
        Margin = null;
        Border?.Dispose ();
        Border = null;
        Padding?.Dispose ();
        Padding = null;
    }
```

**Comment by BDisp** [comment]
For sure is that the case. View was already disposed.

**Comment by tznind** [comment]
Indeed the view being disposed is the bug.  Bug originates in TopLevel which seems to have code that dispose the view on `Remove`.  

`Remove` is not the same as getting rid of.  There are many cases where you might want to remove a view e.g. to add it to a different view. It should not dispose things.

```csharp
    [Fact]
    public void no_dispose_menu ()
    {
        var mb = new MenuBar ();
        var tl = new Toplevel ();

        Assert.False (mb.WasDisposed);
        tl.Add (mb);
        Assert.False (mb.WasDisposed);
        tl.Remove (mb);
        Assert.False (mb.WasDisposed);
    }
```
