### ISSUE TITLE
Mac Error - Error opening terminal: unknown.

### ISSUE THREAD

**Issue by wobbet** [gui-cs/Terminal.Gui#3672]
**Describe the bug**
Created a basic Program.cs with the ExampleWindow example from the website.

I've added a reference to the latest develop version of the NuGet library (2189) to my .csproj file.

When running the app I get a message in the debug console saying "Error opening terminal: unknown."

**To Reproduce**
1. Created empty project file 
2. Added reference to latest NuGet library
3. Added ExampleWindow to my Program.cs file and invoked it

**Expected behavior**
The example app runs w/o error

**Screenshots**
<img width="905" alt="image" src="https://github.com/user-attachments/assets/952911b7-6de7-4d9d-a8e4-3da11e2b1e3a">

**Desktop (please complete the following information):**
 - Device: MacBook Pro 16" w/ M3 Pro
 - OS: macOs 15
 - Browser N/A
 - Version N/A
 - .NET Core 8
 - VS Code

**Additional context**
Went debugging into the code and finally came to binding.cs in the CursesDriver. The error is emitted by the call to         `main_window = new Window (methods.initscr ());` from inside of the `initscr` method. 

No exceptions are thrown.

What am I doing wrong?

**Comment by tig** [comment]
Share your code please.

**Comment by wobbet** [comment]
[Manager.zip](https://github.com/user-attachments/files/16665230/Manager.zip)

Minimal example that gives the error...

**Comment by BDisp** [comment]
I think the cause is due you aren't using the `console` configuration on the `launch.json`.

`"console": "externalTerminal"`
or
`"console": "integratedTerminal"`

**Comment by wobbet** [comment]
I need more coffee... thank you.

**Comment by dodexahedron** [comment]
Mmmmmm... Stimulants. 🤤 

Programmer fuel.
