### ISSUE TITLE
Proposal: Add `Shortcuts` collection to `StatusBar`.

### ISSUE THREAD

**Issue by dasien** [gui-cs/Terminal.Gui#3697]
I would like to propose a collection in the v2 `StatusBar` similar to the one that was in v1 and to what exists in analogous `Views` like `MenuBar`.  In `MenuBar` there is a `Menus` collection that allows a developer to modify the contents without having to re-create the parent `View`.  The previous `StatusBar` also had an `Items` collection for `StatusBarItems`  In the current `StatusBar` implementation, I can't see any way to do that.

I would like to add a property on the `StatusBar` called `Shortcuts`, which will hold an array of `Shortcuts`, patterned after the v1 `StatusBar` and current `MenuBar`.

Unless there is something that i have missed in the current v2 implementation, the only alternative seems to be the creation of a new `StatusBar` object.

I am happy to add this myself, I am just looking for any comments from the group if there is some reason i should not.

**Comment by BDisp** [comment]
Please see first the `DynamicStatusBar` where I struggled to fix it after the changes. I think it's possible to modify the contents now, but I may missing something. If doesn't satisfy your needs then fell free to going on.

**Comment by dasien** [comment]
Thank you for that example @BDisp.  I am curious though, why the difference in the implementation between that example and the `DynamicMenuBar` example.  Internally, the `DynamicMenuBar` example appears to be using the `Menus` property to add/replace/remove `MenuBarItems`, while the `DynamicStatusBar` one manipulates the `SubViews` of the `StatusBar`.  

I can see that doing that `SubView` manipulation would achieve the same goal, I guess i am curious why we would want to have that deviation from both the v1 `StatusBar` and the v2 `MenuBar`.  Is that the direction other `Bar` classes will take?

For certain, i know very little about the overall project, so if there is a reason to have the difference in sub-classes of `Bar`, then i will leave it and just modify my client code to manipulate the `SubViews` of my `StatusBar`.

**Comment by dasien** [comment]
Hi @tig I suppose one could do that, but i need to update the commands shown en masse and that was much easier when there was an `Items` array that could just be overwritten at once, rather than one item at a time.  If `SubViews` were settable, that would have the same effect (single operation updating the list of items at once).  In my case, it is much more tedious to order/insert/remove the list of `Shortcuts` one at a time, rather than just overlaying the entire array.  Here is a snippet of the code that was working in v1, which i need to migrate for v2.  This code is part of  a method that gets called in a couple of places.  It is called once when the `ListView` is initially loaded, and other times during `ListView` events.

```
                // Check to see that there is a list item source.
                if (lvwItems.Source != null)
                {
                    // Get the data source for list.
                    ItemListDataSource items = (ItemListDataSource) lvwItems.Source;

                    // Check to see how many rows have been selected.
                    switch (items.MarkedItemCount)
                    {
                        // If 0 or 1, enable single item menu items.
                        case 0:
                        case 1:

                            // Only add collection move and copy options if appropriate.
                            if (colMoveOk && copyOk)
                            {
                                // Add them to the status bar.
                                staMain.Items = [stiNew, stiView, stiEdit, stiCopyUser, stiCopyPwd, 
                                    stiFolderMove, stiCollectionMove, stiDelete];
                            }

                            else if (copyOk)
                            {
                                // Add them to the status bar.
                                staMain.Items = [stiNew, stiView, stiEdit, stiCopyUser, 
                                    stiCopyPwd, stiFolderMove, stiDelete];
                            }
                            
                            else if (colMoveOk)
                            {
                                // Add them to the status bar.
                                staMain.Items = [stiNew, stiView, stiEdit,  
                                    stiFolderMove, stiCollectionMove, stiDelete];
                            }

                            else
                            {
                                // Add them to the status bar.
                                staMain.Items = [stiNew, stiView, stiEdit, stiFolderMove, stiDelete];
                            }
                            break;

                        // If > 1, enable only bulk menu items (add to folder/collection).
                        default:
                            
                            // Only add collection move option if it is allowed.
                            if (colMoveOk)
                            {
                                // Add them to the status bar.
                                staMain.Items = [stiFolderMove, stiCollectionMove];
                            }

                            else
                            {
                                // Add them to the status bar.
                                staMain.Items = [stiFolderMove];
                            }

                            break;
                    }
                }

                else
                {
                    staMain.Items = [stiNew];
                }
```

The way i would have to do that using `SubViews` is to understand what was already in the `StatusBar`, then add/remove accordingly.  I will most likely just do a remove of all subviews of `Shortcut` type until nothing is left, then re-add them in order.  That just seems like several steps when compared to a single assignment of the array of options, similar to how `MenuBar` works in v1 and v2 and how `StatusBar` worked in v1.  

Again, there may be some larger context that i am unaware of, and if the overall direction is to leverage `SubViews` for this, then i can do that.

**Comment by dasien** [comment]
I went ahead and used the `RemoveAll()` and `Add(View[])` methods on the `StatusBar`, so I will close this.

**Comment by BDisp** [comment]
> I went ahead and used the `RemoveAll()` and `Add(View[])` methods on the `StatusBar`, so I will close this.

You are right. This way is much more easer to update the status bar than than the tedious and erroneous propone of bring to front or send to back, etc.

**Comment by tig** [comment]
> I went ahead and used the `RemoveAll()` and `Add(View[])` methods on the `StatusBar`, so I will close this.

I was just about to suggest that.

**Comment by tig** [comment]
Relevant: https://github.com/gui-cs/Terminal.Gui/issues/538

**Comment by dasien** [comment]
Thank you both for the insight and discussion!
