### ISSUE TITLE
ResourceManager GetResourceSet doesn't fallback to default for no translated keys.

### ISSUE THREAD

**Issue by BDisp** [gui-cs/Terminal.Gui#3698]
The solution must be aligned with a more robust generic approach that allow also using the most used `ResourceManager` methods, although the others methods fallback to default for no translated keys.

**Comment by BDisp** [comment]
Sorry, I forgot. Done. Thanks.

**Comment by tig** [comment]
Not a huge deal. I generally do it if it wasn't already done, but it'd be nice if I didn't have to.

**Comment by BDisp** [comment]
I understand, lately I've been doing this but this time I really forgot. You can remind me how much it takes for me to get used to it.
