### ISSUE TITLE
`FileDialog` doesn't show button shadows correctly

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#3701]
![image](https://github.com/user-attachments/assets/da1ec024-e902-44ae-a9dc-e0b87f67bc66)

This is caused by the fact `FileDialog` doesn't take full advantage of `Pos/Dim` for layout.

Generally, the fix is 

- use `Pos.AnchorEnd` for any buttons that are supposed to be at the bottom/right.
- dont position views with absolute values, such as the "up" dir button

**Comment by tznind** [comment]
What is the easiest way to turn on shadow buttons in UICatalog?

**Comment by tig** [comment]
> What is the easiest way to turn on shadow buttons in UICatalog?

Select the UI Catalog Theme.

Or in any `config.json` 

```cs
{
  "SOME THEME": {
        "Dialog.DefaultShadow": "Transparent",
```

**Comment by tig** [comment]
`Hot Dog Stand` has it enabled too

**Comment by tznind** [comment]
The main table view is hosted in a tile.  It needs to `Fill` up to the buttons.  But the buttons are now of variable height (i.e. `Pos.AnchorEnd`).  

What is best approach here @tig ? some kind of `Dim.Func` that looks at the current Y of the buttons above and below?

```csharp
_splitContainer = new TileView
{
    X = 0,
    Y = Pos.Bottom (_btnBack),
    Width = Dim.Fill (),
    Height = Dim.Fill (1/*TODO needs to be 2 for shadow buttons, how best?*/)
};
```

![image](https://github.com/user-attachments/assets/b15de24a-0e9a-47ea-bcc9-390b3680a81a)

**Comment by BDisp** [comment]
Bellow the Up and Right buttons it's a space? If affirmative you can remove it and add it bellow before the buttons and search text.

**Comment by tznind** [comment]
> Bellow the Up and Right buttons it's a space? If affirmative you can remove it and add it bellow before the buttons and search text.

There is no space, it looks like there is only because of the use of shadow buttons.

The issue is how to declare the `Height` property of the main table tile.  At the moment it is `Fill(1)` which works for normal theme but when buttons become height 2 then it needs to be `Fill(2)`.  I'm looking for suggestions on smart way to handle that.

![image](https://github.com/user-attachments/assets/c1333d09-8dd4-4f1d-be4b-98f10e0988cd)

**Comment by BDisp** [comment]
I think the best solution is including the `Shadow` adornment as part of the `View` class, as the `Margin`, `Border` and `Padding` and included in the layout for calculation of the `Frame` size, based on his thickness. So, any view that want to used it only needs to set the thickness as desired.

**Comment by tig** [comment]
I'd love to come up with an elegant, easy to use, solution for this. It's a common case. 

One of the reasons I was thinking of putting dialog buttons in Padding was to address this (I've backed away from that idea). 

I've solved this several times differently in places. Later today when I'm at a 'puter I'll remind myself and share. 

I also have an idea for a new Dim type along the lines of "table.Height = Dim.Track (okBtn)".

**Comment by tznind** [comment]
What about `Dim.FillTo(Pos a)`.

Or does this create a circular dependency?

**Comment by tig** [comment]
> What about `Dim.FillTo(Pos a)`. Actually I guess that would just be a `Pos` overload of the regular `Fill` method.
> 
> Or does this create a circular dependency?

Yeah, maybe something like that.

**Comment by tig** [comment]
> I think the best solution is including the `Shadow` adornment as part of the `View` class, as the `Margin`, `Border` and `Padding` and included in the layout for calculation of the `Frame` size, based on his thickness. So, any view that want to use it, only needs to set the thickness as desired.

Shadow is in Margin.

**Comment by tig** [comment]
This works:

```cs
Height = Dim.Fill () - Dim.Func (() => IsInitialized ? Subviews.First (view => view.Y.Has (typeof(PosAnchorEnd), out _)).Frame.Height : 1),
```

![image](https://github.com/user-attachments/assets/ef9db57e-01d2-4910-ab81-fa8bf86124ad)

![image](https://github.com/user-attachments/assets/59e2e51a-4d21-4975-88f0-3dab94c8a37f)

**Comment by tig** [comment]
And... 

With #3716, this works:

```cs
Height = Dim.Fill (Dim.Func (() => IsInitialized ? Subviews.First (view => view.Y.Has<PosAnchorEnd> (out _)).Frame.Height : 1)),
```

**Comment by tig** [comment]
#3716 has been merged.

@tznind you can do 

```cs
table.Height = Dim.Fill (Dim.Func (() => IsInitialized ? Subviews.First (view => view.Y.Has<PosAnchorEnd> (out _)).Frame.Height : 1));
```

**Comment by BDisp** [comment]
> Shadow is in Margin.

Makes sense. Good choice.

**Comment by tznind** [comment]
> @tznind you can do [...]

Thanks, I have referenced view directly rather than use linq but the Dim overload for Fill is super helpful

```
Height = Dim.Fill (Dim.Func (() => IsInitialized ? _btnOk.Frame.Height : 1)),
```
