### ISSUE TITLE
Forcing focus to a `RadioGroup` inside of a Wizard cause the `RadioGroup` and the `Next/Finish` button to be focused at the same time

### ISSUE THREAD

**Issue by MangelMaxime** [gui-cs/Terminal.Gui#3707]
**Describe the bug**

When loading a wizard, it seems like the focus is on the `Next/Submit` button. The problem is that I didn't found how to escape the  `Next/Submit` button using keyboard to focus the content of the Wizard. 

I can click on the content area but this is "slow".

For this reason, I had the idea of forcing the focus on the `choice` component directly, but it seems like now the focus is on both `choice` and the `Next/Submit` button.

```fs
type InteractiveWindow(config: CommitParserConfig) as this =
    inherit Window()

    let promptCommitType (config: CommitParserConfig) =
        let step = new WizardStep()

        let commitTypeLabel = new Label(Text = "Select the type of commit")

        let listOfCommitTypes =
            [| "feat"; "fix"; "docs"; "style"; "refactor"; "perf"; "test"; "chore" |]

        let choices =
            new RadioGroup(X = 1, Y = Pos.Bottom(commitTypeLabel), RadioLabels = listOfCommitTypes)

        choices.SelectedItemChanged.Add(fun _ ->
            InteractiveWindow.CommitType <- choices.RadioLabels[choices.SelectedItem]
        )

        // Force focus on the radio group for faster
        choices.SetFocus()

        step.Add(commitTypeLabel, choices)
        step

    do
        this.Title <- $"Commit editor (%O{Application.QuitKey} to quit)"

        let wizard = new Wizard()

        wizard.AddStep(promptCommitType config) |> ignore
        wizard.AddStep(promptCommitType config) |> ignore

        wizard.Finished.Add(fun _ -> Application.RequestStop())

        this.Add(wizard) |> ignore

	static member val CommitType = "You should not see this text" with get, set
```

**Expected behavior**

Only choice, should be focused and I should be able to use `tab` to focus the `Next/Submit` button.

In the console, I should see the selected "commit type" and not "You should not see this text"

**Screenshots**

![CleanShot 2024-08-30 at 17 34 29@2x](https://github.com/user-attachments/assets/fd0a44e7-3908-4488-871d-953bf959252d)

https://github.com/user-attachments/assets/124ad785-ce11-478e-96e4-3708b81b79e1

**Additional context**

I am using version `2.0.0-v2-develop.2214` on MacOS.

**Comment by tig** [comment]
I just completely broke Wizard in the focus PR I just merged. 

I'll fix this when I fix that. Sorry!

**Comment by MangelMaxime** [comment]
No problem, it happens :) Will wait for the wait.

For information, I think my version is from before this merge happened but I will check once I get some news.

**Comment by tig** [comment]
Pull this down and see if it does what you want.

I fixed some focus things in Wizard and WizardStep and then added code to the Wizard Scenario showing how to overrride the behavior that sets the focus to the next/back buttons on `Wizard.GoToStep`:

![image](https://github.com/user-attachments/assets/da88f9b9-8df8-4d1d-a328-6f9f5162807f)

**Comment by MangelMaxime** [comment]
The exemple for RadioGroup seems to be working fine now.

However, on the second step you can move from the `Next/Submit` button into the view step content but once your are inside of it you cannot go back to the `Next/Submit` button user the keyboard only.

https://github.com/user-attachments/assets/a894d195-7af3-4431-a95d-45026a59fafa

**Comment by tig** [comment]
Yep, I'm working on fixing that... 

For now, just makes sure there's a hotkey for any next/back button so the user can at least use those.

Also, when I wrote this in v1, consistent `Accept` event handling wasn't implemented. Now, with v2, it is. For this reason, i've removed the code that sets focus to the next/back buttons automatically. As long as the wizard step's first focusable subview doesn't eat "Accept", pressing ENTER will cause "Next" as expected.

**Comment by tig** [comment]
Ok, I think this all works as expected now.

Note that because Wizard uses a hidden "content view" within WizardStep, Tab navigation is a bit odd, but correct:

When tabbing from the back/next buttons into the wizard step, the focus gets RESTORED. This is because the behavior for tabbing into a view with subviews is to restore focus, not "focus first". 

With #2485 I plan on refactoring wizard to not use all this nesting, but that may never happen... ;-).
