### ISSUE TITLE
Arrow Right in TextField/TextView should not move tab if there is a selection

### ISSUE THREAD

**Issue by tznind** [gui-cs/Terminal.Gui#3713]
**Describe the bug**
1. make a selection up to the end of the text by holding shift and pressing right
2. release shift
3. press right

Expected behaviour: selection should clear and cursor should be at end, the same as if you had pressed the End key.  Tab should only occur on second press of Right i.e. when there is no longer a selection.

Observed behaviour: tab moves to next view

Happy to discuss if people disagree

![image](https://github.com/user-attachments/assets/fabe6723-8043-46b7-869e-8d1216aada7a)
_TextField has an active selection so right cursor could be resolved by clearing that selection_

**Comment by BDisp** [comment]
I agree but you also have to consider the opposite, when pressing the shift key and left up to the start of the text, at position (0,0), release shift and press left. I didn't test but probably it will move to the previous view.

**Comment by tig** [comment]
I agree.

It should be trivial to update `TextField` and `TextView` to fix this.
