### ISSUE TITLE
Application stops responding

### ISSUE THREAD

**Issue by kacperpikacz** [gui-cs/Terminal.Gui#3738]
**Describe the bug**
In less than minute the application is not responding anymore. No exception is thrown.

**To Reproduce**
```using System;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Text.RegularExpressions;
using Terminal.Gui;

namespace Playground
{
    public class Program
    {
        // Same issue with class List
        private static ObservableCollection<string> List = new();
        private static ListView ListView = new();
        private static Timer? _timer;

        public static void Main(string[] args)
        {
            List.CollectionChanged += (obj, args) =>
            {
                Application.MainLoop.Invoke(() =>
                {
                    if (List.Count == 100) List.RemoveAt(0);
                    ListView.MoveDown();
                    ListView.SetNeedsDisplay();
                });
            };

            ListView = new ListView()
            {
                Width = 16,
                Height = 12,

            };
            ListView.SetSource(List);

            ListView.Enter += (args) =>
            {
                // We can use Application.MainLoop.AddTimeout(timespan, callback) but it will behave the same.
                _timer = new Timer(Refresh, null, TimeSpan.Zero, TimeSpan.FromMilliseconds(2));
            };

            Application.Init();
            Application.Top.Add(ListView);
            Application.Run();
        }

        private static void Refresh(object? state)
        {
            Application.MainLoop.Invoke(() =>
            {
                List.Add(new Random().Next(100000, 999999).ToString());
            });

        }

    }
}

```

**Desktop:**
`Tested with Apple Silicon & Linux x64 and arm64`

**Additional context**
Tested with Windows ARM and the application is working correctly in 5min timeframe.

**Comment by tznind** [comment]
Can confirm working correctly on Windows

![image](https://github.com/user-attachments/assets/e46e2bef-b8ad-4725-ab06-8cc8e6e649d5)


As I understand it you are adding a new object to list every 2 ms and refreshing the UI at that time.

You can try decoupling list modification from screen refresh e.g.

Can you try running this adjusted code and see if you have same issue:

```csharp
using System.Collections.ObjectModel;
using Terminal.Gui;

namespace Playground
{
    public class Program
    {
        // Same issue with class List
        private static ObservableCollection<string> List = new();
        private static ListView ListView = new();
        private static Timer? _timer = null;

        public static void Main(string[] args)
        {

            // Move init to top before controls are created
            Application.Init();

            bool listChanged = false;

            // Update the list in 'real time'
            List.CollectionChanged += (obj, args) =>
            {
                listChanged = true;
                if (List.Count == 100)
                {
                      /* I've left this in, but do notice that you are already in a list changed callback and are 
                          making another modification - presumably resulting in re-entry.  This is likely to
                          compound performance issue i.e. we are now adding an object every 1ms because
                          of re-entry.
                     */
                    List.RemoveAt(0);
                }
            };

            // Every 250 ms update the UI
            Application.MainLoop.AddTimeout(TimeSpan.FromMilliseconds(250), (m) =>
            {

                Application.MainLoop?.Invoke(() =>
                {
                    ListView.MoveEnd();
                    ListView.SetNeedsDisplay();
                    listChanged = false;
                });
                return true;
            });

            ListView = new ListView()
            {
                Width = 16,
                Height = 12,

            };
            ListView.SetSource(List);

            ListView.Enter += (args) =>
            {
                // Only ever start 1 timer
                if (_timer == null)
                {
                    // We can use Application.MainLoop.AddTimeout(timespan, callback) but it will behave the same.
                    _timer = new Timer(Refresh, null, TimeSpan.Zero, TimeSpan.FromMilliseconds(2));
                }
            };
            Application.Top.Add(ListView);
            Application.Run();
        }

        private static void Refresh(object? state)
        {
            Application.MainLoop.Invoke(() =>
            {
                List.Add(new Random().Next(100000, 999999).ToString());
            });

        }
    }
}
```

**Comment by kacperpikacz** [comment]
Tried with limiting screen refresh every 25 ms

```
using System;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Text.RegularExpressions;
using Terminal.Gui;

namespace Playground
{
    public class Program
    {
        private static ObservableCollection<string> List = new();
        private static ListView ListView = new();
        private static List<Timer> _timers = new();

        public static void Main(string[] args)
        {
            Application.Init();

            ListView = new ListView()
            {
                Width = 16,
                Height = 12,

            };

            ListView.SetSource(List);
            ListView.Enter += (args) =>
            {
                Application.MainLoop.Invoke(() =>
                {
                    _timers.Add(new Timer(Generate, null, TimeSpan.Zero, TimeSpan.FromMilliseconds(1)));
                });
                
            };

            _timers.Add(new Timer(Refresh, null, TimeSpan.Zero, TimeSpan.FromMilliseconds(50)));

            Application.Top.Add(ListView);
            Application.Run();
        }

        private static void Generate(object? state)
        {
            Application.MainLoop.Invoke(() =>
            {
                List.Add(new Random().Next(100000, 999999).ToString());
            });
        }

        private static void Refresh(object? state)
        {
            Application.MainLoop.Invoke(() =>
            {
                ListView.MoveDown();
                ListView.SetNeedsDisplay();

                if (List.Count is 100) List.RemoveAt(0);
            });
        }

    }
}
```

After around 90 sec

https://github.com/user-attachments/assets/193315e1-c41c-4130-9558-6fd112f633cb

**Comment by tznind** [comment]
Try removing invokes on the list change events

```
 private static void Generate(object? state)
        {
            Application.MainLoop.Invoke(() =>
            {
                List.Add(new Random().Next(100000, 999999).ToString());
            });
        }
```

This basically says "every 1ms switch to UI thread and modify list".  There is no reason to switch to the UI thread to do this.  See in my above code the only invoke is when updating the view.

Likewise you dont need main loop invoke when setting up the timer for Generate.

Try my exact code or make the above changes and lets see.  I think the performance is down to switching constantly to the UI loop every millisecond.  Evidence for this is that when it slows down its not just the UI refresh that is slowing down, the generation of numbers is much slower too.

**Comment by dodexahedron** [comment]
To add to @tznind's analysis, which is spot on except for one little detail, the way that ListView works unconditionally is going to cause additional copies of your entire collection to be made, as a list. That little detail I mentioned is that the use of a concurrent collection by the consumer won't solve concurrency problems TG itself has, since the collection gets copied anyway, and has additional concurrency issues not directly related to the collections themselves, as well.

But the copy behavior means that, depending on size, there could be _multiple_ heap allocations each time, not counting the ones that are happening for growth/modification of your source collections.

With that in mind, do try to limit how "real-time" you try to be with ListView, especially as the number of elements grows. And remember that 16ms is already 60FPS, so consider the utility of updating on really small timescales in the first place, anyway.

I'm pretty sure I've got an open issue for taking a look at how to improve the memory pressure situation under the hood for ListView, already. If not, it _is_ on my personal list of things I want to address at some point, since it is a lot heavier than it needs to be.

If you're adding and removing a bunch of elements in a ListView, it is best, with the current implementation, to do all the modifications you need to your collection _first_, or at least do them in batches, and then provide the collection to the ListView.

Rapid modification will encounter the memory thrashing seen above, which compound with garbage generated by string handling in certain places, and is also likely to encounter concurrency issues that can result in deadlocks and race conditions, as we haven't yet addressed thread-safety for ListView and many other components, including some core parts of the infrastructure.

**Comment by dodexahedron** [comment]
As for Timer vs the TG Timeout struct... Yeah... I'm probably ripping that out while I'm doing the ConsoleDriver stuff I'm working on, so keep using built-in timer constructs if those are working better for you. The Timeout implementation has a lot of concurrency problems.

**Comment by tznind** [comment]
@dodexahedron just heads up that OP is using v1 library dependency.

I saw you put tag on ticket for v2 - or was that just to address this kind of use case in v2?

**Comment by kacperpikacz** [comment]
I was doing some tests with v1_release/v1.5.0 and seems it behaves much better since I didn't get any ui lock/exception in a 2 hour timeframe. Even with modifying a ListView source every 5ms

**Comment by dodexahedron** [comment]
> @dodexahedron just heads up that OP is using v1 library dependency (based on the code).
> 
> I saw you put tag on ticket for v2 - or was that just to address this kind of use case in v2?
> 

Oops, I just mis-clicked, actually. Wrong tag.

I didn't really differentiate in my commentary since the issues in that area are mostly the same, though I probably should have specified my work related to it is v2 only.

**Comment by dodexahedron** [comment]
> @dodexahedron even if I apply lock while modifying the source of ListView I will get an Exception after few minutes in latest version of v1


Yep. That's what I was saying about how you can't fix the concurrency problems in your code. They're in the library itself, and are caused by unsynchronized access to various things, for the most part.

**Comment by BDisp** [comment]
This is a changed sample which is working as expected with the PR #3739.

```cs
#define TIMER

using System;
using System.Collections.ObjectModel;
using System.Threading;
using Terminal.Gui;

namespace Playground {
	public class public class Program {
		// No issue with class List as well
		private static ObservableCollection<string> List = new ();
		// Don't initialize here because it's initialized again bellow to avoid not disposed issues
		private static ListView ListView;
#if TIMER
		private static Timer? _timer;
#endif
		public static void Main(string[] args)
		{
			List.CollectionChanged += (obj, args) => {
				Application.MainLoop.Invoke (() => {
					ListView.MoveEnd ();
					ListView.SetNeedsDisplay ();
				});
			};

			ListView = new ListView () {
				Width = 16,
				Height = 12,

			};
			ListView.SetSource (List);

			ListView.Enter += (args) => {
#if TIMER
				if (_timer == null) {
					_timer = new Timer (Refresh, null, TimeSpan.Zero, TimeSpan.FromMilliseconds (2));
				}
#else
				// We can use Application.MainLoop.AddTimeout(timespan, callback) as well.
				Application.MainLoop.AddTimeout (TimeSpan.FromMilliseconds (2), _ => {
					Refresh (null);
					return true;
				});
#endif
			};

			Application.Init ();
			Application.Top.Add (ListView);
			Application.Run ();
#if TIMER
			_timer?.Dispose ();
#endif
			// I recommend always using this
			Application.Shutdown ();
		}

		private void Refresh (object? state)
		{
			// No need to use Application.MainLoop.Invoke here because the List.CollectionChanged 
			// will be raised during this method

			// Move this to here to ensure there always have 100 items
			if (List.Count == 100) List.RemoveAt (0);

			List.Add (new Random ().Next (100000, 999999).ToString ());
		}
	}
}
```

**Comment by BDisp** [comment]
![image](https://github.com/user-attachments/assets/34f865fa-4e25-4048-a489-147573e48578)

To avoid of the above error it's need surround with a lock block. Note that this error was in the v2 because the `ListView` already uses a `ObservableCollection` as source and thus exposed to concurrency problems. Just to remember that the `ListView.CollectionChanged` event can be used instead of `List.CollectionChanged`.

```cs
    private void Refresh (object? state)
    {
        lock (_list)
        {
            if (_list.Count == 100)
            {
                _list.RemoveAt (0);
            }

            _list.Add (new Random ().Next (100000, 999999).ToString ());
        }
    }

```

**Comment by BDisp** [comment]
> ![image](https://private-user-images.githubusercontent.com/13117724/367821432-34f865fa-4e25-4048-a489-147573e48578.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1MDMxMDUsIm5iZiI6MTcyNjUwMjgwNSwicGF0aCI6Ii8xMzExNzcyNC8zNjc4MjE0MzItMzRmODY1ZmEtNGUyNS00MDQ4LWE0ODktMTQ3NTczZTQ4NTc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDE2MDY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1NmQzZmZiNjQxYTcwYzZiNzhkODdjMjg4ZjFhZTI5MWU1ZGMwYjUyMzZiNDNhNmE4MGFkN2E4OTcyM2M0ODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T1JzL2mkoWil3sjXRow2OJ_qrcXoa4deYX5KUDvWmXk)
> 
> To avoid the above error it's need surround with a lock block. Note that this error was in the v2 because the `ListView` already uses a `ObservableCollection` as source and thus exposed to concurrency problems. Just to remember that the `ListView.CollectionChanged` event can be used instead of `List.CollectionChanged` in the v2.
> 
> ```cs
>     private void Refresh (object? state)
>     {
>         lock (_list)
>         {
>             if (_list.Count == 100)
>             {
>                 _list.RemoveAt (0);
>             }
> 
>             _list.Add (new Random ().Next (100000, 999999).ToString ());
>         }
>     }
> ```

**Comment by kacperpikacz** [comment]
@BDisp your recent PR fixes the issue. I will do some longer tests but looks like no more problems with my use case.
