### ISSUE TITLE
Disabled MenuItem triggers exception

### ISSUE THREAD

**Issue by rneeft** [gui-cs/Terminal.Gui#3740]
**Describe the bug**
Having a menu item list with **only** disabled menuitem crashes the app

**To Reproduce**
Create a new dotnet 8 console application with Terminal.Gui nuget. Replace the Program.cs code with the following and run the application.

```csharp
using Terminal.Gui;

Application.Run<ExampleWindow>();
Application.Shutdown();

public class ExampleWindow : Toplevel
{
    public ExampleWindow()
    {
        this.ColorScheme = Colors.ColorSchemes["Base"];

        var menu = new MenuBar
        {
            Menus =
           [
               new MenuBarItem("Only disabled", new MenuItem[] {
                    new("Hover to crash me","", () => { }, canExecute: () => false),
                }),
                new MenuBarItem("False and true", new MenuItem[]{
                    new("Hover me is fine","", () => { }, canExecute: () => true),
                    new("Hover me is fine","", () => { }, canExecute: () => false),
                })
            ]
        };

        this.Add(menu);
    }
}
```

**Expected behavior**
No exception occuring

**Workaround **
Having enabled menu items in the list prevents the crash (see example)

**Desktop**
- Windows 11

**Comment by tig** [comment]
I'm assuming this is with v1.

Regardless, `MenuBar` will be replaced in v2 and it's probably not a great use of time to fix this now.

Instead, lets see if we can come up with a workaround that addresses your use case?

**Comment by rneeft** [comment]
I'm sorry I forgot to specify the version. I'm using the V2 : 2.0.0-v2-develop.2329.

Yes the workaround is to add another menu item that is not disabled.

I've seen a Menuv2 class, should I start using those classes?

**Comment by tig** [comment]
> I've seen a Menuv2 class, should I start using those classes?

Nope. That's just a placeholder.

See 

- #2975
