### ISSUE TITLE
ShadowView throws System.IndexOutOfRangeException if left is less than zero.

### ISSUE THREAD

**Issue by BDisp** [gui-cs/Terminal.Gui#3757]
Try move a Dialog with shadow enabled to the left and you see this error. i.e. the about UICatalog dialog.

![image](https://github.com/user-attachments/assets/00a7da15-ddf9-487d-8dc1-4514b7e7ef24)

**Comment by tig** [comment]
Yeah, I fixed this in the #3691 PR.
