### ISSUE TITLE
Latest version of all 3 drivers call refresh constantly

### ISSUE THREAD

**Issue by tznind** [gui-cs/Terminal.Gui#3761]
**Describe the bug**

![refresh-bug](https://github.com/user-attachments/assets/cb784909-a0b6-44ba-85a7-a091f46e28b3)
_Clicking the mouse causes about 68 screen refreshes (it does eventually stop)_

**To Reproduce**
This changed recently.

1. Add a debug counter to `UpdateScreen` 
2. Click mouse

**Expected behavior**
Only redraw when something has changed.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tig** [comment]
I probably did this when I fixed a bunch of repaint logic last week. I focused on WindowsDriver.

**Comment by tig** [comment]
I finally got frustrated with all this enough today. I have started a branch where I finally make 

- layout decoupled from draw
- enforce that Clear rarely happens 
- ensure drivers minimize full repaints
- minimize when Draw/OnDrawContent are called 

More soon.
