### ISSUE TITLE
After V2-develeop.2214, TextField focus seems broken

### ISSUE THREAD

**Issue by ChristopheI** [gui-cs/Terminal.Gui#3769]
**Describe the bug**

After V2-develeop.2214 (I tried each version until the last one V2-develeop.2329) on a simple example I cannot update the content of a TextField. (Using Windows 11)

There is no more the "flashing prompt" when a TextField has the focus (to know where the next character will be added when a new kay is typed)

**To Reproduce**
A small example to reproduce the problem:
```
using Terminal.Gui;

// Use "BotWindow" as main window for Terminal.Gui.Application
Terminal.Gui.Application.Run<TestWindow>().Dispose();

//// Before the application exits, reset Terminal.Gui for clean shutdown
Terminal.Gui.Application.Shutdown();

public class TestWindow : Window
{
    public TestWindow()
    {

        Title = "TestWindow";
        Width = Dim.Fill();
        Height = Dim.Fill();

        var testView = new TestView()
        {
            X = 0,
            Y = 0,
            Width = Dim.Fill(),
            Height = Dim.Fill(),
        };

        Add(testView);
    }
}

public class TestView : View
{
    public TestView()
    {

        Title = $"TestView";

        // Create Login and Password Label
        var loginLabel = new Label
        {
            Text = "Login:",
            TextAlignment = Alignment.End,
            Width = 9
        };
        var passwordLabel = new Label
        {
            Text = "Password:",
            TextAlignment = Alignment.End,
            X = Pos.Left(loginLabel),
            Y = Pos.Bottom(loginLabel) + 1,
            Width = 9
        };

        // Create Login and Password TextField
        var loginText = new TextField
        {
            // Position text field adjacent to the label
            X = Pos.Right(passwordLabel) + 1,

            // Fill remaining horizontal space
            Width = Dim.Fill(1),

            Text = "login@test.com",
            TextAlignment = Alignment.End
        };
        var passwordText = new TextField
        {
            Secret = true,

            // align with the text box above
            X = Pos.Left(loginText),
            Y = Pos.Top(passwordLabel),
            Width = Dim.Fill(1),

            Text = "my incredible pwd"
        };

        // Create login button
        var btnLogin = new Button
        {
            Text = "Login",
            Y = Pos.Bottom(passwordLabel) + 1,

            // center the login button horizontally
            X = Pos.Center(),
            IsDefault = true,
        };

        // Add elements to this View
        Add(loginLabel, loginText, passwordLabel, passwordText, btnLogin);
    }
}
```
After V2-develeop.2214, loginText and passwordText cannot be selected using the mouse or tab. So their content cannot be updated
With V2-develeop.2214 (and with V2-develeop.2169 at least) it's working well

**Expected behavior**
TextField can have the focus and its content can be updated

**Desktop (please complete the following information):**
 - OS: Checked only on Windows 11

**Comment by ChristopheI** [comment]
IMPORTANT NOTE: If I don't use TestView but add directly its content in TestWindow class it's working fine in V2-develep.2214 and later

**Comment by tznind** [comment]
I noticed something similar I think, I added `CanFocus` to true on the intermediate view and it came back to life.

Not saying that's the solution just that it might give more info.  Can you try setting the TestView CanFocus to true see if that changes anything?

**Comment by tig** [comment]
`CanFocus` now defaults to `false` in v2 in `View`. Subclasses that want to be focusable must set it to `true` to enable focus.

Looks like I failed to explicitly call this out here:

https://gui-cs.github.io/Terminal.GuiV2Docs/docs/migratingfromv1.html#focus

I will fix asap.

**Comment by ChristopheI** [comment]
Thanks for your quick answers. `CanFocus` set to true in hierarchy resolves the pb

**Comment by BDisp** [comment]
The logic is when super-view isn't yet initialized and a sub-view is added with `CanFocus` as true, then the super-view `CanFocus` will also be true. If a super-view is already initialized with `CanFocus` as false when a sub-view with `CanFocus` as true is added the super-view `CanFocus` must prevail his setting as false. In this case there is automatization on how to handle with the `CanFocus` property.

**Comment by tig** [comment]
> The logic is when a super-view isn't yet initialized and a sub-view is added with `CanFocus` as true, then the super-view `CanFocus` will also be true. If a super-view is already initialized with `CanFocus` as false when a sub-view with `CanFocus` as true is added the super-view `CanFocus` must prevail his setting as false. In this case there is automatization on how to handle with the `CanFocus` property.

This is how it used to work. Please read `navigation.md`.

**Comment by BDisp** [comment]
> This is how it used to work. Please read `navigation.md`.

I read it. It was just to confirm and not to criticize, of course.
