### ISSUE TITLE
Display Text including different color to emphasize some part (in a easy way)

### ISSUE THREAD

**Issue by ChristopheI** [gui-cs/Terminal.Gui#3773]
**Is your feature request related to a problem? Please describe.**
I would like in the same line (and in a easy way) to display text with different color to emphasize specific part:

For example with the text below I want to use specific colors for names:
**Stallone** invites you to the room **Rambo XII** 

(yes I'm really bad to find examples ... 😥)

**Describe the solution you'd like**
In **Label** and/or **TextView** add a new property like RuneCellsList (as `List<RuneCell>`) to set directly RuneCell to use for display

Or even better a **FomattedText** (as String) property, with a specific syntax to set colors:
`<color="#ff0000,#888888">Stallone</color> invites you to the room <color="#ff0000,#888888">Rambo XII</color>`
With <color="#ff0000,#888888"> to set foreground (#ff0000) and background (#888888") color 

Also add a property to avoid the use of ContextMenu for **TextView**

**Describe alternatives you've considered**
I already used **TextView** to highlight some part based on the example scenario **SyntaxHighlighting** but it's based on RegEx and needs al lot of code to manage it correclty.  I created my own "loggerView" to highlight logs input on specific keyword. But totally to complex for my scenario here.

**Comment by BDisp** [comment]
Sorry for not to mention that the example you want is in the `ApplyLoadRuneCells` and `SaveRuneCells` (in case want to save to a file) of the `SyntaxHighlighting` scenario. The @tznind explained was for format words with specific color and thus the use of RegEx. In the `ApplyLoadRuneCells` it's highlighting each name of `Colors.ColorSchemes` but you can use any string you want with the color you want. In the case you want to save the text formatted to a file use the example in the `SaveRuneCells`.
What you are ask is a generic format for all views, but they may want to display it as text, unless a property is used to enable/ignore the format.
`RuneCell` is used by `TextField` and `TextView` and uses `ColorScheme` to set the color. It could be used `Color` for that, but I thought it was useful to display different colors for `Normal, Focus`, etc.

To avoid the use of `ContextMenu` then a generic solution is creating a interface `IContextMenu` with `public ContextMenu? ContextMenu { get; }` and `public bool DisableContextMenu { get; set; }`. Thus only the interface is public and not the `ContextMenu` and all views that want to use it must explicitly declaring in the class.

**Comment by ChristopheI** [comment]
I missed it this part of the example . Thx. !
I didn't see that Text.View.Load() was what i wanted

And TextModel.ToRuneCellList() will help me a lot too

Amazing library 👍

**Comment by BDisp** [comment]
> Unfortunately TextModel is internal. But I can copy the content of ToRuneCellList()

It can be moved to the public `RuneCell` class where it can be more useful for others users views that want to use it.

**Comment by BDisp** [comment]
Done in https://github.com/gui-cs/Terminal.Gui/pull/3772/commits/026a20ee7fcec4ffbdb8ae91fe5774eb34073f7c.

**Comment by ChristopheI** [comment]
Digging a little more about this perhaps these static methods in `TextModel` could also be moved in `RuneCell ` or changed/removed
- `StringToLinesOfRuneCells()`  (which could internally use `ToRuneCellList()`) moved in `RuneCell` 
- `ToString (IEnumerable<RuneCell> cells)` moved in `RuneCell` 
- `StringToRuneCells()` moved in `RuneCell` 
- `ToRuneCells (IEnumerable<Rune> runes, ColorScheme? colorScheme = null)` moved in `RuneCell` 
- `SplitNewLines()` (it's private but should be public) moved in `RuneCell`
- `ToRuneCells (List<RuneCell> cells)` (ambigous name with another `ToRuneCells ()`) can be removed - use instead `SplitNewLines()`
