### ISSUE TITLE
`HexEditor` right side editing is broken

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#3777]
Somewhere along the way, the ability to type on the right side of HexEditor broke. 

Also: 

- Needs Code Cleanup.
- `Enter` should not switch sides, but `Tab` and `Shift+Tab` should (and navigate out).
- `Enter` should accept.
- Needs Better unit tests.

**Comment by BDisp** [comment]
Only to remember that the navigation have to be fixed in `Navigation` API and not in the `HexEditor`.
