### ISSUE TITLE
Content Scrolling scenario clear the contents on mouse move or key press.

### ISSUE THREAD

**Issue by BDisp** [gui-cs/Terminal.Gui#3780]
@tig do you have any idea about this?

![WindowsTerminal_f49ayTB37Z](https://github.com/user-attachments/assets/3a747b04-4b96-45fc-955e-4d663d795ed1)

**Comment by tig** [comment]
I can't reproduce it.

**Comment by BDisp** [comment]
> I can't reproduce it.

I'm using Windows Terminal version 1.21.2701.0. I can reproduce in all drivers. WT version issue?

**Comment by tig** [comment]
![GKeMp5f 1](https://github.com/user-attachments/assets/1450d468-1a79-412f-b028-354a4528099e)

**Comment by BDisp** [comment]
Scroll to the bottom like I did.

**Comment by tig** [comment]
![3TCeRyt 1](https://github.com/user-attachments/assets/0464f8a1-6948-4974-a6cd-58b55d65ffd1)

**Comment by BDisp** [comment]
This issue still happens with me with the v2_develop. @tznind can you please check if this is happening with you or not. Thanks.

**Comment by tig** [comment]
Still happening? I've tried to repro on several machines but can't.

**Comment by BDisp** [comment]
> Still happening? I've tried to repro on several machines but can't.

Yes is still happening. Normally happens when you stop scrolling and move the mouse.

![WindowsTerminal_3FCz8gkXMB](https://github.com/user-attachments/assets/d7bbde70-b6cd-4f7e-a00b-405e117a9c34)

**Comment by tig** [comment]
Got it!!! I'll look into it.

**Comment by BDisp** [comment]
> Got it!!! I'll look into it.

I think that is related to this https://github.com/gui-cs/Terminal.Gui/pull/3734#issuecomment-2411828255.
