### ISSUE TITLE
Pressing 'c' in UICatalog does not move to 'Colors' category

### ISSUE THREAD

**Issue by tznind** [gui-cs/Terminal.Gui#3793]
**Describe the bug**
Presume there is some kind fo hotkey or something that is absorbing this keystroke

**To Reproduce**
1. Launch UICatalog
2. Press 'f' 
3. See Categories move to 'Files and IO' (yay)
4. Press 'l'
5. See Categories move to 'Layout' (yay)
6. Press 'c'

Nothing happens (sad)

**Expected behavior**
Pressing c should move you to the Colors category

**Screenshots**
![c-not-working](https://github.com/user-attachments/assets/b7c7ebdd-ff5c-4e24-8a27-91d0c1908a0e)
_Test jumping to F by pressing F.  Then I press c repeatedly and nothing happens on screen_

**Comment by tig** [comment]
Force 16 Colors hotkey is _color. 

Two possible fixes:

1) Just remove hotkey. 

2) Change shortcut to only register .WithAlt when the shortcut is application scope. 

The former is easiest. The later may be smarter as this condition is hard to detect.

**Comment by tig** [comment]
Another thought is "why isn't searchnavigator seeing the key first?"

**Comment by tig** [comment]
Actually, the problem revolves around the fact the `ListView`'s `Title` is `_Categories`... 

To engage `CollectionNavigator` `ListView` overrides `OnProcessKeyDown`, which is called AFTER key-bindings are handled.

It should override `OnKeyDown` instead, as that is called BEFORE key-bindings are handled.
