### ISSUE TITLE
Error when using through ssh (V1.17.1)

### ISSUE THREAD

**Issue by GPh83** [gui-cs/Terminal.Gui#3796]
**Describe the bug**
Error when using through ssh
Application made with GUI.cs V1.17.1 stop working without message.
After mouse send ESC code on screen.
Only over SSH, under Windows, Linux and putty (with xterm-256color)
Working with bash under Linux or WSL

**To Reproduce**
1. Get resticterm (https://github.com/GPh83/resticterm)
2. Run it through ssh 

**Expected behavior**
Working as local console

**Desktop (please complete the following information):**
 - OS: Windows 10, Linux Ubuntu 20.04, WSL Ubuntu 22.04
 - Version GUI.cs 1.17.1
 - Application under .NET 6.0

**Comment by GPh83** [comment]
![GUI cs](https://github.com/user-attachments/assets/71c9a150-0a22-445c-8bf6-9c5ffd962ab1)

**Comment by BDisp** [comment]
You are using Environment.Exit(-1); (maybe is better using Application.RequestStop) in your app and you aren't using Application.Shutdown after Application.Run.

**Comment by tznind** [comment]
Basic structure of a Terminal.Gui startup is:

```csharp
Application.Init();

try
{
    Application.Run(new MyView());
}
finally
{
    Application.Shutdown();
}
```

`Environment.Exit` is actually ok as long as its only used before you start the Terminal.Gui init/run code i.e. looks like you are using it for startup param validation.  

But as @BDisp says once app starts you should exit views using `Application.RequestStop`

**Comment by GPh83** [comment]
Thanks,
This explain why terminal is in strange state after exit.
But didn't explain why application doesn't start !

**Comment by tznind** [comment]
Please can you try a basic project in same environment and see if it also crashes on startup?

```
dotnet new --install Terminal.Gui.templates
dotnet new tui -n myproj
cd myproj
dotnet run
```

**Comment by BDisp** [comment]
You are calling `CheckConfigFilename` after `Application.Init` and `it may call `Environment.Exit(-1);`. So, my recommendation is only calling `Application.Init` after you call `CheckConfigFilename` method.

**Comment by GPh83** [comment]
You're right !
But in my case the config is OK and there is no exit here.
I made the modification, thanks for your help.

I'll continue to search because finally i am not sure the problem is a GUI problem ... Sorry.

**Comment by tznind** [comment]
Good luck! App looks cool 👍
