### ISSUE TITLE
Resizing console programmatically

### ISSUE THREAD

**Issue by swftq** [gui-cs/Terminal.Gui#3801]
Hello,
first I'd like to thank you for your amazing work, you should setup a donation link :)
I am trying to resize the console programmatically so it matches the users preferences. However `Console.SetWindowSize` does not seem to be enough, the content is always drawn based on the initial console size (debug mode) or is just completely messed up (release mode). Any way I can make this happen? Thanks!

**Comment by tznind** [comment]
> I am trying to resize the console programmatically

Do you mean
a) That when the user resizes the terminal your UI grows with it to the new size?
b) That when user launches your program the terminal window should grow (e.g. to fullscreen)?

Terminal.Gui can only help with a.  If you define your sizes (e.g. `Width`) as `Dim.Fill()` then it will fill the available space and resize automatically.

The only time I have seen this not work correctly is in certain osx terminals which do not seem to send resize events in the same way as we are expecting (via CursesDriver).

**Comment by swftq** [comment]
What I meant is that Terminal.GUI was not resizing the content after a Console.SetWindowSize call.However this is not a Terminal.GUI issue, I was using the Windows Terminal which does not support this API call. I fixed it using the Win32's MoveWindow api. Sorry and thanks for your help!

**Comment by BDisp** [comment]
> I fixed it using the Win32's MoveWindow api. Sorry and thanks for your help!

Do you want to share your solution, please?

**Comment by swftq** [comment]
Sure:

```
        struct Rect
        {
            public int Left;
            public int Top;
            public int Right;
            public int Bottom;
        };

        private static (int Width, int Height)? GetCurrentConsoleSize()
        {
            IntPtr consoleWindowHandle = GetForegroundWindow();
            if (consoleWindowHandle == IntPtr.Zero)
            {
                return null;
            }
            GetWindowRect(consoleWindowHandle, out Rect screenRect);
            return (screenRect.Right - screenRect.Left, screenRect.Bottom - screenRect.Top);
        }

        private static void ResizeWindowByPixelDimensions(int width, int height)
        {
            IntPtr consoleWindowHandle = GetForegroundWindow();
            if (consoleWindowHandle == IntPtr.Zero)
            {
                return;
            }
            GetWindowRect(consoleWindowHandle, out Rect screenRect);
            MoveWindow(consoleWindowHandle, screenRect.Left, screenRect.Top, width, height, true);
        }

        [DllImport("user32.dll")]
        static extern IntPtr GetForegroundWindow();
        [DllImport("user32.dll")]
        static extern bool GetWindowRect(IntPtr hWnd, out Rect lpRect);
        [DllImport("user32.dll")]
        static extern bool MoveWindow(IntPtr hWnd, int x, int y, int nWidth, int nHeight, bool bRepaint);
```

**Comment by BDisp** [comment]
And this also work with Windows Terminal?

**Comment by swftq** [comment]
Yes, this also resizes the Windows Terminal and raises the necessary events for Terminal.Gui to redraw the content to the new size.

**Comment by BDisp** [comment]
> Yes, this also resizes the Windows Terminal and raises the necessary events for Terminal.Gui to redraw the content to the new size.

Thanks for the information. If you are you comfortable to submit a PR with this implementation please feel free.
