### ISSUE TITLE
Content is not properly drawn when using ViewArrangement.Fixed

### ISSUE THREAD

**Issue by swftq** [gui-cs/Terminal.Gui#3804]
**Describe the bug**
When explicitly setting the Arrangement.Fixed property, the window content is not properly drawn. This issue becomes noticeable when interacting with modals or draggable elements within the window.

**To Reproduce**
1. Set Window's Arrangement to ViewArrangement.Fixed;
2. Add a button
3. Open a MessageBox.Query on the button click
4. Move the modal around and see the bug 

**Screenshots**
![bug](https://i.gyazo.com/37f16c08a19b8d4f94370b9e07eddf07.gif)

**Expected behavior**
![expected](https://i.gyazo.com/92967f53289e3332c2e818f9f10fce74.gif)

**Desktop:**
 - OS: Window
 - Version: 10

**Code**
```
internal class MainWindow : Window
{
    public MainWindow()
    {
        this.Width = Dim.Fill();
        this.Height = Dim.Fill();
        this.Arrangement = ViewArrangement.Fixed;
        var button = new Button()
        {
            Text = "Click me",
            X = Pos.Center(),
            Y = Pos.Center()
        };
        button.Accepting += (sender, e) =>
        {
            MessageBox.Query("Accepted", "You clicked the button", "Ok");
        };
        Add(button);
    }
}
```

**Comment by tig** [comment]
This will be fixed soon!

I'm working on a pr now for this and other things.

**Comment by tig** [comment]
This should be fixed in v2_develop now.
