### ISSUE TITLE
WindowsDriver doesn't process characters with accents.

### ISSUE THREAD

**Issue by BDisp** [gui-cs/Terminal.Gui#3807]
For those who have a Portuguese keyboard the characters with accents aren't processed. In the Editor scenario try to write the below characters and they only will being processed as normal characters without accentuation.

```
áéíóú
ÁÉÍÓÚ
àèìòù
ÀÈÌÒÙ
ãõ
ÃÕ
âêîôû
ÂÊÎÔÛ
```

**Comment by tig** [comment]
Darn. I wonder when this stopped working?

**Comment by tig** [comment]
I think I broke this when I fixed a hotkey thing.

I think the fix is this:

![image](https://github.com/user-attachments/assets/4b6becaf-3a1a-49e3-93f4-cd6698a531df)

Seems to work. 

If KeyInfo.Key is A...Z and KeyInfo.KeyChar is not a...z then we have an accent.

**Comment by BDisp** [comment]
I add a lot of changes that fixed this and others similares in the PR #3768, please take a look.

**Comment by BDisp** [comment]
Done in https://github.com/gui-cs/Terminal.Gui/pull/3768/commits/eb987071c864a3a0e381c20e89fced21e1aed830.
