### ISSUE TITLE
Visual Studio 17.12 isn't compatible with SDK version 8.0.0

### ISSUE THREAD

**Issue by BDisp** [gui-cs/Terminal.Gui#3816]
It's needed to change the version in the `global.json` file to `"version":"9.0.0"` for both, v1 and v2.

**Comment by BDisp** [comment]
@tig it's better to update all projects to `net9.0` as well?

**Comment by BDisp** [comment]
I think it's better because trying download the .NET 8.0 SDK (v8.0.404) give this alert and in my case I want to use always the latest stable VS release.

`Using Visual Studio? This release is only compatible with Visual Studio 2022 (v17.11). Using a different version? See [.NET SDKs for Visual Studio](https://dotnet.microsoft.com/en-us/download/visual-studio-sdks).`

![image](https://github.com/user-attachments/assets/9d21290e-c507-45aa-92c0-c453a4611edc)

**Comment by BDisp** [comment]
Don't forget to update WSL as well:

In Windows:
```
wsl --update
```

In WSL:
```
sudo apt install dotnet-sdk-9.0

sudo dotnet workload update
```

**Comment by tznind** [comment]
dotnet 9 is short term support so many people will stick on 8.

We should be careful about using an dotnet 9 features that will make it incompatibile with peoples dotnet 8 programs.

**Comment by tznind** [comment]
Seems unlikely there would be a version of visual studio released that was unable to compile dotnet 8 or 7 or earlier projects.  What happens if you try to build ?

**Comment by BDisp** [comment]
When VS updated it automatically removed the .NET 8.0 SDK. When I tried to run `UICatalog` it gave an error that the SDK version doesn't exist. I found this strange and tried to install the .NET 8.0 SDK again but I came across the below message and I gave up.

`Using Visual Studio? This release is only compatible with Visual Studio 2022 (v17.11). Using a different version? See [.NET SDKs for Visual Studio](https://dotnet.microsoft.com/en-us/download/visual-studio-sdks).`

**Comment by BDisp** [comment]
Reinstalling the the .NET 8.0 SDK (v8.0.404) fix the issue and VS2022 isn't complaining. My question is why it removed the net80 by installing, without asking, the net90.
So, I'm closing because it's working well now with `"version":"8.0.0"` in the `global.json` file. Thanks @tznind.
