### ISSUE TITLE
Terminal.GUI plugin display as black 

### ISSUE THREAD

**Issue by karqical2016** [gui-cs/Terminal.Gui#3819]
Using C# WinForms Programming:

Create a program named test.exe using the Terminal.GUI plugin.
In a WinForms application, create a TerminalControl using Rebex.TerminalEmulation.TerminalControl, then use Rebex.Net.Ssh to establish an SSH connection and bind it to the TerminalControl.
Input mono test.exe in this TerminalControl to execute test.exe.
The current issue is that after executing mono test.exe, although the test.exe program using the Terminal.GUI plugin runs, its UI is not visible and appears as a black screen.
How to address the problem of the interface being displayed as black?

 public static void LoadRebexSSH(Rebex.TerminalEmulation.TerminalControl terminalControl)
 {
     Rebex.Licensing.Key = LinuxUtil.RebexKey;

     // unbind the client object from the terminal console
     terminalControl.Unbind();

     //terminalControl.ForeColor = Color.White; 
     //terminalControl.BackColor = Color.Black;
     // clear the screen
     terminalControl.Screen.Clear();

     // create a new Ssh client object
     var _ssh = new Rebex.Net.Ssh();
     _ssh.Encoding = Rebex.EncodingTools.UTF8;
     // connect to the SSH server
     _ssh.Connect(SqLiteUtil.LinuxSetting.Host, int.Parse(SqLiteUtil.LinuxSetting.Port));
     // login to the SSH server
     _ssh.Login(SqLiteUtil.LinuxSetting.Sa, SqLiteUtil.LinuxSetting.Passwd);

     //set utf8 
     terminalControl.Options.Encoding = Rebex.EncodingTools.UTF8;
     terminalControl.Options.FunctionKeysMode = FunctionKeysMode.Linux;
     // 1.changes the default selection mode to block mode
     // terminalControl.SelectionMode = TextSelectionMode.Block;
     // 2.specifies whether the right mouse button pastes text from clipboard
     // terminalControl.MousePasteEnabled = true;
     // 3.specifies whether selection a text using a mouse automatically copies the selected text into clipboard
     terminalControl.MouseSelectionCopiesToClipboard = true;
     //set font
     terminalControl.AutoAdjustTerminalSize = true;
     terminalControl.Palette = TerminalPalette.Dos;
  
     //terminalControl.TerminalFont = TerminalFont.FromDosFont(fontByte);
     terminalControl.TerminalFont = new Rebex.TerminalEmulation.TerminalFont(FontUtil.LoadFontFamily(), 12.00f);
     //terminalControl.TerminalFont = new Rebex.TerminalEmulation.TerminalFont("Consolas", 12.00f);
     Size cellSize = terminalControl.CellSize;
     // bind the connected and authenticated Ssh instance to the terminal console
     

     terminalControl.Bind(_ssh);
     terminalControl.Screen.WriteLine($"{DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss")} Session connected.");
     RebexSSHDisconnected = true;

 }
![image](https://github.com/user-attachments/assets/ea67fb55-832f-41a3-af11-36b77c6c2f40)

**Comment by tznind** [comment]
You are running your terminal app `test.exe` but using `mono` to launch it i.e. the program for running windows programs on linux.  Why do you not simply compile for linux directly? `dotnet publish -r linux-x64`

Also one thing to try is to switc to NetDriver?

```
Application.UseSystemConsole = true;
```

**Comment by karqical2016** [comment]
> You are running your terminal app `test.exe` but using `mono` to launch it i.e. the program for running windows programs on linux? Why do you not simply compile for linux directly?
> 
> ```
> dotnet publish --self-contained -r linux-x64
> ```
> 
> Also one thing to try is to switch to NetDriver?
> 
> ```
> Application.UseSystemConsole = true;
> ```
> 
> If this is running with the curses driver, then you may need to specify TERM environment variable in the environment that the exe is running e.g. setting it to 'xterm' .
> 
> Are you targetting version 1 or version 2 of Terminal.Gui

I have checked the driver type of the Terminal.GUI program, and indeed it is of the curses type. The version of Terminal.Gui is 1.7.
The program is written using .NET Framework 4.8, so I can only run it using Mono.
Are there any other good solutions?

**Comment by tznind** [comment]
Have you tried setting TERM to xterm in the linux box?

```
export TERM=xterm
```

Also have you tried adding `Application.UseSystemConsole = true;` before the `Application.Init()` call in your program?

**Comment by karqical2016** [comment]
it's working well after i try to add Application.UseSystemConsole = true; before the Application.Init() call in my program.
thank you very much!

**Comment by karqical2016** [comment]
> Have you tried setting TERM environment variable to xterm in the linux box? You should be able to do this via SSH (before launching your program) with
> 
> ```
> export TERM=xterm
> ```
> 
> Also have you tried adding `Application.UseSystemConsole = true;` before the `Application.Init()` call in your program?

it's working well after i try to add Application.UseSystemConsole = true; before the Application.Init() call in my program.
thank you very much!

**Comment by tznind** [comment]
Glad you got it working, it's cool to see such a combination of technologies working together correctly.  Good luck!

**Comment by BDisp** [comment]
Do you know what driver was loading before you adding the `Application.UseSystemConsole = true;` before the `Application.Init()`? Thanks.

**Comment by tznind** [comment]
@karqical2016 said:

> I have checked the driver type of the Terminal.GUI program, and indeed it is of the curses type. 

So CursesDriver v1 @BDisp .  Most likely curses is not able to determine the colors correctly - I have seen this before when TERM env var is missing etc.

**Comment by BDisp** [comment]
> So CursesDriver v1 @BDisp . Most likely curses is not able to determine the colors correctly - I have seen this before when TERM env var is missing etc.

Thanks for the feedback. Can you please show me a simple case where I can reproduce this without using third API? I would like to fix that in `CursesDriver`. Thanks.

**Comment by tznind** [comment]
Sounds like:

- A linux server, or docker container, or VM
- SSH connection
- Terminal control in a WinForms app (presumably running on local Windows PC)

To debug the curses driver issue, we would need to know more information about what kind of linux/unix is running.

**Comment by BDisp** [comment]
But it's possible to reproduce this without using the `WinForms`? When you also had this issue you ws using `WinForms`?
