### ISSUE TITLE
`TabView` changes focus to `Tab` on Layout

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#3847]
![SJU9Pji 1](https://github.com/user-attachments/assets/0e38ce22-7dae-4646-99d9-6aa2dd55b419)

**Comment by BDisp** [comment]
But this issue https://github.com/gui-cs/Terminal.Gui/pull/3828#issuecomment-2486942893 still exist which it's due a navigation issue not related with `TabView` navigation.

![WindowsTerminal_pHMHIRPFgo](https://github.com/user-attachments/assets/4f330dc8-b03f-44ff-a5a9-52a02f4ca2d1)

**Comment by BDisp** [comment]
One solution that I can use for this is set `TabStop = TabBehavior.TabGroup;` in the `TabRowView`. Thus it's possible to navigate to the Tab by pressing F6 key. Do you want I do this changes?

**Comment by BDisp** [comment]
> One solution that I can use for this is set `TabStop = TabBehavior.TabGroup;` in the `TabRowView`. Thus it's possible to navigate to the `Tab` by pressing `F6` key. Do you want I do this changes?

Done and also added wheel support.
