### ISSUE TITLE
'IThankful' needs moar expression

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#3869]
Here in the US it's Thanksgiving. Also know as turkey day. 

While we should always try to be grateful, this day is an opportunity to really share the things one's grateful for. 

I am incredibly grateful to @migueldeicaza for creating gui-cs and then giving me the opportunity to shepherd it forward. 

I am grateful for all the users/developers of Terminal.Gui. 

And I am grateful for the contributors who pour their hearts into improving the library and community around it. 

Thank you.

**Comment by tznind** [comment]
Thank you too for all the diligent review work, coding and pushing for best practices/quality
