### ISSUE TITLE
Overriding Key Handling by ComboBox

### ISSUE THREAD

**Issue by Tookles** [gui-cs/Terminal.Gui#3883]
Hello, I'm looking to set an action based on the user pressing the left or right arrow on their keypad. I've found that I can't use this on the same window where I have a combo as the combo handles it first. I've tried to create a wrap around CustomComboBlock class to override the ProcessKey method but that didn't work. Is there any other way around this? Thanks for any advice!

**Comment by tznind** [comment]
Are you referencing v1 or v2? 

Is this a 'global' action you are trying to configure? Or is it specific to a single view e.g. the Window containing the ComboBox?

Global key event handlers can use the events on `Application` to get 'first priority' on events before any views process the events.

Are you able to provide a sample of code showing what you have at the moment please.

**Comment by Tookles** [comment]
Using v.1. It's a specific to the window, I'm using the windows like a state machine so I can't access Global Key events on that specific window.  On that window, I have a grid display. The combo box lets you select one of 3 items on the grid. Once selected, the user can move them using the up, down, left or right keys on the grid. If it can't work, I will probably try and use buttons instead of the combobox selection. This is the relevant code excerpt that is not currently working.: 

```  
var comboBox = new CustomComboBox
        {
            X = xAlignment,
            Y = Pos.Bottom(comboBoxLabel) + 1,
            Width = 40,
            Height = 40
        };

 comboBox.SetSource(missionControl.Rovers.Select(x => x.Id).ToList());

 comboBox.SelectedItemChanged += (e) =>
        {
            selectedRover = missionControl.GetRoverById((ulong)comboBox.SelectedItem);
            roverPosition.Text = selectedRover.ToString();
        };

 openingWindow.KeyPress += (e) =>
        {
            if (e.KeyEvent.Key == Key.CursorLeft || e.KeyEvent.Key == Key.CursorRight)
            {
                missionControl.RunInstructions(selectedRover, new List<Instructions>() { Instructions.M });
                openingWindow.Remove(displayGrid);
                displayGrid = GetGrid();
                openingWindow.Add(displayGrid);
                openingWindow.SetNeedsDisplay();
            }
            e.Handled = true;
        };
```

**Comment by tznind** [comment]
In my experience combo boxes are a pain to get working properly in v1, I would suggest using a radio if few options or listview if many (you can even add search filtering text box if lots of options)

**Comment by Tookles** [comment]
I had a try at radio, but had the opposite issue where it disabled the up and down arrow instead of left and right. I'll explore list view and if that doesn't work, I'll use buttons as the back-up. There are only up to 3 options.   Thanks for your help!

**Comment by tznind** [comment]
Have you tried changing left/right to KeyDown instead of press?

**Comment by Tookles** [comment]
KeyDown instead of Press has got it working! Didn't even think of that. Thanks for your help, love the liibrary.

**Comment by tznind** [comment]
No worries! Glad we got to the bottom of it!

The key press comes after down and up. But many inbuilt views use keydown to for their event handlers.
