### ISSUE TITLE
Issue: Tabs not working!

### ISSUE THREAD

**Issue by mimmeer-github** [gui-cs/Terminal.Gui#3888]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Use code lines "var tabSystem = new Tab 
{
    DisplayText = "System"
};
var tabVersion = new Tab 
{ 
    DisplayText = "Version"
};

var tabs = new TabView()
{
    MaxTabTextWidth = 14
};

tabs.AddTab(tabSystem, true);
tabs.AddTab(tabVersion, false);

Add(tabs);" in an app.
2. Click on build making sure to use Terminal.Gui 2.0.0-v2-develop.2203+
3. See no tabs!

**Expected behaviour**
I expected a tab bar saying System and Version.

**Screenshots**
![image](https://github.com/user-attachments/assets/f9bd3810-f782-4c28-bc04-fdc4489506fe)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 130

**Smartphone (please complete the following information):**
 - Device: Huawei Mediapad T3
 - OS: Android 7.0
 - Browser: Chrome
 - Version: Unknown

**Additional context**
It seems to only be happening to me, I've read the code carefully.

**Set Project & Milestone**
If you have access, please don't forget to set the right Project and Milestone.
*I don't have access*

**Comment by BDisp** [comment]
You're using the minimum `TabView` size and needed to set the `Width` and `Height` properties.

**Comment by tznind** [comment]
Here is how to use TabView in v2

It is a bit harder than in v1 because `Tab` is now a `View` too so it is easy to accidentally add it with `Add` instead of `AddTab` etc.  So I suggest you use [Terminal Gui Designer](https://github.com/gui-cs/TerminalGuiDesigner) ;) 

```csharp

using Terminal.Gui;

Application.Init();

Application.Run(new MyViewYay());

Application.Shutdown();

class MyViewYay : Window
{
    public MyViewYay()
    {
        var tv = new TabView()
        {
            Width = Dim.Fill(),
            Height = Dim.Fill(),
        };

        var lbl = new Label()
        {
            Text="Hello World",
            Width = Dim.Auto(),
        };

        var tab1 = new Tab()
        {
            DisplayText = "System",
            View = new View{Width = Dim.Fill(),Height = Dim.Fill()}
        };
        tab1.View.Add(lbl);

        var lbl2 = new Label()
        {
            Text = "Goodbye World",
            Width = Dim.Auto(),
        };

        var tab2 = new Tab()
        {
            DisplayText = "Stuff",
            View = new View { Width = Dim.Fill(), Height = Dim.Fill() }
        };
        tab2.View.Add(lbl2);

        tv.AddTab(tab1,true);
        tv.AddTab(tab2, true);

        Add(tv);
    }
}
```

**Comment by tznind** [comment]
@mimmeer-github please re-open if you are still unable to get it work after following these suggestions.
