### ISSUE TITLE
Colors: The native method "COLOR_PAIRS" does not exist

### ISSUE THREAD

**Issue by psantosl** [gui-cs/Terminal.Gui#415]
Hey,

Just got

The native method "COLOR_PAIRS" does not exist

Trying to run a sample app (https://github.com/psantosl/htopsharp) in OpenSuse Leap 15.1 freshly installed.

**Comment by psantosl** [comment]
I do have /lib64/libncursesw.so.5  on my system

and 

```
nm -D /lib64/libncursesw.so.5 | grep COLOR
000000000000fb70 T COLOR_PAIR
0000000000232434 B COLOR_PAIRS
0000000000232430 B COLORS

```

**Comment by psantosl** [comment]
Ok, the problem is that it probably tries to load libncursesw.so.6 instead 

```
 nm -D /lib64/libncursesw.so.5 | grep COLOR
000000000000fb70 T COLOR_PAIR
0000000000232434 B COLOR_PAIRS
0000000000232430 B COLORS
pablo@linux-pablo:~/wkspaces/htopsharp> nm -D /lib64/libncursesw.so.6 | grep COLOR
0000000000011110 T COLOR_PAIR
000000000000f120 T _nc_COLOR_PAIRS
000000000000f140 T _nc_COLORS

```

**Comment by psantosl** [comment]
It works if I try to load "libncursesw.so.5" before so.6 in bindings.cs...

I tried to load the equivalent methods, but failed to locate the so.6 equivalent for LINES

**Comment by tig** [comment]
Is this still an issue? If not, please close it.

**Comment by migueldeicaza** [comment]
I think we should make it so we probe _nc_COLOR_PARIS and _nc_COLORS first, and if we fail, we fallback to COLOR_PAIR, COLOR_PAIRS.

**Comment by migueldeicaza** [comment]
Honestly - the long term solution is to avoid curses at all.

Curses is so often miss-compiled, so often old, so often compiled with missing capabilities, and with semantics that I end up working around more often than I wish.

The main case for ncurses is the optimization code that can compute the best commands to compute the area of the screen to update, but that is no longer a hard problem, and the speed of terminals is faster than it used to be.

Since I have recently completed two terminal emulators, I think that ncurses is really working against fully leveraging the capabilities of an xterm (what most things implement now).   

So I would love to build a new backend that does not rely on all these bad hacks.

**Comment by migueldeicaza** [comment]
haha, I knew I had written something about it:

https://github.com/migueldeicaza/gui.cs/issues/370

**Comment by psantosl** [comment]
Hey! But the new backend is not ready to use, right?

I only had issues in opensuse so far. Couple of cloud servers in amazon and google went well :-)

**Comment by tig** [comment]
This is covered by #370. Closing.

**Comment by adam8797** [comment]
Do we have a workaround for this? Looks like v2 is a long way off yet.

**Comment by tig** [comment]
I dunno. But I'm reopening as my closing it was clearly in error. 

Maybe another contributor more familiar with Linux can help!

**Comment by BDisp** [comment]
> Do we have a workaround for this? Looks like v2 is a long way off yet.

`CursesDriver` uses the `COLOR_PAIRS` if I'm not wrong. Can you be more specific about the issue to try to help, please.

**Comment by adam8797** [comment]
Sure, I commented because I'm having the exact same problem as @psantosl was having.

On the target system, I have both `libncursesw.so.5` and `libncursesw.so.6`.

When the application loads, it chooses `libncursesw.so.6` which doesn't have the `COLOR_PAIRS` function defined

**Comment by BDisp** [comment]
> Sure, I commented because I'm having the exact same problem as @psantosl was having.
> 
> On the target system, I have both `libncursesw.so.5` and `libncursesw.so.6`.
> 
> When the application loads, it chooses `libncursesw.so.6` which doesn't have the `COLOR_PAIRS` function defined

Thanks for the explanation. But this is happening with all the `Linux` system or only with some specific version? What do you suggest? If exist both `libncursesw*` only loads the `libncursesw.so.5`? This may cause issue for the users who want using `libncursesw.so.6`. What colors system the `libncursesw.so.6` is using? Perhaps `true color` with `rgb` color which `Terminal.Gui` doesn't support yet.

**Comment by tznind** [comment]
Do you know the steps to get these `.so` files on your target? Did they ship with the distro or was there a package/packages that were added that then broke `Terminal.Gui`? For example installing or updating the nucurses package from command line.

I don't know exactly how the binding / locating of libraries is happening but might be possible to probe the ones that are found and decide whether they are a compatible version (have the required methods).  If a dll or so file doesn't have a required method from our API and theres an alternative one available on the machine that does have the required methods then we should probably at least try to use that one?

**Comment by adam8797** [comment]
I actually don't have that level of control on these machines, they were built and managed by others. They're running SLES (an OpenSuSE variant) so that seems to be the common thread here, as the original post was on OpenSuSE Leap

I'll try setting the `UseSystemConsole` option and report back

**Comment by tznind** [comment]
Its a good idea to make `Application.UseSystemConsole = true` a user setting from CLI (or config file).  That empowers users as there can be advantages/drawbacks depending on environment and remoting tech (SSH / Guacamole etc)

**Comment by adam8797** [comment]
@BDisp looks like you found the workaround!

```c#
Application.UseSystemConsole = true;
Application.Init();
```

Seems to work in this situation. 

I can probably rely on this in my case (as all of the target machines are the same), but more generally a workaround could be to look for the `libncursesw.so.6` file, and/or take an argument.

Thanks for everyone's help, hopefully this edge case can be remediated in the library proper.

**Comment by adam8797** [comment]
@tznind are there any drawbacks to setting `Application.UseSystemConsole = true`?

**Comment by BDisp** [comment]
> @BDisp I don't know exactly how the binding / locating of libraries is happening in `CursesDriver` but it might be possible to probe the ones that are found and decide whether they are a compatible version (have the required methods). If a dll or so file doesn't have a required method from our API and theres an alternative one available on the machine that does have the required methods then we should probably at least try to use that one?

That checks are made in the binding.cs file. But as @migueldeicaza said in https://github.com/gui-cs/Terminal.Gui/issues/415#issuecomment-631651926 comment we can't rely totally on ncurses.

**Comment by adam8797** [comment]
Weird, maybe the OpenSuSE family of products just has a different/bad version of `libncursesw.so`:

```
$ nm -D /lib64/libncursesw.so.6 | grep COLOR
0000000000010990 T COLOR_PAIR
000000000000f020 T _nc_COLOR_PAIRS
000000000000f040 T _nc_COLORS
```

**Comment by BDisp** [comment]
Yes probably they don't compile the `ncurses` source with all the options.

**Comment by BDisp** [comment]
> But I don't think I've seen any environments where it won't work with some permutation of $TERM and/or `UseSystemConsole`. I've even had it running on the lite install of Raspbian (see #1697).

The $TERM environment is needed with `NetDriver` to get the mouse moves in `Linux`.

**Comment by BDisp** [comment]
`Opensuse` doesn't work with the `libncurses6` and the workaround is install the `libncurses5` (with the command `sudo zypper install libncurses5`) and `Terminal.Gui` will load it at run.

**Comment by BDisp** [comment]
Reopening this to submit another PR with a different approach to fix it.
