### ISSUE TITLE
Make demo.cs a simple, pretty, demo - move 'tests' to UI Catalog or UnitTests

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#433]
Now that we have UI Catalog that allows quickly adding test scenarios that don't step on other tests, please move any tests out of the `Example` project (`demo.cs`) and add them to `UI Catalog`.

We should clean up `demo.cs` so it actually looks like a little app we'd be proud of. Right now it is full of cruft that either doesn't work, or is just haphazardly placed. 

I've already moved `Text Alignment` and `Mouse` and will remove them from `demo.cs` as soon as the UI Catalog PR (#387)  is accepted.

**Comment by FreddieMercurial** [comment]
+1

Would love to see more or less a text editor application (Edit.com clone)...  Not sure if that is more complex than you were aiming, but it would be immensely helpful. All the extra control demos are neat, but harder to peel apart to learn.

**Comment by BDisp** [comment]
I think we should maintain this project to have an alternative execution test. Because of this project I found a bug (#1613) that is not reproducible on the `UICatalog`.

**Comment by tig** [comment]
In a recent Reddit post on Terminal.Gui, a commenter complained that the "Terminal.Gui samples are horrible". 

I asked him to explain what he meant and he said he looked at `Example` and that was the basis of his assertions.

I am going to submit a PR to address this issue that will 

- Delete `./Example/demo.cs`
- Add `./Example/Example.cs` - using the contents of the simple c# example that is in `./README.md`
- Update `./Example/README.md` to note that the sample is intended to be a very simple example of using Terminal.Gui in C#. And to note that `demo.cs` has been deleted, but if people really still want it, it is in git history.

@BDisp, if you believe we should have an "alternative execution test" based on `demo.cs` please submit a PR that adds it, but ensure it's named in such a way that makes it obvious it is NOT an example, but a test app. Thanks.
