### ISSUE TITLE
Replace Colors.Base.Normal with Attributes.Normal

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#458]
From TODO.md, which I'm about to delete:

>## Color and Dialogs
>
>Replaces `Colors.Base.Normal` with `Attributes.Normal`, and perhaps attributes
points to the container.

**Comment by BDisp** [comment]
> Replaces `Colors.Base.Normal` with `Attributes.Normal`, and perhaps attributes
> points to the container.

I'm confused about this. How can you distinguish the `Attributes.Normal` from others ColorScheme `Attributes.Normal`? Did you are meaning this?

```
Replaces Colors.Base.Normal with Attributes.Base.Normal, and perhaps attributes
points to the container.
```

**Comment by tig** [comment]
I don't know. I created this issue from an old "TODO.md" file that Miguel had. It may be a defunct issue.
