### ISSUE TITLE
`Application.Init` / `Shutdown` are confused about `TopLevel`s created by `Application.Begin` and not cleaned up by `Application.End`

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#520]
In `UI Catalog`, before I start a `Scenario` I call `Application.Shutdown`. You are supposed to book end every call to `Applciation.Begin` with `Shutdown`. 

I just discovered that `Shutdown` does not actually clean up. As a result, the next time `Application.Begin` is called, fields like `topLevels` still have data. This means that the 'old' stuff interferes with the 'new' stuff.

Short-term fix is to uninitialize stuff:

```csharp
		/// <summary>
		/// Shutdown an application initalized with <see cref="Init()"/>
		/// </summary>
		public static void Shutdown ()
		{
			Driver.End ();
			foreach (var t in toplevels) {
				t.Running = false;
			}
			toplevels.Clear ();
			Current = null;
			CurrentView = null;
			Top = null;
			MainLoop = null; 
			_initialized = false;
		}
```

Crux of issue (added Nov 2, 2022 via #2162):
 
Init/Shutdown are supposed to clean up. But in `ResetState`, the loop that disposes of the `topLevels` does nothing because the `Toplevel` that was created by `Init` has not been added to `topLevels` (it gets added by `Begin`).

The right fix (IMO) would be to move all that state into `RunState` and leverage the fact that `RunState` is already `IDisposable`. However, it may not be possible to do this without a breaking change.

**Comment by BDisp** [comment]
That was what I was referring to when I said that it was better to always build on top of the same Toplevel so as not to create too many instances that then remain in memory, spending resources, if we do not remove them. Creating new instances is always a good idea if you want to navigate between pages (this is a suggestion). So in this case you did well to create this resource to clean up resources that are no longer used.

**Comment by tig** [comment]
Right.

But in the case of `UI Catalog` we want each `Scenario` to have the ability to run as though it were a 'virgin' `Terminal.Gui` app. So, it's a good thing I wrote it that way because it has helped uncover more bugs like this one.

**Comment by tig** [comment]
Reopening for v2 - See #2162.

**Comment by tig** [comment]
Digging into this, I think UI Catalog is correct.

I think the bug is actually here:

<img width="412" alt="image" src="https://user-images.githubusercontent.com/585482/199633908-c7ca87dc-27e4-485e-ae66-b18bcd346ba1.png">

This check for multiple Mdi containers should see if `MdiTop != topLevel`:

<img width="394" alt="image" src="https://user-images.githubusercontent.com/585482/199633963-d49b72b8-d8cd-4363-8c55-84162b2cccc2.png">

With this change, and `BackgroundWorkerCollection.cs` changed thusly:

```csharp
namespace UICatalog.Scenarios {
	[ScenarioMetadata (Name: "BackgroundWorker Collection", Description: "A persisting multi Toplevel BackgroundWorker threading")]
	[ScenarioCategory ("Threading")]
	[ScenarioCategory ("Top Level Windows")]
	[ScenarioCategory ("Dialogs")]
	[ScenarioCategory ("Controls")]
	public class BackgroundWorkerCollection : Scenario {
		public override void Init (Toplevel top, ColorScheme colorScheme)
		{
			// Do nothing as, the call to `Application.Run<MdiMain>` in `Run` implies an `Application.Init()` call.
		}

		public override void Run ()
		{
			Application.Run<MdiMain> ();
		}

```

Alternatively, this works too:

```csharp
namespace UICatalog.Scenarios {
	[ScenarioMetadata (Name: "BackgroundWorker Collection", Description: "A persisting multi Toplevel BackgroundWorker threading")]
	[ScenarioCategory ("Threading")]
	[ScenarioCategory ("Top Level Windows")]
	[ScenarioCategory ("Dialogs")]
	[ScenarioCategory ("Controls")]
	public class BackgroundWorkerCollection : Scenario {
		public override void Init (Toplevel top, ColorScheme colorScheme)
		{
			Application.Init ();
			Application.Top.Dispose (); // We're going to be creating a new TopLevel (MdiMain) so kill this one
		}

		public override void Run ()
		{
			Application.Run<MdiMain> ();
		}
```

It all works correctly.

Related: (I had forgotten about this): https://github.com/gui-cs/Terminal.Gui/issues/520

The real cause of the problems here is that 

- Init/Shutdown are supposed to clean up. But in `ResetState`, the loop that disposes the `topLevels` does nothing because the `Toplevel that was created by `Init` has not been added to `topLevels` (it gets added by `Begin`).

@BDisp what are your thoughts? Please review #2165.

> > > I can repo. Are you sure it didn't do this before?
> > 
> > 
> > I don't think so.
> 
> I just reverted to before I merged the UI Catalog refactoring and this issue still exits.
> 
> Go back to your `vkpacket-fix4` branch, which was merged before I did the UI Cat work and you'll see this double menu thing reproduces there.
> 
> I then went back to v1.82 and it repros there too. So this has nothing to with my UI Cat changes or THIS PR.
> 
> > In the `scenario.Init (Application.Top, _colorScheme);` the parameter `Application.Top` now will be always null. I think this method shouldn't have any parameters, because if the user don't use it he can initialize a customized toplevel, by overridden the `Run` method without code..
> 
> I completely agree! I will do another PR to simplify this (I had considered it before but then forgot).
> 
> > Doing in the `scenario.Run ();` is a waste of resources because we need to `Dispose` before recreate a new one. Because `Application.Top` is created by calling the `Application.Init()` and it's not already added to the topLevels, is more accurate to call `Top.Dispose();` before set `Top = null;` in the `ResetState` method, to ensure that the `Top` is disposed in the case it wasn't added to the `toplevels`, because the `foreach (var t in toplevels)` will be empty.
> 
> I think this is right, but I need to look more closely. BackgroundWorker Collection is the only Scenario that uses Run(). So it's a great test case for all of this.
> 
> I suggest we close THIS PR and move the discussion to #520, which is where the root cause is. Ok?

**Comment by tig** [comment]
Digging into this, I think UI Catalog is correct.

I think the bug is actually here:

<img width="412" alt="image" src="https://user-images.githubusercontent.com/585482/199633908-c7ca87dc-27e4-485e-ae66-b18bcd346ba1.png">

This check for multiple Mdi containers should see if `MdiTop != topLevel`:

<img width="394" alt="image" src="https://user-images.githubusercontent.com/585482/199633963-d49b72b8-d8cd-4363-8c55-84162b2cccc2.png">

With this change, and `BackgroundWorkerCollection.cs` changed thusly:

```csharp
namespace UICatalog.Scenarios {
	[ScenarioMetadata (Name: "BackgroundWorker Collection", Description: "A persisting multi Toplevel BackgroundWorker threading")]
	[ScenarioCategory ("Threading")]
	[ScenarioCategory ("Top Level Windows")]
	[ScenarioCategory ("Dialogs")]
	[ScenarioCategory ("Controls")]
	public class BackgroundWorkerCollection : Scenario {
		public override void Init (Toplevel top, ColorScheme colorScheme)
		{
			// Do nothing as, the call to `Application.Run<MdiMain>` in `Run` implies an `Application.Init()` call.
		}

		public override void Run ()
		{
			Application.Run<MdiMain> ();
		}

```

Alternatively, this works too:

```csharp
namespace UICatalog.Scenarios {
	[ScenarioMetadata (Name: "BackgroundWorker Collection", Description: "A persisting multi Toplevel BackgroundWorker threading")]
	[ScenarioCategory ("Threading")]
	[ScenarioCategory ("Top Level Windows")]
	[ScenarioCategory ("Dialogs")]
	[ScenarioCategory ("Controls")]
	public class BackgroundWorkerCollection : Scenario {
		public override void Init (Toplevel top, ColorScheme colorScheme)
		{
			Application.Init ();
			Application.Top.Dispose (); // We're going to be creating a new TopLevel (MdiMain) so kill this one
		}

		public override void Run ()
		{
			Application.Run<MdiMain> ();
		}
```

It all works correctly.

Related: (I had forgotten about this): https://github.com/gui-cs/Terminal.Gui/issues/520

The real cause of the problems here is that 

- Init/Shutdown are supposed to clean up. But in `ResetState`, the loop that disposes the `topLevels` does nothing because the `Toplevel that was created by `Init` has not been added to `topLevels` (it gets added by `Begin`).

@BDisp what are your thoughts? Please review #2165.

> > > I can repo. Are you sure it didn't do this before?
> > 
> > 
> > I don't think so.
> 
> I just reverted to before I merged the UI Catalog refactoring and this issue still exits.
> 
> Go back to your `vkpacket-fix4` branch, which was merged before I did the UI Cat work and you'll see this double menu thing reproduces there.
> 
> I then went back to v1.82 and it repros there too. So this has nothing to with my UI Cat changes or THIS PR.
> 
> > In the `scenario.Init (Application.Top, _colorScheme);` the parameter `Application.Top` now will be always null. I think this method shouldn't have any parameters, because if the user don't use it he can initialize a customized toplevel, by overridden the `Run` method without code..
> 
> I completely agree! I will do another PR to simplify this (I had considered it before but then forgot).
> 
> > Doing in the `scenario.Run ();` is a waste of resources because we need to `Dispose` before recreate a new one. Because `Application.Top` is created by calling the `Application.Init()` and it's not already added to the topLevels, is more accurate to call `Top.Dispose();` before set `Top = null;` in the `ResetState` method, to ensure that the `Top` is disposed in the case it wasn't added to the `toplevels`, because the `foreach (var t in toplevels)` will be empty.
> 
> I think this is right, but I need to look more closely. BackgroundWorker Collection is the only Scenario that uses Run(). So it's a great test case for all of this.
> 
> I suggest we close THIS PR and move the discussion to #520, which is where the root cause is. Ok?

**Comment by tig** [comment]
Just noted there are no unit tests that test `void Run<T> (Func<Exception, bool> errorHandler = null) where T : Toplevel, new()` aka `Run<T>`.

First step here is to write some.

**Comment by tig** [comment]
Note the BUGBUGs I put here; good questions, I think, but probably not related:

```csharp
		public static void Run<T> (Func<Exception, bool> errorHandler = null) where T : Toplevel, new()
		{
			if (_initialized && Driver != null) {
				var top = new T ();
				var type = top.GetType ().BaseType;
				while (type != typeof (Toplevel) && type != typeof (object)) {
					type = type.BaseType;
				}
				if (type != typeof (Toplevel)) {
					throw new ArgumentException ($"{top.GetType ().Name} must be derived from TopLevel");
				}
				// BUGBUG: Note `Top` is not set here, so `Top` will be null. Is this correct?
				Run (top, errorHandler);
			} else {
				// BUGBUG: Note in this case, we don't verify the type of the Toplevel created by new T(). Is this an issue?
				Init (() => new T ());
				Run (Top, errorHandler);
			}
		}
```

**Comment by tig** [comment]
> Note the BUGBUGs I put here; good questions, I think, but probably not related:
> 
> ```cs
> 		public static void Run<T> (Func<Exception, bool> errorHandler = null) where T : Toplevel, new()
> 		{
> 			if (_initialized && Driver != null) {
> 				var top = new T ();
> 				var type = top.GetType ().BaseType;
> 				while (type != typeof (Toplevel) && type != typeof (object)) {
> 					type = type.BaseType;
> 				}
> 				if (type != typeof (Toplevel)) {
> 					throw new ArgumentException ($"{top.GetType ().Name} must be derived from TopLevel");
> 				}
> 				// BUGBUG: Note `Top` is not set here, so `Top` will be null. Is this correct?
> 				Run (top, errorHandler);
> 			} else {
> 				// BUGBUG: Note in this case, we don't verify the type of the Toplevel created by new T(). Is this an issue?
> 				Init (() => new T ());
> 				Run (Top, errorHandler);
> 			}
> 		}
> ```

On the 1st BUGBUG above, I've verified that `Top` does indeed eventually get set in this codepath (in `SetCurrentTop`). Call stack:

<img width="635" alt="image" src="https://user-images.githubusercontent.com/585482/199749884-e7301ce3-fe30-414a-9e51-aec96ab7e35b.png">

**Comment by BDisp** [comment]
> Note the BUGBUGs I put here; good questions, I think, but probably not related:
> 
> ```cs
> 		public static void Run<T> (Func<Exception, bool> errorHandler = null) where T : Toplevel, new()
> 		{
> 			if (_initialized && Driver != null) {
> 				var top = new T ();
> 				var type = top.GetType ().BaseType;
> 				while (type != typeof (Toplevel) && type != typeof (object)) {
> 					type = type.BaseType;
> 				}
> 				if (type != typeof (Toplevel)) {
> 					throw new ArgumentException ($"{top.GetType ().Name} must be derived from TopLevel");
> 				}
> 				// BUGBUG: Note `Top` is not set here, so `Top` will be null. Is this correct?
> 				Run (top, errorHandler);
> 			} else {
> 				// BUGBUG: Note in this case, we don't verify the type of the Toplevel created by new T(). Is this an issue?
> 				Init (() => new T ());
> 				Run (Top, errorHandler);
> 			}
> 		}
> ```

>// BUGBUG: Note `Top` is not set here, so `Top` will be null. Is this correct?

Yes it's null but will be initialized with the call `Run (top, errorHandler);`

>// BUGBUG: Note in this case, we don't verify the type of the Toplevel created by new T(). Is this an issue?

No it isn't because the generic type is referencing a `Toplevel` on the method `where T : Toplevel, new()`.

**Comment by tig** [comment]
> > // BUGBUG: Note in this case, we don't verify the type of the Toplevel created by new T(). Is this an issue?
> 
> No it isn't because the generic type is referencing a `Toplevel` on the method `where T : Toplevel, new()`.

But then why is the type checked in the other codepath?

**Comment by BDisp** [comment]
> But then why is the type checked in the other codepath?

The first code-path is used when the `Init` method was already called and the drivers are already initialized. Then it checks into the `BaseType`. If it isn't a `Toplevel` type an exception is throw.

**Comment by tig** [comment]
> > But then why is the type checked in the other codepath?
> 
> The first code-path is used when the `Init` method was already called and the drivers are already initialized. Then it checks into the `BaseType`. If it isn't a `Toplevel` type an exception is throw.

```csharp
var top = new T ();
var type = top.GetType ().BaseType;
while (type != typeof (Toplevel) && type != typeof (object)) {
   type = type.BaseType;
}
if (type != typeof (Toplevel)) {
  throw new ArgumentException ($"{top.GetType ().Name} must be derived from TopLevel");
 				}
```

Educate me please: if I do a `new T()` where `T` is type-checked at compile time because `Run<T>` is defined as `where T : Toplevel, new()`, isn't it impossible for `type != typeof(Toplevel)`?

**Comment by BDisp** [comment]
> Educate me please: if I do a `new T()` where `T` is type-checked at compile time because `Run<T>` is defined as `where T : Toplevel, new()`, isn't it impossible for `type != typeof(Toplevel)`?

Well, `Toplevel` is derived from `View` but we want only accept 'T' with an object that is derived from `Toplevel` and not an object that is derived from `View.`

**Comment by BDisp** [comment]
> Do you think `NotifyNewRunState` could be invoked safely even if `ExitRunLoopAfterFirstIteration` is `false`.

`ExitRunLoopAfterFirstIteration` as true will exit the `RunLoop` and it's needed to manually rerun it. That is only used for drivers that can't be blocked into the `RunLoop`, like the `WebConsole`. But perhaps is safely also to invoke the `NotifyNewRunState` event if it's false. I never try it but it should do not screw up anything.

**Comment by tig** [comment]
> > Do you think `NotifyNewRunState` could be invoked safely even if `ExitRunLoopAfterFirstIteration` is `false`.
> 
> `ExitRunLoopAfterFirstIteration` as `true` will exit the `RunLoop` and it's needed to manually rerun it. That is only used for drivers that can't be blocked into the `RunLoop`, like the `WebConsole`. But perhaps is safely also to invoke the `NotifyNewRunState` event if it's `false`. I never try it but it should do not screw up anything.

I did this and wrote more unit tests to prove it works. The new docs for these actions are:

```csharp
		/// <summary>
		/// Notify that a new <see cref="RunState"/> was created (<see cref="Begin(Toplevel)"/> was called). The token is created in 
		/// <see cref="Begin(Toplevel)"/> and this event will be fired before that function exits.
		/// </summary>
		/// <remarks>
		///	If <see cref="ExitRunLoopAfterFirstIteration"/> is <see langword="true"/> callers to
		///	<see cref="Begin(Toplevel)"/> must also subscribe to <see cref="NotifyStopRunState"/>
		///	and manually dispose of the <see cref="RunState"/> token when the application is done.
		/// </remarks>
		public static event Action<RunState> NotifyNewRunState;

		/// <summary>
		/// Notify that a existent <see cref="RunState"/> is stopping (<see cref="End(RunState)"/> was called).
		/// </summary>
		/// <remarks>
		///	If <see cref="ExitRunLoopAfterFirstIteration"/> is <see langword="true"/> callers to
		///	<see cref="Begin(Toplevel)"/> must also subscribe to <see cref="NotifyStopRunState"/>
		///	and manually dispose of the <see cref="RunState"/> token when the application is done.
		/// </remarks>
		public static event Action<Toplevel> NotifyStopRunState;
```

**Comment by tig** [comment]
Wow, `Run<T>` is massively broken. The deeper I go, the more issues I find.

The crux is that it calls (the internal) `Init (Func<Toplevel> topLevelFactory)` when `void Init (ConsoleDriver driver = null, IMainLoopDriver mainLoopDriver = null) => Init (() => Toplevel.Create (), driver, mainLoopDriver)` has not yet been called. 

But `Init (Func<Toplevel> topLevelFactory)` relies on auto-detection of the driver & mainloop. This means, as-is, `Run<T>` can't be unit tested!

As an experiment, I changed the method to take a driver & mainloop, thinking this could be done in a non breaking-change way:
<img width="542" alt="image" src="https://user-images.githubusercontent.com/585482/199806378-e5650c6e-a487-45be-833a-1d5ccd87aa3d.png">

This almost works, but then I discovered that `Init (Func<Toplevel> topLevelFactory)` calls `ResetState()` which means there's no way to key `Applicaton.Iteration` set.

I think I've resolved this by changing the internal `Init` to:

```csharp
		/// <summary>
		/// Internal function for initializing a Terminal.Gui application with a <see cref="Toplevel"/> factory object, 
		/// a <see cref="ConsoleDriver"/>, and <see cref="MainLoop"/>.
		/// <para>
		/// This is a low-level function; most applications will use <see cref="Init(ConsoleDriver, IMainLoopDriver)"/> as it is simpler.</para>
		/// </summary>
		/// <param name="topLevelFactory">Specifies the <see cref="Toplevel"> factory funtion.</see>/></param>
		/// <param name="driver">The <see cref="ConsoleDriver"/> to use. If not specified the default driver for the
		/// platform will be used (see <see cref="WindowsDriver"/>, <see cref="CursesDriver"/>, and <see cref="NetDriver"/>).</param>
		/// <param name="mainLoopDriver">Specifies the <see cref="MainLoop"/> to use.</param>
		/// <param name="resetState">If <see langword="true"/> (default) all <see cref="Application"/> state will be reset. 
		/// Set to <see langword="false"/> to not reset the state (for when this function is called via 
		/// <see cref="Run{T}(Func{Exception, bool}, ConsoleDriver, IMainLoopDriver)"/> when <see cref="Init(ConsoleDriver, IMainLoopDriver)"/>
		/// has not already been called. f</param>
	internal static void Init (Func<Toplevel> topLevelFactory, ConsoleDriver driver = null, IMainLoopDriver mainLoopDriver = null, bool resetState = true)
		{
			if (_initialized && driver == null) return;

			if (_initialized) {
				throw new InvalidOperationException ("Init has already been called and must be bracketed by Shutdown.");
			}

			// Used only for start debugging on Unix.
			//#if DEBUG
			//			while (!System.Diagnostics.Debugger.IsAttached) {
			//				System.Threading.Thread.Sleep (100);
			//			}
			//			System.Diagnostics.Debugger.Break ();
			//#endif

			// Reset all class variables (Application is a singleton).
			if (resetState) {
				ResetState ();
			}
...
```

Writing more unit tests now to prove this doesn't break anything.

**Comment by BDisp** [comment]
@tig try to press the `Enter` key to run some scenario and` Ctrl+Q` to quit. Do this continuously in the same scenario and you will observe that it take more time to run and exit more and more. I think the memory it isn't disposing and freeing safely on shutdown.

**Comment by BDisp** [comment]
> This almost works, but then I discovered that `Init (Func<Toplevel> topLevelFactory)` calls `ResetState()` which means there's no way to key `Applicaton.Iteration` set.

Well the `Init` method isn't for`Applicaton.Iteration`. This is only used on the `RunLoop` method. The `Init` is only to initialize the drivers and the principals variables.

**Comment by BDisp** [comment]
I prefer this approach because is not needed to create the `Window` if we don't needed it as this scenario. We don't need to call `Application.Shutdown()` because it will be called after exit the scenario in the `UICatalog`.

```cs
	public class BackgroundWorkerCollection : Scenario {
		public override void Init (Toplevel top, ColorScheme colorScheme)
		{
			Application.Init ();

			Application.Run<MdiMain> ();
		}

		public override void Run ()
		{
		}

```

If `Top` was already initialized with `Init` method and never was called on `Begin` method and the current toplevel that is passed to the `Begin` method isn't the same as `Top` and isn't added in the toplevels, then that original `Top` must be disposed. To fix it we need to make this change.

![imagem](https://user-images.githubusercontent.com/13117724/199820364-a052c0e5-7ebf-4a8c-b7d7-bbd6b6f609c3.png)

If the `Begin` method was never called and `Init` is called again after a `Shutdown` then this fix is needed:

![imagem](https://user-images.githubusercontent.com/13117724/199817049-95a40ccd-7cbc-4ff7-a52b-9dca6ecf2806.png)

Here are some unit tests I've made in the `ApplicationTests.cs`. It fail without the fixes:

```cs
		[Fact]
		public void Dispose_Toplevel_Without_Begin_End ()
		{
			Application.Init (new FakeDriver (), new FakeMainLoop (() => FakeConsole.ReadKey (true)));

			Application.Shutdown ();

			Assert.Single (Responder.Instances);
			foreach (var inst in Responder.Instances) {
				Assert.True (inst.WasDisposed);
			}
		}

		[Fact]
		public void Dispose_Toplevel_IsMdiContainer_False_With_Begin_End ()
		{
			Application.Init (new FakeDriver (), new FakeMainLoop (() => FakeConsole.ReadKey (true)));

			var top = new Toplevel ();
			var rs = Application.Begin (top);
			Application.End (rs);

			Application.Shutdown ();

			Assert.Equal (2, Responder.Instances.Count);
			foreach (var inst in Responder.Instances) {
				Assert.True (inst.WasDisposed);
			}
		}

		[Fact]
		public void Dispose_Toplevel_IsMdiContainer_True_With_Begin ()
		{
			Application.Init (new FakeDriver (), new FakeMainLoop (() => FakeConsole.ReadKey (true)));

			var mdi = new Toplevel { IsMdiContainer = true };
			var rs = Application.Begin (mdi);
			Application.End (rs);

			Application.Shutdown ();

			Assert.Equal (2, Responder.Instances.Count);
			foreach (var inst in Responder.Instances) {
				Assert.True (inst.WasDisposed);
			}
		}

```

**Comment by tig** [comment]
> I prefer this approach because is not needed to create the `Window` if we don't needed it as this scenario. We don't need to call `Application.Shutdown()` because it will be called after exit the scenario in the `UICatalog`.

Please see PR #2167 - pull it down and use it as the basis for conversations on this topic. Feel free to submit PRs to this PR.

The fixes you suggested above are not valid as far as I can see. I implemented them and tons of other things broke.

**Comment by tig** [comment]
> ```cs
> 		[Fact]
> 		public void Dispose_Toplevel_Without_Begin_End ()
> 		{
> 			Application.Init (new FakeDriver (), new FakeMainLoop (() => FakeConsole.ReadKey (true)));
> 
> 			Application.Shutdown ();
> 
> 			Assert.Single (Responder.Instances);
> 			foreach (var inst in Responder.Instances) {
> 				Assert.True (inst.WasDisposed);
> 			}
> 		}

This test already exists (effectively) in my latest PR, but with a comment noting #520 means callers must Dispose `Top` themselves: `Init_Shutdown_Cleans_Up`. The intent is to remove that line once #520 is fixed.

> 		[Fact]
> 		public void Dispose_Toplevel_IsMdiContainer_False_With_Begin_End ()
> 		{
> 			Application.Init (new FakeDriver (), new FakeMainLoop (() => FakeConsole.ReadKey (true)));
> 
> 			var top = new Toplevel ();
> 			var rs = Application.Begin (top);
> 			Application.End (rs);
> 
> 			Application.Shutdown ();
> 
> 			Assert.Equal (2, Responder.Instances.Count);
> 			foreach (var inst in Responder.Instances) {
> 				Assert.True (inst.WasDisposed);
> 			}
> 		}
> 
> 		[Fact]
> 		public void Dispose_Toplevel_IsMdiContainer_True_With_Begin ()
> 		{
> 			Application.Init (new FakeDriver (), new FakeMainLoop (() => FakeConsole.ReadKey (true)));
> 
> 			var mdi = new Toplevel { IsMdiContainer = true };
> 			var rs = Application.Begin (mdi);
> 			Application.End (rs);
> 
> 			Application.Shutdown ();
> 
> 			Assert.Equal (2, Responder.Instances.Count);
> 			foreach (var inst in Responder.Instances) {
> 				Assert.True (inst.WasDisposed);
> 			}
> 		}
> ```

These tests are good! Added them.

**Comment by tig** [comment]
> If `Top` was already initialized with `Init` method and never was called on `Begin` method and the current toplevel that is passed to the `Begin` method isn't the same as `Top` and isn't added in the toplevels, then that original `Top` must be disposed. To fix it we need to make this change.
> 
> ![imagem](https://user-images.githubusercontent.com/13117724/199820364-a052c0e5-7ebf-4a8c-b7d7-bbd6b6f609c3.png)
> 

The issue with this proposed fix is: You don't set `Top = null;` after the calling Dispose. If you DO set it to null other things that use `Top` break (like `MdiTop`):

<img width="338" alt="image" src="https://user-images.githubusercontent.com/585482/199850874-4b3802e8-d669-467a-9af7-746ab4c13bee.png">

This does the trick, I think:

<img width="320" alt="image" src="https://user-images.githubusercontent.com/585482/199851183-d803edb6-f43d-4bcc-9b3f-425cc4b55398.png">

**Comment by BDisp** [comment]
> The issue with this proposed fix is: You don't set `Top = null;` after the calling Dispose. If you DO set it to null other things that use `Top` break (like `MdiTop`):

But I think it is not set to null. Is only to set the `Responder.WasDisposed` to `true`, but I could be wrong.

**Comment by tig** [comment]
See latest update to the PR.

I have implemented your suggested fix (with tweaks). All unit tests except `KeyBindings_Command_With_MdiTop` pass.

No asserts from UI Catalog.

Check it out!!!!

See if you can figure out why that test broke...

**Comment by tig** [comment]
I feel good about this for v1.9. I had originally tagged it as v2.0 because I was skeptical it could be fixed without breaking changes.

I need @tznind and @BDisp to take a close look at it though!
