### ISSUE TITLE
Refactor ConsoleDrivers to remove duplicate code

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#666]
There is a LOT of common code across the three (now four with Fake) Drivers.

I was just thinking about how to fix bugs related to non-printable chars causing rendering issues on some terminals. For example, in Windows Terminal and Fluent if `AddRune` gets called with `\n` it does this:
![image](https://user-images.githubusercontent.com/585482/84306468-bf950280-ab18-11ea-8e37-b4d623d69152.png)

The fix is to modify `AddRune` to look for non-printable chars like this, that may cause the underlying console to take action and replace them with the right glyph. E.g:

![image](https://user-images.githubusercontent.com/585482/84306987-7d1ff580-ab19-11ea-9fe4-8dc9ad200b62.png)

However, it's stupid to do this 4 times. Instead the `base` should implement the least-common-denominator functionality. 

Right?

**Comment by BDisp** [comment]
I think is already fixed with your creating of the `public static Rune MakePrintable (Rune c)` method and the `TextFormatter` class.

**Comment by tig** [comment]
Woo-hoo! Finally!

It ain't perfect, but this radically simplifies and improves the ability to prove quality.
