### ISSUE TITLE
TextView: TextChanged event doesn't fire when user types

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#730]
It only gets sent when `Text` is set, and `Text` is never set internally by the control.

The fix needs to be carefully considered because `TextView` is often used to hold very large amounts of text. For example, blindly setting `Text` internally will cause the entire contents to get copied at least once every time a user types something.

Perhaps the best way to address this is to add another event, `ContentsChanged` which is not tied to the `Text` property?

**Comment by BDisp** [comment]
Perhaps it is ideal and with location information (`Col `and (`Row `or `Line`)).
