### ISSUE TITLE
numeric keypad cant enter ","

### ISSUE THREAD

**Issue by yadbo** [gui-cs/Terminal.Gui#977]
Hello there,

I have troubles at reading the "," on the numeric keypad side using german keyboard. I don't get any events for KeyPress. When I press the numbers it's working as expected except for the comma.

Any solutions or ideas?

Regards

**Comment by tig** [comment]
Can you please give us more details on your enviroment?

OS?
Terminal?
Build of Terminal.Gui?

**Comment by yadbo** [comment]
Sure... Running on Windows and starting as normal console application.
Currently using Terminal.Gui 0.89 (I guess that's the number, couldn't find another version/build number).
I've cloned the project on 25. Aug 2020, not sure which version that was.

**Comment by tig** [comment]
Would you pretty please, do a `git pull upstream master` and see if it repros with the latest?

I, unfortunately, use a 10-keypad-less keyboard ;-(

**Comment by BDisp** [comment]
Mine is working. Only in my case it is the period instead of the comma.

**Comment by tig** [comment]
I just hooked up another keyboard.

I can't reproduce this with US settings. With Numlock off I hit every key on the numeric keypad:

![image](https://user-images.githubusercontent.com/585482/97349192-64a44380-184c-11eb-8000-a9e9dced7599.png)

Please do me a favor of setting a breakpoint on line 1043 of WindowsDriver.cs and stepping through when you press that key.

![image](https://user-images.githubusercontent.com/585482/97349408-ae8d2980-184c-11eb-9ac2-d9a2c32bfc66.png)

**Comment by yadbo** [comment]
This is what I get...: @tig 

![grafik](https://user-images.githubusercontent.com/20045399/97354902-6561c780-1896-11eb-9b37-713e5688e037.png)

**Comment by tig** [comment]
If you step through that function, on what line does it return?

I set my keyboard to "English (Germany) - German" and I get the same keyInfo, but it works fine.

**Comment by tig** [comment]
it also works fine if I set langauge to
![image](https://user-images.githubusercontent.com/585482/97358977-4ee94b00-1859-11eb-9713-ed43cc0aab22.png)

**Comment by tig** [comment]
I don't have a keyboard here with num keys. Can someone please try to repro?

**Comment by tig** [comment]
Still looking for a repro.

**Comment by jmperricone** [comment]
In my laptop with numpad, with ENG or DEU keyboard, in UIcatalog and ReactiveExample, works perfectly. Of course with NumLock off, works as arrows and home, end....

**Comment by BDisp** [comment]
I also do not have any issue with that. Works fine. If we use a virtual machine sometimes there is some conflicts with the numeric keyboard on a laptop where a tweak can solve.
